window.MM=window.MM||{};
window.MM.community=[
{"t":"Biostatistics","q":"Which of the following is the main objective of biostatistics in community medicine?","a":"Clinical diagnosis","b":"Individual patient care","c":"Collection, analysis, and interpretation of health data","d":"Hospital management","ans":"C"},
{"t":"Biostatistics","q":"Blood group classification (A, B, AB, O) represents which type of data?","a":"Continuous","b":"Discrete","c":"Nominal","d":"Ordinal","ans":"C"},
{"t":"Biostatistics","q":"Number of children in a family is an example of:","a":"Continuous variable","b":"Discrete variable","c":"Ordinal variable","d":"Nominal variable","ans":"B"},
{"t":"Biostatistics","q":"Which scale of measurement has a true zero point?","a":"Nominal","b":"Ordinal","c":"Interval","d":"Ratio","ans":"D"},
{"t":"Biostatistics","q":"Weight measured in kilograms is an example of:","a":"Nominal scale","b":"Ordinal scale","c":"Interval scale","d":"Ratio scale","ans":"D"},
{"t":"Biostatistics","q":"The most suitable diagram to present qualitative data is:","a":"Histogram","b":"Bar diagram","c":"Frequency polygon","d":"Ogive","ans":"B"},
{"t":"Biostatistics","q":"Histogram is used for presenting:","a":"Qualitative data","b":"Discrete data","c":"Continuous data","d":"Proportional data","ans":"C"},
{"t":"Biostatistics","q":"In a histogram, the bars:","a":"Are separated by gaps","b":"Represent categories","c":"Touch each other","d":"Represent percentages only","ans":"C"},
{"t":"Biostatistics","q":"Pie chart is most useful for showing:","a":"Time trends","b":"Comparison between groups","c":"Proportion of components","d":"Continuous distribution","ans":"C"},
{"t":"Biostatistics","q":"Which diagram is best to show changes in disease incidence over years?","a":"Pie chart","b":"Bar diagram","c":"Line diagram","d":"Histogram","ans":"C"},
{"t":"Biostatistics","q":"Measures of central tendency include all EXCEPT:","a":"Mean","b":"Median","c":"Mode","d":"Variance","ans":"D"},
{"t":"Biostatistics","q":"Arithmetic mean is defined as:","a":"Middle value","b":"Most frequent value","c":"Sum of observations divided by number of observations","d":"Difference between extreme values","ans":"C"},
{"t":"Biostatistics","q":"Median is the value which:","a":"Occurs most frequently","b":"Lies at the center of ordered data","c":"Is the arithmetic average","d":"Has minimum deviation","ans":"B"},
{"t":"Biostatistics","q":"Mode is particularly useful when data are:","a":"Symmetrical","b":"Continuous","c":"Qualitative","d":"Skewed","ans":"C"},
{"t":"Biostatistics","q":"Which measure of central tendency is NOT affected by extreme values?","a":"Mean","b":"Median","c":"Arithmetic mean","d":"Weighted mean","ans":"B"},
{"t":"Biostatistics","q":"In a positively skewed distribution, the relationship is:","a":"Mean < Median < Mode","b":"Mean > Median > Mode","c":"Mode < Mean < Median","d":"Mean = Median = Mode","ans":"B"},
{"t":"Biostatistics","q":"Median is preferred over mean when:","a":"Data are symmetrical","b":"Data contain extreme values","c":"Sample size is small","d":"Data are nominal","ans":"B"},
{"t":"Biostatistics","q":"Which measure of central tendency can be calculated for open-ended class intervals?","a":"Mean","b":"Median","c":"Mode","d":"Arithmetic mean only","ans":"B"},
{"t":"Biostatistics","q":"Which measure is most stable with respect to sampling fluctuations?","a":"Mean","b":"Median","c":"Mode","d":"Range","ans":"A"},
{"t":"Biostatistics","q":"Mode is calculated by which method in grouped data?","a":"Direct observation","b":"Graphical method","c":"Interpolation","d":"Ogive method","ans":"B"},
{"t":"Biostatistics","q":"If all observations are multiplied by a constant, the mean:","a":"Remains unchanged","b":"Increases by constant","c":"Is multiplied by the same constant","d":"Becomes zero","ans":"C"},
{"t":"Biostatistics","q":"Median divides the data into:","a":"Four equal parts","b":"Three equal parts","c":"Two equal parts","d":"Unequal parts","ans":"C"},
{"t":"Biostatistics","q":"The most appropriate average for income data is:","a":"Mean","b":"Median","c":"Mode","d":"Geometric mean","ans":"B"},
{"t":"Biostatistics","q":"Which average is used in calculating growth rates?","a":"Arithmetic mean","b":"Median","c":"Mode","d":"Geometric mean","ans":"D"},
{"t":"Biostatistics","q":"When all values in a dataset are identical, mean, median, and mode are:","a":"Different","b":"Zero","c":"Equal","d":"Undefined","ans":"C"},
{"t":"Biostatistics","q":"Which measure of central tendency is least affected by sampling variation?","a":"Mode","b":"Median","c":"Mean","d":"Quartile","ans":"C"},
{"t":"Biostatistics","q":"Mean cannot be calculated for:","a":"Nominal data","b":"Interval data","c":"Ratio data","d":"Continuous data","ans":"A"},
{"t":"Biostatistics","q":"The graphical representation of cumulative frequency is called:","a":"Histogram","b":"Frequency polygon","c":"Ogive","d":"Bar chart","ans":"C"},
{"t":"Biostatistics","q":"The area of a histogram is proportional to:","a":"Class interval","b":"Frequency","c":"Percentage","d":"Mean","ans":"B"},
{"t":"Biostatistics","q":"The midpoint of a class interval is known as:","a":"Class width","b":"Class limit","c":"Class mark","d":"Class boundary","ans":"C"},
{"t":"Biostatistics","q":"Which of the following averages is most suitable for shoe size data?","a":"Mean","b":"Median","c":"Mode","d":"Geometric mean","ans":"C"},
{"t":"Biostatistics","q":"Median is obtained graphically from:","a":"Histogram","b":"Frequency polygon","c":"Ogive","d":"Bar diagram","ans":"C"},
{"t":"Biostatistics","q":"Which of the following is NOT a measure of central tendency?","a":"Mean","b":"Median","c":"Mode","d":"Standard deviation","ans":"D"},
{"t":"Biostatistics","q":"Mean is least appropriate measure when distribution is:","a":"Normal","b":"Symmetrical","c":"Skewed","d":"Continuous","ans":"C"},
{"t":"Biostatistics","q":"In a normal distribution:","a":"Mean > Median > Mode","b":"Mean < Median < Mode","c":"Mean = Median = Mode","d":"Mean ≠ Median ≠ Mode","ans":"C"},
{"t":"Biostatistics","q":"Which average is based on position rather than magnitude?","a":"Mean","b":"Median","c":"Arithmetic mean","d":"Weighted mean","ans":"B"},
{"t":"Biostatistics","q":"The most frequently occurring class in a distribution is called:","a":"Median class","b":"Mean class","c":"Modal class","d":"Central class","ans":"C"},
{"t":"Biostatistics","q":"Which measure is useful for quick estimation?","a":"Mean","b":"Median","c":"Mode","d":"Geometric mean","ans":"C"},
{"t":"Biostatistics","q":"If extreme values are present, which average is preferred?","a":"Mean","b":"Median","c":"Arithmetic mean","d":"Weighted mean","ans":"B"},
{"t":"Biostatistics","q":"Which average is most commonly used in health statistics?","a":"Median","b":"Mode","c":"Arithmetic mean","d":"Geometric mean","ans":"C"},
{"t":"Biostatistics","q":"The sum of deviations from the arithmetic mean is always:","a":"Maximum","b":"Minimum","c":"Zero","d":"One","ans":"C"},
{"t":"Biostatistics","q":"Median can be calculated for:","a":"Nominal data","b":"Ordinal data","c":"Interval data","d":"All except nominal","ans":"D"},
{"t":"Biostatistics","q":"Which of the following is a positional average?","a":"Mean","b":"Median","c":"Geometric mean","d":"Harmonic mean","ans":"B"},
{"t":"Biostatistics","q":"Mode is unreliable when:","a":"Data are qualitative","b":"Data are bimodal","c":"One value repeats frequently","d":"Distribution is skewed","ans":"B"},
{"t":"Biostatistics","q":"Which measure is easiest to understand by laypersons?","a":"Mean","b":"Median","c":"Mode","d":"Variance","ans":"C"},
{"t":"Biostatistics","q":"Arithmetic mean is unsuitable when:","a":"Data are symmetrical","b":"Data are skewed","c":"Sample size is large","d":"Values are continuous","ans":"B"},
{"t":"Biostatistics","q":"Median is also known as:","a":"Arithmetic average","b":"Positional average","c":"Frequency average","d":"Central limit","ans":"B"},
{"t":"Biostatistics","q":"Which measure of central tendency may not exist in a dataset?","a":"Mean","b":"Median","c":"Mode","d":"Arithmetic mean","ans":"C"},
{"t":"Biostatistics","q":"The value that divides data into two equal halves is:","a":"Mean","b":"Mode","c":"Median","d":"Quartile","ans":"C"},
{"t":"Biostatistics","q":"In community medicine, biostatistics is MOST important for:","a":"Individual diagnosis","b":"Drug prescription","c":"Planning and evaluation of health services","d":"Surgical management","ans":"C"},
{"t":"Biostatistics","q":"Which condition must be satisfied for the arithmetic mean to be zero?","a":"All observations are zero","b":"Sum of observations equals number of observations","c":"Sum of deviations from an arbitrary origin equals zero","d":"Sum of observations equals zero","ans":"D"},
{"t":"Biostatistics","q":"In a frequency distribution with unequal class intervals, the correct representation is done using:","a":"Simple histogram","b":"Frequency polygon","c":"Histogram with adjusted frequencies","d":"Bar diagram","ans":"C"},
{"t":"Biostatistics","q":"Which average is MOST affected if one extremely large value is added to the dataset?","a":"Mode","b":"Median","c":"Mean","d":"Quartile","ans":"C"},
{"t":"Biostatistics","q":"The median of grouped data is obtained using which specific class?","a":"Modal class","b":"Central class","c":"Median class","d":"Mean class","ans":"C"},
{"t":"Biostatistics","q":"If the mean of 10 observations is 20 and one observation is wrongly recorded as 50 instead of 30, the correct mean is:","a":"18","b":"22","c":"24","d":"20","ans":"A"},
{"t":"Biostatistics","q":"In a distribution where mean = 30 and median = 40, the distribution is:","a":"Symmetrical","b":"Positively skewed","c":"Negatively skewed","d":"Normal","ans":"C"},
{"t":"Biostatistics","q":"Which of the following measures CANNOT be determined graphically?","a":"Median","b":"Mode","c":"Mean","d":"Quartiles","ans":"C"},
{"t":"Biostatistics","q":"The geometric mean is preferred over arithmetic mean when dealing with:","a":"Income data","b":"Age distribution","c":"Rates and ratios","d":"Ordinal data","ans":"C"},
{"t":"Biostatistics","q":"The area under a frequency polygon represents:","a":"Mean","b":"Total frequency","c":"Class interval","d":"Median","ans":"B"},
{"t":"Biostatistics","q":"When two distributions have the same mean but different spreads, which measure detects this difference?","a":"Median","b":"Mode","c":"Range","d":"Mean","ans":"C"},
{"t":"Biostatistics","q":"If all observations in a dataset are increased by 5, the median will:","a":"Remain unchanged","b":"Increase by 5","c":"Double","d":"Become zero","ans":"B"},
{"t":"Biostatistics","q":"Which measure of central tendency is MOST suitable for describing socioeconomic status?","a":"Mean","b":"Mode","c":"Median","d":"Harmonic mean","ans":"C"},
{"t":"Biostatistics","q":"The formula for median in grouped data includes:","a":"Lower class boundary","b":"Upper class limit","c":"Class mark","d":"Arithmetic mean","ans":"A"},
{"t":"Biostatistics","q":"In which situation can the mode be misleading?","a":"Unimodal distribution","b":"Continuous data","c":"Bimodal distribution","d":"Skewed distribution","ans":"C"},
{"t":"Biostatistics","q":"Which of the following averages depends on all observations but NOT on their order?","a":"Median","b":"Mode","c":"Mean","d":"Quartile","ans":"C"},
{"t":"Biostatistics","q":"The sum of squared deviations from which value is MINIMUM?","a":"Median","b":"Mode","c":"Arithmetic mean","d":"Zero","ans":"C"},
{"t":"Biostatistics","q":"For open-ended distributions, which measure remains reliable?","a":"Mean","b":"Mode","c":"Median","d":"Range","ans":"C"},
{"t":"Biostatistics","q":"In a moderately skewed distribution, the relationship is best expressed as:","a":"Mean – Mode = 3(Median – Mean)","b":"Mean – Median = 3(Mean – Mode)","c":"Mean – Mode = 3(Mean – Median)","d":"Median – Mean = 3(Mode – Mean)","ans":"C"},
{"t":"Biostatistics","q":"Which diagram is LEAST appropriate for representing continuous data?","a":"Histogram","b":"Frequency polygon","c":"Ogive","d":"Pie chart","ans":"D"},
{"t":"Biostatistics","q":"The midpoint of a class interval is used directly in calculating:","a":"Median","b":"Mode","c":"Mean","d":"Quartiles","ans":"C"},
{"t":"Biostatistics","q":"Which measure of central tendency is a positional average?","a":"Mean","b":"Median","c":"Geometric mean","d":"Harmonic mean","ans":"B"},
{"t":"Biostatistics","q":"If the class intervals are unequal, which average becomes difficult to compute accurately?","a":"Median","b":"Mode","c":"Mean","d":"Quartile","ans":"C"},
{"t":"Biostatistics","q":"The cumulative frequency curve used to determine median is called:","a":"Less-than ogive","b":"More-than ogive","c":"Frequency polygon","d":"Histogram","ans":"A"},
{"t":"Biostatistics","q":"Which measure may have more than one value in a dataset?","a":"Mean","b":"Median","c":"Mode","d":"Quartile","ans":"C"},
{"t":"Biostatistics","q":"If Σx = 500 and n = 25, then mean is:","a":"10","b":"15","c":"20","d":"25","ans":"C"},
{"t":"Biostatistics","q":"Which average is MOST suitable for describing the incubation period of diseases?","a":"Mean","b":"Median","c":"Mode","d":"Geometric mean","ans":"B"},
{"t":"Biostatistics","q":"In an exactly symmetrical distribution:","a":"Mean > Median","b":"Mode > Mean","c":"Mean = Median = Mode","d":"Median > Mode","ans":"C"},
{"t":"Biostatistics","q":"Which measure cannot be located from an ogive?","a":"Median","b":"Quartile","c":"Percentile","d":"Mean","ans":"D"},
{"t":"Biostatistics","q":"If all observations are multiplied by a constant k, the variance becomes:","a":"k times","b":"k² times","c":"√k times","d":"Unchanged","ans":"B"},
{"t":"Biostatistics","q":"Which of the following averages is MOST influenced by sampling fluctuations?","a":"Mean","b":"Median","c":"Mode","d":"Quartile","ans":"C"},
{"t":"Biostatistics","q":"Which diagram represents both the shape and spread of a distribution?","a":"Bar diagram","b":"Histogram","c":"Pie chart","d":"Line diagram","ans":"B"},
{"t":"Biostatistics","q":"Median is preferred to mean in income data primarily because:","a":"It is easy to calculate","b":"It is unaffected by extremes","c":"It uses all observations","d":"It shows variability","ans":"B"},
{"t":"Biostatistics","q":"Which measure becomes zero when all observations are identical?","a":"Mean","b":"Median","c":"Mode","d":"Variance","ans":"D"},
{"t":"Biostatistics","q":"The modal class in grouped data is identified as the class with:","a":"Highest class mark","b":"Largest frequency","c":"Median position","d":"Lowest boundary","ans":"B"},
{"t":"Biostatistics","q":"In negatively skewed distribution, the tail is towards:","a":"Right side","b":"Left side","c":"Center","d":"Both sides","ans":"B"},
{"t":"Biostatistics","q":"Which average is theoretically the most stable?","a":"Mode","b":"Median","c":"Mean","d":"Quartile","ans":"C"},
{"t":"Biostatistics","q":"Which measure of central tendency is NOT suitable for qualitative data?","a":"Mode","b":"Median","c":"Mean","d":"Percentile","ans":"C"},
{"t":"Biostatistics","q":"The relationship Mean – Median = 0 indicates:","a":"Skewed distribution","b":"Bimodal distribution","c":"Symmetrical distribution","d":"Kurtosis","ans":"C"},
{"t":"Biostatistics","q":"In health statistics, which average is MOST frequently used?","a":"Mode","b":"Median","c":"Arithmetic mean","d":"Harmonic mean","ans":"C"},
{"t":"Biostatistics","q":"Which measure of central tendency is easiest to compute but least precise?","a":"Mean","b":"Median","c":"Mode","d":"Quartile","ans":"C"},
{"t":"Biostatistics","q":"If the median lies closer to the upper quartile, the distribution is:","a":"Positively skewed","b":"Negatively skewed","c":"Symmetrical","d":"Uniform","ans":"B"},
{"t":"Biostatistics","q":"Which of the following is NOT affected by change of origin?","a":"Mean","b":"Median","c":"Mode","d":"Variance","ans":"B"},
{"t":"Biostatistics","q":"The graphical method of locating mode uses:","a":"Ogive","b":"Histogram","c":"Line diagram","d":"Pie chart","ans":"B"},
{"t":"Biostatistics","q":"Which measure of average is based on logarithms?","a":"Arithmetic mean","b":"Median","c":"Geometric mean","d":"Mode","ans":"C"},
{"t":"Biostatistics","q":"Mean is unsuitable when:","a":"Data are symmetrical","b":"Distribution is skewed","c":"Sample size is large","d":"Data are continuous","ans":"B"},
{"t":"Biostatistics","q":"Which measure divides data into two equal halves?","a":"Mean","b":"Mode","c":"Median","d":"Range","ans":"C"},
{"t":"Biostatistics","q":"If a distribution has no repeating values, the mode is:","a":"Zero","b":"Mean","c":"Undefined","d":"Median","ans":"C"},
{"t":"Biostatistics","q":"Which average uses frequency as weight?","a":"Simple mean","b":"Weighted mean","c":"Median","d":"Mode","ans":"B"},
{"t":"Biostatistics","q":"Which of the following is LEAST influenced by extreme observations?","a":"Mean","b":"Median","c":"Arithmetic mean","d":"Weighted mean","ans":"B"},
{"t":"Biostatistics","q":"In community medicine research, the MOST appropriate average for mortality rates is:","a":"Median","b":"Mode","c":"Arithmetic mean","d":"Geometric mean","ans":"D"},
{"t":"Biostatistics","q":"Which condition must be satisfied for the application of a Z-test instead of a Student’s t-test?","a":"Unknown population variance with small sample","b":"Known population variance or large sample size","c":"Non-normal population distribution","d":"Ordinal scale data","ans":"B"},
{"t":"Biostatistics","q":"In hypothesis testing, the null hypothesis is generally framed as:","a":"A statement of difference","b":"A statement of causation","c":"A statement of no difference or no association","d":"A predictive statement","ans":"C"},
{"t":"Biostatistics","q":"Type I error in hypothesis testing refers to:","a":"Accepting a false null hypothesis","b":"Rejecting a true null hypothesis","c":"Accepting a true null hypothesis","d":"Rejecting a false alternative hypothesis","ans":"B"},
{"t":"Biostatistics","q":"The probability of committing a Type I error is denoted by:","a":"β","b":"1 − β","c":"α","d":"p","ans":"C"},
{"t":"Biostatistics","q":"Type II error occurs when:","a":"A true null hypothesis is rejected","b":"A false null hypothesis is accepted","c":"Sample size is very large","d":"P-value is less than alpha","ans":"B"},
{"t":"Biostatistics","q":"Power of a statistical test is defined as:","a":"1 − α","b":"α + β","c":"1 − β","d":"β","ans":"C"},
{"t":"Biostatistics","q":"Student’s t-test is preferred over Z-test when:","a":"Sample size is large and variance known","b":"Population variance is unknown and sample size is small","c":"Data are categorical","d":"Distribution is uniform","ans":"B"},
{"t":"Biostatistics","q":"Which of the following is an assumption of the Student’s t-test?","a":"Data must be categorical","b":"Population must be normally distributed","c":"Variance must be zero","d":"Observations must be paired","ans":"B"},
{"t":"Biostatistics","q":"Paired t-test is used when:","a":"Comparing two independent groups","b":"Comparing more than two groups","c":"Measurements are taken from the same subjects","d":"Population variance is known","ans":"C"},
{"t":"Biostatistics","q":"Which test is most appropriate for comparing proportions between two large independent samples?","a":"Paired t-test","b":"Chi-square test","c":"Z-test","d":"ANOVA","ans":"C"},
{"t":"Biostatistics","q":"Chi-square test is primarily used to test:","a":"Difference between means","b":"Correlation between variables","c":"Association between categorical variables","d":"Difference between variances","ans":"C"},
{"t":"Biostatistics","q":"One key assumption of the chi-square test is that:","a":"Expected frequency in each cell should be zero","b":"Expected frequency should generally be ≥5","c":"Data must be normally distributed","d":"Sample size must be small","ans":"B"},
{"t":"Biostatistics","q":"Degrees of freedom for a 2×3 contingency table are:","a":"2","b":"3","c":"4","d":"6","ans":"A"},
{"t":"Biostatistics","q":"If p-value is less than the level of significance, the correct decision is to:","a":"Accept null hypothesis","b":"Reject null hypothesis","c":"Increase sample size","d":"Commit Type II error","ans":"B"},
{"t":"Biostatistics","q":"A p-value of 0.03 at α = 0.05 indicates:","a":"Result is not statistically significant","b":"Null hypothesis should be accepted","c":"Result is statistically significant","d":"Beta error has occurred","ans":"C"},
{"t":"Biostatistics","q":"Confidence interval provides information about:","a":"Probability that hypothesis is true","b":"Range in which population parameter lies","c":"Power of the test","d":"Level of significance","ans":"B"},
{"t":"Biostatistics","q":"A 95% confidence interval implies that:","a":"95% of observations lie in the interval","b":"Parameter has 95% chance of being in interval","c":"Interval contains the true parameter in 95% of samples","d":"Alpha is 0.95","ans":"C"},
{"t":"Biostatistics","q":"Increasing sample size will generally:","a":"Increase alpha error","b":"Increase beta error","c":"Narrow confidence interval","d":"Reduce level of significance","ans":"C"},
{"t":"Biostatistics","q":"Which factor does NOT affect the width of a confidence interval?","a":"Sample size","b":"Variability of data","c":"Confidence level","d":"Type I error only","ans":"D"},
{"t":"Biostatistics","q":"Correlation analysis measures:","a":"Causation","b":"Difference between means","c":"Strength and direction of relationship","d":"Variance","ans":"C"},
{"t":"Biostatistics","q":"Pearson’s correlation coefficient ranges from:","a":"0 to +1","b":"−1 to +1","c":"−∞ to +∞","d":"0 to −1","ans":"B"},
{"t":"Biostatistics","q":"A correlation coefficient of −0.8 indicates:","a":"Weak positive correlation","b":"Strong positive correlation","c":"Weak negative correlation","d":"Strong negative correlation","ans":"D"},
{"t":"Biostatistics","q":"Zero correlation implies:","a":"Strong association","b":"No linear relationship","c":"No causal relationship","d":"Perfect relationship","ans":"B"},
{"t":"Biostatistics","q":"Regression analysis is used to:","a":"Measure association only","b":"Predict dependent variable","c":"Test independence","d":"Compare proportions","ans":"B"},
{"t":"Biostatistics","q":"In simple linear regression, the dependent variable is also called:","a":"Predictor","b":"Independent variable","c":"Response variable","d":"Explanatory constant","ans":"C"},
{"t":"Biostatistics","q":"The regression coefficient represents:","a":"Correlation strength","b":"Change in Y per unit change in X","c":"Intercept value","d":"Error variance","ans":"B"},
{"t":"Biostatistics","q":"If r = 0, the regression line will be:","a":"Vertical","b":"Horizontal","c":"Diagonal","d":"Curved","ans":"B"},
{"t":"Biostatistics","q":"Which of the following indicates stronger correlation?","a":"r = 0.2","b":"r = −0.3","c":"r = 0.6","d":"r = −0.1","ans":"C"},
{"t":"Biostatistics","q":"Coefficient of determination is given by:","a":"r","b":"√r","c":"r²","d":"1 − r","ans":"C"},
{"t":"Biostatistics","q":"r² indicates:","a":"Direction of correlation","b":"Percentage of variance explained","c":"Standard error","d":"Level of significance","ans":"B"},
{"t":"Biostatistics","q":"Hypothesis testing begins with:","a":"Selecting statistical test","b":"Formulating null hypothesis","c":"Calculating p-value","d":"Drawing conclusion","ans":"B"},
{"t":"Biostatistics","q":"Which step follows calculation of test statistic?","a":"Frame hypothesis","b":"Decide level of significance","c":"Compare with critical value / p-value","d":"Collect data","ans":"C"},
{"t":"Biostatistics","q":"Alpha error can be reduced by:","a":"Increasing alpha","b":"Decreasing sample size","c":"Lowering level of significance","d":"Increasing beta","ans":"C"},
{"t":"Biostatistics","q":"Beta error can be reduced by:","a":"Decreasing sample size","b":"Increasing sample size","c":"Increasing alpha","d":"Lowering power","ans":"B"},
{"t":"Biostatistics","q":"Which situation increases the risk of Type II error?","a":"Large sample size","b":"High power","c":"Very small sample size","d":"High alpha","ans":"C"},
{"t":"Biostatistics","q":"Two-tailed test is used when:","a":"Direction of difference is known","b":"Only increase is expected","c":"Difference in either direction is expected","d":"Variance is known","ans":"C"},
{"t":"Biostatistics","q":"One-tailed test is more powerful than two-tailed because:","a":"Alpha is doubled","b":"Critical region is concentrated in one tail","c":"Sample size is larger","d":"Variance is reduced","ans":"B"},
{"t":"Biostatistics","q":"Which test is suitable for testing association in a 2×2 table with small expected frequencies?","a":"Z-test","b":"Chi-square test","c":"Fisher’s exact test","d":"Paired t-test","ans":"C"},
{"t":"Biostatistics","q":"In regression equation Y = a + bX, ‘a’ represents:","a":"Slope","b":"Correlation","c":"Intercept","d":"Error term","ans":"C"},
{"t":"Biostatistics","q":"If correlation coefficient is high, it implies:","a":"Causation is confirmed","b":"Strong association only","c":"Null hypothesis is false","d":"Regression is invalid","ans":"B"},
{"t":"Biostatistics","q":"The standard error reflects:","a":"Variability of population","b":"Variability of sample statistic","c":"Level of confidence","d":"Strength of correlation","ans":"B"},
{"t":"Biostatistics","q":"Narrow confidence interval indicates:","a":"Less precision","b":"More variability","c":"More precision","d":"Higher alpha","ans":"C"},
{"t":"Biostatistics","q":"Increasing confidence level from 95% to 99% will:","a":"Narrow CI","b":"Widen CI","c":"Reduce standard error","d":"Reduce sample size","ans":"B"},
{"t":"Biostatistics","q":"Which of the following statements about p-value is correct?","a":"It is probability that null hypothesis is true","b":"It measures size of effect","c":"It is probability of observing result under null hypothesis","d":"It equals alpha","ans":"C"},
{"t":"Biostatistics","q":"If p = 0.08 and α = 0.05, the correct conclusion is:","a":"Reject null hypothesis","b":"Accept null hypothesis","c":"Result is statistically insignificant","d":"Type I error","ans":"C"},
{"t":"Biostatistics","q":"In inferential statistics, parameter refers to:","a":"Sample characteristic","b":"Population characteristic","c":"Test statistic","d":"Random error","ans":"B"},
{"t":"Biostatistics","q":"Statistic differs from parameter because statistic is:","a":"Fixed","b":"Unknown","c":"Based on sample","d":"Constant","ans":"C"},
{"t":"Biostatistics","q":"Which test compares means of two independent small samples?","a":"Z-test","b":"Paired t-test","c":"Unpaired t-test","d":"Chi-square test","ans":"C"},
{"t":"Biostatistics","q":"Which of the following affects both alpha and beta errors inversely?","a":"Sample size","b":"Level of significance","c":"Power","d":"Confidence interval","ans":"B"},
{"t":"Biostatistics","q":"Inferential biostatistics is mainly concerned with:","a":"Data collection","b":"Data presentation","c":"Drawing conclusions about population from sample","d":"Data summarization","ans":"C"},
{"t":"Epidemiology","q":"Infectious disease epidemiology primarily deals with:","a":"Genetic disorders","b":"Non-communicable diseases","c":"Distribution and determinants of infectious diseases","d":"Hospital-based infections only","ans":"C"},
{"t":"Epidemiology","q":"The agent–host–environment model is also known as:","a":"Web of causation","b":"Iceberg phenomenon","c":"Epidemiological triad","d":"Natural history of disease","ans":"C"},
{"t":"Epidemiology","q":"In the epidemiological triad, the host factor includes:","a":"Climate","b":"Vector density","c":"Immunity status","d":"Sanitation","ans":"C"},
{"t":"Epidemiology","q":"Which of the following is an agent factor?","a":"Nutritional status","b":"Socioeconomic condition","c":"Virulence","d":"Housing","ans":"C"},
{"t":"Epidemiology","q":"Environment in the epidemiological triad includes all EXCEPT:","a":"Climate","b":"Housing","c":"Age","d":"Sanitation","ans":"C"},
{"t":"Epidemiology","q":"Primary prevention is best defined as:","a":"Early diagnosis and treatment","b":"Prevention of complications","c":"Prevention of disease occurrence","d":"Rehabilitation","ans":"C"},
{"t":"Epidemiology","q":"Immunization is an example of:","a":"Secondary prevention","b":"Tertiary prevention","c":"Primordial prevention","d":"Primary prevention","ans":"D"},
{"t":"Epidemiology","q":"Secondary prevention mainly aims at:","a":"Reducing disability","b":"Preventing exposure","c":"Early detection and prompt treatment","d":"Rehabilitation","ans":"C"},
{"t":"Epidemiology","q":"Screening programs fall under:","a":"Primary prevention","b":"Secondary prevention","c":"Tertiary prevention","d":"Primordial prevention","ans":"B"},
{"t":"Epidemiology","q":"Tertiary prevention is mainly concerned with:","a":"Health promotion","b":"Specific protection","c":"Disability limitation and rehabilitation","d":"Early diagnosis","ans":"C"},
{"t":"Epidemiology","q":"Incidence rate measures:","a":"All existing cases at a given time","b":"New cases occurring over a period","c":"Mortality due to disease","d":"Case fatality","ans":"B"},
{"t":"Epidemiology","q":"Prevalence includes:","a":"Only old cases","b":"Only new cases","c":"Both new and existing cases","d":"Only diagnosed cases","ans":"C"},
{"t":"Epidemiology","q":"Point prevalence refers to:","a":"Disease occurrence over a year","b":"Disease occurrence over a month","c":"Disease present at a specific point in time","d":"Only new cases in a week","ans":"C"},
{"t":"Epidemiology","q":"Period prevalence differs from point prevalence because it:","a":"Excludes old cases","b":"Includes a time interval","c":"Includes only incidence","d":"Measures mortality","ans":"B"},
{"t":"Epidemiology","q":"Which relationship between incidence and prevalence is correct?","a":"Prevalence = Incidence × Duration","b":"Incidence = Prevalence × Duration","c":"Incidence = Prevalence ÷ Duration","d":"Prevalence = Incidence ÷ Duration","ans":"A"},
{"t":"Epidemiology","q":"A disease with high incidence but short duration will have:","a":"High prevalence","b":"Low prevalence","c":"Zero prevalence","d":"Constant prevalence","ans":"B"},
{"t":"Epidemiology","q":"Chronic diseases usually have:","a":"High incidence and low prevalence","b":"Low incidence and low prevalence","c":"Low incidence and high prevalence","d":"High incidence and high prevalence","ans":"C"},
{"t":"Epidemiology","q":"Case fatality rate is a measure of:","a":"Disease occurrence","b":"Disease severity","c":"Disease transmission","d":"Disease prevalence","ans":"B"},
{"t":"Epidemiology","q":"Which factor increases prevalence without affecting incidence?","a":"Improved cure rate","b":"Increased mortality","c":"Longer survival of patients","d":"Decreased duration of disease","ans":"C"},
{"t":"Epidemiology","q":"An epidemic is defined as:","a":"Constant presence of disease","b":"Sporadic occurrence","c":"Occurrence of cases in excess of normal expectancy","d":"Worldwide spread","ans":"C"},
{"t":"Epidemiology","q":"Endemic disease refers to:","a":"Sudden outbreak","b":"Constant presence in a region","c":"Global spread","d":"Seasonal variation","ans":"B"},
{"t":"Epidemiology","q":"Pandemic differs from epidemic in that it:","a":"Has fewer cases","b":"Is seasonal","c":"Spreads across countries or continents","d":"Occurs in one locality","ans":"C"},
{"t":"Epidemiology","q":"Herd immunity primarily protects:","a":"Immune individuals","b":"Unvaccinated susceptible individuals","c":"Only children","d":"Only elderly","ans":"B"},
{"t":"Epidemiology","q":"The minimum proportion of immune individuals required to interrupt transmission is called:","a":"Attack rate","b":"Case fatality rate","c":"Herd immunity threshold","d":"Incidence rate","ans":"C"},
{"t":"Epidemiology","q":"Attack rate is best described as:","a":"Incidence rate during an outbreak","b":"Prevalence at a point","c":"Mortality rate","d":"Case fatality rate","ans":"A"},
{"t":"Epidemiology","q":"Secondary attack rate measures:","a":"Disease severity","b":"Transmission among contacts","c":"Mortality","d":"Incubation period","ans":"B"},
{"t":"Epidemiology","q":"Reservoir of infection refers to:","a":"Mode of transmission","b":"Source of infection","c":"Habitat where agent normally lives","d":"Susceptible host","ans":"C"},
{"t":"Epidemiology","q":"Man is the only reservoir in:","a":"Plague","b":"Rabies","c":"Measles","d":"Anthrax","ans":"C"},
{"t":"Epidemiology","q":"Vector-borne transmission involves:","a":"Direct contact","b":"Droplet spread","c":"Living carriers","d":"Fomites","ans":"C"},
{"t":"Epidemiology","q":"Biological vectors differ from mechanical vectors because they:","a":"Do not transmit disease","b":"Allow multiplication of agent","c":"Are non-living","d":"Only contaminate food","ans":"B"},
{"t":"Epidemiology","q":"Incubation period is defined as:","a":"Time between exposure and appearance of symptoms","b":"Time between diagnosis and recovery","c":"Duration of illness","d":"Time of infectivity","ans":"A"},
{"t":"Epidemiology","q":"Which disease has the shortest incubation period?","a":"Measles","b":"Cholera","c":"Rabies","d":"Hepatitis B","ans":"B"},
{"t":"Epidemiology","q":"Infectivity refers to:","a":"Ability to cause severe disease","b":"Ability to produce toxins","c":"Ability to invade and multiply in host","d":"Ability to cause death","ans":"C"},
{"t":"Epidemiology","q":"Virulence is best described as:","a":"Ability to infect","b":"Severity of disease","c":"Mode of transmission","d":"Host resistance","ans":"B"},
{"t":"Epidemiology","q":"Pathogenicity measures the:","a":"Ability to spread","b":"Ability to cause infection","c":"Ability to cause clinical disease","d":"Ability to cause death","ans":"C"},
{"t":"Epidemiology","q":"Which prevention level includes isolation of cases?","a":"Primary","b":"Secondary","c":"Tertiary","d":"Primordial","ans":"B"},
{"t":"Epidemiology","q":"Health education regarding handwashing is an example of:","a":"Secondary prevention","b":"Tertiary prevention","c":"Primary prevention","d":"Rehabilitation","ans":"C"},
{"t":"Epidemiology","q":"Quarantine is applied to:","a":"Sick individuals","b":"Carriers","c":"Contacts of cases","d":"Immune individuals","ans":"C"},
{"t":"Epidemiology","q":"Surveillance in infectious diseases is mainly aimed at:","a":"Treatment","b":"Early detection of outbreaks","c":"Rehabilitation","d":"Health promotion only","ans":"B"},
{"t":"Epidemiology","q":"Sentinel surveillance is characterized by:","a":"Complete population coverage","b":"Selected reporting sites","c":"Passive data collection","d":"One-time survey","ans":"B"},
{"t":"Epidemiology","q":"Which factor decreases incidence but increases prevalence?","a":"Increased cure rate","b":"Prolonged survival","c":"Increased mortality","d":"Reduced transmission","ans":"B"},
{"t":"Epidemiology","q":"The iceberg phenomenon of disease indicates:","a":"All cases are visible","b":"Hidden burden of disease","c":"Seasonal variation","d":"Epidemic potential","ans":"B"},
{"t":"Epidemiology","q":"The most effective level of prevention for infectious diseases is:","a":"Secondary","b":"Tertiary","c":"Primary","d":"Rehabilitation","ans":"C"},
{"t":"Epidemiology","q":"Case definition in epidemiology is important for:","a":"Treatment decisions","b":"Uniform identification of cases","c":"Rehabilitation","d":"Prognosis","ans":"B"},
{"t":"Epidemiology","q":"A carrier is defined as a person who:","a":"Is immune","b":"Shows severe symptoms","c":"Harbors pathogen without symptoms","d":"Has recovered completely","ans":"C"},
{"t":"Epidemiology","q":"Which carrier state is most dangerous epidemiologically?","a":"Incubatory carrier","b":"Convalescent carrier","c":"Healthy carrier","d":"Temporary carrier","ans":"C"},
{"t":"Epidemiology","q":"R₀ (basic reproduction number) indicates:","a":"Severity of disease","b":"Duration of disease","c":"Transmission potential","d":"Mortality rate","ans":"C"},
{"t":"Epidemiology","q":"If R₀ is greater than 1, the disease will:","a":"Die out","b":"Remain constant","c":"Spread in population","d":"Become endemic immediately","ans":"C"},
{"t":"Epidemiology","q":"Which factor reduces R₀ most effectively?","a":"Increasing virulence","b":"Increasing host susceptibility","c":"Increasing immunity","d":"Increasing incubation period","ans":"C"},
{"t":"Epidemiology","q":"Infectious disease control programs primarily focus on:","a":"Host factors only","b":"Agent factors only","c":"Breaking the chain of transmission","d":"Treating complications","ans":"C"},
{"t":"Epidemiology","q":"The iceberg phenomenon of disease implies that:","a":"All cases of disease are clinically apparent","b":"Only severe cases are recorded","c":"Large proportion of disease remains hidden","d":"Disease occurs only in epidemics","ans":"C"},
{"t":"Epidemiology","q":"The visible part of the iceberg represents:","a":"Subclinical cases","b":"Latent infections","c":"Clinically apparent cases","d":"Carriers only","ans":"C"},
{"t":"Epidemiology","q":"The submerged portion of the iceberg mainly consists of:","a":"Fatal cases","b":"Diagnosed cases","c":"Asymptomatic and undiagnosed cases","d":"Hospitalized cases","ans":"C"},
{"t":"Epidemiology","q":"Iceberg phenomenon is MOST commonly associated with:","a":"Acute infections only","b":"Chronic diseases only","c":"Infectious diseases with many subclinical cases","d":"Surgical conditions","ans":"C"},
{"t":"Epidemiology","q":"Which disease best demonstrates the iceberg phenomenon?","a":"Rabies","b":"Measles","c":"Poliomyelitis","d":"Tetanus","ans":"C"},
{"t":"Epidemiology","q":"Iceberg phenomenon highlights the importance of:","a":"Hospital records","b":"Surveillance and screening","c":"Case fatality rate","d":"Treatment only","ans":"B"},
{"t":"Epidemiology","q":"The epidemiological significance of iceberg phenomenon lies in:","a":"Clinical management","b":"Resource wastage","c":"Hidden reservoir of infection","d":"Reduction in mortality","ans":"C"},
{"t":"Epidemiology","q":"Which condition has the LEAST iceberg effect?","a":"Hypertension","b":"Diabetes mellitus","c":"Poliomyelitis","d":"Rabies","ans":"D"},
{"t":"Epidemiology","q":"The iceberg phenomenon explains why:","a":"Prevalence is always less than incidence","b":"True magnitude of disease is underestimated","c":"Incidence equals prevalence","d":"All cases are reported","ans":"B"},
{"t":"Epidemiology","q":"Which of the following lies below the waterline of the iceberg?","a":"Notified cases","b":"Hospitalized cases","c":"Latent infections","d":"Fatal cases","ans":"C"},
{"t":"Epidemiology","q":"The chain of disease transmission consists of how many essential links?","a":"Three","b":"Four","c":"Five","d":"Six","ans":"D"},
{"t":"Epidemiology","q":"Which of the following is NOT a link in the chain of transmission?","a":"Agent","b":"Reservoir","c":"Vector","d":"Susceptible host","ans":"C"},
{"t":"Epidemiology","q":"The first link in the chain of transmission is:","a":"Mode of transmission","b":"Susceptible host","c":"Infectious agent","d":"Portal of exit","ans":"C"},
{"t":"Epidemiology","q":"Reservoir of infection refers to:","a":"Person who transmits disease","b":"Source of infection","c":"Natural habitat of the agent","d":"Portal of entry","ans":"C"},
{"t":"Epidemiology","q":"Portal of exit is the:","a":"Route through which agent enters host","b":"Route through which agent leaves reservoir","c":"Mode of transmission","d":"Susceptible host","ans":"B"},
{"t":"Epidemiology","q":"Which of the following is a portal of entry?","a":"Nose","b":"Blood","c":"Vector","d":"Reservoir","ans":"A"},
{"t":"Epidemiology","q":"Mode of transmission refers to:","a":"Survival of agent","b":"Growth of agent","c":"Method by which agent is transferred","d":"Host immunity","ans":"C"},
{"t":"Epidemiology","q":"Susceptible host is defined as:","a":"Carrier","b":"Immune person","c":"Person capable of developing disease","d":"Reservoir","ans":"C"},
{"t":"Epidemiology","q":"Breaking which link is MOST effective in controlling infectious diseases?","a":"Agent","b":"Reservoir","c":"Mode of transmission","d":"Host","ans":"C"},
{"t":"Epidemiology","q":"Which intervention breaks the reservoir link?","a":"Hand hygiene","b":"Isolation of cases","c":"Immunization","d":"Vector control","ans":"B"},
{"t":"Epidemiology","q":"Direct transmission includes all EXCEPT:","a":"Droplet spread","b":"Contact","c":"Transplacental transmission","d":"Vector-borne spread","ans":"D"},
{"t":"Epidemiology","q":"Indirect transmission involves:","a":"Physical contact","b":"Droplet nuclei","c":"Intermediate agent","d":"Skin contact","ans":"C"},
{"t":"Epidemiology","q":"Airborne transmission differs from droplet transmission because:","a":"Droplets are larger","b":"Droplet nuclei remain suspended longer","c":"Requires close contact","d":"Occurs through vectors","ans":"B"},
{"t":"Epidemiology","q":"Which disease is transmitted by droplet infection?","a":"Cholera","b":"Tuberculosis","c":"Typhoid","d":"Malaria","ans":"B"},
{"t":"Epidemiology","q":"Fomite transmission is best described as:","a":"Vector transmission","b":"Airborne spread","c":"Transmission through inanimate objects","d":"Vertical transmission","ans":"C"},
{"t":"Epidemiology","q":"Which disease is classically transmitted by fomites?","a":"Influenza","b":"Measles","c":"Trachoma","d":"Rabies","ans":"C"},
{"t":"Epidemiology","q":"Vehicle-borne transmission includes all EXCEPT:","a":"Water","b":"Food","c":"Blood","d":"Mosquito","ans":"D"},
{"t":"Epidemiology","q":"Vector-borne transmission involves:","a":"Inanimate objects","b":"Living carriers","c":"Direct contact","d":"Droplets","ans":"B"},
{"t":"Epidemiology","q":"Mechanical vectors differ from biological vectors because they:","a":"Allow multiplication of agent","b":"Are part of life cycle","c":"Carry agent passively","d":"Require incubation","ans":"C"},
{"t":"Epidemiology","q":"Biological transmission of malaria occurs through:","a":"Housefly","b":"Aedes mosquito","c":"Anopheles mosquito","d":"Culex mosquito","ans":"C"},
{"t":"Epidemiology","q":"Vertical transmission refers to transmission from:","a":"Adult to adult","b":"Child to adult","c":"Mother to child","d":"Vector to human","ans":"C"},
{"t":"Epidemiology","q":"Transplacental transmission is seen in:","a":"Malaria only","b":"HIV","c":"Tetanus","d":"Influenza","ans":"B"},
{"t":"Epidemiology","q":"Which mode of transmission is MOST difficult to control?","a":"Contact","b":"Vehicle-borne","c":"Airborne","d":"Vector-borne","ans":"C"},
{"t":"Epidemiology","q":"Isolation of cases interrupts which link of transmission?","a":"Agent","b":"Reservoir","c":"Mode of transmission","d":"Susceptible host","ans":"B"},
{"t":"Epidemiology","q":"Hand washing is MOST effective in preventing:","a":"Airborne transmission","b":"Vector-borne transmission","c":"Feco-oral transmission","d":"Vertical transmission","ans":"C"},
{"t":"Epidemiology","q":"Which disease spreads mainly through the feco-oral route?","a":"Influenza","b":"Tuberculosis","c":"Hepatitis A","d":"Measles","ans":"C"},
{"t":"Epidemiology","q":"Droplet infection requires a distance of:","a":">10 meters","b":"<1 meter","c":">5 meters","d":"Unlimited","ans":"B"},
{"t":"Epidemiology","q":"Which of the following is an example of contact transmission?","a":"Tuberculosis","b":"Measles","c":"Scabies","d":"Cholera","ans":"C"},
{"t":"Epidemiology","q":"Which factor MOST influences susceptibility of the host?","a":"Climate","b":"Immunity","c":"Vector density","d":"Sanitation","ans":"B"},
{"t":"Epidemiology","q":"Universal precautions are MOST important for preventing:","a":"Airborne transmission","b":"Blood-borne infections","c":"Feco-oral diseases","d":"Vector-borne diseases","ans":"B"},
{"t":"Epidemiology","q":"Which disease is transmitted through contaminated water?","a":"Typhoid","b":"Tuberculosis","c":"Influenza","d":"Rabies","ans":"A"},
{"t":"Epidemiology","q":"Chain of transmission can be broken at which stage?","a":"Only at reservoir","b":"Only at host","c":"At any link","d":"Only at agent","ans":"C"},
{"t":"Epidemiology","q":"Use of masks primarily interrupts:","a":"Reservoir","b":"Portal of exit","c":"Mode of transmission","d":"Susceptible host","ans":"C"},
{"t":"Epidemiology","q":"Chemoprophylaxis acts by protecting the:","a":"Agent","b":"Environment","c":"Host","d":"Reservoir","ans":"C"},
{"t":"Epidemiology","q":"Which disease has NO iceberg phenomenon?","a":"Polio","b":"Hypertension","c":"Diabetes","d":"Rabies","ans":"D"},
{"t":"Epidemiology","q":"Which transmission route is MOST associated with outbreaks?","a":"Contact","b":"Vehicle-borne","c":"Vertical","d":"Vector-borne","ans":"B"},
{"t":"Epidemiology","q":"Which intervention breaks the susceptible host link?","a":"Isolation","b":"Disinfection","c":"Immunization","d":"Quarantine","ans":"C"},
{"t":"Epidemiology","q":"Quarantine acts by interrupting:","a":"Agent","b":"Portal of exit","c":"Reservoir","d":"Mode of transmission","ans":"D"},
{"t":"Epidemiology","q":"Which disease spreads by airborne transmission?","a":"Cholera","b":"Typhoid","c":"Measles","d":"Hepatitis A","ans":"C"},
{"t":"Epidemiology","q":"The MOST important epidemiological significance of modes of transmission is to:","a":"Improve diagnosis","b":"Improve treatment","c":"Plan control measures","d":"Calculate incidence","ans":"C"},
{"t":"Epidemiology","q":"Chronic non-communicable diseases are best characterized by:","a":"Short duration and rapid recovery","b":"Infectious etiology","c":"Long duration and slow progression","d":"Seasonal occurrence","ans":"C"},
{"t":"Epidemiology","q":"The most important epidemiological feature of non-communicable diseases is:","a":"Epidemic potential","b":"Multifactorial causation","c":"Single agent causation","d":"Short incubation period","ans":"B"},
{"t":"Epidemiology","q":"The epidemiological triad in chronic diseases is replaced by:","a":"Iceberg phenomenon","b":"Chain of transmission","c":"Web of causation","d":"Natural history of disease","ans":"C"},
{"t":"Epidemiology","q":"Which level of prevention aims to prevent the emergence of risk factors?","a":"Primary","b":"Secondary","c":"Tertiary","d":"Primordial","ans":"D"},
{"t":"Epidemiology","q":"Lifestyle modification to prevent hypertension is an example of:","a":"Secondary prevention","b":"Tertiary prevention","c":"Primary prevention","d":"Rehabilitation","ans":"C"},
{"t":"Epidemiology","q":"Screening for cervical cancer falls under:","a":"Primordial prevention","b":"Primary prevention","c":"Secondary prevention","d":"Tertiary prevention","ans":"C"},
{"t":"Epidemiology","q":"Rehabilitation of stroke patients is an example of:","a":"Primary prevention","b":"Secondary prevention","c":"Tertiary prevention","d":"Primordial prevention","ans":"C"},
{"t":"Epidemiology","q":"Which cancer is MOST effectively preventable by vaccination?","a":"Breast cancer","b":"Cervical cancer","c":"Lung cancer","d":"Prostate cancer","ans":"B"},
{"t":"Epidemiology","q":"Tobacco cessation helps prevent all EXCEPT:","a":"Lung cancer","b":"Oral cancer","c":"Cervical cancer","d":"Cardiovascular disease","ans":"C"},
{"t":"Epidemiology","q":"The MOST common preventable cause of cancer worldwide is:","a":"Radiation","b":"Infection","c":"Tobacco use","d":"Alcohol","ans":"C"},
{"t":"Epidemiology","q":"Which infection is causally associated with gastric cancer?","a":"HPV","b":"EBV","c":"Helicobacter pylori","d":"Hepatitis B virus","ans":"C"},
{"t":"Epidemiology","q":"Preventable blindness in India is MOST commonly due to:","a":"Cataract","b":"Glaucoma","c":"Diabetic retinopathy","d":"Trachoma","ans":"A"},
{"t":"Epidemiology","q":"Vitamin A deficiency leads to blindness mainly by causing:","a":"Cataract","b":"Glaucoma","c":"Xerophthalmia","d":"Retinal detachment","ans":"C"},
{"t":"Epidemiology","q":"Trachoma prevention primarily involves:","a":"Chemotherapy","b":"Surgery","c":"SAFE strategy","d":"Vaccination","ans":"C"},
{"t":"Epidemiology","q":"Which component of SAFE strategy stands for Environmental improvement?","a":"S","b":"A","c":"F","d":"E","ans":"D"},
{"t":"Epidemiology","q":"Cardiovascular diseases are primarily caused by:","a":"Single pathogen","b":"Nutritional deficiency alone","c":"Combination of lifestyle and metabolic factors","d":"Genetic factors only","ans":"C"},
{"t":"Epidemiology","q":"The MOST important modifiable risk factor for coronary artery disease is:","a":"Age","b":"Sex","c":"Smoking","d":"Family history","ans":"C"},
{"t":"Epidemiology","q":"Hypertension prevention through salt reduction is an example of:","a":"Secondary prevention","b":"Tertiary prevention","c":"Primary prevention","d":"Rehabilitation","ans":"C"},
{"t":"Epidemiology","q":"The leading cause of death globally among NCDs is:","a":"Cancer","b":"Chronic respiratory diseases","c":"Diabetes mellitus","d":"Cardiovascular diseases","ans":"D"},
{"t":"Epidemiology","q":"Obesity increases cardiovascular risk mainly by increasing:","a":"HDL cholesterol","b":"Insulin sensitivity","c":"Blood pressure and dyslipidemia","d":"Bone density","ans":"C"},
{"t":"Epidemiology","q":"Which dietary factor is protective against cardiovascular diseases?","a":"Saturated fats","b":"Trans fats","c":"Dietary fiber","d":"Excess salt","ans":"C"},
{"t":"Epidemiology","q":"Primary prevention of cardiovascular disease includes:","a":"Thrombolysis","b":"Coronary bypass surgery","c":"Risk factor modification","d":"Cardiac rehabilitation","ans":"C"},
{"t":"Epidemiology","q":"Diabetes mellitus is best classified epidemiologically as:","a":"Acute disease","b":"Infectious disease","c":"Chronic non-communicable disease","d":"Degenerative disease only","ans":"C"},
{"t":"Epidemiology","q":"Screening for diabetes is an example of:","a":"Primary prevention","b":"Secondary prevention","c":"Tertiary prevention","d":"Primordial prevention","ans":"B"},
{"t":"Epidemiology","q":"Diabetic foot care to prevent amputation is:","a":"Primary prevention","b":"Secondary prevention","c":"Tertiary prevention","d":"Primordial prevention","ans":"C"},
{"t":"Epidemiology","q":"The MOST common nutritional deficiency disorder worldwide is:","a":"Protein-energy malnutrition","b":"Iron deficiency anemia","c":"Vitamin A deficiency","d":"Iodine deficiency","ans":"B"},
{"t":"Epidemiology","q":"Iron deficiency anemia prevention through food fortification is:","a":"Secondary prevention","b":"Tertiary prevention","c":"Primary prevention","d":"Rehabilitation","ans":"C"},
{"t":"Epidemiology","q":"Iodine deficiency disorder prevention is best achieved by:","a":"Vitamin supplementation","b":"Health education","c":"Universal salt iodization","d":"Screening","ans":"C"},
{"t":"Epidemiology","q":"Goiter due to iodine deficiency is classified as:","a":"Infectious disease","b":"Genetic disorder","c":"Nutritional deficiency disease","d":"Metabolic disorder","ans":"C"},
{"t":"Epidemiology","q":"Protein-energy malnutrition mainly affects:","a":"Elderly","b":"Adolescents","c":"Under-five children","d":"Pregnant women only","ans":"C"},
{"t":"Epidemiology","q":"Kwashiorkor differs from marasmus by presence of:","a":"Severe wasting","b":"Growth retardation","c":"Edema","d":"Muscle loss","ans":"C"},
{"t":"Epidemiology","q":"Which nutritional deficiency causes night blindness?","a":"Vitamin D","b":"Vitamin A","c":"Vitamin C","d":"Iron","ans":"B"},
{"t":"Epidemiology","q":"Prevention of nutritional diseases at community level primarily involves:","a":"Hospital treatment","b":"Mass drug administration","c":"Balanced diet and food security","d":"Surgical intervention","ans":"C"},
{"t":"Epidemiology","q":"Which cancer is strongly associated with tobacco chewing?","a":"Lung cancer","b":"Oral cancer","c":"Cervical cancer","d":"Colon cancer","ans":"B"},
{"t":"Epidemiology","q":"Regular physical activity mainly helps prevent:","a":"Tuberculosis","b":"Hypertension and diabetes","c":"Acute infections","d":"Genetic disorders","ans":"B"},
{"t":"Epidemiology","q":"The main goal of tertiary prevention in NCDs is:","a":"Prevent disease occurrence","b":"Early diagnosis","c":"Reduce complications and disability","d":"Health promotion","ans":"C"},
{"t":"Epidemiology","q":"Which of the following is a non-modifiable risk factor for cardiovascular disease?","a":"Smoking","b":"Physical inactivity","c":"Age","d":"Diet","ans":"C"},
{"t":"Epidemiology","q":"Population strategy for NCD prevention focuses on:","a":"High-risk individuals","b":"Entire population","c":"Hospital patients only","d":"Genetic screening","ans":"B"},
{"t":"Epidemiology","q":"High-risk strategy mainly targets:","a":"Whole population","b":"Healthy individuals","c":"Individuals with risk factors","d":"Children only","ans":"C"},
{"t":"Epidemiology","q":"The MOST cost-effective strategy for NCD prevention is:","a":"Hospital-based care","b":"Population-based prevention","c":"Intensive care","d":"Surgical intervention","ans":"B"},
{"t":"Epidemiology","q":"Which cancer screening is recommended at population level in many countries?","a":"Prostate cancer","b":"Pancreatic cancer","c":"Cervical cancer","d":"Brain tumor","ans":"C"},
{"t":"Epidemiology","q":"The main objective of preventable blindness programs is to:","a":"Treat glaucoma","b":"Reduce cataract surgery cost","c":"Reduce avoidable blindness","d":"Improve eye hospitals","ans":"C"},
{"t":"Epidemiology","q":"Diabetic retinopathy prevention mainly involves:","a":"Vitamin supplementation","b":"Good glycemic control","c":"Cataract surgery","d":"Antibiotics","ans":"B"},
{"t":"Epidemiology","q":"Which nutritional disease is prevented by vitamin D?","a":"Scurvy","b":"Pellagra","c":"Rickets","d":"Beriberi","ans":"C"},
{"t":"Epidemiology","q":"Excess intake of which nutrient increases cardiovascular risk?","a":"Polyunsaturated fat","b":"Dietary fiber","c":"Saturated fat","d":"Omega-3 fatty acids","ans":"C"},
{"t":"Epidemiology","q":"Community-based rehabilitation is part of:","a":"Primary prevention","b":"Secondary prevention","c":"Tertiary prevention","d":"Primordial prevention","ans":"C"},
{"t":"Epidemiology","q":"Which factor links obesity to diabetes mellitus?","a":"Increased insulin secretion","b":"Increased insulin sensitivity","c":"Insulin resistance","d":"Reduced glucose intake","ans":"C"},
{"t":"Epidemiology","q":"The epidemiological transition refers to shift from:","a":"Acute to chronic diseases","b":"Chronic to infectious diseases","c":"Nutritional to genetic diseases","d":"Individual to population diseases","ans":"A"},
{"t":"Epidemiology","q":"The MOST important preventive strategy for NCDs is:","a":"Early diagnosis","b":"Curative services","c":"Lifestyle modification","d":"Rehabilitation","ans":"C"},
{"t":"Epidemiology","q":"Chronic disease epidemiology is MOST useful for:","a":"Predicting epidemics","b":"Planning long-term health services","c":"Managing outbreaks","d":"Quarantine measures","ans":"B"},
{"t":"Research Methodology","q":"Quantitative study designs are primarily used to:","a":"Explore perceptions and experiences","b":"Generate hypotheses only","c":"Measure association and test hypotheses","d":"Conduct ethnographic research","ans":"C"},
{"t":"Research Methodology","q":"A cross-sectional study is best described as:","a":"Study with follow-up over time","b":"Snapshot study at a single point in time","c":"Experimental study","d":"Interventional study","ans":"B"},
{"t":"Research Methodology","q":"Cross-sectional studies are MOST suitable for estimating:","a":"Incidence","b":"Relative risk","c":"Prevalence","d":"Attributable risk","ans":"C"},
{"t":"Research Methodology","q":"A major limitation of cross-sectional studies is inability to:","a":"Measure prevalence","b":"Study multiple variables","c":"Establish temporal relationship","d":"Be conducted quickly","ans":"C"},
{"t":"Research Methodology","q":"Case-control studies are particularly useful for studying:","a":"Common diseases","b":"Rare diseases","c":"Diseases with short latency","d":"Incidence rates","ans":"B"},
{"t":"Research Methodology","q":"In a case-control study, subjects are selected based on:","a":"Exposure status","b":"Outcome status","c":"Duration of disease","d":"Risk factor level","ans":"B"},
{"t":"Research Methodology","q":"The measure of association commonly used in case-control studies is:","a":"Relative risk","b":"Incidence rate","c":"Odds ratio","d":"Attributable risk","ans":"C"},
{"t":"Research Methodology","q":"Which bias is MOST commonly associated with case-control studies?","a":"Selection bias","b":"Recall bias","c":"Measurement bias","d":"Confounding only","ans":"B"},
{"t":"Research Methodology","q":"Matching in case-control studies is done to control:","a":"Random error","b":"Bias due to chance","c":"Confounding","d":"Recall bias","ans":"C"},
{"t":"Research Methodology","q":"Cohort studies begin with selection of participants based on:","a":"Disease status","b":"Exposure status","c":"Outcome status","d":"Treatment received","ans":"B"},
{"t":"Research Methodology","q":"Cohort studies are BEST suited to measure:","a":"Prevalence","b":"Odds ratio","c":"Relative risk","d":"Case fatality rate","ans":"C"},
{"t":"Research Methodology","q":"A prospective cohort study involves:","a":"Looking back in time","b":"No follow-up","c":"Following exposed and unexposed groups forward","d":"Intervention by investigator","ans":"C"},
{"t":"Research Methodology","q":"Which of the following is an advantage of cohort studies?","a":"Less expensive","b":"Short duration","c":"Can study multiple outcomes","d":"Minimal loss to follow-up","ans":"C"},
{"t":"Research Methodology","q":"The MAIN disadvantage of cohort studies is:","a":"Recall bias","b":"Selection bias","c":"High cost and long duration","d":"Inability to calculate risk","ans":"C"},
{"t":"Research Methodology","q":"Loss to follow-up in cohort studies primarily leads to:","a":"Recall bias","b":"Selection bias","c":"Attrition bias","d":"Information bias","ans":"C"},
{"t":"Research Methodology","q":"Experimental studies differ from observational studies because they involve:","a":"Passive observation","b":"Random sampling only","c":"Investigator-controlled intervention","d":"Retrospective analysis","ans":"C"},
{"t":"Research Methodology","q":"The gold standard of experimental study design is:","a":"Cohort study","b":"Case-control study","c":"Randomized controlled trial","d":"Cross-sectional study","ans":"C"},
{"t":"Research Methodology","q":"Randomization in RCTs is done primarily to:","a":"Reduce sample size","b":"Eliminate confounding","c":"Reduce measurement error","d":"Improve compliance","ans":"B"},
{"t":"Research Methodology","q":"Allocation concealment is used in RCTs to prevent:","a":"Measurement bias","b":"Recall bias","c":"Selection bias","d":"Attrition bias","ans":"C"},
{"t":"Research Methodology","q":"Blinding in RCTs helps reduce:","a":"Confounding","b":"Selection bias","c":"Information bias","d":"Sampling error","ans":"C"},
{"t":"Research Methodology","q":"Double-blind randomized controlled trial means:","a":"Two interventions used","b":"Two outcomes measured","c":"Both participant and investigator are unaware of allocation","d":"Two control groups included","ans":"C"},
{"t":"Research Methodology","q":"Placebo is used in trials to control:","a":"Random error","b":"Observer bias","c":"Placebo effect","d":"Confounding","ans":"C"},
{"t":"Research Methodology","q":"Which phase of clinical trial assesses efficacy and side effects?","a":"Phase I","b":"Phase II","c":"Phase III","d":"Phase IV","ans":"B"},
{"t":"Research Methodology","q":"Phase IV clinical trials are conducted to study:","a":"Toxicity only","b":"Pharmacokinetics","c":"Post-marketing surveillance","d":"Dose ranging","ans":"C"},
{"t":"Research Methodology","q":"Non-randomized controlled trials differ from RCTs because:","a":"No control group is present","b":"Allocation is not random","c":"No intervention is given","d":"Outcome is not measured","ans":"B"},
{"t":"Research Methodology","q":"Which bias is MORE common in non-randomized trials?","a":"Recall bias","b":"Selection bias","c":"Reporting bias","d":"Sampling bias","ans":"B"},
{"t":"Research Methodology","q":"Field trials are usually conducted on:","a":"Diseased individuals","b":"Hospital patients","c":"Healthy populations","d":"Laboratory animals","ans":"C"},
{"t":"Research Methodology","q":"Community trials differ from field trials because they:","a":"Include individuals only","b":"Randomize communities","c":"Are hospital-based","d":"Are retrospective","ans":"B"},
{"t":"Research Methodology","q":"Which study design is MOST suitable to establish causality?","a":"Cross-sectional","b":"Case-control","c":"Cohort","d":"Randomized controlled trial","ans":"D"},
{"t":"Research Methodology","q":"Ethical issues are MOST significant in:","a":"Cross-sectional studies","b":"Case-control studies","c":"Cohort studies","d":"Experimental studies","ans":"D"},
{"t":"Research Methodology","q":"Intention-to-treat analysis means:","a":"Analyzing only compliant subjects","b":"Analyzing subjects as per treatment received","c":"Analyzing subjects as per original allocation","d":"Excluding dropouts","ans":"C"},
{"t":"Research Methodology","q":"Which design is fastest and least expensive?","a":"Cohort","b":"Case-control","c":"Randomized trial","d":"Community trial","ans":"B"},
{"t":"Research Methodology","q":"Which study design is BEST for studying rare exposures?","a":"Case-control","b":"Cross-sectional","c":"Cohort","d":"Experimental","ans":"C"},
{"t":"Research Methodology","q":"Temporality is BEST established in:","a":"Cross-sectional studies","b":"Case-control studies","c":"Cohort studies","d":"Ecological studies","ans":"C"},
{"t":"Research Methodology","q":"Which study design can estimate both incidence and prevalence?","a":"Cross-sectional","b":"Case-control","c":"Cohort","d":"Case series","ans":"C"},
{"t":"Research Methodology","q":"Selection of controls in case-control studies should be from:","a":"Hospital patients only","b":"General population always","c":"Same population as cases","d":"Only healthy individuals","ans":"C"},
{"t":"Research Methodology","q":"Which study design is most prone to recall bias?","a":"Cohort","b":"Cross-sectional","c":"Case-control","d":"Randomized trial","ans":"C"},
{"t":"Research Methodology","q":"Random error is reduced mainly by:","a":"Blinding","b":"Randomization","c":"Increasing sample size","d":"Matching","ans":"C"},
{"t":"Research Methodology","q":"External validity refers to:","a":"Absence of bias","b":"Precision of results","c":"Generalizability of findings","d":"Random error","ans":"C"},
{"t":"Research Methodology","q":"Internal validity is threatened MOST by:","a":"Large sample size","b":"Confounding","c":"External validity","d":"Generalizability","ans":"B"},
{"t":"Research Methodology","q":"Which study design cannot establish a sequence of events?","a":"Cohort","b":"Case-control","c":"Cross-sectional","d":"Experimental","ans":"C"},
{"t":"Research Methodology","q":"In cohort studies, exposed and unexposed groups should be:","a":"Similar in all aspects except exposure","b":"Selected randomly from population","c":"Matched only for age","d":"Selected from different populations","ans":"A"},
{"t":"Research Methodology","q":"Which trial design uses historical controls?","a":"Randomized trial","b":"Non-randomized trial","c":"Cross-over trial","d":"Factorial trial","ans":"B"},
{"t":"Research Methodology","q":"Factorial design allows:","a":"Study of one intervention","b":"Study of multiple interventions simultaneously","c":"No control group","d":"Only observational analysis","ans":"B"},
{"t":"Research Methodology","q":"Cross-over trials are NOT suitable when:","a":"Disease is chronic and stable","b":"Intervention has permanent effect","c":"Washout period is possible","d":"Sample size is small","ans":"B"},
{"t":"Research Methodology","q":"Which design is MOST affected by loss to follow-up?","a":"Case-control","b":"Cross-sectional","c":"Cohort","d":"Ecological","ans":"C"},
{"t":"Research Methodology","q":"In RCTs, randomization primarily ensures:","a":"Equal sample size","b":"Equal follow-up","c":"Comparable groups","d":"Complete blinding","ans":"C"},
{"t":"Research Methodology","q":"Which design is observational but longitudinal?","a":"Cross-sectional","b":"Case series","c":"Cohort","d":"Ecological","ans":"C"},
{"t":"Research Methodology","q":"Non-randomized trials are also known as:","a":"True experiments","b":"Quasi-experimental studies","c":"Descriptive studies","d":"Ecological studies","ans":"B"},
{"t":"Research Methodology","q":"Quantitative study designs are MOST useful for:","a":"Generating theories","b":"Measuring frequency and association","c":"Understanding behavior","d":"Exploring perceptions","ans":"B"},
{"t":"Research Methodology","q":"Measures of risk are primarily used to quantify:","a":"Disease severity","b":"Association between exposure and outcome","c":"Diagnostic accuracy","d":"Treatment effectiveness only","ans":"B"},
{"t":"Research Methodology","q":"Relative risk is defined as:","a":"Ratio of odds of exposure","b":"Ratio of incidence in exposed to incidence in unexposed","c":"Difference between two incidences","d":"Ratio of prevalence rates","ans":"B"},
{"t":"Research Methodology","q":"Relative risk can be directly calculated from:","a":"Cross-sectional studies","b":"Case-control studies","c":"Cohort studies","d":"Ecological studies","ans":"C"},
{"t":"Research Methodology","q":"Odds ratio is best defined as:","a":"Ratio of two risks","b":"Ratio of two prevalences","c":"Ratio of odds of exposure among cases to controls","d":"Difference in risk","ans":"C"},
{"t":"Research Methodology","q":"Odds ratio is the preferred measure in:","a":"Cohort studies","b":"Case-control studies","c":"Cross-sectional studies","d":"Randomized trials","ans":"B"},
{"t":"Research Methodology","q":"When a disease is rare, odds ratio approximates:","a":"Attributable risk","b":"Prevalence ratio","c":"Relative risk","d":"Risk difference","ans":"C"},
{"t":"Research Methodology","q":"If RR = 1, it indicates:","a":"Positive association","b":"Negative association","c":"No association","d":"Causation","ans":"C"},
{"t":"Research Methodology","q":"A relative risk greater than 1 implies:","a":"Protective exposure","b":"No effect","c":"Increased risk with exposure","d":"Bias","ans":"C"},
{"t":"Research Methodology","q":"Relative risk less than 1 suggests:","a":"Harmful exposure","b":"Protective effect","c":"No association","d":"Confounding","ans":"B"},
{"t":"Research Methodology","q":"Odds ratio equals 1 when:","a":"Exposure causes disease","b":"Exposure is protective","c":"There is no association","d":"Bias is present","ans":"C"},
{"t":"Research Methodology","q":"Which measure expresses excess risk due to exposure?","a":"Relative risk","b":"Odds ratio","c":"Attributable risk","d":"Population risk","ans":"C"},
{"t":"Research Methodology","q":"Attributable risk is calculated as:","a":"Ie / Iu","b":"Ie − Iu","c":"Iu − Ie","d":"Ie × Iu","ans":"B"},
{"t":"Research Methodology","q":"Population attributable risk reflects:","a":"Risk in exposed only","b":"Risk difference in unexposed","c":"Excess risk in whole population due to exposure","d":"Relative strength of association","ans":"C"},
{"t":"Research Methodology","q":"Which measure is MOST useful for public health planning?","a":"Odds ratio","b":"Relative risk","c":"Population attributable risk","d":"Case fatality rate","ans":"C"},
{"t":"Research Methodology","q":"Odds ratio is calculated from a 2×2 table as:","a":"ad/bc","b":"ab/cd","c":"(a+b)/(c+d)","d":"a/c","ans":"A"},
{"t":"Research Methodology","q":"Relative risk is calculated as:","a":"a/c","b":"ad/bc","c":"[a/(a+b)] / [c/(c+d)]","d":"(a+b)/(c+d)","ans":"C"},
{"t":"Research Methodology","q":"Which measure cannot be calculated if incidence is unknown?","a":"Odds ratio","b":"Relative risk","c":"Prevalence ratio","d":"Proportion","ans":"B"},
{"t":"Research Methodology","q":"In case-control studies, incidence cannot be calculated because:","a":"Sample size is small","b":"Follow-up is absent","c":"Exposure is rare","d":"Outcome is common","ans":"B"},
{"t":"Research Methodology","q":"Which statement about odds ratio is TRUE?","a":"It always equals relative risk","b":"It measures prevalence","c":"It can overestimate risk when disease is common","d":"It requires incidence data","ans":"C"},
{"t":"Research Methodology","q":"Association between exposure and disease does NOT imply:","a":"Statistical relationship","b":"Temporal sequence","c":"Causation","d":"Measurable link","ans":"C"},
{"t":"Research Methodology","q":"The strongest evidence for causation comes from:","a":"Cross-sectional studies","b":"Case-control studies","c":"Cohort studies","d":"Randomized controlled trials","ans":"D"},
{"t":"Research Methodology","q":"Temporality as a criterion of causation means:","a":"Exposure precedes disease","b":"Disease precedes exposure","c":"Both occur together","d":"No time relationship","ans":"A"},
{"t":"Research Methodology","q":"Which is NOT a Bradford Hill criterion?","a":"Consistency","b":"Specificity","c":"Plausibility","d":"Randomization","ans":"D"},
{"t":"Research Methodology","q":"Strength of association is best reflected by:","a":"P-value","b":"Relative risk magnitude","c":"Sample size","d":"Confidence interval width","ans":"B"},
{"t":"Research Methodology","q":"Biological plausibility refers to:","a":"Statistical significance","b":"Dose-response relationship","c":"Logical biological explanation","d":"Temporal sequence","ans":"C"},
{"t":"Research Methodology","q":"Consistency criterion implies:","a":"Same result in one study","b":"Reproducibility across different studies","c":"Large sample size","d":"Absence of bias","ans":"B"},
{"t":"Research Methodology","q":"Dose-response relationship supports causation because:","a":"Exposure is common","b":"Risk increases with exposure level","c":"Disease is severe","d":"Outcome is rare","ans":"B"},
{"t":"Research Methodology","q":"Which criterion is considered ESSENTIAL for causation?","a":"Strength","b":"Consistency","c":"Temporality","d":"Specificity","ans":"C"},
{"t":"Research Methodology","q":"Specificity criterion is considered weakest because:","a":"Diseases have single causes","b":"Exposures cause multiple diseases","c":"It is always present","d":"It proves causation","ans":"B"},
{"t":"Research Methodology","q":"Which measure expresses the proportion of disease among exposed attributable to exposure?","a":"Relative risk","b":"Attributable fraction among exposed","c":"Odds ratio","d":"Prevalence ratio","ans":"B"},
{"t":"Research Methodology","q":"Attributable fraction among exposed is calculated as:","a":"(RR − 1) / RR","b":"RR − 1","c":"1 / RR","d":"Ie − Iu","ans":"A"},
{"t":"Research Methodology","q":"Population attributable fraction depends on all EXCEPT:","a":"Relative risk","b":"Prevalence of exposure","c":"Sample size","d":"Outcome frequency","ans":"C"},
{"t":"Research Methodology","q":"Which measure best answers “How much disease can be prevented if exposure is removed?”","a":"Relative risk","b":"Odds ratio","c":"Population attributable risk","d":"Case fatality rate","ans":"C"},
{"t":"Research Methodology","q":"If OR < 1, the exposure is considered:","a":"Harmful","b":"Neutral","c":"Protective","d":"Confounded","ans":"C"},
{"t":"Research Methodology","q":"Confidence interval of RR that includes 1 indicates:","a":"Strong association","b":"Statistical significance","c":"No statistical significance","d":"Causation","ans":"C"},
{"t":"Research Methodology","q":"Which measure is symmetrical with respect to disease and exposure?","a":"Relative risk","b":"Odds ratio","c":"Attributable risk","d":"Incidence rate","ans":"B"},
{"t":"Research Methodology","q":"Odds ratio is especially useful when:","a":"Disease is common","b":"Incidence is known","c":"Retrospective design is used","d":"Follow-up is possible","ans":"C"},
{"t":"Research Methodology","q":"Which factor can create a false association?","a":"Temporality","b":"Consistency","c":"Confounding","d":"Dose-response","ans":"C"},
{"t":"Research Methodology","q":"Confounding occurs when:","a":"Exposure causes disease","b":"A third factor is related to both exposure and outcome","c":"Sample size is small","d":"Random error occurs","ans":"B"},
{"t":"Research Methodology","q":"Which method helps control confounding at the analysis stage?","a":"Randomization","b":"Matching","c":"Stratification","d":"Blinding","ans":"C"},
{"t":"Research Methodology","q":"Effect modification differs from confounding because it:","a":"Is a bias","b":"Distorts true association","c":"Represents real variation of effect","d":"Must be eliminated","ans":"C"},
{"t":"Research Methodology","q":"Which study design provides the most valid estimate of RR?","a":"Case-control","b":"Cross-sectional","c":"Cohort","d":"Ecological","ans":"C"},
{"t":"Research Methodology","q":"Which association is most likely causal?","a":"Weak, inconsistent, no temporality","b":"Strong, consistent, biologically plausible","c":"Statistically significant only","d":"Based on single study","ans":"B"},
{"t":"Research Methodology","q":"Hill’s criteria were proposed to:","a":"Prove causation definitively","b":"Disprove association","c":"Aid judgment about causation","d":"Replace statistical tests","ans":"C"},
{"t":"Research Methodology","q":"Which criterion asks whether removal of exposure reduces disease?","a":"Consistency","b":"Experiment","c":"Coherence","d":"Specificity","ans":"B"},
{"t":"Research Methodology","q":"Coherence criterion implies:","a":"Agreement with existing knowledge","b":"Strong statistical association","c":"Temporal relationship","d":"Experimental proof","ans":"A"},
{"t":"Research Methodology","q":"Which measure is dimensionless?","a":"Incidence rate","b":"Relative risk","c":"Attributable risk","d":"Prevalence rate","ans":"B"},
{"t":"Research Methodology","q":"Which measure is expressed in absolute terms?","a":"Relative risk","b":"Odds ratio","c":"Attributable risk","d":"Correlation coefficient","ans":"C"},
{"t":"Research Methodology","q":"A very high RR with wide confidence interval suggests:","a":"Precise estimate","b":"Large sample size","c":"Imprecise estimate","d":"No association","ans":"C"},
{"t":"Research Methodology","q":"Measures of risk are MOST important for:","a":"Clinical diagnosis","b":"Individual treatment","c":"Etiological research and prevention","d":"Rehabilitation planning","ans":"C"},
{"t":"Research Methodology","q":"Validity of a screening test refers to its ability to:","a":"Give consistent results","b":"Measure what it is intended to measure","c":"Be easily performed","d":"Be cost-effective","ans":"B"},
{"t":"Research Methodology","q":"Reliability of a test is concerned with:","a":"Accuracy","b":"Consistency and reproducibility","c":"Predictive value","d":"Sensitivity only","ans":"B"},
{"t":"Research Methodology","q":"A test can be reliable but not valid because it:","a":"Gives random results","b":"Gives consistent but inaccurate results","c":"Has low sensitivity","d":"Has low specificity","ans":"B"},
{"t":"Research Methodology","q":"Inter-observer reliability refers to:","a":"Same observer repeating measurement","b":"Different observers giving similar results","c":"Accuracy of measurement","d":"Validity of instrument","ans":"B"},
{"t":"Research Methodology","q":"Intra-observer reliability assesses:","a":"Accuracy of diagnosis","b":"Agreement between two observers","c":"Consistency of same observer over time","d":"Predictive ability","ans":"C"},
{"t":"Research Methodology","q":"Sensitivity of a screening test is the ability to:","a":"Identify true negatives","b":"Identify true positives","c":"Exclude disease","d":"Predict future disease","ans":"B"},
{"t":"Research Methodology","q":"Specificity of a screening test is the ability to:","a":"Identify true positives","b":"Identify false positives","c":"Identify true negatives","d":"Detect disease early","ans":"C"},
{"t":"Research Methodology","q":"A highly sensitive test is most useful for:","a":"Confirming disease","b":"Ruling in disease","c":"Screening to rule out disease","d":"Estimating prevalence","ans":"C"},
{"t":"Research Methodology","q":"A highly specific test is best used for:","a":"Mass screening","b":"Confirmatory diagnosis","c":"Early detection","d":"Surveillance","ans":"B"},
{"t":"Research Methodology","q":"The mnemonic “SnNout” implies:","a":"Sensitive test when positive rules in disease","b":"Sensitive test when negative rules out disease","c":"Specific test when negative rules out disease","d":"Specific test when positive rules in disease","ans":"B"},
{"t":"Research Methodology","q":"The mnemonic “SpPin” implies:","a":"Specific test when positive rules in disease","b":"Specific test when negative rules out disease","c":"Sensitive test when positive rules in disease","d":"Sensitive test when negative rules out disease","ans":"A"},
{"t":"Research Methodology","q":"Predictive value of a test depends on:","a":"Sensitivity only","b":"Specificity only","c":"Disease prevalence","d":"Sample size only","ans":"C"},
{"t":"Research Methodology","q":"Positive predictive value is defined as:","a":"Probability that a person with disease tests positive","b":"Probability that a person without disease tests negative","c":"Probability that a person with positive test has disease","d":"Probability that a person with negative test has disease","ans":"C"},
{"t":"Research Methodology","q":"Negative predictive value is:","a":"Probability that test is negative in disease","b":"Probability that person with negative test is disease-free","c":"Probability of false negatives","d":"Probability of true positives","ans":"B"},
{"t":"Research Methodology","q":"Increasing prevalence of disease will:","a":"Increase NPV","b":"Decrease PPV","c":"Increase PPV","d":"Not affect predictive values","ans":"C"},
{"t":"Research Methodology","q":"An ideal screening test should be all EXCEPT:","a":"Highly sensitive","b":"Highly specific","c":"Acceptable to population","d":"Definitive diagnostic test","ans":"D"},
{"t":"Research Methodology","q":"Screening is defined as:","a":"Diagnosis of disease","b":"Treatment of disease","c":"Presumptive identification of unrecognized disease","d":"Rehabilitation","ans":"C"},
{"t":"Research Methodology","q":"Screening programs are justified only when:","a":"Disease is rare","b":"Disease has no treatment","c":"Early detection improves outcome","d":"Test is expensive","ans":"C"},
{"t":"Research Methodology","q":"Lead time bias in screening results in:","a":"True increase in survival","b":"Apparent increase in survival without changing outcome","c":"False positive results","d":"Reduced incidence","ans":"B"},
{"t":"Research Methodology","q":"Length bias occurs because screening is more likely to detect:","a":"Rapidly progressing cases","b":"Severe cases","c":"Slowly progressing cases","d":"Fatal cases","ans":"C"},
{"t":"Research Methodology","q":"Overdiagnosis bias refers to:","a":"Missed diagnosis","b":"Diagnosis of disease that would not cause harm","c":"False negative results","d":"Incorrect treatment","ans":"B"},
{"t":"Research Methodology","q":"Validity of a screening test is measured by:","a":"Sensitivity and specificity","b":"Predictive values","c":"Reliability","d":"Accuracy alone","ans":"A"},
{"t":"Research Methodology","q":"Reliability can be improved by:","a":"Increasing disease prevalence","b":"Standardization of procedures","c":"Increasing sensitivity","d":"Reducing specificity","ans":"B"},
{"t":"Research Methodology","q":"Ethical principle of autonomy emphasizes:","a":"Doing good","b":"Avoiding harm","c":"Respecting participant’s decision","d":"Fair distribution of benefits","ans":"C"},
{"t":"Research Methodology","q":"Beneficence in research ethics means:","a":"Do no harm","b":"Maximize benefits","c":"Respect autonomy","d":"Ensure justice","ans":"B"},
{"t":"Research Methodology","q":"Non-maleficence refers to:","a":"Fair selection of subjects","b":"Avoiding harm to participants","c":"Obtaining consent","d":"Providing compensation","ans":"B"},
{"t":"Research Methodology","q":"Justice in research ethics ensures:","a":"Voluntary participation","b":"Risk-benefit balance","c":"Fair selection and distribution","d":"Confidentiality","ans":"C"},
{"t":"Research Methodology","q":"Informed consent must include all EXCEPT:","a":"Purpose of study","b":"Risks and benefits","c":"Guaranteed cure","d":"Voluntary participation","ans":"C"},
{"t":"Research Methodology","q":"Informed consent should be obtained:","a":"After study completion","b":"Before enrollment","c":"Only from relatives","d":"Only for high-risk studies","ans":"B"},
{"t":"Research Methodology","q":"Confidentiality in research means:","a":"Publishing all data","b":"Revealing participant identity","c":"Protecting participant information","d":"Sharing data freely","ans":"C"},
{"t":"Research Methodology","q":"Ethical clearance for research is given by:","a":"Hospital director","b":"Research supervisor","c":"Institutional Ethics Committee","d":"Funding agency","ans":"C"},
{"t":"Research Methodology","q":"Vulnerable populations in research include:","a":"Doctors","b":"Adults","c":"Prisoners","d":"Researchers","ans":"C"},
{"t":"Research Methodology","q":"Research involving human subjects must comply with:","a":"Clinical guidelines only","b":"Ethical principles and regulations","c":"Researcher preference","d":"Funding agency rules only","ans":"B"},
{"t":"Research Methodology","q":"The Declaration of Helsinki relates to:","a":"Animal experimentation","b":"Human research ethics","c":"Laboratory safety","d":"Drug manufacturing","ans":"B"},
{"t":"Research Methodology","q":"Which situation requires special ethical justification?","a":"Anonymous survey","b":"Observational study","c":"Research involving children","d":"Retrospective record review","ans":"C"},
{"t":"Research Methodology","q":"Conflict of interest in research refers to:","a":"Multiple authorship","b":"Financial or personal influence on research","c":"Ethical approval delay","d":"Data analysis error","ans":"B"},
{"t":"Research Methodology","q":"Which is an example of unethical research practice?","a":"Peer review","b":"Plagiarism","c":"Data sharing","d":"Replication","ans":"B"},
{"t":"Research Methodology","q":"Fabrication in research means:","a":"Copying others’ work","b":"Making up data or results","c":"Improper citation","d":"Selective reporting","ans":"B"},
{"t":"Research Methodology","q":"Falsification refers to:","a":"Inventing data","b":"Manipulating research data","c":"Publishing negative results","d":"Peer reviewing","ans":"B"},
{"t":"Research Methodology","q":"Ethical principle MOST relevant to screening programs is:","a":"Autonomy","b":"Beneficence","c":"Justice","d":"Non-maleficence","ans":"D"},
{"t":"Research Methodology","q":"A screening test with low specificity will result in:","a":"Many false negatives","b":"Many false positives","c":"Low sensitivity","d":"High PPV","ans":"B"},
{"t":"Research Methodology","q":"Which bias is directly related to validity of screening?","a":"Recall bias","b":"Selection bias","c":"Lead time bias","d":"Confounding","ans":"C"},
{"t":"Research Methodology","q":"Which ethical principle supports right to withdraw from study?","a":"Justice","b":"Beneficence","c":"Autonomy","d":"Non-maleficence","ans":"C"},
{"t":"Research Methodology","q":"Research misconduct includes all EXCEPT:","a":"Fabrication","b":"Falsification","c":"Honest error","d":"Plagiarism","ans":"C"},
{"t":"Research Methodology","q":"A screening test suitable for mass use should preferably be:","a":"Invasive","b":"Expensive","c":"Simple and safe","d":"Highly technical","ans":"C"},
{"t":"Research Methodology","q":"Which measure reflects overall correctness of a test?","a":"Sensitivity","b":"Specificity","c":"Accuracy","d":"Predictive value","ans":"C"},
{"t":"Research Methodology","q":"Ethical research requires that risks should be:","a":"Ignored","b":"Greater than benefits","c":"Minimized and justified","d":"Undefined","ans":"C"},
{"t":"Research Methodology","q":"Who is responsible for ethical conduct of research?","a":"Ethics committee only","b":"Funding agency","c":"Principal investigator","d":"Journal editor","ans":"C"},
{"t":"Research Methodology","q":"Screening differs from diagnosis because screening is:","a":"Definitive","b":"Presumptive","c":"Therapeutic","d":"Curative","ans":"B"},
{"t":"Research Methodology","q":"Validity, reliability, and ethics together ensure:","a":"Fast research","b":"Cheap research","c":"High-quality and trustworthy research","d":"Large sample size","ans":"C"},
{"t":"Miscellaneous","q":"In an outbreak investigation, the FIRST epidemiological step after confirming diagnosis is to:","a":"Identify risk factors","b":"Define and identify cases","c":"Implement control measures","d":"Formulate hypothesis","ans":"B"},
{"t":"Miscellaneous","q":"A disease with low incidence but high prevalence MOST likely has:","a":"High mortality","b":"Short duration","c":"Long duration","d":"High case fatality","ans":"C"},
{"t":"Miscellaneous","q":"Which demographic indicator BEST reflects socioeconomic development?","a":"Crude birth rate","b":"Crude death rate","c":"Infant mortality rate","d":"Sex ratio","ans":"C"},
{"t":"Miscellaneous","q":"In a population where life expectancy is increasing but birth rate remains constant, the population structure will show:","a":"Expanding pyramid","b":"Stationary pyramid","c":"Contracting pyramid","d":"Inverted pyramid","ans":"C"},
{"t":"Miscellaneous","q":"The most sensitive indicator of health system performance is:","a":"Maternal mortality rate","b":"Infant mortality rate","c":"Life expectancy","d":"Crude death rate","ans":"B"},
{"t":"Miscellaneous","q":"A screening test with very high sensitivity but low specificity is MOST likely to be used for:","a":"Confirmatory diagnosis","b":"Treatment decisions","c":"Initial mass screening","d":"Prognosis","ans":"C"},
{"t":"Miscellaneous","q":"In a cohort study, if loss to follow-up is higher in exposed group, the most likely bias introduced is:","a":"Recall bias","b":"Measurement bias","c":"Attrition bias","d":"Selection bias","ans":"C"},
{"t":"Miscellaneous","q":"Which health program component primarily aims to reduce inequity rather than overall disease burden?","a":"High-risk strategy","b":"Population strategy","c":"Targeted universalism","d":"Opportunistic screening","ans":"A"},
{"t":"Miscellaneous","q":"A disease that shows iceberg phenomenon, long latency, multifactorial causation, and no single necessary cause is MOST likely:","a":"Measles","b":"Tuberculosis","c":"Hypertension","d":"Cholera","ans":"C"},
{"t":"Miscellaneous","q":"The epidemiological transition theory describes a shift from:","a":"Infectious to genetic diseases","b":"Communicable to non-communicable diseases","c":"Acute to traumatic diseases","d":"Nutritional to occupational diseases","ans":"B"},
{"t":"Miscellaneous","q":"A 45-year-old asymptomatic man is detected to have hypertension during a community screening program. He receives lifestyle advice and antihypertensive drugs to prevent stroke and myocardial infarction. This intervention best represents:","a":"Primordial prevention","b":"Primary prevention","c":"Secondary prevention","d":"Tertiary prevention","ans":"C"},
{"t":"Miscellaneous","q":"In a case-control study assessing association between smoking and lung cancer, controls are selected from orthopedic ward patients. The MOST serious issue with this approach is:","a":"Recall bias","b":"Berkson’s bias","c":"Confounding","d":"Lead time bias","ans":"B"},
{"t":"Miscellaneous","q":"A screening test has sensitivity 95%, specificity 60%, and disease prevalence 1%. The major programmatic consequence of using this test will be:","a":"Large number of false negatives","b":"Low negative predictive value","c":"Large number of false positives","d":"Missed cases","ans":"C"},
{"t":"Miscellaneous","q":"A disease is transmitted by droplets, has a short incubation period, and shows seasonal peaks. The MOST effective immediate control measure during outbreak is:","a":"Mass immunization","b":"Case isolation","c":"Chemoprophylaxis","d":"Vector control","ans":"B"},
{"t":"Miscellaneous","q":"A new vaccine shows 80% efficacy in trials but poor effectiveness in field conditions. The MOST plausible explanation is:","a":"Low biological potency","b":"Poor cold chain maintenance","c":"Selection bias","d":"Herd immunity effect","ans":"B"},
{"t":"Miscellaneous","q":"A community has high relative risk for cardiovascular disease but low population attributable risk. This indicates:","a":"Exposure is rare","b":"Disease is rare","c":"Exposure is very common","d":"Relative risk is incorrect","ans":"A"},
{"t":"Miscellaneous","q":"In a randomized controlled trial, allocation concealment primarily prevents:","a":"Measurement bias","b":"Confounding","c":"Selection bias","d":"Attrition bias","ans":"C"},
{"t":"Miscellaneous","q":"A national screening program detects many early-stage cancers but mortality remains unchanged after 10 years. This phenomenon is BEST explained by:","a":"Lead time bias","b":"Length bias","c":"Overdiagnosis","d":"Selection bias","ans":"C"},
{"t":"Miscellaneous","q":"During an outbreak, secondary attack rate is MOST useful to assess:","a":"Disease severity","b":"Effectiveness of treatment","c":"Transmissibility among contacts","d":"Case fatality","ans":"C"},
{"t":"Miscellaneous","q":"A researcher reports a very narrow confidence interval with a small sample size. The MOST likely explanation is:","a":"High variability","b":"Calculation error","c":"High confidence level","d":"Selection bias","ans":"B"},
{"t":"Miscellaneous","q":"Which indicator BEST reflects effectiveness of antenatal care services?","a":"Crude birth rate","b":"Neonatal mortality rate","c":"Maternal mortality ratio","d":"Total fertility rate","ans":"C"},
{"t":"Miscellaneous","q":"In Bradford Hill criteria, the ONLY mandatory criterion for causation is:","a":"Strength","b":"Consistency","c":"Temporality","d":"Plausibility","ans":"C"},
{"t":"Miscellaneous","q":"A study that compares average salt intake and stroke mortality across countries is an example of:","a":"Case-control study","b":"Cohort study","c":"Ecological study","d":"Cross-sectional study","ans":"C"},
{"t":"Miscellaneous","q":"Which measure is MOST appropriate to assess burden of disease combining mortality and morbidity?","a":"IMR","b":"QALY","c":"DALY","d":"CFR","ans":"C"},
{"t":"Miscellaneous","q":"Which nutritional deficiency has the STRONGEST association with neural tube defects?","a":"Vitamin B12","b":"Iron","c":"Folic acid","d":"Iodine","ans":"C"},
{"t":"Miscellaneous","q":"A screening test acceptable ethically MUST ensure:","a":"High sensitivity only","b":"Availability of confirmatory test and treatment","c":"Low cost only","d":"High prevalence of disease","ans":"B"},
{"t":"Miscellaneous","q":"Which disease control strategy aims at reducing incidence to zero in a defined area?","a":"Control","b":"Elimination","c":"Eradication","d":"Mitigation","ans":"B"},
{"t":"Miscellaneous","q":"Global eradication has been achieved ONLY for:","a":"Measles","b":"Polio","c":"Smallpox","d":"Neonatal tetanus","ans":"C"},
{"t":"Miscellaneous","q":"Which health financing mechanism MOST strongly promotes equity?","a":"Out-of-pocket payment","b":"Private insurance","c":"General taxation","d":"User fees","ans":"C"},
{"t":"Miscellaneous","q":"A patient-reported outcome measure primarily assesses:","a":"Mortality","b":"Laboratory values","c":"Quality of life","d":"Incidence","ans":"C"},
{"t":"Miscellaneous","q":"In a community trial evaluating fluoridation of water supply, entire villages are randomized rather than individuals. This design primarily reduces:","a":"Confounding","b":"Contamination","c":"Random error","d":"Selection bias","ans":"B"},
{"t":"Miscellaneous","q":"A disease with R₀ = 5 requires what minimum proportion of immune individuals to interrupt transmission?","a":"20%","b":"50%","c":"60%","d":"80%","ans":"D"},
{"t":"Miscellaneous","q":"Which indicator is MOST sensitive to short-term changes in fertility behavior?","a":"Crude birth rate","b":"General fertility rate","c":"Total fertility rate","d":"Net reproduction rate","ans":"B"},
{"t":"Miscellaneous","q":"A false negative screening result is MOST dangerous in:","a":"Rare disease","b":"Mild disease","c":"Rapidly fatal but treatable disease","d":"Chronic disease","ans":"C"},
{"t":"Miscellaneous","q":"Which principle justifies inclusion of vulnerable populations in research ONLY when necessary?","a":"Justice","b":"Beneficence","c":"Autonomy","d":"Non-maleficence","ans":"A"},
{"t":"Miscellaneous","q":"The strongest limitation of ecological studies is:","a":"Cost","b":"Time","c":"Ecological fallacy","d":"Small sample size","ans":"C"},
{"t":"Miscellaneous","q":"Which measure is MOST appropriate for evaluating effectiveness of TB control program?","a":"TB prevalence","b":"TB incidence","c":"TB mortality","d":"Treatment success rate","ans":"D"},
{"t":"Miscellaneous","q":"A community shows declining crude death rate but increasing age-specific death rates. This paradox is explained by:","a":"Improved nutrition","b":"Migration","c":"Population aging","d":"Better reporting","ans":"C"},
{"t":"Miscellaneous","q":"Which is the MOST important modifiable determinant of non-communicable diseases globally?","a":"Genetics","b":"Age","c":"Lifestyle factors","d":"Sex","ans":"C"},
{"t":"Miscellaneous","q":"In health program evaluation, impact indicators measure:","a":"Resources used","b":"Activities conducted","c":"Immediate outputs","d":"Long-term health outcomes","ans":"D"},
{"t":"Miscellaneous","q":"Which bias falsely increases survival time without changing outcome?","a":"Selection bias","b":"Lead time bias","c":"Recall bias","d":"Confounding","ans":"B"},
{"t":"Miscellaneous","q":"The MOST appropriate design to evaluate vaccine effectiveness post-licensure is:","a":"Randomized trial","b":"Case-control study","c":"Cross-sectional study","d":"Ecological study","ans":"B"},
{"t":"Miscellaneous","q":"Which health indicator BEST reflects nutritional status of children at population level?","a":"Weight-for-age","b":"Height-for-age","c":"BMI","d":"MUAC","ans":"B"},
{"t":"Miscellaneous","q":"Which error decreases power of a study?","a":"Type I error","b":"Type II error","c":"Confidence interval","d":"Randomization","ans":"B"},
{"t":"Miscellaneous","q":"A p-value of 0.001 MOST correctly implies:","a":"Large effect size","b":"Null hypothesis is false","c":"Very low probability under null hypothesis","d":"Clinical significance","ans":"C"},
{"t":"Miscellaneous","q":"Which study design provides strongest evidence for screening effectiveness?","a":"Case-control","b":"Cohort","c":"Randomized controlled trial","d":"Cross-sectional","ans":"C"},
{"t":"Miscellaneous","q":"Which indicator is LEAST affected by age structure of population?","a":"Crude death rate","b":"Infant mortality rate","c":"Age-specific death rate","d":"Life expectancy","ans":"B"},
{"t":"Miscellaneous","q":"Which is the MOST ethical justification for population screening?","a":"High disease prevalence","b":"Cheap test","c":"Effective treatment available","d":"Research interest","ans":"C"},
{"t":"Miscellaneous","q":"Which disease control strategy requires global coordination?","a":"Control","b":"Elimination","c":"Eradication","d":"Prevention","ans":"C"},
{"t":"Miscellaneous","q":"Community Medicine as a discipline is BEST defined as:","a":"Hospital-based clinical care","b":"Preventive medicine only","c":"Integration of clinical care, prevention, and public health","d":"Epidemiology alone","ans":"C"}
];