// MedMasters — Gynae & Obs Paper 2: Pathology in Obs & Gyne
// 250 MCQs
(function(){
  if(!window.MM) window.MM={};
  window.MM['gynae_p2_patho'] = [
    {q:'A 45-year-old woman presents with postcoital bleeding. Cervical biopsy reveals carcinoma confined to the cervix with stromal invasion measuring 3 mm in depth and 6 mm in horizontal spread. According to FIGO staging, this corresponds to:',o:['Stage IA1','Stage IA2','Stage IB1','Stage IB2'],a:0},
    {q:'A patient with cervical carcinoma has stromal invasion of 6 mm depth but the lesion is not visible clinically. What is the FIGO stage?',o:['Stage IA1','Stage IA2','Stage IB1','Stage IB2'],a:1},
    {q:'A 38-year-old woman has a visible cervical tumor measuring 3 cm confined to the cervix. What is the correct FIGO stage?',o:['Stage IA2','Stage IB1','Stage IB2','Stage IIA'],a:1},
    {q:'A cervical carcinoma measuring 5 cm is confined to the cervix without vaginal or parametrial involvement. What is the FIGO stage?',o:['Stage IB2','Stage IB3','Stage IIA1','Stage IIB'],a:1},
    {q:'A patient with cervical carcinoma has extension to the upper two-thirds of the vagina without parametrial invasion. Tumor size is 3 cm. What stage is this?',o:['Stage IB3','Stage IIA1','Stage IIA2','Stage IIB'],a:1},
    {q:'A cervical tumor measuring 5 cm extends to the upper vagina but there is no parametrial invasion. What is the stage?',o:['Stage IIA1','Stage IIA2','Stage IIB','Stage IIIA'],a:1},
    {q:'A woman with cervical cancer has tumor extension to the lower third of the vagina without pelvic wall involvement. Which stage is this?',o:['Stage IIB','Stage IIIA','Stage IIIB','Stage IVA'],a:1},
    {q:'Cervical carcinoma causes hydronephrosis due to ureteric obstruction. What FIGO stage does this represent?',o:['Stage IIIA','Stage IIIB','Stage IVA','Stage IVB'],a:1},
    {q:'A patient with cervical carcinoma has metastasis to pelvic lymph nodes but no distant metastasis. What is the stage according to FIGO 2018 classification?',o:['Stage IIB','Stage IIIA','Stage IIIC1','Stage IVB'],a:2},
    {q:'Cervical carcinoma with para-aortic lymph node metastasis corresponds to:',o:['Stage IIIC1','Stage IIIC2','Stage IVA','Stage IVB'],a:1},
    {q:'A patient with cervical carcinoma has invasion into the mucosa of the rectum. What is the FIGO stage?',o:['Stage IIIB','Stage IIIA','Stage IVA','Stage IVB'],a:2},
    {q:'A woman with cervical carcinoma develops lung metastases. What is the FIGO stage?',o:['Stage IIIA','Stage IIIC2','Stage IVA','Stage IVB'],a:3},
    {q:'A 55-year-old woman presents with ovarian carcinoma involving one ovary with capsule rupture before surgery but no tumor on surface and negative washings. What stage is this?',o:['Stage IA','Stage IB','Stage IC1','Stage IC3'],a:2},
    {q:'Ovarian carcinoma with tumor on ovarian surface but confined to ovaries corresponds to:',o:['Stage IA','Stage IB','Stage IC2','Stage II'],a:2},
    {q:'A patient with ovarian carcinoma has malignant cells in peritoneal washings but disease limited to ovaries. What stage is this?',o:['Stage IC1','Stage IC2','Stage IC3','Stage II'],a:2},
    {q:'Ovarian carcinoma with pelvic extension to bladder peritoneum corresponds to:',o:['Stage IIA','Stage IIB','Stage IIIA','Stage IIIC'],a:1},
    {q:'Ovarian carcinoma with microscopic peritoneal metastasis outside pelvis corresponds to:',o:['Stage IIB','Stage IIIA1','Stage IIIA2','Stage IIIB'],a:2},
    {q:'Ovarian carcinoma with metastasis to retroperitoneal lymph nodes only corresponds to:',o:['Stage IIIA1','Stage IIIA2','Stage IIIB','Stage IIIC'],a:0},
    {q:'Ovarian carcinoma with peritoneal metastasis larger than 2 cm outside pelvis corresponds to:',o:['Stage IIIB','Stage IIIC','Stage IV','Stage IIIA'],a:1},
    {q:'Ovarian carcinoma with pleural effusion containing malignant cells corresponds to:',o:['Stage IIIC','Stage IIIA','Stage IVA','Stage IVB'],a:2},
    {q:'Ovarian carcinoma with liver parenchymal metastasis corresponds to:',o:['Stage IIIC','Stage IVA','Stage IVB','Stage IIIA'],a:2},
    {q:'The most common histological type of ovarian carcinoma is:',o:['Mucinous carcinoma','Endometrioid carcinoma','Serous cystadenocarcinoma','Clear cell carcinoma'],a:2},
    {q:'A young woman with ovarian tumor associated with elevated AFP most likely has:',o:['Dysgerminoma','Yolk sac tumor','Granulosa cell tumor','Brenner tumor'],a:1},
    {q:'A granulosa cell tumor of ovary commonly secretes:',o:['hCG','Estrogen','AFP','Androgens'],a:1},
    {q:'The tumor marker most commonly elevated in epithelial ovarian carcinoma is:',o:['AFP','CA-125','hCG','CEA'],a:1},
    {q:'A patient with cervical intraepithelial neoplasia grade III has:',o:['Mild dysplasia','Moderate dysplasia','Severe dysplasia / carcinoma in situ','Invasive carcinoma'],a:2},
    {q:'The most important etiological factor in cervical carcinoma is infection with:',o:['HPV','HSV','EBV','CMV'],a:0},
    {q:'The HPV types most strongly associated with cervical carcinoma are:',o:['6 and 11','16 and 18','31 and 33','42 and 43'],a:1},
    {q:'A Krukenberg tumor of the ovary most commonly originates from primary carcinoma of the:',o:['Colon','Breast','Stomach','Pancreas'],a:2},
    {q:'A woman with hydatidiform mole later develops choriocarcinoma with lung metastases only. According to FIGO staging for gestational trophoblastic neoplasia, this is:',o:['Stage II','Stage III','Stage IV','Stage I'],a:1},
    {q:'Gestational trophoblastic neoplasia with metastasis to the brain is classified as:',o:['Stage II','Stage III','Stage IV','Stage I'],a:2},
    {q:'A 52-year-old postmenopausal woman presents with abnormal vaginal bleeding. Endometrial biopsy reveals endometrioid adenocarcinoma confined to the uterus with invasion into less than half of the myometrium. According to FIGO staging, what is the stage?',o:['Stage IA','Stage IB','Stage II','Stage IIIA'],a:0},
    {q:'A 60-year-old woman is diagnosed with carcinoma of the cervix extending beyond the uterus but not to the pelvic wall. The upper two-thirds of the vagina is involved without parametrial invasion. What is the FIGO stage?',o:['Stage IB','Stage IIA','Stage IIB','Stage IIIA'],a:1},
    {q:'A patient with cervical carcinoma shows parametrial invasion but no extension to the pelvic wall. What is the correct FIGO stage?',o:['Stage IB2','Stage IIA','Stage IIB','Stage IIIA'],a:2},
    {q:'A 48-year-old woman with cervical cancer has tumor extension to the pelvic wall and hydronephrosis due to ureteric obstruction. Which stage does this represent?',o:['Stage IIB','Stage IIIA','Stage IIIB','Stage IVA'],a:2},
    {q:'A patient with cervical carcinoma shows invasion into the mucosa of the bladder. According to FIGO staging, this corresponds to:',o:['Stage IIIB','Stage IVA','Stage IVB','Stage IIIA'],a:1},
    {q:'A 65-year-old woman is diagnosed with ovarian carcinoma limited to one ovary with intact capsule and no tumor on surface. Peritoneal washings are negative. What is the FIGO stage?',o:['Stage IA','Stage IB','Stage IC','Stage II'],a:0},
    {q:'A patient with ovarian carcinoma involving both ovaries but confined to the ovaries with intact capsules is staged as:',o:['Stage IA','Stage IB','Stage IC','Stage II'],a:1},
    {q:'A woman with ovarian carcinoma confined to the ovaries but with capsule rupture and positive peritoneal washings. What is the stage?',o:['Stage IA','Stage IB','Stage IC','Stage II'],a:2},
    {q:'Ovarian carcinoma involving one or both ovaries with pelvic extension to the uterus or fallopian tubes corresponds to:',o:['Stage I','Stage II','Stage III','Stage IV'],a:1},
    {q:'A patient with ovarian carcinoma has peritoneal metastasis outside the pelvis with deposits smaller than 2 cm. What is the FIGO stage?',o:['Stage IIB','Stage IIIA','Stage IIIB','Stage IIIC'],a:2},
    {q:'Ovarian carcinoma with liver parenchymal metastasis is classified as:',o:['Stage IIIC','Stage IV','Stage IIIA','Stage IIIB'],a:1},
    {q:'A 45-year-old woman is diagnosed with carcinoma of the endometrium extending into the cervical stroma but not beyond the uterus. What stage is this?',o:['Stage IA','Stage IB','Stage II','Stage IIIA'],a:2},
    {q:'Endometrial carcinoma invading the serosa of the uterus or adnexa is staged as:',o:['Stage II','Stage IIIA','Stage IIIB','Stage IV'],a:1},
    {q:'Endometrial carcinoma with vaginal involvement but no distant metastasis corresponds to:',o:['Stage II','Stage IIIA','Stage IIIB','Stage IIIC'],a:2},
    {q:'A patient with endometrial carcinoma has metastasis to pelvic lymph nodes only. What is the stage?',o:['Stage IIIA','Stage IIIB','Stage IIIC1','Stage IV'],a:2},
    {q:'Metastasis of endometrial carcinoma to para-aortic lymph nodes corresponds to:',o:['Stage IIIB','Stage IIIC1','Stage IIIC2','Stage IV'],a:2},
    {q:'A patient with endometrial carcinoma has invasion of bladder mucosa. According to FIGO staging, this is:',o:['Stage IIIC','Stage IVA','Stage IVB','Stage IIIB'],a:1},
    {q:'A woman with vulvar carcinoma has tumor confined to vulva measuring less than 2 cm with stromal invasion less than 1 mm and no nodal metastasis. What stage is this?',o:['Stage IA','Stage IB','Stage II','Stage III'],a:0},
    {q:'Vulvar carcinoma greater than 2 cm but confined to vulva without nodal involvement corresponds to:',o:['Stage IA','Stage IB','Stage II','Stage III'],a:1},
    {q:'Vulvar carcinoma with positive inguinofemoral lymph nodes is staged as:',o:['Stage II','Stage III','Stage IVA','Stage IVB'],a:1},
    {q:'Vulvar carcinoma invading the upper urethra or rectal mucosa corresponds to:',o:['Stage II','Stage III','Stage IVA','Stage IVB'],a:2},
    {q:'Vaginal carcinoma confined to the vaginal wall without extension outside is classified as:',o:['Stage I','Stage II','Stage III','Stage IV'],a:0},
    {q:'Vaginal carcinoma extending to subvaginal tissues but not reaching pelvic wall corresponds to:',o:['Stage I','Stage II','Stage III','Stage IV'],a:1},
    {q:'Vaginal carcinoma extending to the pelvic wall is staged as:',o:['Stage II','Stage III','Stage IVA','Stage IVB'],a:1},
    {q:'Vaginal carcinoma invading bladder or rectal mucosa corresponds to:',o:['Stage III','Stage IVA','Stage IVB','Stage II'],a:1},
    {q:'A patient with gestational trophoblastic neoplasia has lung metastases only. What stage according to FIGO staging?',o:['Stage I','Stage II','Stage III','Stage IV'],a:2},
    {q:'Gestational trophoblastic neoplasia confined to the uterus is staged as:',o:['Stage I','Stage II','Stage III','Stage IV'],a:0},
    {q:'Gestational trophoblastic neoplasia extending to genital structures such as vagina or ovary corresponds to:',o:['Stage I','Stage II','Stage III','Stage IV'],a:1},
    {q:'Gestational trophoblastic neoplasia with metastases to liver or brain corresponds to:',o:['Stage II','Stage III','Stage IV','Stage I'],a:2},
    {q:'Implantation of the blastocyst normally occurs at approximately which time after fertilization?',o:['Day 2-3','Day 4-5','Day 6-7','Day 10-12'],a:2},
    {q:'The most common site of implantation in ectopic pregnancy is:',o:['Ampulla of fallopian tube','Isthmus of fallopian tube','Interstitial portion of tube','Ovary'],a:0},
    {q:'A 28-year-old woman presents with amenorrhea, abdominal pain, and vaginal bleeding. Ultrasound shows no intrauterine pregnancy but β-hCG is elevated. Which condition should be suspected first?',o:['Missed miscarriage','Ectopic pregnancy','Molar pregnancy','Intrauterine fetal death'],a:1},
    {q:'The most common cause of first-trimester miscarriage is:',o:['Maternal diabetes','Uterine anomalies','Chromosomal abnormalities','Cervical incompetence'],a:2},
    {q:'A patient presents with vaginal bleeding at 10 weeks of pregnancy. Cervix is closed and ultrasound shows viable fetus. What is the diagnosis?',o:['Threatened miscarriage','Inevitable miscarriage','Incomplete miscarriage','Missed miscarriage'],a:0},
    {q:'Vaginal bleeding with open cervical os and inevitable expulsion of products of conception describes:',o:['Missed miscarriage','Threatened miscarriage','Inevitable miscarriage','Septic miscarriage'],a:2},
    {q:'A woman presents with vaginal bleeding and partial passage of products of conception with retained tissue in uterus. This is:',o:['Complete miscarriage','Incomplete miscarriage','Missed miscarriage','Threatened miscarriage'],a:1},
    {q:'A patient has fetal death but products of conception remain in uterus for several weeks without expulsion. This condition is called:',o:['Threatened miscarriage','Missed miscarriage','Septic miscarriage','Inevitable miscarriage'],a:1},
    {q:'Recurrent miscarriage is defined as:',o:['Two or more consecutive pregnancy losses','Three or more consecutive pregnancy losses','Two pregnancy losses at any time','Four consecutive miscarriages'],a:1},
    {q:'Which chromosomal abnormality is most commonly associated with early spontaneous miscarriage?',o:['Trisomy 21','Trisomy 16','Turner syndrome','Triploidy'],a:1},
    {q:'The most sensitive test for early detection of pregnancy is measurement of:',o:['Serum progesterone','Serum estradiol','Serum β-hCG','Serum prolactin'],a:2},
    {q:'In ectopic pregnancy, the classical triad includes amenorrhea, abdominal pain, and:',o:['Fever','Vaginal bleeding','Hypertension','Vomiting'],a:1},
    {q:'The most serious complication of ectopic pregnancy is:',o:['Infertility','Hemorrhagic shock','Pelvic infection','Chronic pelvic pain'],a:1},
    {q:'The most common risk factor for ectopic pregnancy is:',o:['Pelvic inflammatory disease','Diabetes mellitus','Multiparity','Previous cesarean section'],a:0},
    {q:'A patient with ectopic pregnancy is hemodynamically stable and β-hCG levels are low. Which treatment is most appropriate?',o:['Immediate laparotomy','Methotrexate therapy','Hysterectomy','Progesterone therapy'],a:1},
    {q:'In gestational trophoblastic disease, the most common form is:',o:['Invasive mole','Choriocarcinoma','Hydatidiform mole','Placental site trophoblastic tumor'],a:2},
    {q:'Complete hydatidiform mole usually has which karyotype?',o:['46XX paternal origin','46XY maternal origin','69XXX','45XO'],a:0},
    {q:'Partial hydatidiform mole most commonly has which karyotype?',o:['46XX','69XXX','45XO','47XXY'],a:1},
    {q:'The most common presenting symptom of molar pregnancy is:',o:['Severe abdominal pain','Vaginal bleeding in early pregnancy','Hypertension','Fever'],a:1},
    {q:'Ultrasound appearance of complete molar pregnancy typically shows:',o:['Snowstorm appearance','Banana sign','Lemon sign','Double bubble sign'],a:0},
    {q:'A patient with molar pregnancy has very high β-hCG levels. Which complication is commonly associated?',o:['Hyperthyroidism','Hypothyroidism','Diabetes','Hypocalcemia'],a:0},
    {q:'The most malignant form of gestational trophoblastic disease is:',o:['Hydatidiform mole','Invasive mole','Choriocarcinoma','Placental site trophoblastic tumor'],a:2},
    {q:'The most common site of metastasis in choriocarcinoma is:',o:['Brain','Liver','Lung','Kidney'],a:2},
    {q:'Intrauterine fetal death (IUFD) refers to fetal death occurring after:',o:['12 weeks','20 weeks','24 weeks','refers to fetal death occurring after: A) 12 weeks B) 20 weeks C) 24 weeks D) 28 weeks'],a:1},
    {q:'The most common cause of intrauterine fetal death in developed countries is:',o:['Congenital anomalies','Placental insufficiency','Infection','Trauma'],a:1},
    {q:'Ultrasound sign most consistent with IUFD is:',o:['Absence of fetal cardiac activity','Increased amniotic fluid','Enlarged placenta','Rapid fetal movements'],a:0},
    {q:'The Spalding sign in IUFD refers to:',o:['Overlapping fetal skull bones','Absence of fetal movement','Reduced amniotic fluid','Placental calcification'],a:0},
    {q:'In IUFD, coagulopathy can develop due to release of:',o:['Fibrinogen','Thromboplastin','Estrogen','Oxytocin'],a:1},
    {q:'Intrauterine growth restriction (IUGR) is defined as fetal weight below:',o:['20th percentile','15th percentile','10th percentile','5th percentile'],a:2},
    {q:'The most common cause of IUGR worldwide is:',o:['Maternal malnutrition','Maternal hypertension','Diabetes mellitus','Smoking'],a:1},
    {q:'Symmetrical IUGR usually occurs due to:',o:['Late placental insufficiency','Early fetal insult','Maternal anemia','Cord compression'],a:1},
    {q:'Asymmetrical IUGR is characterized by:',o:['Proportionate reduction of all organs','Normal head size with reduced abdominal circumference','Increased head circumference','Enlarged liver'],a:1},
    {q:'The most useful ultrasound parameter to detect IUGR is:',o:['Biparietal diameter','Femur length','Abdominal circumference','Head circumference'],a:2},
    {q:'Doppler study in IUGR commonly shows increased resistance in:',o:['Umbilical artery','Middle cerebral artery','Renal artery','Aorta'],a:0},
    {q:'Brain-sparing effect in IUGR refers to:',o:['Reduced blood flow to brain','Increased blood flow to brain','Reduced placental perfusion','Increased fetal heart rate'],a:1},
    {q:'Which maternal habit significantly increases risk of IUGR?',o:['Smoking','Exercise','High protein diet','Vitamin supplementation'],a:0},
    {q:'A fetus with severe IUGR is at highest risk of:',o:['Macrosomia','Hypoglycemia after birth','Polycythemia','Both B and C'],a:3},
    {q:'The most common placental pathology associated with IUGR is:',o:['Placental infarction','Placenta previa','Placental cysts','Placental calcification'],a:0},
    {q:'A woman with previous molar pregnancy should avoid pregnancy for at least:',o:['3 months','6 months','1 year','2 years'],a:2},
    {q:'Persistent elevation of β-hCG after evacuation of molar pregnancy suggests:',o:['Complete cure','Persistent trophoblastic disease','Normal pregnancy','IUFD'],a:1},
    {q:'The most reliable method to diagnose ectopic pregnancy early is:',o:['Urine pregnancy test','Serum β-hCG with transvaginal ultrasound','Abdominal X-ray','Serum progesterone alone'],a:1},
    {q:'A patient with ruptured ectopic pregnancy most commonly presents with:',o:['Severe abdominal pain and shock','Fever and chills','Headache','Hypertension'],a:0},
    {q:'A patient with molar pregnancy develops very large uterus for gestational age. What explains this finding?',o:['Increased amniotic fluid','Proliferation of trophoblastic tissue','Fetal macrosomia','Placental insufficiency'],a:1},
    {q:'Theca lutein cysts associated with molar pregnancy are caused by:',o:['Elevated estrogen','Elevated β-hCG','Elevated progesterone','Elevated prolactin'],a:1},
    {q:'Which complication is commonly associated with molar pregnancy before 20 weeks?',o:['Preeclampsia','Placenta previa','Gestational diabetes','Polyhydramnios'],a:0},
    {q:'The most common symptom of IUFD noticed by mother is:',o:['Vaginal bleeding','Loss of fetal movements','Severe abdominal pain','Hypertension'],a:1},
    {q:'The gold standard for confirming IUFD is:',o:['Absence of fetal movements','Ultrasound showing absent cardiac activity','Maternal symptoms','CT scan'],a:1},
    {q:'One important complication after IUFD if fetus retained for long is:',o:['DIC','Diabetes','Polycythemia','Hypertension'],a:0},
    {q:'The most common chromosomal abnormality associated with complete mole is:',o:['Triploidy','Diploid androgenetic genome','Turner syndrome','Trisomy 21'],a:1},
    {q:'A partial mole usually contains:',o:['No fetal tissue','Some fetal tissue','Two placentas','No trophoblast'],a:1},
    {q:'The most sensitive marker for monitoring treatment of trophoblastic disease is:',o:['CA-125','β-hCG','AFP','CEA'],a:1},
    {q:'A fetus with symmetrical IUGR usually has:',o:['Normal head size','Reduced head and abdominal size proportionately','Enlarged head','Enlarged abdomen'],a:1},
    {q:'The most important determinant of fetal growth is:',o:['Maternal age','Placental function','Fetal gender','Maternal height'],a:1},
    {q:'A fetus with asymmetrical IUGR usually develops during:',o:['First trimester','Second trimester','Third trimester','Preconception'],a:2},
    {q:'The main pathological process in placental insufficiency leading to IUGR is:',o:['Reduced uteroplacental blood flow','Increased fetal movement','Increased amniotic fluid','Increased estrogen'],a:0},
    {q:'A major risk factor for miscarriage in early pregnancy is:',o:['Advanced maternal age','Maternal exercise','High protein diet','Multivitamin intake'],a:0},
    {q:'Septic miscarriage most commonly occurs due to:',o:['Unsafe abortion','Chromosomal abnormality','Placental insufficiency','Cervical incompetence'],a:0},
    {q:'Which hormone maintains early pregnancy until placental function is established?',o:['Estrogen','Progesterone from corpus luteum','Prolactin','Oxytocin'],a:1},
    {q:'Implantation occurs most commonly in which part of uterus?',o:['Lower uterine segment','Fundus/posterior wall','Cervical canal','Broad ligament'],a:1},
    {q:'Failure of trophoblastic invasion into spiral arteries is a key mechanism in:',o:['Macrosomia','IUGR','Hydatidiform mole','Polyhydramnios'],a:1},
    {q:'A 28-year-old woman develops heavy vaginal bleeding immediately after delivery of the placenta. The uterus is soft and enlarged on palpation. What is the most likely cause of the hemorrhage?',o:['Cervical laceration','Retained placental tissue','Uterine atony','Uterine rupture'],a:2},
    {q:'Postpartum hemorrhage is defined as blood loss of more than how much following vaginal delivery?',o:['300 mL','400 mL','500 mL','1000 mL'],a:2},
    {q:'The most common cause of primary postpartum hemorrhage is:',o:['Trauma to genital tract','Retained placenta','Uterine atony','Coagulation disorders'],a:2},
    {q:'A woman develops heavy bleeding 10 days after delivery. What type of postpartum hemorrhage is this?',o:['Primary postpartum hemorrhage','Immediate postpartum hemorrhage','Secondary postpartum hemorrhage','Antepartum hemorrhage'],a:2},
    {q:'Which uterotonic drug is considered the first-line treatment for postpartum hemorrhage due to uterine atony?',o:['Misoprostol','Methylergometrine','Oxytocin','Carboprost'],a:2},
    {q:'A patient develops antepartum hemorrhage at 34 weeks with painless vaginal bleeding. The uterus is soft and non-tender. What is the most likely diagnosis?',o:['Placental abruption','Uterine rupture','Placenta previa','Vasa previa'],a:2},
    {q:'A pregnant woman presents with abdominal pain, vaginal bleeding, and a tender uterus at 36 weeks gestation. What is the most likely diagnosis?',o:['Placenta previa','Uterine rupture','Placental abruption','Cervical polyp'],a:2},
    {q:'In placental abruption, bleeding occurs due to:',o:['Placental implantation in lower segment','Rupture of fetal vessels','Premature separation of placenta from uterine wall','Placental infection'],a:2},
    {q:'The most serious complication of placental abruption is:',o:['Polyhydramnios','Maternal anemia','Disseminated intravascular coagulation','Preterm labor'],a:2},
    {q:'Vasa previa is characterized by:',o:['Placenta covering cervical os','Separation of placenta before delivery','Fetal vessels crossing internal cervical os','Placenta attached to uterine fundus'],a:2},
    {q:'A patient with placenta previa develops heavy bleeding during labor. What is the safest mode of delivery?',o:['Induction of labor','Forceps delivery','Vacuum extraction','Cesarean section'],a:3},
    {q:'A patient develops severe bleeding after delivery due to retained placental fragments. What is the most appropriate management?',o:['Oxytocin infusion','Uterine massage only','Surgical evacuation of uterus','Antibiotics'],a:2},
    {q:'The four major causes of postpartum hemorrhage are commonly remembered as:',o:['Pain, placenta, pressure, prolapse','Trauma, tumor, thrombus, torsion','Tone, trauma, tissue, thrombin','Uterus, cervix, placenta, blood'],a:2},
    {q:'A woman with postpartum hemorrhage has a firm uterus but continued vaginal bleeding. What is the most likely cause?',o:['Uterine atony','Retained placenta','Cervical or vaginal laceration','Placenta accreta'],a:2},
    {q:'Placenta accreta occurs when:',o:['Placenta implants in cervix','Placenta separates prematurely','Placenta invades deeply into myometrium','Placenta detaches completely'],a:2},
    {q:'Placenta increta refers to:',o:['Placenta attached to decidua only','Placenta invading myometrium','Placenta penetrating through serosa','Placenta covering cervical os'],a:1},
    {q:'Placenta percreta is characterized by:',o:['Placental attachment to endometrium only','Partial placental separation','Placenta invading bladder wall','Placenta detached before delivery'],a:2},
    {q:'The most important risk factor for placenta accreta is:',o:['Primigravidity','Previous cesarean section','Maternal anemia','Polyhydramnios'],a:1},
    {q:'The most common cause of secondary postpartum hemorrhage is:',o:['Uterine rupture','Retained placental tissue','Placenta previa','DIC'],a:1},
    {q:'A woman develops postpartum hemorrhage due to uterine atony. Which immediate bedside intervention should be performed first?',o:['Blood transfusion','Hysterectomy','Uterine massage','Antibiotics'],a:2},
    {q:'A patient continues bleeding despite uterotonics and uterine massage. What is the next surgical step to control hemorrhage?',o:['Cervical cerclage','Tubal ligation','B-Lynch uterine compression suture','Oophorectomy'],a:2},
    {q:'A pregnant woman presents with painless vaginal bleeding and ultrasound shows placenta covering the internal os. What is the diagnosis?',o:['Placental abruption','Uterine rupture','Placenta previa','Vasa previa'],a:2},
    {q:'In placental abruption, fetal distress occurs mainly due to:',o:['Reduced placental perfusion','Umbilical cord prolapse','Placenta previa','Cervical dilatation'],a:0},
    {q:'The most common clinical sign of uterine rupture during labor is:',o:['Sudden severe abdominal pain with fetal distress','Painless bleeding','Hypertension','Fever'],a:0},
    {q:'A woman with severe postpartum hemorrhage develops hypotension and tachycardia. What type of shock is this?',o:['Septic shock','Cardiogenic shock','Hypovolemic shock','Neurogenic shock'],a:2},
    {q:'The most important initial step in management of obstetric hemorrhage is:',o:['Immediate surgery','Blood transfusion','Stabilization and fluid resuscitation','Antibiotic therapy'],a:2},
    {q:'Which coagulation disorder may develop in severe placental abruption?',o:['Hemophilia','Thrombocytopenia','Disseminated intravascular coagulation','Polycythemia'],a:2},
    {q:'A fetus dies suddenly after rupture of membranes due to bleeding from fetal vessels. What condition is responsible?',o:['Placenta previa','Placental abruption','Vasa previa','Uterine rupture'],a:2},
    {q:'The most effective drug for preventing postpartum hemorrhage during active management of third stage is:',o:['Misoprostol','Methylergometrine','Oxytocin','Carboprost'],a:2},
    {q:'A woman develops massive bleeding after delivery due to failure of placenta to separate because of abnormal placental adherence. What is the most likely diagnosis?',o:['Placenta previa','Placenta accreta spectrum','Placental abruption','Vasa previa'],a:1},
    {q:'Multiple pregnancy is defined as pregnancy with:',o:['More than one fetus in the uterus','More than two placentas','More than one amniotic sac only','More than one ovary involved'],a:0},
    {q:'The most common type of twin pregnancy is:',o:['Monozygotic twins','Dizygotic twins','Conjoined twins','Monoamniotic twins'],a:1},
    {q:'Dizygotic twins occur due to:',o:['Division of one fertilized ovum','Fertilization of two separate ova by two sperms','Fertilization of one ovum by two sperms','Fusion of two embryos'],a:1},
    {q:'Monozygotic twins arise from:',o:['Two ova fertilized by two sperms','Fertilization of ovum by two sperms','Division of a single fertilized ovum','Implantation of two embryos'],a:2},
    {q:'If division of the zygote occurs within the first 3 days after fertilization, the twins will most likely be:',o:['Dichorionic diamniotic','Monochorionic diamniotic','Monochorionic monoamniotic','Conjoined twins'],a:0},
    {q:'Division of the embryo between days 4-8 after fertilization results in:',o:['Dichorionic diamniotic twins','Monochorionic diamniotic twins','Monochorionic monoamniotic twins','Conjoined twins'],a:1},
    {q:'Division of the embryo between days 8-13 after fertilization produces:',o:['Dichorionic twins','Monochorionic diamniotic twins','Monochorionic monoamniotic twins','Conjoined twins'],a:2},
    {q:'Division occurring after day 13 following fertilization may result in:',o:['Dichorionic twins','Conjoined twins','Monoamniotic twins','Diamniotic twins'],a:1},
    {q:'The most reliable ultrasound sign in early pregnancy to diagnose dichorionic twins is:',o:['Lambda sign','Banana sign','Lemon sign','Snowstorm sign'],a:0},
    {q:'The ultrasound sign suggesting monochorionic twins is:',o:['Twin peak sign','T sign','Double bubble sign','Banana sign'],a:1},
    {q:'The most common complication of monochorionic twin pregnancy is:',o:['Placenta previa','Twin-to-twin transfusion syndrome','Gestational diabetes','Hyperemesis gravidarum'],a:1},
    {q:'Twin-to-twin transfusion syndrome occurs due to:',o:['Placental infarction','Unequal placental implantation','Vascular anastomoses between twins','Maternal hypertension'],a:2},
    {q:'In twin-to-twin transfusion syndrome, the donor twin typically develops:',o:['Polyhydramnios','Oligohydramnios','Macrosomia','Hydrops fetalis'],a:1},
    {q:'In twin-to-twin transfusion syndrome, the recipient twin usually develops:',o:['Oligohydramnios','Growth restriction','Polyhydramnios','Severe anemia'],a:2},
    {q:'The most common presentation of the first twin at delivery is:',o:['Breech','Transverse lie','Cephalic','Face presentation'],a:2},
    {q:'The most common maternal complication of multiple pregnancy is:',o:['Postpartum hemorrhage','Ectopic pregnancy','Cervical cancer','Placenta accreta'],a:0},
    {q:'The most common fetal complication in twin pregnancy is:',o:['Macrosomia','Preterm birth','Polyhydramnios','Congenital anomalies'],a:1},
    {q:'A condition in which one twin dies and becomes flattened and compressed in utero is called:',o:['Vanishing twin syndrome','Fetus papyraceus','Twin anemia polycythemia sequence','Hydrops fetalis'],a:1},
    {q:'The disappearance of one twin in early pregnancy is known as:',o:['Twin-to-twin transfusion syndrome','Vanishing twin syndrome','Fetus papyraceus','Conjoined twins'],a:1},
    {q:'The most accurate method for determining chorionicity in twin pregnancy is:',o:['Second trimester ultrasound','Third trimester ultrasound','Ultrasound in first trimester','Doppler study'],a:2},
    {q:'The most common congenital anomaly in monozygotic twins is:',o:['Neural tube defect','Congenital heart disease','Anencephaly','Omphalocele'],a:1},
    {q:'Which maternal factor increases the likelihood of dizygotic twins?',o:['Young maternal age','Nulliparity','Advanced maternal age','Short maternal stature'],a:2},
    {q:'Which drug used in infertility treatment increases the risk of multiple pregnancy?',o:['Oxytocin','Clomiphene citrate','Methotrexate','Progesterone'],a:1},
    {q:'In twin pregnancy, fundal height is usually:',o:['Smaller than gestational age','Equal to gestational age','Larger than gestational age','Absent'],a:2},
    {q:'The most common placental arrangement in twin pregnancy is:',o:['Monochorionic monoamniotic','Dichorionic diamniotic','Monochorionic diamniotic','Conjoined twins'],a:1},
    {q:'The risk of congenital anomalies is highest in:',o:['Dizygotic twins','Monochorionic twins','Dichorionic twins','Twins conceived naturally'],a:1},
    {q:'The most dangerous complication of monoamniotic twins is:',o:['Cord entanglement','Placenta previa','Polyhydramnios','Maternal anemia'],a:0},
    {q:'The recommended mode of delivery when first twin is cephalic and second twin breech is usually:',o:['Elective cesarean section','Vaginal delivery','Hysterectomy','Forceps delivery'],a:1},
    {q:'The most common cause of perinatal mortality in twins is:',o:['Congenital anomalies','Birth trauma','Prematurity','Placental abruption'],a:2},
    {q:'In twin pregnancy, maternal anemia occurs mainly due to:',o:['Reduced iron absorption','Increased plasma volume and fetal demand','Decreased hemoglobin synthesis','Reduced erythropoiesis'],a:1},
    {q:'Preterm labour is defined as onset of regular uterine contractions with cervical changes occurring between:',o:['28-40 weeks','24-36+6 weeks','20-28 weeks','30-37 weeks'],a:1},
    {q:'The most common cause of spontaneous preterm labour is:',o:['Placenta previa','Maternal diabetes','Idiopathic','Fetal anomalies'],a:2},
    {q:'Which infection is most commonly associated with preterm labour?',o:['Upper respiratory infection','Skin infection','Urinary tract infection','Bacterial vaginosis'],a:3},
    {q:'A woman at 32 weeks gestation presents with regular contractions and cervical dilation of 3 cm. What is the most appropriate diagnosis?',o:['Preterm labour','False labour','Threatened abortion','Term labour'],a:0},
    {q:'Which hormone is primarily responsible for maintaining uterine quiescence during pregnancy?',o:['Oxytocin','Prostaglandin','Progesterone','Estrogen'],a:2},
    {q:'Which test is commonly used to predict risk of preterm labour in symptomatic women?',o:['Fetal fibronectin test','Biophysical profile','Non-stress test','Amniotic fluid index'],a:0},
    {q:'A cervical length less than what value on transvaginal ultrasound indicates increased risk of preterm birth?',o:['30 mm','25 mm','35 mm','15 mm'],a:1},
    {q:'Which drug is commonly used as a tocolytic to suppress uterine contractions in preterm labour?',o:['Methylergometrine','Misoprostol','Nifedipine','Oxytocin'],a:2},
    {q:'Which medication is given to accelerate fetal lung maturity in preterm labour?',o:['Magnesium sulfate','Betamethasone','Progesterone','Oxytocin'],a:1},
    {q:'Antenatal corticosteroids are most beneficial when administered between:',o:['24-34 weeks','20-24 weeks','34-40 weeks','30-38 weeks'],a:0},
    {q:'Which medication is administered in preterm labour to reduce risk of cerebral palsy in preterm infants?',o:['Nifedipine','Betamethasone','Oxytocin','Magnesium sulfate'],a:3},
    {q:'The most common neonatal complication of preterm birth is:',o:['Respiratory distress syndrome','Meconium aspiration','Polycythemia','Congenital heart disease'],a:0},
    {q:'Surfactant deficiency in preterm infants leads to:',o:['Hyperbilirubinemia','Respiratory distress syndrome','Necrotizing enterocolitis','Neonatal sepsis'],a:1},
    {q:'A major maternal risk factor for preterm labour is:',o:['Previous preterm birth','Maternal obesity','Postdated pregnancy','Multiparity'],a:0},
    {q:'Which condition increases uterine stretch and predisposes to preterm labour?',o:['Placenta previa','Maternal anemia','Multiple pregnancy','Oligohydramnios'],a:2},
    {q:'Which prostaglandin plays a key role in initiation of labour including preterm labour?',o:['Prostaglandin F1','Prostaglandin I2','Prostaglandin A2','Prostaglandin E2'],a:3},
    {q:'Which infection may trigger preterm labour through inflammatory cytokine release?',o:['Bacterial vaginosis','Viral hepatitis','Tuberculosis','Malaria'],a:0},
    {q:'A woman presents at 30 weeks with uterine contractions but no cervical change. What is the diagnosis?',o:['Active labour','False preterm labour','True preterm labour','Inevitable abortion'],a:1},
    {q:'Which fetal complication is associated with prematurity?',o:['Polycythemia','Macrosomia','Intraventricular hemorrhage','Shoulder dystocia'],a:2},
    {q:'Which neonatal complication is strongly associated with prematurity and intestinal ischemia?',o:['Congenital diaphragmatic hernia','Necrotizing enterocolitis','Neonatal jaundice','Meconium aspiration'],a:1},
    {q:'The most important benefit of tocolysis in preterm labour is to:',o:['Increase fetal growth','Prevent infection','Allow time for corticosteroid administration','Prevent labour completely'],a:2},
    {q:'Which drug class acts as a calcium channel blocker for tocolysis?',o:['Indomethacin','Ritodrine','Magnesium sulfate','Nifedipine'],a:3},
    {q:'Indomethacin suppresses uterine contractions by inhibiting:',o:['Prostaglandin synthesis','Oxytocin release','Progesterone metabolism','Estrogen production'],a:0},
    {q:'A fetus born at 28 weeks is at highest risk of which neurological complication?',o:['Cerebral palsy','Hydrocephalus','Intraventricular hemorrhage','Epilepsy'],a:2},
    {q:'A common long-term complication of prematurity affecting vision is:',o:['Retinopathy of prematurity','Cataract','Optic neuritis','Glaucoma'],a:0},
    {q:'Which intervention is recommended in women with previous spontaneous preterm birth to reduce recurrence?',o:['Antibiotics','Progesterone therapy','Oxytocin infusion','Daily estrogen'],a:1},
    {q:'Cervical cerclage is indicated in:',o:['Polyhydramnios','Placenta previa','Cervical incompetence','Fetal macrosomia'],a:2},
    {q:'Which hormone level increases toward term and contributes to labour onset?',o:['Estrogen','hCG','Prolactin','Progesterone'],a:0},
    {q:'Which fetal hormone is believed to play a role in triggering labour?',o:['Insulin','Thyroxine','Growth hormone','Fetal cortisol'],a:3},
    {q:'The most reliable imaging technique to assess cervical length in preterm labour risk is:',o:['CT scan','Transabdominal ultrasound','Transvaginal ultrasound','MRI'],a:2},
    {q:'Which type of diabetes is first recognized during pregnancy?',o:['Type 1 diabetes mellitus','Maturity-onset diabetes of the young','Gestational diabetes mellitus','Type 2 diabetes mellitus'],a:2},
    {q:'The screening test commonly used for gestational diabetes at 24-28 weeks is:',o:['Fasting blood glucose','Oral glucose tolerance test','HbA1c measurement','Random blood glucose'],a:1},
    {q:'Which fetal complication is most strongly associated with poorly controlled maternal diabetes?',o:['Intrauterine growth restriction','Oligohydramnios','Macrosomia','Microcephaly'],a:2},
    {q:'The most common congenital anomaly associated with pregestational diabetes is:',o:['Neural tube defect','Ventricular septal defect','Renal agenesis','Cleft palate'],a:1},
    {q:'A newborn of a diabetic mother is most likely to develop which metabolic complication after birth?',o:['Hyperglycemia','Hypoglycemia','Hypernatremia','Metabolic alkalosis'],a:1},
    {q:'Which drug is considered the first-line pharmacological treatment for diabetes during pregnancy?',o:['Metformin','Glyburide','Insulin','Pioglitazone'],a:2},
    {q:'The most common maternal complication associated with diabetes in pregnancy is:',o:['Pre-eclampsia','Postpartum hemorrhage','Placenta previa','Abruptio placentae'],a:0},
    {q:'Which fetal cardiac condition is associated with maternal diabetes?',o:['Tetralogy of Fallot','Transposition of great arteries','Hypertrophic cardiomyopathy','Coarctation of aorta'],a:2},
    {q:'Chronic hypertension in pregnancy is defined as hypertension diagnosed:',o:['After 20 weeks gestation','Before pregnancy or before 20 weeks gestation','Only during labour','After delivery'],a:1},
    {q:'Gestational hypertension is defined as hypertension developing:',o:['Before 20 weeks gestation','After 20 weeks gestation without proteinuria','Before pregnancy','With seizures during pregnancy'],a:1},
    {q:'Which antihypertensive drug is commonly used as first-line treatment in pregnancy?',o:['Enalapril','Labetalol','Atenolol','Losartan'],a:1},
    {q:'Which antihypertensive drug is contraindicated in pregnancy due to risk of fetal renal failure?',o:['Methyldopa','Hydralazine','Labetalol','Enalapril'],a:3},
    {q:'Severe hypertension in pregnancy is defined as blood pressure ≥:',o:['130/80 mmHg','140/90 mmHg','160/110 mmHg','150/95 mmHg'],a:2},
    {q:'Which fetal complication is most commonly associated with maternal hypertension?',o:['Macrosomia','Intrauterine growth restriction','Polyhydramnios','Fetal hydrops'],a:1},
    {q:'Which antihypertensive drug has historically been widely used and considered safe in pregnancy?',o:['Methyldopa','Captopril','Losartan','Propranolol'],a:0},
    {q:'Antiphospholipid antibody syndrome is characterized by:',o:['Increased platelet production','Hypercoagulable state','Severe anemia','Leukopenia'],a:1},
    {q:'The most common pregnancy complication of antiphospholipid syndrome is:',o:['Recurrent miscarriage','Gestational diabetes','Polyhydramnios','Placenta previa'],a:0},
    {q:'Which antibody is commonly detected in antiphospholipid syndrome?',o:['Anti-thyroid peroxidase','Anti-cardiolipin antibody','Anti-smooth muscle antibody','Anti-mitochondrial antibody'],a:1},
    {q:'The lupus anticoagulant test is used to diagnose:',o:['Systemic lupus erythematosus only','Antiphospholipid syndrome','Hemophilia A','Von Willebrand disease'],a:1},
    {q:'A major obstetric complication associated with antiphospholipid syndrome is:',o:['Polyhydramnios','Post-term pregnancy','Placental thrombosis','Fetal macrosomia'],a:2},
    {q:'The standard treatment for pregnant women with antiphospholipid syndrome and recurrent miscarriage is:',o:['Corticosteroids alone','Warfarin therapy','Aspirin plus heparin','Methotrexate'],a:2},
    {q:'Warfarin is avoided during pregnancy primarily because it:',o:['Causes fetal anemia','Causes fetal growth restriction','Causes teratogenic effects','Causes maternal hypertension'],a:2},
    {q:'Which autoimmune disease commonly affects women of reproductive age and may impair fertility?',o:['Rheumatoid arthritis','Systemic lupus erythematosus','Multiple sclerosis','Psoriasis'],a:1},
    {q:'Women with systemic lupus erythematosus in pregnancy are at increased risk of:',o:['Placenta previa','Pre-eclampsia','Macrosomia','Post-term pregnancy'],a:1},
    {q:'Which antibody in SLE is associated with congenital heart block in the fetus?',o:['Anti-dsDNA','Anti-Ro (SSA) antibody','Anti-histone antibody','Anti-Sm antibody'],a:1},
    {q:'Neonatal lupus is primarily associated with maternal antibodies against:',o:['SSA/Ro and SSB/La','dsDNA','Phospholipids','Histones'],a:0},
    {q:'Which complication may occur in pregnancies affected by antiphospholipid syndrome due to placental insufficiency?',o:['Fetal macrosomia','Hydramnios','Intrauterine growth restriction','Shoulder dystocia'],a:2},
    {q:'Which autoimmune condition is most strongly associated with recurrent second-trimester pregnancy loss?',o:['Rheumatoid arthritis','Antiphospholipid syndrome','Graves disease','Hashimoto thyroiditis'],a:1},
    {q:'Low-dose aspirin in pregnancy primarily works by:',o:['Increasing prostaglandin synthesis','Reducing platelet aggregation','Increasing fibrin formation','Increasing coagulation factor production'],a:1},
    {q:'In women with antiphospholipid syndrome, which anticoagulant is preferred during pregnancy?',o:['Warfarin','Rivaroxaban','Low molecular weight heparin','Dabigatran'],a:2},
    {q:'Which screening test is recommended early in pregnancy for women with high risk of gestational diabetes?',o:['Oral glucose tolerance test','HbA1c','Fasting plasma glucose','Random blood glucose'],a:2},
    {q:'The most common cause of fetal macrosomia in pregnancies complicated by diabetes is:',o:['Maternal hyperinsulinemia','Fetal hyperinsulinemia','Increased placental estrogen','Maternal hypoglycemia'],a:1},
    {q:'Which maternal metabolic disturbance in diabetes contributes to congenital malformations in early pregnancy?',o:['Hypoglycemia','Hyperlipidemia','Hyperglycemia','Hypocalcemia'],a:2},
    {q:'Which complication of diabetes in pregnancy is associated with excessive amniotic fluid?',o:['Oligohydramnios','Polyhydramnios','Placental insufficiency','Placental abruption'],a:1},
    {q:'The most common cause of maternal mortality in women with systemic lupus erythematosus during pregnancy is:',o:['Severe anemia','Renal failure','Infection','Thromboembolism'],a:3},
    {q:'Which laboratory test is most specific for diagnosing antiphospholipid syndrome?',o:['Antinuclear antibody','Anti-dsDNA antibody','Lupus anticoagulant test','Rheumatoid factor'],a:2},
    {q:'Which hypertensive disorder of pregnancy is characterized by hypertension, proteinuria, and end-organ dysfunction after 20 weeks?',o:['Chronic hypertension','Pre-eclampsia','Gestational hypertension','White coat hypertension'],a:1},
    {q:'Which antihypertensive drug is commonly used intravenously for acute severe hypertension in pregnancy?',o:['Hydralazine','Methyldopa','Enalapril','Losartan'],a:0},
    {q:'Which fetal complication may occur in infants of diabetic mothers due to delayed lung maturation?',o:['Meconium aspiration','Pulmonary hypoplasia','Congenital diaphragmatic hernia','Respiratory distress syndrome'],a:3},
    {q:'Which obstetric complication is increased in women with chronic hypertension during pregnancy?',o:['Placenta accreta','Uterine rupture','Shoulder dystocia','Placental abruption'],a:3}
  ];
})();