// MedMasters — Gynae & Obs Paper 2: Common Congenital Anomalies
// 60 MCQs
(function(){
  if(!window.MM) window.MM={};
  window.MM['gynae_p2_congenital'] = [
    {q:'The most common physiological hematological change during normal pregnancy is:',o:['Leukopenia','Physiological anemia due to hemodilution','Thrombocytopenia','Polycythemia'],a:1},
    {q:'The most common cause of anemia during pregnancy worldwide is:',o:['Folate deficiency','Vitamin B12 deficiency','Iron deficiency anemia','Hemolytic anemia'],a:2},
    {q:'The typical peripheral blood smear finding in iron deficiency anemia is:',o:['Macrocytic normochromic cells','Normocytic normochromic cells','Microcytic hypochromic cells','Spherocytes'],a:2},
    {q:'Which index is most useful for differentiating iron deficiency anemia from thalassemia trait?',o:['Mean corpuscular volume (MCV)','Red cell distribution width (RDW)','Mentzer index','Hematocrit'],a:2},
    {q:'Beta-thalassemia major is characterized by:',o:['Reduced alpha globin synthesis','Reduced beta globin synthesis','Excess hemoglobin A','Excess hemoglobin F only'],a:1},
    {q:'The inheritance pattern of thalassemia is:',o:['Autosomal dominant','X-linked recessive','Autosomal recessive','Mitochondrial'],a:2},
    {q:'Which hemoglobin is predominantly increased in beta-thalassemia major?',o:['HbA','HbF','HbA2','HbS'],a:1},
    {q:'The most important screening test for thalassemia carriers in reproductive-age women is:',o:['Peripheral smear','Serum ferritin','Hemoglobin electrophoresis','Reticulocyte count'],a:2},
    {q:'Which prenatal diagnostic test can detect thalassemia in the fetus early in pregnancy?',o:['Amniocentesis','Chorionic villus sampling','Ultrasound Doppler','Non-stress test'],a:1},
    {q:'Severe untreated anemia in pregnancy is associated with which obstetric complication?',o:['Post-term pregnancy','Macrosomia','Preterm labour','Polyhydramnios'],a:2},
    {q:'Which anemia is characterized by macrocytic red blood cells during pregnancy?',o:['Iron deficiency anemia','Folate deficiency anemia','Thalassemia','Hemolytic anemia'],a:1},
    {q:'The daily folic acid requirement during pregnancy is approximately:',o:['100 µg','200 µg','400 µg','1000 µg'],a:2},
    {q:'Vitamin B12 deficiency anemia is most commonly associated with:',o:['Strict vegetarian diet','High protein diet','High iron intake','Excess vitamin C intake'],a:0},
    {q:'Which anemia is characterized by destruction of red blood cells leading to elevated bilirubin?',o:['Iron deficiency anemia','Hemolytic anemia','Aplastic anemia','Megaloblastic anemia'],a:1},
    {q:'The most common inherited bleeding disorder is:',o:['Hemophilia A','Hemophilia B','Von Willebrand disease','Factor X deficiency'],a:2},
    {q:'Hemophilia A is caused by deficiency of:',o:['Factor VIII','Factor IX','Factor X','Factor XIII'],a:0},
    {q:'Hemophilia B is caused by deficiency of:',o:['Factor VII','Factor VIII','Factor IX','Factor XI'],a:2},
    {q:'Hemophilia is inherited as:',o:['Autosomal dominant','Autosomal recessive','X-linked recessive','X-linked dominant'],a:2},
    {q:'A woman who is a carrier of hemophilia has a risk of transmitting the disease to:',o:['All daughters','Half of her sons','All sons','Half of her daughters'],a:1},
    {q:'Which coagulation test is prolonged in hemophilia?',o:['Prothrombin time','Bleeding time','Activated partial thromboplastin time','Thrombin time'],a:2},
    {q:'Disseminated intravascular coagulation (DIC) is characterized by:',o:['Hypercoagulation only','Simultaneous thrombosis and bleeding','is characterized by: A) Hypercoagulation only B) Simultaneous thrombosis and bleeding C) Isolated platelet deficiency','Reduced fibrinolysis'],a:1},
    {q:'Which obstetric condition commonly precipitates DIC?',o:['Placenta previa','Postdated pregnancy','Abruptio placentae','Mild anemia'],a:2},
    {q:'In DIC, which laboratory finding is typically present?',o:['Increased fibrinogen','Decreased D-dimer','Thrombocytosis','Decreased fibrinogen'],a:3},
    {q:'Which anemia is characterized by bone marrow failure?',o:['Iron deficiency anemia','Aplastic anemia','Hemolytic anemia','Megaloblastic anemia'],a:1},
    {q:'Sickle cell anemia results from a mutation in the gene encoding:',o:['Alpha globin','Beta globin','Gamma globin','Delta globin'],a:1},
    {q:'The abnormal hemoglobin present in sickle cell disease is:',o:['HbA','HbF','HbS','HbA2'],a:2},
    {q:'Pregnant women with sickle cell disease are at increased risk of:',o:['Macrosomia','Pre-eclampsia','Post-term pregnancy','Polyhydramnios'],a:1},
    {q:'Which laboratory test best assesses iron stores in the body?',o:['Serum ferritin','Hemoglobin level','Hematocrit','Reticulocyte count'],a:0},
    {q:'Which platelet disorder is most commonly seen during pregnancy?',o:['Immune thrombocytopenic purpura','Gestational thrombocytopenia','Thrombotic thrombocytopenic purpura','Aplastic thrombocytopenia'],a:1},
    {q:'Which coagulation factor deficiency causes the most severe bleeding disorder known as hemophilia A?',o:['Factor IX','Factor XI','Factor XII','Factor VIII'],a:3},
    {q:'The most common cause of jaundice during pregnancy is:',o:['Acute fatty liver of pregnancy','Viral hepatitis','Intrahepatic cholestasis of pregnancy','HELLP syndrome'],a:1},
    {q:'Intrahepatic cholestasis of pregnancy typically presents with:',o:['Severe hypertension','Generalized edema','Pruritus without rash','Severe abdominal pain'],a:2},
    {q:'The most sensitive laboratory marker for intrahepatic cholestasis of pregnancy is:',o:['Serum bilirubin','ALT level','AST level','Serum bile acids'],a:3},
    {q:'Which fetal complication is most associated with intrahepatic cholestasis of pregnancy?',o:['Macrosomia','Preterm birth','Neural tube defects','Shoulder dystocia'],a:1},
    {q:'The drug commonly used to treat intrahepatic cholestasis of pregnancy is:',o:['Ursodeoxycholic acid','Prednisolone','Methyldopa','Nifedipine'],a:0},
    {q:'Acute fatty liver of pregnancy usually occurs in which trimester?',o:['First trimester','Second trimester','Early second trimester','Third trimester'],a:3},
    {q:'Acute fatty liver of pregnancy is associated with deficiency of which fetal enzyme?',o:['Glucose-6-phosphate dehydrogenase','Long-chain 3-hydroxyacyl-CoA dehydrogenase','Pyruvate dehydrogenase','Lactate dehydrogenase'],a:1},
    {q:'HELLP syndrome is characterized by hemolysis, elevated liver enzymes, and:',o:['Leukocytosis','Hypoglycemia','Thrombocytopenia','Hypernatremia'],a:2},
    {q:'The most common viral cause of jaundice during pregnancy in developing countries is:',o:['Hepatitis A','Hepatitis B','Hepatitis C','Hepatitis E'],a:3},
    {q:'Hepatitis E infection during pregnancy is associated with:',o:['Mild disease only','High maternal mortality','No fetal complications','Reduced liver enzymes'],a:1},
    {q:'Physiological jaundice of pregnancy may occur due to:',o:['Increased hemolysis','Increased bile acid secretion','Increased estrogen causing cholestasis','Increased albumin production'],a:2},
    {q:'The most important fetal risk associated with maternal cholestasis is:',o:['Neural tube defects','Sudden intrauterine fetal death','Congenital heart disease','Limb deformities'],a:1},
    {q:'Which laboratory finding is typical in obstructive jaundice?',o:['Elevated unconjugated bilirubin','Elevated alkaline phosphatase','Decreased AST','Decreased ALT'],a:1},
    {q:'Hemolytic jaundice is primarily caused by:',o:['Increased red cell destruction','Obstruction of bile ducts','Liver cell necrosis','Reduced bile production'],a:0},
    {q:'Which type of bilirubin is elevated in hemolytic jaundice?',o:['Conjugated bilirubin','Direct bilirubin','Unconjugated bilirubin','Mixed bilirubin'],a:2},
    {q:'The classical symptom of cholestasis in pregnancy is:',o:['Severe headache','Pruritus especially on palms and soles','Visual disturbances','Hematemesis'],a:1},
    {q:'Which pregnancy-related liver disorder is associated with microvesicular fatty infiltration of hepatocytes?',o:['HELLP syndrome','Viral hepatitis','Acute fatty liver of pregnancy','Gallstone disease'],a:2},
    {q:'Gallstones during pregnancy are mainly formed due to:',o:['Increased bile flow','Increased progesterone causing gallbladder stasis','Reduced cholesterol levels','Increased bile acid secretion'],a:1},
    {q:'Which enzyme level is markedly elevated in hepatocellular jaundice?',o:['Alkaline phosphatase','AST and ALT','Amylase','Creatine kinase'],a:1},
    {q:'Acute fatty liver of pregnancy may lead to which serious maternal complication?',o:['Renal failure','Hyperthyroidism','Diabetes mellitus','Pulmonary embolism'],a:0},
    {q:'Which pregnancy-related liver disorder is strongly associated with preeclampsia?',o:['Acute fatty liver of pregnancy','Intrahepatic cholestasis','HELLP syndrome','Viral hepatitis'],a:2},
    {q:'Elevated bilirubin, hemolysis, and low platelets in pregnancy should raise suspicion of:',o:['Viral hepatitis','HELLP syndrome','Gallstones','Intrahepatic cholestasis'],a:1},
    {q:'Which hormone contributes to reduced gallbladder motility during pregnancy?',o:['Estrogen','Progesterone','Prolactin','Oxytocin'],a:1},
    {q:'Which form of jaundice results from obstruction of bile flow?',o:['Hemolytic jaundice','Hepatocellular jaundice','Obstructive jaundice','Neonatal jaundice'],a:2},
    {q:'In obstructive jaundice, stool color typically becomes:',o:['Dark black','Clay-colored','Green','Bright red'],a:1},
    {q:'Dark urine in jaundice occurs due to increased excretion of:',o:['Unconjugated bilirubin','Hemoglobin','Conjugated bilirubin','Urobilinogen only'],a:2},
    {q:'Which pregnancy-related liver disorder has the highest maternal mortality if untreated?',o:['Acute fatty liver of pregnancy','Intrahepatic cholestasis','Gallstones','Mild hepatitis A'],a:0},
    {q:'Which test is most useful for confirming viral hepatitis during pregnancy?',o:['Serum bilirubin','Liver ultrasound','Complete blood count','Viral serology'],a:3},
    {q:'Intrahepatic cholestasis of pregnancy typically resolves:',o:['Immediately after conception','After first trimester','After delivery','Before labor begins'],a:2},
    {q:'The primary mechanism of jaundice in hemolytic disorders is:',o:['Increased bile duct obstruction','Reduced liver blood flow','Decreased bilirubin production','Excess breakdown of red blood cells'],a:3}
  ];
})();