// MedMasters — Gynae & Obs Paper 2: Infections
// 150 MCQs
(function(){
  if(!window.MM) window.MM={};
  window.MM['gynae_p2_infections'] = [
    {q:'The most common cause of puerperal sepsis after delivery is:',o:['Staphylococcus aureus','Clostridium perfringens','Escherichia coli','Streptococcus pyogenes'],a:3},
    {q:'Puerperal fever is defined as temperature ≥38°C occurring after:',o:['First 12 hours postpartum','First 24 hours postpartum','First 48 hours postpartum','First 72 hours postpartum'],a:1},
    {q:'The most common source of postpartum infection is:',o:['Respiratory tract','Urinary tract','Genital tract','Surgical incision'],a:2},
    {q:'The most important risk factor for puerperal infection is:',o:['Early rupture of membranes','Short labor','Cesarean section','Maternal obesity'],a:2},
    {q:'Endometritis after delivery most commonly presents with:',o:['Severe hypertension','Fever with uterine tenderness','Hematuria','Severe jaundice'],a:1},
    {q:'The most common organism responsible for post-cesarean wound infection is:',o:['Pseudomonas aeruginosa','Klebsiella pneumoniae','Enterococcus species','Staphylococcus aureus'],a:3},
    {q:'Which microorganism is classically associated with gas gangrene in obstetric infections?',o:['Escherichia coli','Streptococcus viridans','Clostridium perfringens','Staphylococcus epidermidis'],a:2},
    {q:'The most effective preventive measure for postoperative infection after cesarean section is:',o:['Routine blood transfusion','Prophylactic antibiotics','Early ambulation','Intravenous fluids'],a:1},
    {q:'Septic pelvic thrombophlebitis usually presents with:',o:['Persistent fever despite antibiotics','Severe anemia','Hypoglycemia','Severe jaundice'],a:0},
    {q:'The most common bacteria causing postpartum urinary tract infection is:',o:['Proteus mirabilis','Staphylococcus saprophyticus','Enterococcus faecalis','Escherichia coli'],a:3},
    {q:'Necrotizing fasciitis following cesarean section is most commonly caused by:',o:['Streptococcus pyogenes','Mycoplasma','Candida species','Chlamydia trachomatis'],a:0},
    {q:'The most common site of infection after cesarean delivery is:',o:['Lungs','Surgical wound','Kidney','Endometrium'],a:3},
    {q:'Which condition predisposes most strongly to puerperal sepsis?',o:['Short duration of labour','Premature rupture of membranes','Early breastfeeding','Normal vaginal delivery'],a:1},
    {q:'A foul-smelling lochia in the postpartum period suggests:',o:['Mastitis','Endometritis','Pulmonary embolism','Septic infection of uterus'],a:3},
    {q:'The most important route of infection in puerperal sepsis is:',o:['Hematogenous spread','Lymphatic spread','Ascending infection from vagina','Respiratory droplets'],a:2},
    {q:'Which organism is commonly associated with polymicrobial postpartum infections?',o:['Neisseria gonorrhoeae','Mycoplasma hominis','Listeria monocytogenes','Bacteroides species'],a:3},
    {q:'The most common breast infection during lactation is:',o:['Breast abscess','Mastitis','Fibroadenoma','Galactocele'],a:1},
    {q:'Lactational mastitis is most commonly caused by:',o:['Streptococcus pneumoniae','Pseudomonas aeruginosa','Escherichia coli','Staphylococcus aureus'],a:3},
    {q:'The most common symptom of postpartum endometritis is:',o:['High fever and uterine tenderness','Severe headache','Severe hypertension','Persistent vomiting'],a:0},
    {q:'The first-line management of puerperal sepsis is:',o:['Immediate hysterectomy','Intravenous broad-spectrum antibiotics','Blood transfusion','Chemotherapy'],a:1},
    {q:'Which complication can result from untreated puerperal infection?',o:['Septic shock','Macrosomia','Gestational diabetes','Placenta previa'],a:0},
    {q:'Which sign suggests severe postpartum infection progressing to sepsis?',o:['Tachycardia and hypotension','Mild headache','Bradycardia','Increased appetite'],a:0},
    {q:'Pelvic abscess after delivery most commonly develops in the:',o:['Ovarian ligament','Broad ligament','Rectouterine pouch','Cervical canal'],a:2},
    {q:'The most common pathogen causing neonatal infection from maternal genital tract infection is:',o:['Streptococcus agalactiae (Group B)','B) Candida albicans','Mycoplasma genitalium','Neisseria gonorrhoeae'],a:0},
    {q:'Which condition significantly increases the risk of postoperative pelvic infection after gynecological surgery?',o:['Short operative time','Prophylactic antibiotics','Strict aseptic technique','Poor surgical sterility'],a:3},
    {q:'Which complication may occur from severe pelvic infection after surgery?',o:['Pelvic abscess formation','Hyperthyroidism','Migraine','Asthma'],a:0},
    {q:'Which organism is most commonly responsible for toxic shock syndrome after gynecological surgery?',o:['Streptococcus pneumoniae','Clostridium difficile','Staphylococcus aureus','Escherichia coli'],a:2},
    {q:'A breast abscess is most commonly a complication of:',o:['Mastitis','Fibrocystic disease','Breast carcinoma','Duct ectasia'],a:0},
    {q:'Which infection may develop at the episiotomy site postpartum?',o:['Surgical wound infection','Pelvic thrombosis','Liver abscess','Episiotomy wound infection'],a:3},
    {q:'Which preventive measure reduces postpartum infection risk the most?',o:['Routine analgesics','Prolonged hospital stay','Late ambulation','Strict aseptic technique during delivery'],a:3},
    {q:'Septicemia in postpartum infection is characterized by:',o:['Bacteria in bloodstream with systemic illness','Mild fever only','Isolated urinary infection','Local wound infection only'],a:0},
    {q:'Which postoperative infection typically presents with localized redness, warmth, and pus discharge?',o:['Wound infection','Urinary infection','Pneumonia','Septicemia'],a:0},
    {q:'The most common anaerobic organism involved in pelvic infections is:',o:['Lactobacillus','Bacteroides fragilis','Streptococcus pneumoniae','Haemophilus influenzae'],a:1},
    {q:'Which condition increases infection risk during labour due to repeated vaginal examinations?',o:['Prolonged labour','Early induction','Normal labour','Short labour'],a:0},
    {q:'Postpartum infection spreading through lymphatics may result in:',o:['Pelvic cellulitis','Osteoporosis','Hyperthyroidism','Diabetes mellitus'],a:0},
    {q:'Which infection is characterized by inflammation of the breast tissue during lactation?',o:['Mastitis','Fibroadenoma','Breast cyst','Breast carcinoma'],a:0},
    {q:'Which clinical feature is most suggestive of necrotizing infection after surgery?',o:['Mild redness','Gradual pain improvement','Severe pain with tissue necrosis','Mild fever'],a:2},
    {q:'Which systemic complication can occur from severe puerperal infection?',o:['Septic shock','Hyperlipidemia','Hypothyroidism','Osteoarthritis'],a:0},
    {q:'Which infection control practice is most important to prevent hospital-acquired obstetric infections?',o:['Frequent blood testing','Prolonged bed rest','Routine vitamin supplements','Proper hand hygiene'],a:3},
    {q:'Which route is the most common pathway for bacteria causing postpartum uterine infection?',o:['Respiratory spread','Hematogenous spread','Skin contact','Ascending infection from vagina'],a:3},
    {q:'The most common route of mother-to-child transmission of HIV is:',o:['During labor and delivery','Transplacental in early pregnancy','Through insect vectors','Through contaminated food'],a:0},
    {q:'The most important screening test for HIV during pregnancy is:',o:['Viral load test','Western blot only','ELISA test','CD4 count'],a:2},
    {q:'The most effective intervention to reduce vertical transmission of HIV is:',o:['Antiretroviral therapy','Corticosteroid therapy','Early induction of labor','Iron supplementation'],a:0},
    {q:'Hepatitis B virus is primarily transmitted through:',o:['Airborne droplets','Blood and body fluids','Mosquito bites','Fecal contamination'],a:1},
    {q:'Which marker indicates active infectivity in hepatitis B infection?',o:['Anti-HBc IgG','HBsAg only','Anti-HBs','HBeAg'],a:3},
    {q:'The most effective method to prevent neonatal hepatitis B infection is:',o:['HBV vaccine plus HBIG at birth','Cesarean delivery','Maternal antibiotics','Avoid breastfeeding'],a:0},
    {q:'Hepatitis C virus is mainly transmitted through:',o:['Blood exposure','Respiratory droplets','Mosquito bite','Fecal contamination'],a:0},
    {q:'The risk of vertical transmission of hepatitis C increases significantly when the mother also has:',o:['Tuberculosis','Syphilis','HIV infection','Hepatitis A infection'],a:2},
    {q:'Hepatitis A virus is mainly transmitted by:',o:['Respiratory droplets','Blood transfusion','Sexual contact','Fecal-oral route'],a:3},
    {q:'The hepatitis virus associated with high maternal mortality during pregnancy is:',o:['Hepatitis A','Hepatitis E','Hepatitis B','Hepatitis C'],a:1},
    {q:'Parvovirus B19 infection during pregnancy can cause:',o:['Neural tube defects','Fetal hydrops','Shoulder dystocia','Macrosomia'],a:1},
    {q:'The mechanism of fetal hydrops in parvovirus B19 infection is:',o:['Severe fetal anemia','Liver failure','Placental thrombosis','Cardiac arrhythmia'],a:0},
    {q:'The most common sexually transmitted infection worldwide is caused by:',o:['Human papillomavirus','Chlamydia trachomatis','Neisseria gonorrhoeae','Treponema pallidum'],a:0},
    {q:'Human papillomavirus infection is most strongly associated with:',o:['Breast cancer','Cervical cancer','Ovarian cancer','Endometrial cancer'],a:1},
    {q:'The HPV types most commonly associated with cervical cancer are:',o:['31 and 33','42 and 44','16 and 18','6 and 11'],a:2},
    {q:'Genital herpes is caused by:',o:['Cytomegalovirus','Herpes simplex virus','Epstein-Barr virus','Varicella zoster virus'],a:1},
    {q:'Neonatal herpes infection is most commonly acquired:',o:['Through placenta early in pregnancy','Through contaminated food','During vaginal delivery','During breastfeeding'],a:2},
    {q:'The recommended mode of delivery in active genital herpes infection is:',o:['Cesarean section','Vacuum delivery','Forceps delivery','Normal vaginal delivery'],a:0},
    {q:'The most sensitive test for diagnosing HIV infection is:',o:['Viral culture','PCR test','Western blot','CD4 count'],a:1},
    {q:'TORCH infections include:',o:['Tuberculosis, oral herpes, rubella, chlamydia, hepatitis','Toxoplasmosis, others, rubella, cytomegalovirus, herpes','Tetanus, osteomyelitis, rubella, cytomegalovirus, herpes','Toxoplasmosis, otitis media, rubella, candida, hepatitis'],a:1},
    {q:'Congenital toxoplasmosis most commonly results from infection acquired:',o:['During adolescence','During pregnancy','During childhood','Before pregnancy'],a:1},
    {q:'The classic triad of congenital toxoplasmosis includes:',o:['Deafness, cataract, microcephaly','Hydrops, anemia, jaundice','Chorioretinitis, hydrocephalus, intracranial calcifications','Macrosomia, cardiomegaly, edema'],a:2},
    {q:'Congenital rubella syndrome commonly presents with:',o:['Limb defects only','Cataracts, deafness, heart defects','Spina bifida, hydrocephalus','Clubfoot, hydrops, anemia'],a:1},
    {q:'Cytomegalovirus infection in pregnancy most commonly causes:',o:['Neural tube defects','Microcephaly','Polyhydramnios','Macrosomia'],a:1},
    {q:'The most common congenital viral infection worldwide is:',o:['Rubella','Varicella','Cytomegalovirus','Herpes simplex virus'],a:2},
    {q:'Syphilis during pregnancy is caused by:',o:['Treponema pallidum','Chlamydia trachomatis','Neisseria gonorrhoeae','Mycoplasma genitalium'],a:0},
    {q:'The screening test commonly used for syphilis in pregnancy is:',o:['PCR','Viral culture','ELISA','VDRL test'],a:3},
    {q:'Untreated maternal syphilis may result in:',o:['Macrosomia','Congenital syphilis','Shoulder dystocia','Post-term pregnancy'],a:1},
    {q:'The drug of choice for treating syphilis during pregnancy is:',o:['Azithromycin','Doxycycline','Penicillin','Erythromycin'],a:2},
    {q:'Gonorrhea infection is caused by:',o:['Treponema pallidum','Neisseria gonorrhoeae','Chlamydia trachomatis','Mycoplasma hominis'],a:1},
    {q:'A common complication of untreated gonorrhea in pregnancy is:',o:['Hyperemesis gravidarum','Macrosomia','Preterm labor','Polyhydramnios'],a:2},
    {q:'Chlamydia trachomatis infection during pregnancy can cause:',o:['Diabetes mellitus','Neural tube defects','Neonatal conjunctivitis','Post-term pregnancy'],a:2},
    {q:'The most common manifestation of congenital CMV infection is:',o:['Cataract','Hydrocephalus','Cardiac defects','Sensorineural hearing loss'],a:3},
    {q:'Which infection can cause erythema infectiosum (fifth disease)?',o:['Rubella virus','Cytomegalovirus','Varicella virus','Parvovirus B19'],a:3},
    {q:'Which TORCH infection is associated with periventricular calcifications in the fetus?',o:['Toxoplasmosis','Rubella','Herpes simplex virus','Cytomegalovirus'],a:3},
    {q:'The main route of transmission of HPV is:',o:['Airborne transmission','Blood transfusion','Fecal contamination','Sexual contact'],a:3},
    {q:'The vaccine used to prevent HPV infection protects mainly against types:',o:['1 and 2','16 and 18','3 and 4','8 and 9'],a:1},
    {q:'Which STI is commonly associated with pelvic inflammatory disease?',o:['Hepatitis B','Hepatitis A','Chlamydia trachomatis','Human papillomavirus'],a:2},
    {q:'Neonatal conjunctivitis caused by gonorrhea is called:',o:['Keratitis','Blepharitis','Dacryocystitis','Ophthalmia neonatorum'],a:3},
    {q:'Which infection in early pregnancy causes highest risk of congenital anomalies?',o:['Hepatitis A','Hepatitis B','Hepatitis C','Rubella'],a:3},
    {q:'The best prevention for congenital rubella syndrome is:',o:['Antibiotic therapy','Rubella vaccination','Antiviral therapy','Corticosteroid therapy'],a:1},
    {q:'Vertical transmission of HIV can occur during:',o:['Pregnancy','Labor','All of the above','Breastfeeding'],a:2},
    {q:'The most common symptom of acute hepatitis infection is:',o:['Hypertension','Edema','Tachycardia','Jaundice'],a:3},
    {q:'The incubation period of hepatitis B virus is approximately:',o:['1 week','2 weeks','1-6 months','1 month'],a:2},
    {q:'Which infection is strongly associated with genital warts?',o:['HPV','HSV','HIV','HBV'],a:0},
    {q:'Condyloma acuminata is caused by:',o:['HPV type 31','HPV type 33','HPV type 6 and 11','HPV type 16'],a:2},
    {q:'Which TORCH infection is most associated with intracranial calcifications and hydrocephalus?',o:['Cytomegalovirus','Toxoplasmosis','Rubella','Herpes simplex virus'],a:1},
    {q:'Which infection may cause severe anemia and hydrops fetalis during pregnancy?',o:['Parvovirus B19','Hepatitis B','Rubella','Cytomegalovirus'],a:0},
    {q:'Which virus is associated with Kaposi sarcoma in HIV patients?',o:['Epstein-Barr virus','Cytomegalovirus','Human herpesvirus 8','Human papillomavirus'],a:2},
    {q:'Which infection can cause microcephaly, intracranial calcifications, and sensorineural hearing loss in the fetus?',o:['Cytomegalovirus','Rubella','Herpes simplex virus','Toxoplasmosis'],a:0},
    {q:'The causative agent of COVID-19 is:',o:['Influenza virus','Adenovirus','Respiratory syncytial virus','SARS-CoV-2'],a:3},
    {q:'The primary mode of transmission of COVID-19 is:',o:['Fecal-oral route','Mosquito bite','Blood transfusion','Respiratory droplets'],a:3},
    {q:'Which symptom is most commonly associated with COVID-19 infection?',o:['Jaundice','Fever and cough','Severe anemia','Hematuria'],a:1},
    {q:'The most common hematological abnormality seen in COVID-19 infection is:',o:['Polycythemia','Leukocytosis','Lymphopenia','Thrombocytosis'],a:2},
    {q:'The gold standard test for diagnosis of COVID-19 infection is:',o:['Rapid antigen test','ELISA','Antibody test','RT-PCR'],a:3},
    {q:'Which complication of COVID-19 is related to hypercoagulability?',o:['Anemia','Deep vein thrombosis','Hypoglycemia','Osteoporosis'],a:1},
    {q:'In pregnancy, severe COVID-19 infection increases the risk of:',o:['Macrosomia','Preterm birth','Post-term pregnancy','Shoulder dystocia'],a:1},
    {q:'Dengue fever is caused by:',o:['Bacteria','Parasite','Fungus','Virus'],a:3},
    {q:'Dengue virus is transmitted by:',o:['Anopheles mosquito','Culex mosquito','Sandfly','Aedes mosquito'],a:3},
    {q:'The most common clinical feature of dengue fever is:',o:['Severe hypertension','Sudden high fever','Bradycardia','Severe jaundice'],a:1},
    {q:'Dengue hemorrhagic fever is characterized by:',o:['Leukocytosis','Hyperglycemia','Severe thrombocytopenia','Polycythemia'],a:2},
    {q:'Which laboratory finding is typical in dengue infection?',o:['Increased platelets','Thrombocytopenia','Severe neutrophilia','Hypercalcemia'],a:1},
    {q:'The confirmatory diagnostic test for dengue infection is:',o:['Blood culture','Urine microscopy','Chest X-ray','NS1 antigen test'],a:3},
    {q:'A major complication of dengue hemorrhagic fever is:',o:['Septic shock','Dengue shock syndrome','Pulmonary fibrosis','Renal calculi'],a:1},
    {q:'Malaria is caused by:',o:['Virus','Bacteria','Protozoan parasite','Fungus'],a:2},
    {q:'The vector responsible for transmission of malaria is:',o:['Aedes mosquito','Female Anopheles mosquito','Culex mosquito','Sandfly'],a:1},
    {q:'The most severe form of malaria is caused by:',o:['Plasmodium vivax','Plasmodium malariae','Plasmodium ovale','Plasmodium falciparum'],a:3},
    {q:'The classical fever pattern of malaria is:',o:['Continuous fever','Intermittent fever with chills and rigors','Low-grade persistent fever','Evening fever only'],a:1},
    {q:'The gold standard test for malaria diagnosis is:',o:['Rapid antigen test','Blood culture','Peripheral blood smear','Urine antigen test'],a:2},
    {q:'Which complication is most commonly associated with severe falciparum malaria?',o:['Hyperthyroidism','Cerebral malaria','Osteoporosis','Gastritis'],a:1},
    {q:'Malaria in pregnancy increases the risk of:',o:['Macrosomia','Post-term pregnancy','Polyhydramnios','Intrauterine growth restriction'],a:3},
    {q:'Severe malaria may lead to:',o:['Severe anemia','Hyperlipidemia','Hypercalcemia','Hypothyroidism'],a:0},
    {q:'The rapid diagnostic test for malaria detects:',o:['Antibodies only','Parasite antigen','Viral RNA','Bacterial toxin'],a:1},
    {q:'Which species of Plasmodium can remain dormant in the liver causing relapse?',o:['Plasmodium falciparum','Plasmodium malariae','Plasmodium vivax','Plasmodium knowlesi'],a:2},
    {q:'Which complication of malaria is characterized by altered consciousness and seizures?',o:['Hepatic malaria','Renal malaria','Cerebral malaria','Cardiac malaria'],a:2},
    {q:'A pregnant woman at 34 weeks presents with high fever, severe myalgia, and platelet count of 40,000/µL after returning from a dengue-endemic area. What is the most likely diagnosis?',o:['Malaria','COVID-19 infection','Typhoid fever','Dengue hemorrhagic fever'],a:3},
    {q:'A pregnant woman presents with fever every 48 hours associated with chills and rigors. Peripheral smear reveals ring forms of Plasmodium species. Which complication is she most at risk of during pregnancy?',o:['Macrosomia','Placenta previa','Shoulder dystocia','Intrauterine growth restriction'],a:3},
    {q:'A 30-year-old pregnant woman develops severe COVID-19 infection with hypoxia and bilateral lung infiltrates on imaging. Which life-threatening complication is most likely responsible for her respiratory failure?',o:['Pulmonary tuberculosis','Acute respiratory distress syndrome','Bronchial asthma','Pleural effusion'],a:1},
    {q:'A traveler returns from a malaria-endemic region with high fever, confusion, and seizures. Blood smear shows Plasmodium falciparum. Which severe complication explains his neurological symptoms?',o:['Viral encephalitis','Hepatic malaria','Cerebral malaria','Septic meningitis'],a:2},
    {q:'A pregnant patient with confirmed dengue infection develops hypotension, tachycardia, and signs of plasma leakage. What is the most likely diagnosis?',o:['Septic shock','Hypovolemic shock','Anaphylactic shock','Dengue shock syndrome'],a:3},
    {q:'A 28-year-old primigravida at 12 weeks develops fever and lymphadenopathy. Serology shows positive IgM for Toxoplasma gondii. Which fetal complication is most strongly associated with congenital infection?',o:['Congenital heart disease','Limb reduction defects','Cataracts','Hydrocephalus with intracranial calcifications'],a:3},
    {q:'A pregnant woman at 20 weeks presents with mild fever and malaise. Ultrasound later reveals fetal microcephaly and periventricular calcifications. Which infection is most likely responsible?',o:['Toxoplasmosis','Cytomegalovirus','Rubella','Parvovirus B19'],a:1},
    {q:'A pregnant healthcare worker is exposed to a child with erythema infectiosum. Two weeks later ultrasound shows fetal ascites and cardiomegaly. What is the underlying fetal mechanism?',o:['Placental thrombosis','Severe fetal anemia','Congenital heart malformation','Hepatic failure'],a:1},
    {q:'A woman at 34 weeks gestation presents with intense pruritus, elevated liver enzymes, and positive hepatitis E serology. Which complication is most feared in pregnancy?',o:['Mild self-limiting hepatitis','Chronic liver disease','Fulminant hepatic failure','Renal calculi'],a:2},
    {q:'A pregnant woman with untreated syphilis delivers a stillborn fetus with hepatosplenomegaly and skin lesions. Which diagnostic test during pregnancy would most likely have identified the infection early?',o:['VDRL screening','Liver biopsy','Blood culture','Ultrasound Doppler'],a:0},
    {q:'A neonate born to an untreated HIV-positive mother develops infection. Which factor most strongly increases vertical transmission risk?',o:['Maternal anemia','Maternal hypertension','High maternal viral load','Multiparity'],a:2},
    {q:'A pregnant woman with active genital herpes lesions presents in labor. Which management strategy best prevents neonatal infection?',o:['Immediate cesarean delivery','Vacuum extraction','Forceps delivery','Induction with oxytocin'],a:0},
    {q:'A fetus is found to have hydrops fetalis with severe anemia on Doppler study after maternal viral illness. Which investigation confirms the suspected infection?',o:['Maternal HIV ELISA','Parvovirus B19 IgM serology','Hepatitis B surface antigen','Syphilis VDRL'],a:1},
    {q:'A newborn presents with cataracts, sensorineural deafness, and patent ductus arteriosus. Maternal infection during pregnancy most likely involved which pathogen?',o:['Toxoplasma gondii','Cytomegalovirus','Rubella virus','Herpes simplex virus'],a:2},
    {q:'A pregnant woman presents with high fever and thrombocytopenia after travel to a tropical region. Laboratory findings show plasma leakage and hemoconcentration. What is the most likely diagnosis?',o:['Viral hepatitis','Malaria','COVID-19','Dengue hemorrhagic fever'],a:3},
    {q:'A 32-year-old pregnant woman presents with periodic fever every 48 hours and anemia. Peripheral smear shows trophozoites in erythrocytes. Which complication is most concerning for the fetus?',o:['Neural tube defects','Congenital heart disease','Intrauterine growth restriction','Limb deformities'],a:2},
    {q:'A pregnant woman develops fever and jaundice with positive HBsAg and HBeAg. Which neonatal complication is most likely without prophylaxis?',o:['Neonatal anemia','Chronic hepatitis B infection','Neonatal pneumonia','Congenital heart disease'],a:1},
    {q:'A patient at 30 weeks gestation develops severe COVID-19 pneumonia with hypoxia. Which obstetric complication is most associated with severe maternal infection?',o:['Macrosomia','Preterm birth','Post-term pregnancy','Placenta accreta'],a:1},
    {q:'A fetus shows intracranial calcifications and chorioretinitis on ultrasound. Maternal ingestion of undercooked meat earlier in pregnancy is reported. Which infection is responsible?',o:['Cytomegalovirus','Rubella','Toxoplasmosis','Parvovirus B19'],a:2},
    {q:'A pregnant woman with untreated gonorrhea delivers a newborn who develops purulent conjunctivitis within 48 hours. What is the most likely diagnosis?',o:['Viral conjunctivitis','Ophthalmia neonatorum','Congenital glaucoma','Allergic conjunctivitis'],a:1},
    {q:'A pregnant woman develops genital warts during antenatal care. Which virus is responsible for this condition?',o:['HSV','HBV','HIV','HPV'],a:3},
    {q:'A neonate develops hepatosplenomegaly and thrombocytopenia with "blueberry muffin" rash. Which congenital infection is most likely responsible?',o:['Cytomegalovirus','Toxoplasmosis','Rubella','Syphilis'],a:2},
    {q:'A pregnant woman with untreated HIV infection delivers vaginally without ART. Which neonatal complication is most likely?',o:['Congenital heart disease','Neonatal HIV infection','Neural tube defect','Spina bifida'],a:1},
    {q:'A fetus shows sensorineural hearing loss and microcephaly on postnatal evaluation. Which congenital infection is the most common cause?',o:['Toxoplasmosis','Cytomegalovirus','Rubella','Syphilis'],a:1},
    {q:'A pregnant traveler from a malaria-endemic region presents with severe anemia and fever. Peripheral smear confirms Plasmodium falciparum. Which maternal complication is most likely?',o:['Cerebral malaria','Hyperthyroidism','Osteoporosis','Renal calculi'],a:0},
    {q:'A pregnant woman develops jaundice and elevated liver enzymes after contaminated water exposure. Which virus is most likely responsible?',o:['Hepatitis B','Hepatitis C','Hepatitis E','Hepatitis D'],a:2},
    {q:'A pregnant patient develops vesicular genital lesions and pain. PCR confirms HSV infection. Which neonatal complication is most feared if transmitted?',o:['Neonatal sepsis','Neonatal herpes encephalitis','Congenital cataracts','Neural tube defects'],a:1},
    {q:'A fetus shows ascites, hepatomegaly, and hydrops after maternal viral illness. Which diagnostic test best detects fetal anemia in this scenario?',o:['Amniocentesis','Doppler of middle cerebral artery','Non-stress test','Biophysical profile'],a:1},
    {q:'A pregnant woman with TORCH infection has fetal intracranial calcifications predominantly in periventricular regions. Which infection is most likely?',o:['Cytomegalovirus','Toxoplasmosis','Rubella','Syphilis'],a:0},
    {q:'A neonate develops hepatosplenomegaly and snuffles shortly after birth. Maternal history reveals untreated infection during pregnancy. Which disease is most likely?',o:['Congenital syphilis','Congenital CMV','Congenital toxoplasmosis','Congenital rubella'],a:0},
    {q:'A pregnant woman presents with high fever, thrombocytopenia, and plasma leakage after dengue infection. Which complication explains hypotension and shock?',o:['Hemorrhagic anemia','Dengue shock syndrome','Septic shock','Hypoglycemic shock'],a:1},
    {q:'A fetus develops hydrops due to maternal parvovirus infection. Which pathophysiological process explains this condition?',o:['Cardiac malformation','Severe fetal anemia','Placental infarction','Liver failure'],a:1},
    {q:'A pregnant patient tests positive for HBsAg. Which neonatal prophylaxis strategy prevents vertical transmission?',o:['Maternal antiviral therapy only','HBV vaccine plus HBIG at birth','Avoid breastfeeding','Elective cesarean delivery'],a:1},
    {q:'A fetus is diagnosed with hydrocephalus and chorioretinitis. Maternal infection occurred after exposure to cat feces. Which infection is most likely responsible?',o:['Cytomegalovirus','Rubella','Toxoplasmosis','Parvovirus B19'],a:2},
    {q:'A neonate develops severe pneumonia and sepsis shortly after birth from maternal genital infection. Which pathogen is most commonly responsible for early neonatal infection?',o:['Listeria monocytogenes','Escherichia coli','Staphylococcus aureus','Group B Streptococcus'],a:3}
  ];
})();