// MedMasters : Gynae & Obs Paper 2: Common Congenital Anomalies
// 60 MCQs | Blood Disorders & Jaundice in Pregnancy
(function(){
  if(!window.MM) window.MM={};
  window.MM['gynae_p2_congenital'] = [

    {q:'The most common physiological haematological change during normal pregnancy is:',o:['Leukopenia','Physiological anaemia due to haemodilution','Thrombocytopenia','Polycythemia'],a:1,
    e:`Plasma volume rises disproportionately to red cell mass during pregnancy, producing relative haemodilution: this physiological anaemia is the most common haematological change in normal pregnancy.<br><br>All physiological changes of pregnancy, including increased cardiac output, volume expansion and haemodilution, are normal adaptations.<br><br>Meanwhile, leukopenia (A), thrombocytopenia (C) and polycythemia (D) are not normal physiological findings in pregnancy.<br><br><em>(Obstetrics by Ten Teachers)</em>`},

    {q:'The most common cause of anaemia during pregnancy worldwide is:',o:['Folate deficiency','Vitamin B12 deficiency','Iron deficiency anaemia','Haemolytic anaemia'],a:2,
    e:`The detection of anaemia should prompt examination of the mean cell volume to identify likely iron deficiency anaemia (microcytic anaemia) : iron deficiency is the most common cause of anaemia in pregnancy worldwide.<br><br>Further investigations may include B12, folate or iron (ferritin) studies, and appropriate treatment should be initiated.<br><br>Folate deficiency (A) is the second most common; B12 deficiency (B) and haemolytic anaemia (D) are far less frequent.<br><br><em>(Obstetrics by Ten Teachers; Chapter 2: Antenatal Care)</em>`},

    {q:'The typical peripheral blood smear finding in iron deficiency anaemia is:',o:['Microcytic hypochromic cells','Macrocytic normochromic cells','Normocytic normochromic cells','Spherocytes'],a:0,
    e:`Iron deficiency anaemia produces microcytic hypochromic red cells on peripheral smear, reflecting reduced haemoglobin synthesis due to inadequate iron stores.<br><br>Examination of the mean cell volume identifies iron deficiency anaemia as microcytic anaemia, distinguishing it from folate or B12 deficiency which produce macrocytic anaemia.<br><br>Macrocytic normochromic cells (B) suggest folate or B12 deficiency; normocytic normochromic cells (C) are seen in anaemia of chronic disease; spherocytes (D) indicate haemolytic anaemia.<br><br><em>(Obstetrics by Ten Teachers; Chapter 2: Antenatal Care)</em>`},

    {q:'Which index is most useful for differentiating iron deficiency anaemia from thalassaemia trait?',o:['Mean corpuscular volume (MCV)','Red cell distribution width (RDW)','Mentzer index','Haematocrit'],a:2,
    e:`The Mentzer index (MCV divided by RBC count) is the most useful tool to differentiate iron deficiency anaemia from thalassaemia trait: a value below 13 suggests thalassaemia, above 13 suggests iron deficiency.<br><br>Both conditions produce microcytic anaemia, making MCV alone insufficient for differentiation.<br><br>MCV (A), RDW (B) and haematocrit (D) contribute to the picture but none differentiates as reliably as the Mentzer index.<br><br><em>(Williams Obstetrics)</em>`},

    {q:'Beta-thalassaemia major is characterised by:',o:['Reduced alpha globin synthesis','Reduced beta globin synthesis','Excess haemoglobin A','Excess haemoglobin F only'],a:1,
    e:`Beta-thalassaemia results from reduced or absent production of the beta-globin chains; beta-thalassaemia major results from the inheritance of two abnormal beta genes, leading to severe anaemia, FGR and poor musculoskeletal development without treatment.<br><br>As the switch from HbF to HbA occurs, absent beta-globin chains shorten red cell survival, with destruction within the bone marrow and spleen.<br><br>Reduced alpha globin synthesis (A) defines alpha-thalassaemia; excess HbA (C) and excess HbF only (D) do not characterise thalassaemia major.<br><br><em>(Obstetrics by Ten Teachers; Chapter 3: Normal Fetal Development and Growth)</em>`},

    {q:'The inheritance pattern of thalassaemia is:',o:['Autosomal dominant','X-linked recessive','Autosomal recessive','Mitochondrial'],a:2,
    e:`Thalassaemias are inherited in an autosomal recessive pattern, although they can occur worldwide; the carrier rate is particularly common in people from Southeast Asia, the Mediterranean, North Africa, the Middle East and Asia.<br><br>Both parents must carry the defective gene for an affected child to be born.<br><br>Autosomal dominant (A), X-linked recessive (B) and mitochondrial (D) inheritance do not apply to thalassaemia.<br><br><em>(Obstetrics by Ten Teachers; Chapter 2: Antenatal Care)</em>`},

    {q:'Which haemoglobin is predominantly increased in beta-thalassaemia major?',o:['HbA','HbF','HbA2','HbS'],a:1,
    e:`Ninety percent of fetal haemoglobin is HbF between 10 and 28 weeks gestation; in beta-thalassaemia major, absent beta-globin chains prevent the switch to HbA, leaving HbF as the predominant haemoglobin.<br><br>HbA is the adult haemoglobin that cannot be produced adequately in this condition.<br><br>HbA (A) is deficient, not increased; HbA2 (C) is mildly elevated in carriers only; HbS (D) is the sickle cell haemoglobin.<br><br><em>(Obstetrics by Ten Teachers; Chapter 3: Normal Fetal Development and Growth)</em>`},

    {q:'The most important screening test for thalassaemia carriers in reproductive-age women is:',o:['Peripheral smear','Serum ferritin','Haemoglobin electrophoresis','Reticulocyte count'],a:2,
    e:`Screening for thalassaemia is offered to all pregnant women at the booking visit using the Family Origin Questionnaire and FBC results; haemoglobin electrophoresis is the definitive test that identifies carrier status by detecting elevated HbA2 in beta-thalassaemia trait.<br><br>Those at high risk should be referred to a fetal medicine unit to discuss the option of invasive confirmatory testing.<br><br>Peripheral smear (A) suggests microcytosis but cannot confirm carrier status; serum ferritin (B) assesses iron stores; reticulocyte count (D) reflects erythropoietic activity.<br><br><em>(Obstetrics by Ten Teachers; Chapter 2: Antenatal Care)</em>`},

    {q:'Which prenatal diagnostic test can detect thalassaemia in the fetus early in pregnancy?',o:['Amniocentesis','Chorionic villus sampling','Ultrasound Doppler','Non-stress test'],a:1,
    e:`Chorionic villus sampling, performed at 10–13 weeks, provides fetal DNA for molecular diagnosis of thalassaemia and is the earliest invasive test available for prenatal diagnosis.<br><br>Partners of women with haemoglobinopathies are offered screening early in pregnancy, with the option of invasive testing to detect an affected fetus if both parents are carriers.<br><br>Amniocentesis (A) is performed later at 15–20 weeks; ultrasound Doppler (C) and non-stress test (D) assess fetal wellbeing but cannot diagnose genetic conditions.<br><br><em>(Obstetrics by Ten Teachers; Chapter 2: Antenatal Care)</em>`},

    {q:'Severe untreated anaemia in pregnancy is associated with which obstetric complication?',o:['Post-term pregnancy','Macrosomia','Preterm labour','Polyhydramnios'],a:2,
    e:`Severe anaemia reduces oxygen delivery to the uterus and placenta, precipitating preterm labour as the most recognised obstetric complication.<br><br>Women with multiple pregnancies, already at higher risk of anaemia, have a significantly increased rate of preterm delivery, illustrating this direct relationship.<br><br>Post-term pregnancy (A) and macrosomia (B) are not associated with anaemia; polyhydramnios (D) relates to fetal swallowing disorders.<br><br><em>(Obstetrics by Ten Teachers)</em>`},

    {q:'Which anaemia is characterised by macrocytic red blood cells during pregnancy?',o:['Iron deficiency anaemia','Folate deficiency anaemia','Thalassaemia','Haemolytic anaemia'],a:1,
    e:`Folate deficiency impairs DNA synthesis, producing large immature red cells: macrocytic anaemia is the classic haematological finding of folate deficiency during pregnancy.<br><br>Examination of the mean cell volume identifies folate or vitamin B12 deficiency as macrocytic anaemia, distinguishing it from iron deficiency which is microcytic.<br><br>Iron deficiency (A) and thalassaemia (C) produce microcytic anaemia; haemolytic anaemia (D) typically produces normocytic red cells.<br><br><em>(Obstetrics by Ten Teachers; Chapter 2: Antenatal Care)</em>`},

    {q:'The daily folic acid requirement during pregnancy is approximately:',o:['100 µg','200 µg','400 µg','1000 µg'],a:2,
    e:`400 µg (0.4 mg) of folic acid daily is the standard recommended dose for pregnant women and those planning pregnancy, specifically to reduce the risk of neural tube defects in the fetus.<br><br>Women with a previous neural tube defect pregnancy or those on antiepileptic medications require a higher dose of 5 mg daily.<br><br>100 µg (A) and 200 µg (B) are insufficient; 1000 µg (D) exceeds the standard requirement for most women.<br><br><em>(Williams Obstetrics)</em>`},

    {q:'Vitamin B12 deficiency anaemia is most commonly associated with:',o:['Strict vegetarian diet','High protein diet','High iron intake','Excess vitamin C intake'],a:0,
    e:`Vitamin B12 is found exclusively in animal products; a strict vegetarian or vegan diet excluding all animal-derived foods is the most common cause of B12 deficiency anaemia in women of reproductive age.<br><br>Further investigations for anaemia in pregnancy may include B12, folate or iron (ferritin) studies, and appropriate treatment should be initiated promptly.<br><br>High protein diet (B), high iron intake (C) and excess vitamin C (D) do not cause B12 deficiency.<br><br><em>(Obstetrics by Ten Teachers; Chapter 2: Antenatal Care)</em>`},

    {q:'Which anaemia is characterised by destruction of red blood cells leading to elevated bilirubin?',o:['Iron deficiency anaemia','Haemolytic anaemia','Aplastic anaemia','Megaloblastic anaemia'],a:1,
    e:`Haemolytic anaemia results from accelerated red cell destruction: unconjugated bilirubin from haemoglobin breakdown accumulates in the circulation before hepatic conjugation, producing indirect hyperbilirubinaemia.<br><br>In utero, unconjugated bilirubin is actively transported from the fetus to the mother across the placenta.<br><br>Iron deficiency (A), aplastic (C) and megaloblastic (D) anaemias are not primarily associated with haemolysis or elevated bilirubin.<br><br><em>(Obstetrics by Ten Teachers; Chapter 3: Normal Fetal Development and Growth)</em>`},

    {q:'The most common inherited bleeding disorder is:',o:['Haemophilia A','Haemophilia B','Von Willebrand disease','Factor X deficiency'],a:2,
    e:`Von Willebrand disease is the most common inherited bleeding disorder, with an estimated prevalence of 1%; it results from either a qualitative or quantitative defect in von Willebrand factor, and its inheritance is usually autosomal dominant.<br><br>Von Willebrand disease, carriers of haemophilia A and B and factor XI deficiency account for over 90% of all women with inherited bleeding disorders.<br><br>Haemophilia A (A) has a prevalence of 1 in 10,000 and haemophilia B (B) 1 in 100,000; factor X deficiency (D) is rare.<br><br><em>(Obstetrics by Ten Teachers; Chapter 10: Medical Complications of Pregnancy)</em>`},

    {q:'Haemophilia A is caused by deficiency of:',o:['Factor VIII','Factor IX','Factor X','Factor XIII'],a:0,
    e:`Haemophilia A (FVIII deficiency) is an X-linked defect with a prevalence of 1 in 10,000 in the population; carriers usually have clotting factor activity about 50% of normal.<br><br>Factor VIIIC levels increase in pregnancy, which can partially buffer the bleeding risk in carriers.<br><br>Factor IX (B) deficiency defines haemophilia B; factor X (C) and XIII (D) deficiencies are distinct rare disorders.<br><br><em>(Obstetrics by Ten Teachers; Chapter 10: Medical Complications of Pregnancy)</em>`},

    {q:'Haemophilia B is caused by deficiency of:',o:['Factor VII','Factor VIII','Factor IX','Factor XI'],a:2,
    e:`Haemophilia B (FIX deficiency) is an X-linked defect with a prevalence of 1 in 100,000 in the population, also known as Christmas disease.<br><br>Unlike haemophilia A carriers, factor IXC levels increase only slightly during pregnancy, providing less buffer against bleeding risk.<br><br>Factor VII (A) deficiency is a separate rare disorder; factor VIII (B) deficiency defines haemophilia A; factor XI (D) deficiency is a distinct autosomal dominant condition.<br><br><em>(Obstetrics by Ten Teachers; Chapter 10: Medical Complications of Pregnancy)</em>`},

    {q:'Haemophilia is inherited as:',o:['Autosomal dominant','Autosomal recessive','X-linked dominant','X-linked recessive'],a:3,
    e:`Haemophilia A and B are X-linked defects: the defective gene is carried on the X chromosome, so females are carriers while males are affected.<br><br>In haemophilia carriers, tests to confirm fetal sex should be offered : either by ultrasound or by sampling fetal DNA in maternal blood : as this influences the use of interventions in labour.<br><br>Autosomal dominant (A) and autosomal recessive (B) patterns do not apply; X-linked dominant (C) would mean all carrier females are clinically affected, which is not the case.<br><br><em>(Obstetrics by Ten Teachers; Chapter 10: Medical Complications of Pregnancy)</em>`},

    {q:'A woman who is a carrier of haemophilia has a risk of transmitting the disease to:',o:['All daughters','Half of her sons','All sons','Half of her daughters'],a:1,
    e:`A carrier mother has one normal and one affected X chromosome: each son has a 50% chance of inheriting the affected X and therefore being affected with haemophilia.<br><br>Daughters have a 50% chance of being carriers but will not themselves be affected, as they receive a Y chromosome from their father.<br><br>All daughters (A) being affected is incorrect; all sons (C) would only apply if the father were also affected; half of daughters (D) become carriers, not clinically affected.<br><br><em>(Obstetrics by Ten Teachers; Chapter 10: Medical Complications of Pregnancy)</em>`},

    {q:'Which coagulation test is prolonged in haemophilia?',o:['Prothrombin time','Bleeding time','Activated partial thromboplastin time','Thrombin time'],a:2,
    e:`The activated partial thromboplastin time (APTT) measures the intrinsic coagulation pathway, which includes factors VIII and IX: deficiency of either prolongs the APTT while leaving other tests normal.<br><br>Haemophilia A and B are intrinsic pathway defects; the prothrombin time and thrombin time remain unaffected.<br><br>Prothrombin time (A) is prolonged by warfarin and extrinsic pathway defects; bleeding time (B) tests platelet function; thrombin time (D) reflects fibrinogen function.<br><br><em>(Williams Obstetrics)</em>`},

    {q:'Disseminated intravascular coagulation (DIC) is characterised by:',o:['Hypercoagulation only','Simultaneous thrombosis and bleeding','Isolated platelet deficiency','Reduced fibrinolysis'],a:1,
    e:`DIC causes acute cardiorespiratory compromise through widespread clotting that consumes platelets and clotting factors, leading paradoxically to simultaneous microvascular thrombosis and systemic bleeding.<br><br>It is a life-threatening condition in which thrombosis and haemorrhage occur together, not in isolation.<br><br>Hypercoagulation alone (A) describes thrombophilia; isolated platelet deficiency (C) describes thrombocytopenia; reduced fibrinolysis (D) is the opposite of what occurs in DIC.<br><br><em>(Obstetrics by Ten Teachers; Chapter 14: Obstetric Emergencies)</em>`},

    {q:'Which obstetric condition commonly precipitates DIC?',o:['Placenta praevia','Post-dated pregnancy','Abruptio placentae','Mild anaemia'],a:2,
    e:`Abruptio placentae releases large amounts of thromboplastin from the retro-placental clot into the maternal circulation, triggering the coagulation cascade and precipitating DIC.<br><br>Disseminated intravascular coagulation is a recognised complication of severe placental abruption, making it one of the most important obstetric precipitants of this condition.<br><br>Placenta praevia (A) causes haemorrhage but not typically DIC; post-dated pregnancy (B) and mild anaemia (D) are not recognised triggers.<br><br><em>(Obstetrics by Ten Teachers)</em>`},

    {q:'In DIC, which laboratory finding is typically present?',o:['Increased fibrinogen','Decreased D-dimer','Thrombocytosis','Decreased fibrinogen'],a:3,
    e:`In DIC, widespread activation of coagulation consumes fibrinogen as it is converted to fibrin clots throughout the microvasculature, resulting in decreased fibrinogen levels.<br><br>Alongside decreased fibrinogen, D-dimer is markedly elevated due to extensive fibrin degradation, and platelets fall rather than rise.<br><br>Increased fibrinogen (A) occurs physiologically in normal pregnancy; decreased D-dimer (B) and thrombocytosis (C) are both the opposite of what is found in DIC.<br><br><em>(Williams Obstetrics)</em>`},

    {q:'Which anaemia is characterised by bone marrow failure?',o:['Iron deficiency anaemia','Aplastic anaemia','Haemolytic anaemia','Megaloblastic anaemia'],a:1,
    e:`Aplastic anaemia results from failure or destruction of bone marrow stem cells, leading to pancytopenia: reduced red cells, white cells and platelets, rather than anaemia alone.<br><br>It is a rare but serious complication in pregnancy, requiring specialist haematological input as the marrow itself is unable to produce blood cells.<br><br>Iron deficiency (A) and megaloblastic (D) anaemias are nutritional; haemolytic anaemia (C) results from red cell destruction, not marrow failure.<br><br><em>(Williams Obstetrics)</em>`},

    {q:'Sickle cell anaemia results from a mutation in the gene encoding:',o:['Alpha globin','Gamma globin','Delta globin','Beta globin'],a:3,
    e:`Sickle cell disease results from a point mutation in the beta-globin gene, producing the abnormal haemoglobin S (HbS): HbSS : homozygous sickle cell disease : is the most serious form, causing chronic haemolytic anaemia and sickle cell crises precipitated by infection.<br><br>Partners of women with sickle cell disease or trait are offered screening early in pregnancy with the option of invasive testing if both parents are carriers.<br><br>Alpha globin (A) mutations cause alpha-thalassaemia; gamma (B) and delta (C) globin mutations produce less clinically significant variants.<br><br><em>(Obstetrics by Ten Teachers; Chapter 2: Antenatal Care)</em>`},

    {q:'The abnormal haemoglobin present in sickle cell disease is:',o:['HbA','HbF','HbS','HbA2'],a:2,
    e:`HbS is the abnormal haemoglobin produced by the sickle cell mutation: the carrier rate for sickle cell trait (HbAS) is approximately 1 in 10 among Afro-Caribbean people but as high as 1 in 4 in people from West Africa.<br><br>Under low oxygen conditions, HbS polymerises and causes red cells to adopt the characteristic sickle shape, producing vaso-occlusion and haemolysis.<br><br>HbA (A) is normal adult haemoglobin; HbF (B) is fetal haemoglobin protective against sickling; HbA2 (D) is mildly elevated in beta-thalassaemia trait.<br><br><em>(Obstetrics by Ten Teachers; Chapter 2: Antenatal Care)</em>`},

    {q:'Pregnant women with sickle cell disease are at increased risk of:',o:['Macrosomia','Pre-eclampsia','Post-term pregnancy','Polyhydramnios'],a:1,
    e:`HbSS patients have chronic haemolytic anaemia and suffer from sickle cell crises precipitated by infection: placental vaso-occlusion drives increased risks of pre-eclampsia, preterm labour and fetal growth restriction in pregnancy.<br><br>Partners of women with sickle cell disease are offered screening early in pregnancy, reflecting the seriousness of this condition in the obstetric context.<br><br>Macrosomia (A) and post-term pregnancy (C) are not associated with sickle cell disease; polyhydramnios (D) relates to fetal swallowing disorders.<br><br><em>(Obstetrics by Ten Teachers; Chapter 2: Antenatal Care)</em>`},

    {q:'Which laboratory test best assesses iron stores in the body?',o:['Serum ferritin','Haemoglobin level','Haematocrit','Reticulocyte count'],a:0,
    e:`Women with known haemoglobinopathy should have serum ferritin checked and offered oral supplements if their ferritin level is below 30 µg/l: serum ferritin is the most accurate marker of body iron stores, falling before anaemia becomes clinically apparent.<br><br>A trial of oral iron is the first-line management option, with an increment demonstrated at two weeks confirming a positive response.<br><br>Haemoglobin (B) and haematocrit (C) only fall once stores are already depleted; reticulocyte count (D) reflects erythropoietic activity, not iron stores.<br><br><em>(Obstetrics by Ten Teachers; Chapter 2: Antenatal Care)</em>`},

    {q:'Which platelet disorder is most commonly seen during pregnancy?',o:['Immune thrombocytopenic purpura','Gestational thrombocytopenia','Thrombotic thrombocytopenic purpura','Aplastic thrombocytopenia'],a:1,
    e:`Incidental or gestational thrombocytopaenia is common, found in 7–8% of pregnant women; a modest drop in platelet count to 100–150 × 10⁹/l is only very rarely associated with poor pregnancy outcomes.<br><br>It usually occurs in late pregnancy with no prior history of thrombocytopaenia, and spontaneous resolution occurs after delivery with no fetal thrombocytopaenia.<br><br>ITP (A) has an incidence of around 1 in 5,000; TTP (C) and aplastic thrombocytopenia (D) are rare and serious conditions.<br><br><em>(Obstetrics by Ten Teachers; Chapter 10: Medical Complications of Pregnancy)</em>`},

    {q:'Which coagulation factor deficiency causes the most severe bleeding disorder known as haemophilia A?',o:['Factor IX','Factor XI','Factor XII','Factor VIII'],a:3,
    e:`Haemophilia A (FVIII deficiency) is an X-linked defect with a prevalence of 1 in 10,000; severe haemophilia A has factor VIII activity below 1% of normal, producing the most severe bleeding phenotype.<br><br>Carriers of haemophilia A usually have clotting factor activity about 50% of normal, and factor VIIIC levels increase in pregnancy.<br><br>Factor IX (A) deficiency defines haemophilia B; factor XI (B) deficiency is a milder autosomal disorder; factor XII (C) deficiency does not cause significant clinical bleeding.<br><br><em>(Obstetrics by Ten Teachers; Chapter 10: Medical Complications of Pregnancy)</em>`},

    {q:'The most common cause of jaundice during pregnancy is:',o:['Acute fatty liver of pregnancy','Viral hepatitis','Intrahepatic cholestasis of pregnancy','HELLP syndrome'],a:1,
    e:`Viral hepatitis is the most common cause of jaundice during pregnancy globally, responsible for the majority of cases presenting with clinical icterus.<br><br>Screening for hepatitis B and HIV is routinely offered in antenatal care, reflecting the importance of viral hepatitis surveillance in pregnancy.<br><br>Acute fatty liver (A) and HELLP (D) are rare but serious; intrahepatic cholestasis (C) typically presents with pruritus and raised liver enzymes rather than overt jaundice.<br><br><em>(Obstetrics by Ten Teachers; Chapter 10: Medical Complications of Pregnancy)</em>`},

    {q:'Intrahepatic cholestasis of pregnancy typically presents with:',o:['Severe hypertension','Generalised oedema','Pruritus without rash','Severe abdominal pain'],a:2,
    e:`Obstetric cholestasis normally presents in the second half of pregnancy with pruritus and abnormal liver function tests, neither of which has an alternative cause and both of which resolve after birth.<br><br>There can also be maternal morbidity in association with the intense pruritus and consequent sleep deprivation.<br><br>Severe hypertension (A) and oedema (B) suggest pre-eclampsia; severe abdominal pain (D) is more characteristic of acute fatty liver or abruption.<br><br><em>(Obstetrics by Ten Teachers; Chapter 6: Antenatal Obstetric Complications)</em>`},

    {q:'The most sensitive laboratory marker for intrahepatic cholestasis of pregnancy is:',o:['Serum bilirubin','ALT level','AST level','Serum bile acids'],a:3,
    e:`Serum bile acids are the most sensitive and specific marker for intrahepatic cholestasis of pregnancy: elevated bile acids confirm the diagnosis and correlate with fetal risk, making them the gold standard investigation.<br><br>The condition presents with pruritus and abnormal liver function tests, both of which resolve after birth.<br><br>Serum bilirubin (A) may not be elevated in all cases; ALT (B) and AST (C) are raised but less specific than bile acids for this diagnosis.<br><br><em>(Shaw's Textbook of Gynaecology)</em>`},

    {q:'Which fetal complication is most associated with intrahepatic cholestasis of pregnancy?',o:['Macrosomia','Preterm birth','Neural tube defects','Shoulder dystocia'],a:1,
    e:`The clinical importance of obstetric cholestasis lies in the potential fetal risks, which may include spontaneous preterm birth, iatrogenic preterm birth and fetal death.<br><br>Women with obstetric cholestasis are therefore normally offered delivery after 37 weeks' gestation.<br><br>Macrosomia (A) and shoulder dystocia (D) are not associated with cholestasis; neural tube defects (C) relate to folate deficiency.<br><br><em>(Obstetrics by Ten Teachers; Chapter 6: Antenatal Obstetric Complications)</em>`},

    {q:'The drug commonly used to treat intrahepatic cholestasis of pregnancy is:',o:['Ursodeoxycholic acid','Prednisolone','Methyldopa','Nifedipine'],a:0,
    e:`Obstetric cholestasis is normally treated with ursodeoxycholic acid (UDCA), which improves pruritus and liver function but has not been proven to improve fetal and neonatal outcomes.<br><br>Delivery after 37 weeks' gestation remains the mainstay of fetal risk reduction.<br><br>Prednisolone (B) has no established role in cholestasis; methyldopa (C) is an antihypertensive; nifedipine (D) is used for hypertension and tocolysis.<br><br><em>(Obstetrics by Ten Teachers; Chapter 6: Antenatal Obstetric Complications)</em>`},

    {q:'Acute fatty liver of pregnancy usually occurs in which trimester?',o:['First trimester','Second trimester','Early second trimester','Third trimester'],a:3,
    e:`Acute fatty liver of pregnancy characteristically presents in the third trimester, typically after 30 weeks and most commonly in the final weeks: it is a medical emergency requiring prompt recognition and delivery.<br><br>Maternal and fetal mortality are high if the condition is not recognised and managed rapidly.<br><br>First (A) and second trimester (B, C) presentations are not characteristic of acute fatty liver of pregnancy.<br><br><em>(Shaw's Textbook of Gynaecology)</em>`},

    {q:'Acute fatty liver of pregnancy is associated with deficiency of which fetal enzyme?',o:['Glucose-6-phosphate dehydrogenase','Long-chain 3-hydroxyacyl-CoA dehydrogenase','Pyruvate dehydrogenase','Lactate dehydrogenase'],a:1,
    e:`Acute fatty liver of pregnancy is strongly linked to fetal deficiency of long-chain 3-hydroxyacyl-CoA dehydrogenase (LCHAD): the fetus cannot metabolise long-chain fatty acids, which accumulate and transfer back to the mother, precipitating hepatic fat deposition.<br><br>This explains why the condition recurs in subsequent pregnancies carrying an LCHAD-deficient fetus, and why delivery is both diagnostic and curative.<br><br>G6PD deficiency (A) causes haemolytic anaemia; pyruvate dehydrogenase (C) and lactate dehydrogenase (D) deficiencies are not linked to this condition.<br><br><em>(Williams Obstetrics)</em>`},

    {q:'HELLP syndrome is characterised by haemolysis, elevated liver enzymes, and:',o:['Leukocytosis','Hypoglycaemia','Thrombocytopenia','Hypernatraemia'],a:2,
    e:`HELLP syndrome is defined by haemolysis, elevated liver enzymes and low platelets: a baseline platelet count is essential in pregnancy if there are concerns regarding pre-eclampsia or HELLP syndrome, which may present with thrombocytopaenia.<br><br>Each component of the acronym represents a distinct pathological process driven by endothelial dysfunction in severe pre-eclampsia.<br><br>Leukocytosis (A) and hypernatraemia (D) are not features; hypoglycaemia (B) may occur in acute fatty liver of pregnancy, not HELLP.<br><br><em>(Obstetrics by Ten Teachers; Chapter 2: Antenatal Care)</em>`},

    {q:'The most common viral cause of jaundice during pregnancy in developing countries is:',o:['Hepatitis A','Hepatitis B','Hepatitis C','Hepatitis E'],a:3,
    e:`Hepatitis E is the most common cause of viral jaundice in pregnant women in developing countries, transmitted via the faecal-oral route through contaminated water, causing disproportionately severe disease in pregnancy.<br><br>Screening for hepatitis B and HIV is routinely offered in antenatal care, reflecting broader viral hepatitis surveillance needs.<br><br>Hepatitis A (A) rarely causes severe disease in pregnancy; hepatitis B (B) and C (C) are important chronic infections but are less commonly the cause of acute jaundice.<br><br><em>(Obstetrics by Ten Teachers; Chapter 10: Medical Complications of Pregnancy)</em>`},

    {q:'Hepatitis E infection during pregnancy is associated with:',o:['Mild disease only','High maternal mortality','No fetal complications','Reduced liver enzymes'],a:1,
    e:`Hepatitis E in pregnancy carries a maternal mortality of up to 20–25% in developing countries, far higher than in non-pregnant individuals, due to a fulminant course with acute liver failure particularly severe in the third trimester.<br><br>This unusually high mortality makes hepatitis E the most dangerous viral hepatitis specifically in the context of pregnancy.<br><br>Mild disease only (A) is incorrect; fetal complications including preterm birth do occur, making (C) wrong; liver enzymes are markedly elevated, not reduced (D).<br><br><em>(Williams Obstetrics)</em>`},

    {q:'Physiological jaundice of the newborn may occur due to:',o:['Increased haemolysis','Increased bile acid secretion','Increased oestrogen causing cholestasis','Relative deficiency of conjugating enzymes'],a:3,
    e:`The fetal liver has a reduced ability to conjugate bilirubin because of relative deficiencies in the necessary enzymes such as glucuronyl transferase; after birth, the loss of the placental route of excretion of unconjugated bilirubin results in transient physiological jaundice of the newborn.<br><br>This is particularly pronounced in premature infants who have even more significant enzyme deficiencies.<br><br>Increased haemolysis (A) causes pathological jaundice; increased bile acid secretion (B) and oestrogen-induced cholestasis (C) describe cholestasis of pregnancy, not neonatal jaundice.<br><br><em>(Obstetrics by Ten Teachers; Chapter 3: Normal Fetal Development and Growth)</em>`},

    {q:'The most important fetal risk associated with maternal cholestasis is:',o:['Neural tube defects','Sudden intrauterine fetal death','Congenital heart disease','Limb deformities'],a:1,
    e:`The potential fetal risks of obstetric cholestasis include spontaneous preterm birth, iatrogenic preterm birth and fetal death: sudden intrauterine fetal death can occur unpredictably, and is the primary reason for offering delivery after 37 weeks.<br><br>Women with obstetric cholestasis are therefore normally offered delivery at that gestation.<br><br>Neural tube defects (A), congenital heart disease (C) and limb deformities (D) are not associated with maternal cholestasis.<br><br><em>(Obstetrics by Ten Teachers; Chapter 6: Antenatal Obstetric Complications)</em>`},

    {q:'Which laboratory finding is typical in obstructive jaundice?',o:['Decreased AST','Elevated unconjugated bilirubin','Decreased ALT','Elevated alkaline phosphatase'],a:3,
    e:`Obstructive jaundice results from blockage of bile flow, causing bile constituents including alkaline phosphatase to accumulate in the circulation: markedly elevated alkaline phosphatase is the hallmark biochemical finding.<br><br>Conjugated bilirubin is also elevated, resulting in dark urine and pale stools.<br><br>Elevated unconjugated bilirubin (B) is characteristic of haemolytic jaundice; decreased AST (A) and decreased ALT (C) are both incorrect, as these may be mildly elevated.<br><br><em>(Shaw's Textbook of Gynaecology)</em>`},

    {q:'Haemolytic jaundice is primarily caused by:',o:['Increased red cell destruction','Obstruction of bile ducts','Liver cell necrosis','Reduced bile production'],a:0,
    e:`Unconjugated bilirubin from haemoglobin breakdown is actively transported from the fetus to the mother via the placenta: in haemolytic disorders, accelerated red cell destruction overwhelms the liver's capacity to conjugate bilirubin, causing unconjugated hyperbilirubinaemia.<br><br>The rate of bilirubin production exceeds hepatic conjugation and excretion.<br><br>Obstruction of bile ducts (B) causes obstructive jaundice; liver cell necrosis (C) causes hepatocellular jaundice; reduced bile production (D) does not primarily cause jaundice.<br><br><em>(Obstetrics by Ten Teachers; Chapter 3: Normal Fetal Development and Growth)</em>`},

    {q:'Which type of bilirubin is elevated in haemolytic jaundice?',o:['Conjugated bilirubin','Direct bilirubin','Unconjugated bilirubin','Mixed bilirubin'],a:2,
    e:`In haemolytic jaundice, excessive red cell breakdown produces large amounts of unconjugated bilirubin that overwhelm hepatic conjugating capacity: unconjugated bilirubin is lipid-soluble, cannot be filtered by the glomerulus, and therefore does not appear in urine.<br><br>This distinguishes haemolytic from obstructive jaundice clinically, as dark urine is absent in pure haemolysis.<br><br>Conjugated (A) and direct (B) bilirubin are the same fraction, elevated in obstructive jaundice; mixed elevation (D) occurs in hepatocellular disease.<br><br><em>(Obstetrics by Ten Teachers; Chapter 3: Normal Fetal Development and Growth)</em>`},

    {q:'The classical symptom of cholestasis in pregnancy is:',o:['Severe headache','Pruritus especially on palms and soles','Visual disturbances','Haematemesis'],a:1,
    e:`Obstetric cholestasis normally presents in the second half of pregnancy with pruritus: this is classically most intense on the palms and soles, helping distinguish it from generalised pruritic skin conditions.<br><br>There can also be maternal morbidity in association with the intense pruritus and consequent sleep deprivation.<br><br>Severe headache (A) and visual disturbances (C) suggest pre-eclampsia; haematemesis (D) indicates oesophageal or gastric pathology.<br><br><em>(Obstetrics by Ten Teachers; Chapter 6: Antenatal Obstetric Complications)</em>`},

    {q:'Which pregnancy-related liver disorder is associated with microvesicular fatty infiltration of hepatocytes?',o:['HELLP syndrome','Viral hepatitis','Acute fatty liver of pregnancy','Gallstone disease'],a:2,
    e:`Acute fatty liver of pregnancy is defined pathologically by microvesicular fatty infiltration of hepatocytes: small fat droplets accumulate within liver cells without displacing the nucleus, a pattern distinct from the macrovesicular steatosis of alcohol-related disease.<br><br>It is a rare but life-threatening obstetric emergency requiring prompt delivery.<br><br>HELLP syndrome (A) involves haemolysis and periportal necrosis; viral hepatitis (B) causes hepatocellular inflammation; gallstone disease (D) causes obstructive pathology.<br><br><em>(Williams Obstetrics)</em>`},

    {q:'Gallstones during pregnancy are mainly formed due to:',o:['Increased bile flow','Increased progesterone causing gallbladder stasis','Reduced cholesterol levels','Increased bile acid secretion'],a:1,
    e:`Progesterone relaxes smooth muscle throughout the body : including the gallbladder wall : leading to reduced gallbladder motility, bile stasis and supersaturation of bile with cholesterol, promoting gallstone formation.<br><br>The relaxant effect of progesterone on vascular smooth muscle is a consistent physiological theme in pregnancy, affecting the gallbladder, ureters and veins.<br><br>Increased bile flow (A) would be protective against stones; cholesterol levels rise in pregnancy, making (C) incorrect; increased bile acid secretion (D) is not the primary mechanism.<br><br><em>(Obstetrics by Ten Teachers; Chapter 6: Antenatal Obstetric Complications)</em>`},

    {q:'Which enzyme level is markedly elevated in hepatocellular jaundice?',o:['Amylase','Alkaline phosphatase','Creatine kinase','AST and ALT'],a:3,
    e:`AST and ALT are intracellular liver enzymes released in large amounts when hepatocytes are damaged: hepatocellular jaundice from viral hepatitis or toxic injury causes marked elevation of both, with ALT being more specific to the liver.<br><br>These are the defining biochemical markers of hepatocellular damage in clinical practice.<br><br>Amylase (A) is elevated in pancreatitis; alkaline phosphatase (B) is the hallmark of obstructive jaundice; creatine kinase (C) marks muscle damage.<br><br><em>(Shaw's Textbook of Gynaecology)</em>`},

    {q:'Acute fatty liver of pregnancy may lead to which serious maternal complication?',o:['Renal failure','Hyperthyroidism','Diabetes mellitus','Pulmonary embolism'],a:0,
    e:`Acute fatty liver of pregnancy can rapidly progress to multiorgan failure: renal failure is a recognised serious complication, occurring alongside hepatic failure, coagulopathy and hypoglycaemia in severe cases.<br><br>Without prompt delivery, maternal mortality is high due to progressive hepatic and renal failure.<br><br>Hyperthyroidism (B), diabetes mellitus (C) and pulmonary embolism (D) are not direct complications of acute fatty liver of pregnancy.<br><br><em>(Williams Obstetrics)</em>`},

    {q:'Which pregnancy-related liver disorder is strongly associated with pre-eclampsia?',o:['Acute fatty liver of pregnancy','Intrahepatic cholestasis','HELLP syndrome','Viral hepatitis'],a:2,
    e:`HELLP syndrome is a severe variant of pre-eclampsia driven by the same endothelial dysfunction: a baseline platelet count is essential if there are concerns regarding pre-eclampsia or HELLP, which may present with thrombocytopaenia.<br><br>It almost always occurs in the context of hypertensive disease of pregnancy.<br><br>Acute fatty liver (A) has some overlap but is a distinct entity; intrahepatic cholestasis (B) and viral hepatitis (D) are not associated with pre-eclampsia.<br><br><em>(Obstetrics by Ten Teachers; Chapter 2: Antenatal Care)</em>`},

    {q:'Elevated bilirubin, haemolysis, and low platelets in pregnancy should raise suspicion of:',o:['Viral hepatitis','HELLP syndrome','Gallstones','Intrahepatic cholestasis'],a:1,
    e:`Haemolysis, elevated liver enzymes and low platelets : the defining triad of HELLP syndrome : demand urgent assessment in any pregnant woman, driven by endothelial injury causing microangiopathic haemolysis, hepatocellular damage and platelet consumption.<br><br>Pre-eclampsia or HELLP syndrome may present with thrombocytopaenia, making platelet monitoring essential.<br><br>Viral hepatitis (A) does not cause thrombocytopenia; gallstones (C) produce obstructive jaundice without haemolysis; intrahepatic cholestasis (D) does not cause haemolysis or low platelets.<br><br><em>(Obstetrics by Ten Teachers; Chapter 2: Antenatal Care)</em>`},

    {q:'Which hormone contributes to reduced gallbladder motility during pregnancy?',o:['Progesterone','Oestrogen','Prolactin','Oxytocin'],a:0,
    e:`Progesterone is a smooth muscle relaxant that reduces gallbladder contractility during pregnancy, leading to bile stasis, increased cholesterol supersaturation of bile and a higher risk of gallstone formation.<br><br>The relaxant effect of progesterone on vascular smooth muscle and hollow viscera is a consistent physiological theme throughout pregnancy.<br><br>Oestrogen (B) may increase cholesterol saturation of bile but does not primarily reduce motility; prolactin (C) and oxytocin (D) have no significant role in gallbladder motility.<br><br><em>(Obstetrics by Ten Teachers; Chapter 6: Antenatal Obstetric Complications)</em>`},

    {q:'Which form of jaundice results from obstruction of bile flow?',o:['Haemolytic jaundice','Hepatocellular jaundice','Obstructive jaundice','Neonatal jaundice'],a:2,
    e:`Obstructive jaundice results from blockage of the biliary system : whether intrahepatic as in cholestasis of pregnancy, or extrahepatic as in gallstones : preventing bile from reaching the duodenum.<br><br>In obstetric cholestasis, the obstruction is intrahepatic, causing bile acid accumulation that produces pruritus and elevated liver enzymes, posing fetal risk.<br><br>Haemolytic (A) and neonatal (D) jaundice result from excessive bilirubin production; hepatocellular jaundice (B) results from liver cell damage.<br><br><em>(Shaw's Textbook of Gynaecology)</em>`},

    {q:'In obstructive jaundice, stool colour typically becomes:',o:['Dark black','Clay-coloured','Green','Bright red'],a:1,
    e:`In obstructive jaundice, bile cannot reach the duodenum, so stercobilin : the pigment that gives stool its brown colour : is not produced, resulting in pale, clay-coloured stools.<br><br>Simultaneously, conjugated bilirubin regurgitates into the bloodstream and is excreted by the kidneys, producing the characteristic dark urine.<br><br>Dark black stools (A) suggest upper gastrointestinal bleeding; green stools (C) occur with rapid intestinal transit; bright red stools (D) indicate lower gastrointestinal bleeding.<br><br><em>(Shaw's Textbook of Gynaecology)</em>`},

    {q:'Dark urine in jaundice occurs due to increased excretion of:',o:['Unconjugated bilirubin','Haemoglobin','Conjugated bilirubin','Urobilinogen only'],a:2,
    e:`Conjugated bilirubin is water-soluble and can be filtered by the kidneys: in obstructive or hepatocellular jaundice, it accumulates in the blood and spills into the urine, producing the characteristic dark brown or tea-coloured appearance.<br><br>Unconjugated bilirubin is lipid-soluble and bound to albumin, so it cannot be filtered by the glomerulus and does not appear in urine.<br><br>Unconjugated bilirubin (A) does not cause dark urine; haemoglobin (B) causes haematuria; urobilinogen alone (D) gives a slightly deeper yellow, not dark brown.<br><br><em>(Shaw's Textbook of Gynaecology)</em>`},

    {q:'Which pregnancy-related liver disorder has the highest maternal mortality if untreated?',o:['Acute fatty liver of pregnancy','Intrahepatic cholestasis','Gallstones','Mild hepatitis A'],a:0,
    e:`Acute fatty liver of pregnancy carries the highest maternal mortality of all pregnancy-related liver disorders if unrecognised and untreated: mortality approaches 70–80% without prompt delivery and intensive care.<br><br>The only definitive treatment is immediate delivery, which is both diagnostic and curative as symptoms resolve after birth.<br><br>Intrahepatic cholestasis (B) carries fetal risk but rarely causes maternal death; gallstones (C) are usually managed conservatively; mild hepatitis A (D) is almost always self-limiting.<br><br><em>(Williams Obstetrics)</em>`},

    {q:'Which test is most useful for confirming viral hepatitis during pregnancy?',o:['Serum bilirubin','Liver ultrasound','Complete blood count','Viral serology'],a:3,
    e:`Viral serology : specific antibody and antigen tests for hepatitis A, B, C, D and E : is the definitive method for diagnosing and typing viral hepatitis, providing both diagnosis and epidemiological classification.<br><br>Screening for hepatitis B and HIV is routinely offered in antenatal care using serological testing as the standard approach.<br><br>Serum bilirubin (A) confirms jaundice but does not identify the cause; liver ultrasound (B) excludes obstruction; complete blood count (C) shows only non-specific changes.<br><br><em>(Obstetrics by Ten Teachers; Chapter 10: Medical Complications of Pregnancy)</em>`},

    {q:'Intrahepatic cholestasis of pregnancy typically resolves:',o:['Immediately after conception','After the first trimester','After delivery','Before labour begins'],a:2,
    e:`Intrahepatic cholestasis of pregnancy is defined by pruritus and abnormal liver function tests, neither of which has an alternative cause and both of which resolve after birth: complete resolution of symptoms and liver function typically occurs within days to weeks of delivery.<br><br>This post-delivery resolution confirms the pregnancy-driven aetiology.<br><br>Resolution during pregnancy (A, B, D) is not characteristic; resolution before labour (D) would be coincidental, not part of the natural history.<br><br><em>(Obstetrics by Ten Teachers; Chapter 6: Antenatal Obstetric Complications)</em>`},

    {q:'The primary mechanism of jaundice in haemolytic disorders is:',o:['Increased bile duct obstruction','Reduced liver blood flow','Decreased bilirubin production','Excess breakdown of red blood cells'],a:3,
    e:`In haemolytic disorders, accelerated destruction of red blood cells releases large amounts of haem, catabolised to unconjugated bilirubin: the rate of production exceeds the liver's capacity to conjugate and excrete it, causing jaundice.<br><br>Unconjugated bilirubin from haemoglobin breakdown is actively transported across the placenta in utero; after birth the neonatal liver must take over this function.<br><br>Increased bile duct obstruction (A) causes obstructive jaundice; reduced liver blood flow (B) does not primarily cause jaundice; decreased bilirubin production (C) is the opposite of what occurs.<br><br><em>(Obstetrics by Ten Teachers; Chapter 3: Normal Fetal Development and Growth)</em>`}

  ];
})();
