// MedMasters — Gynae & Obs Paper 2: Antenatal & Natal Care
// 280 MCQs
(function(){
  if(!window.MM) window.MM={};
  window.MM['gynae_p2_antenatal'] = [
    {q:'A woman with a regular 28-day menstrual cycle reports her last menstrual period began on 10 March 2024. According to Naegele\'s rule, what is her estimated date of delivery (EDD)?',o:['17 December 2024','17 January 2025','3 December 2024','? A) 17 December 2024 B) 17 January 2025 C) 3 December 2024 D) 10 December 2024'],a:1},
    {q:'A pregnant woman presents for booking at 10 weeks gestation. Which investigation is routinely recommended at the first antenatal visit to screen for hemoglobinopathy?',o:['Hemoglobin electrophoresis','Serum ferritin level','Peripheral blood smear','Reticulocyte count'],a:0},
    {q:'A woman\'s LMP was 5 June 2023 and she has regular 30-day cycles. What is the most appropriate method to accurately determine gestational age if the exact LMP is uncertain?',o:['Second-trimester ultrasound biparietal diameter','First-trimester crown-rump length ultrasound','Fundal height measurement','Abdominal circumference measurement'],a:1},
    {q:'During antenatal booking, which infection screening is universally recommended in pregnancy to prevent vertical transmission and allow timely intervention?',o:['Rubella IgG antibody','Hepatitis A serology','Cytomegalovirus IgM','HIV screening test'],a:3},
    {q:'A pregnant woman reports LMP on 1 February 2024 with regular cycles. According to Naegele\'s rule, what is her EDD?',o:['8 November 2024','8 December 2024','1 November 2024','15 December 2024'],a:1},
    {q:'A 24-year-old primigravida presents at 8 weeks for antenatal booking. Which investigation is essential for identifying risk of hemolytic disease of the newborn?',o:['Blood group and Rh typing','Serum bilirubin','Direct Coombs test','Serum LDH'],a:0},
    {q:'A woman with irregular cycles is unsure of her LMP. At booking, ultrasound shows crown-rump length corresponding to 11 weeks 3 days. Which approach is recommended for calculating EDD?',o:['Use LMP estimate despite discrepancy','Use CRL-based dating as definitive gestational age','Average LMP and ultrasound dating','Repeat ultrasound at 20 weeks'],a:1},
    {q:'Which infection screening is recommended at booking to detect maternal infection that may cause congenital deafness and cataracts if acquired in early pregnancy?',o:['Rubella IgG antibody test','Parvovirus B19 serology','Toxoplasma IgM test','HSV PCR'],a:0},
    {q:'A woman with a 28-day cycle has LMP on 20 September 2023. What is the estimated date of delivery?',o:['27 June 2024','20 May 2024','27 June 2024','27 June 2024'],a:2},
    {q:'A 26-year-old woman presents for antenatal booking. Which infection screening is routinely recommended to prevent congenital syphilis?',o:['VDRL or RPR test','TPHA only','Dark field microscopy','Treponemal IgM antibody'],a:0},
    {q:'A patient reports LMP on 12 August 2023 with regular cycles. What is the estimated date of delivery using Naegele\'s rule?',o:['19 May 2024','12 May 2024','19 May 2024','5 May 2024'],a:0},
    {q:'Which infection screening during antenatal booking is specifically recommended for identifying carriers who may transmit infection to the fetus through placental crossing and cause severe fetal anemia?',o:['Toxoplasmosis screening','Parvovirus B19 IgM','CMV IgG','HSV culture'],a:1},
    {q:'A woman with regular cycles reports LMP on 5 April 2024. Using Naegele\'s rule, what is her EDD?',o:['12 January 2025','5 January 2025','5 December 2024','12 December 2024'],a:0},
    {q:'At booking, screening for hepatitis B infection is recommended primarily to reduce which risk?',o:['Maternal hepatic failure','Neonatal vertical transmission','Preterm labor','Placental abruption'],a:1},
    {q:'A pregnant woman attends booking at 9 weeks. Which test helps identify women at risk for rhesus isoimmunization requiring anti-D prophylaxis?',o:['Antibody screen (indirect Coombs test)','Direct Coombs test','Hemoglobin electrophoresis','Serum ferritin'],a:0},
    {q:'A patient presents with uncertain LMP and irregular cycles. Ultrasound at 19 weeks shows fetal measurements corresponding to 17 weeks. Which gestational age should be used for EDD calculation?',o:['LMP-based age','Ultrasound dating','Fundal height measurement','Quickening history'],a:1},
    {q:'Which infection screening is performed during antenatal booking to identify immunity status and prevent congenital rubella syndrome?',o:['Rubella IgM antibody','Rubella IgG antibody','Viral culture','PCR for rubella'],a:1},
    {q:'A woman reports LMP on 15 November 2023. What is her estimated date of delivery?',o:['22 August 2024','15 August 2024','22 September 2024','15 September 2024'],a:0},
    {q:'A 28-year-old primigravida attends antenatal booking. Which screening is recommended to detect asymptomatic bacteriuria associated with pyelonephritis and preterm birth?',o:['Urine dipstick only','Urine culture','Serum creatinine','Urine microscopy only'],a:1},
    {q:'Which booking investigation is essential to detect anemia that may affect maternal and fetal outcomes during pregnancy?',o:['Hemoglobin estimation','Serum ferritin','Vitamin B12 level','Reticulocyte count'],a:0},
    {q:'A woman with LMP on 1 July 2023 has regular cycles. What is the estimated date of delivery?',o:['8 April 2024','8 May 2024','1 April 2024','15 April 2024'],a:0},
    {q:'During antenatal booking, screening for which infection is recommended because untreated maternal infection can cause congenital cataracts, cardiac defects, and deafness?',o:['Cytomegalovirus','Toxoplasmosis','Rubella','Parvovirus B19'],a:2},
    {q:'A woman with LMP on 10 October 2023 attends clinic. What is the estimated date of delivery?',o:['17 July 2024','3 July 2024','10 July 2024','24 July 2024'],a:0},
    {q:'Which infection screening during pregnancy allows prevention of neonatal HIV infection through antiretroviral therapy and delivery planning?',o:['HIV ELISA test','Western blot only','PCR viral load','CD4 count'],a:0},
    {q:'A patient reports LMP on 25 December 2023. What is the estimated date of delivery?',o:['1 October 2024','18 September 2024','25 September 2024','2 October 2024'],a:2},
    {q:'Which infection screening during booking aims to prevent congenital syphilis by enabling early treatment with penicillin?',o:['TPHA screening','VDRL test','Dark field microscopy','Syphilis PCR'],a:1},
    {q:'A woman with LMP on 3 March 2024 presents for antenatal care. What is her estimated date of delivery?',o:['10 December 2024','3 December 2024','17 December 2024','24 December 2024'],a:0},
    {q:'Which infection screening during pregnancy is performed primarily to detect latent infection that may cause congenital anomalies if primary infection occurs during pregnancy?',o:['Toxoplasma IgG and IgM','Hepatitis C antibody','HSV culture','Epstein-Barr virus serology'],a:0},
    {q:'A woman with LMP on 8 January 2024 has regular cycles. What is the estimated date of delivery?',o:['8 October 2024','15 October 2024','1 October 2024','22 October 2024'],a:1},
    {q:'A 25-year-old primigravida attends antenatal booking. Which infection screening is recommended to detect hepatitis infection associated with risk of neonatal chronic liver disease?',o:['Hepatitis A IgM','Hepatitis B surface antigen','Hepatitis D antibody','Hepatitis E IgM'],a:1},
    {q:'During the first stage of labour, the primary physiological process responsible for cervical effacement is:',o:['Descent of the fetal head','Retraction of uterine muscle fibers','Dilatation of the lower uterine segment','Rupture of the membranes'],a:1},
    {q:'The first stage of labour ends when:',o:['Cervix is fully effaced','Cervix is dilated to 8 cm','Cervix is fully dilated','Membranes rupture'],a:2},
    {q:'A primigravida in active labour shows progressive cervical dilatation. The most important physiological force responsible for cervical dilatation is:',o:['Maternal bearing down efforts','Uterine contractions','Pelvic ligament relaxation','Fetal movements'],a:1},
    {q:'In the first stage of labour, uterine contractions originate from:',o:['Lower uterine segment','Cervical ring','Fundal pacemaker area','Broad ligament'],a:2},
    {q:'During normal labour, uterine contractions show a pattern known as polarity. This means:',o:['Cervix contracts while fundus relaxes','Upper segment contracts and retracts while lower segment relaxes','Entire uterus contracts simultaneously','Cervix dilates independently of uterine contractions'],a:1},
    {q:'In the first stage of labour, effacement usually occurs before dilatation in:',o:['Multiparous women','Primigravida','Grand multipara','Women with polyhydramnios'],a:1},
    {q:'The average duration of the first stage of labour in a primigravida is approximately:',o:['4 hours','6 hours','12 hours','18 hours'],a:2},
    {q:'The most important hormone responsible for initiation of uterine contractions during labour is:',o:['Progesterone','Estrogen','Oxytocin','Prolactin'],a:2},
    {q:'The second stage of labour begins with:',o:['Rupture of membranes','Full cervical dilatation','Engagement of fetal head','Onset of uterine contractions'],a:1},
    {q:'The major force responsible for expulsion of the fetus during the second stage of labour is:',o:['Cervical dilatation','Fetal movements','Maternal bearing down efforts','Placental separation'],a:2},
    {q:'The typical duration of the second stage of labour in a primigravida without epidural analgesia is:',o:['10-20 minutes','30 minutes','Up to 2 hours','4 hours'],a:2},
    {q:'The Ferguson reflex during labour refers to:',o:['Reflex increase in oxytocin secretion due to cervical stretching','Reflex inhibition of uterine contractions','Maternal tachycardia during contractions','Reflex fetal heart acceleration'],a:0},
    {q:'During the second stage of labour, the cardinal movement that follows engagement is:',o:['Extension','Internal rotation','Descent','Flexion'],a:3},
    {q:'The physiological mechanism that prevents uterine muscle fibers from returning to their original length after contraction is called:',o:['Relaxation','Retraction','Effacement','Involution'],a:1},
    {q:'The third stage of labour begins with:',o:['Delivery of the fetal head','Full cervical dilatation','Delivery of the baby','Onset of uterine contractions'],a:2},
    {q:'The most common mechanism of placental separation during the third stage of labour is:',o:['Matthews Duncan mechanism','Schultze mechanism','Couvelaire mechanism','Bandl mechanism'],a:1},
    {q:'In the Schultze mechanism of placental separation, the placenta separates:',o:['From the margin first','From the center first','Simultaneously from all sides','From the lower uterine segment'],a:1},
    {q:'One of the earliest clinical signs of placental separation is:',o:['Uterine contraction pain','Lengthening of the umbilical cord','Cervical dilatation','Fetal head descent'],a:1},
    {q:'During the third stage of labour, the uterus becomes:',o:['Soft and enlarged','Firm and globular','Flaccid and elongated','Displaced laterally'],a:1},
    {q:'Controlled cord traction during active management of the third stage of labour is performed primarily to:',o:['Increase uterine contractions','Prevent postpartum hemorrhage','Shorten second stage of labour','Prevent fetal distress'],a:1},
    {q:'The physiological cause of placental separation during the third stage is mainly:',o:['Cervical dilatation','Uterine contraction and retraction','Fetal movements','Maternal pushing'],a:1},
    {q:'The most reliable clinical sign of placental separation is:',o:['Uterine fundus becomes firm and globular','Sudden gush of blood','Lengthening of umbilical cord','Maternal urge to push'],a:2},
    {q:'In multiparous women, the second stage of labour usually lasts:',o:['5-10 minutes','Up to 1 hour','Up to 3 hours','Up to 5 hours'],a:1},
    {q:'The physiological process that shortens the cervix during labour is called:',o:['Dilatation','Effacement','Retraction','Engagement'],a:1},
    {q:'The hormone responsible for cervical ripening prior to labour is primarily:',o:['Oxytocin','Relaxin','Prostaglandins','Estrogen'],a:2},
    {q:'During labour, the upper uterine segment becomes progressively thicker due to:',o:['Dilatation','Retraction','Effacement','Stretching'],a:1},
    {q:'The ring formed between the upper and lower uterine segments during obstructed labour is known as:',o:['Schroeder ring','Bandl\'s ring','Ferguson ring','Hegar\'s ring'],a:1},
    {q:'The primary force responsible for fetal descent during the second stage is:',o:['Amniotic fluid pressure','Maternal bearing down efforts','Placental pressure','Umbilical cord traction'],a:1},
    {q:'During the third stage of labour, average duration in normal delivery is:',o:['5 minutes','30 minutes','60 minutes','2 hours'],a:1},
    {q:'The most important physiological mechanism preventing postpartum hemorrhage after placental delivery is:',o:['Cervical contraction','Retraction of uterine muscle fibers compressing blood vessels','Placental clot formation','Vaginal contraction'],a:1},
    {q:'Which stage of labour is most associated with maternal bearing down reflex?',o:['First stage','Second stage','Third stage','Latent phase'],a:1},
    {q:'The physiological mechanism responsible for progressive descent of the fetus during labour is mainly:',o:['Pelvic ligament relaxation','Uterine contractions and maternal pushing','Placental pressure','Fetal breathing movements'],a:1},
    {q:'During labour, the lower uterine segment becomes:',o:['Thicker and more contractile','Thinner and more distensible','Rigid and non-distensible','Shorter and thicker'],a:1},
    {q:'A sudden gush of blood during the third stage of labour most commonly indicates:',o:['Uterine rupture','Placental separation','Fetal distress','Cervical laceration'],a:1},
    {q:'The mechanism of placental separation where blood escapes early and placenta separates from edge first is:',o:['Schultze mechanism','Matthews Duncan mechanism','Brandt-Andrews mechanism','Couvelaire mechanism'],a:1},
    {q:'The contraction of uterine muscle fibers during labour is mainly mediated by increased intracellular:',o:['Sodium ions','Potassium ions','Calcium ions','Chloride ions'],a:2},
    {q:'The second stage of labour ends with:',o:['Full cervical dilatation','Delivery of placenta','Delivery of the baby','Rupture of membranes'],a:2},
    {q:'The primary physiological role of oxytocin during labour is to:',o:['Ripen the cervix','Initiate fetal descent','Stimulate uterine contractions','Cause placental separation'],a:2},
    {q:'During labour, the uterine contraction frequency typically becomes:',o:['Less frequent and weaker','More frequent and stronger','Irregular and weak','Absent in second stage'],a:1},
    {q:'The first stage of labour is subdivided into:',o:['Early and late phases','Latent and active phases','Induction and augmentation phases','Pre-labour and labour phases'],a:1},
    {q:'Which prostaglandin is most commonly used clinically for cervical ripening?',o:['PGE1 (misoprostol)','PGE2 (dinoprostone)','PGF2α','PGI2'],a:1},
    {q:'The upper uterine segment during labour is characterized by:',o:['Passive stretching','Active contraction and retraction','No muscular activity','Intermittent relaxation only'],a:1},
    {q:'During the third stage of labour, the placenta is usually delivered within:',o:['5 minutes','15 minutes','30 minutes','60 minutes'],a:2},
    {q:'Which factor primarily triggers the Ferguson reflex?',o:['Uterine fundal contraction','Placental separation','Stretching of cervix and vagina by presenting part','Maternal pain perception'],a:2},
    {q:'The physiological function of uterine retraction during labour is to:',o:['Increase amniotic fluid pressure','Shorten uterine muscle fibers permanently','Relax cervical muscles','Increase placental blood flow'],a:1},
    {q:'The force generated by uterine contractions during active labour is approximately:',o:['10-20 mmHg','30-50 mmHg','60-80 mmHg','100-120 mmHg'],a:2},
    {q:'The process by which the fetal head emerges under the pubic symphysis during delivery is called:',o:['Flexion','Extension','Internal rotation','External rotation'],a:1},
    {q:'The primary mechanism preventing placental retention after delivery is:',o:['Cervical closure','Placental contraction','Uterine contraction and retraction','Umbilical cord shortening'],a:2},
    {q:'The latent phase of the first stage of labour typically ends when cervical dilatation reaches:',o:['2 cm','4 cm','6 cm','8 cm'],a:1},
    {q:'The major physiological event marking the end of the third stage of labour is:',o:['Delivery of placenta and membranes','Closure of cervix','Cessation of uterine contractions','Initiation of lactation'],a:0},
    {q:'The physiological onset of labour is associated with a functional withdrawal of which hormone from the uterus?',o:['Progesterone','Oxytocin','Relaxin','Prolactin'],a:0},
    {q:'The pacemaker for uterine contractions during labour is usually located in the:',o:['Cervix','Lower uterine segment','Fundus near the cornua','Posterior uterine wall'],a:2},
    {q:'The most important physiological effect of uterine retraction during labour is:',o:['Relaxation of cervix','Shortening of uterine muscle fibers permanently','Decrease in uterine blood flow','Increased amniotic fluid pressure'],a:1},
    {q:'During the first stage of labour, the normal rate of cervical dilatation in primigravida during active phase is approximately:',o:['0.5 cm/hour','1 cm/hour','2 cm/hour','3 cm/hour'],a:1},
    {q:'The lower uterine segment during labour mainly functions to:',o:['Generate uterine contractions','Stretch and facilitate cervical dilatation','Compress uterine vessels','Initiate placental separation'],a:1},
    {q:'In the second stage of labour, the urge to bear down occurs primarily due to:',o:['Placental separation','Stretching of pelvic floor and vagina','Increased fetal movements','Maternal pain perception'],a:1},
    {q:'The physiological reason for increased uterine contractility near term is mainly due to increased:',o:['Progesterone receptors','Oxytocin receptors in myometrium','Placental blood flow','Fetal urine production'],a:1},
    {q:'The most important mechanical factor aiding cervical dilatation in labour is:',o:['Fetal head pressure on cervix','Amniotic fluid pressure alone','Placental pressure','Umbilical cord traction'],a:0},
    {q:'The typical duration of the third stage of labour in actively managed labour is usually:',o:['Less than 10 minutes','20-30 minutes','45 minutes','60 minutes'],a:0},
    {q:'The physiological process that causes the uterus to become globular during placental separation is:',o:['Uterine contraction and retraction','Cervical dilatation','Vaginal stretching','Placental detachment alone'],a:0},
    {q:'During labour, the fundal dominance of uterine contractions refers to:',o:['Strongest contractions occurring in the cervix','Contractions beginning at the fundus and spreading downward','Lower uterine segment contracting first','Placenta initiating contractions'],a:1},
    {q:'The mechanism that allows the fetal head to navigate the maternal pelvis by changing its shape is called:',o:['Flexion','Moulding','Engagement','Extension'],a:1},
    {q:'The cardinal movement of labour that reduces the presenting diameter of the fetal head is:',o:['Extension','Internal rotation','Flexion','External rotation'],a:2},
    {q:'The physiological increase in prostaglandins near term primarily results in:',o:['Placental growth','Cervical ripening and uterine contractions','Increased fetal movement','Decreased uterine sensitivity'],a:1},
    {q:'During labour, uterine contractions normally occur at intervals of:',o:['Every 10-15 minutes','Every 2-3 minutes in active labour','Every 20 minutes','Every 30 minutes'],a:1},
    {q:'The mechanism of placental separation associated with concealed bleeding is:',o:['Schultze mechanism','Matthews Duncan mechanism','Couvelaire mechanism','Bandl mechanism'],a:0},
    {q:'The physiological basis of the "living ligature" mechanism preventing postpartum hemorrhage is:',o:['Cervical constriction','Uterine muscle fibers compressing blood vessels','Placental clot formation','Vaginal contraction'],a:1},
    {q:'The part of uterus that undergoes the greatest retraction during labour is the:',o:['Cervix','Lower uterine segment','Upper uterine segment','Broad ligament'],a:2},
    {q:'The typical pressure generated during strong uterine contractions in labour may reach:',o:['10 mmHg','20 mmHg','50 mmHg','100 mmHg'],a:3},
    {q:'The physiological mechanism that ensures progressive descent of the fetus during labour is:',o:['Cervical effacement','Uterine retraction','Placental pressure','Maternal tachycardia'],a:1},
    {q:'The major role of relaxin during pregnancy and labour is:',o:['Stimulate uterine contractions','Relax pelvic ligaments and cervix','Increase fetal heart rate','Promote placental separation'],a:1},
    {q:'The most common presenting diameter of the fetal head in normal vertex presentation is:',o:['Occipitofrontal diameter','Suboccipitobregmatic diameter','Biparietal diameter','Mentovertical diameter'],a:1},
    {q:'During labour, the lower uterine segment forms primarily from:',o:['Body of uterus','Isthmus of uterus','Cervical canal','Broad ligament'],a:1},
    {q:'The physiological advantage of moulding of the fetal head during labour is:',o:['Prevents fetal hypoxia','Allows fetal head to adapt to pelvic dimensions','Reduces uterine contractions','Prevents placental separation'],a:1},
    {q:'The Ferguson reflex results in increased secretion of:',o:['Estrogen','Progesterone','Oxytocin','Prolactin'],a:2},
    {q:'During the second stage of labour, descent of the fetus occurs mainly due to:',o:['Placental contraction','Maternal pushing and uterine contractions','Cervical dilatation','Amniotic fluid pressure alone'],a:1},
    {q:'The most common cause of prolonged third stage of labour is:',o:['Placenta previa','Retained placenta','Fetal distress','Maternal hypotension'],a:1},
    {q:'The cardinal movement that occurs immediately before delivery of the head is:',o:['Internal rotation','Extension','Flexion','Descent'],a:1},
    {q:'The physiological hormone surge in the fetus that contributes to onset of labour is mainly:',o:['Fetal insulin','Fetal cortisol','Fetal prolactin','Fetal growth hormone'],a:1},
    {q:'The uterine segment that becomes progressively thinner during labour is the:',o:['Fundus','Upper uterine segment','Lower uterine segment','Cervical canal'],a:2},
    {q:'The most reliable physiological indicator of effective uterine contractions is:',o:['Maternal tachycardia','Progressive cervical dilatation','Increased fetal movement','Vaginal bleeding'],a:1},
    {q:'During labour, uterine contractions are coordinated by electrical signals spreading through:',o:['Pelvic nerves','Gap junctions between myometrial cells','Placental circulation','Cervical nerves'],a:1},
    {q:'The physiological benefit of amniotic fluid during labour is mainly:',o:['Prevent fetal infection','Form hydrostatic wedge aiding cervical dilatation','Increase placental perfusion','Reduce uterine contractions'],a:1},
    {q:'The fetal movement occurring after delivery of the head that aligns shoulders with pelvic outlet is:',o:['Flexion','Internal rotation','Restitution','Engagement'],a:2},
    {q:'The stage of labour most associated with risk of postpartum hemorrhage is:',o:['First stage','Second stage','Third stage','Latent phase'],a:2},
    {q:'The hormone primarily responsible for milk ejection reflex postpartum is:',o:['Oxytocin','Estrogen','Progesterone','Cortisol'],a:0},
    {q:'The most common physiological cause of failure of placental separation is:',o:['Uterine atony','Cervical stenosis','Placenta previa','Maternal anemia'],a:0},
    {q:'During the third stage of labour, controlled cord traction is performed after:',o:['Uterine relaxation','Signs of placental separation','Cervical dilatation','Fetal head engagement'],a:1},
    {q:'The uterine muscle layer responsible for powerful contractions in labour is:',o:['Perimetrium','Myometrium','Endometrium','Decidua'],a:1},
    {q:'The physiological trigger for maternal urge to push is mainly:',o:['Placental separation','Cervical stretching','Pressure of presenting part on pelvic floor','Fetal movements'],a:2},
    {q:'The most common presentation in normal labour is:',o:['Breech','Face','Vertex','Brow'],a:2},
    {q:'The physiological mechanism responsible for progressive shortening of cervix during labour is:',o:['Dilatation','Effacement','Engagement','Extension'],a:1},
    {q:'During labour, uterine blood flow temporarily decreases during:',o:['Relaxation phase','Uterine contraction','Placental separation','Cervical dilatation'],a:1},
    {q:'The physiological purpose of retraction during labour is to:',o:['Prevent uterine rupture','Maintain progress of labour by preventing backward movement','Increase placental perfusion','Prevent fetal descent'],a:1},
    {q:'The mechanism responsible for delivery of shoulders after head is called:',o:['External rotation','Flexion','Internal rotation','Engagement'],a:0},
    {q:'The primary physiological factor that increases uterine excitability near term is increased:',o:['Progesterone activity','Estrogen-to-progesterone ratio','Maternal insulin','Placental growth hormone'],a:1},
    {q:'The main function of the pelvic floor muscles during the second stage is to:',o:['Stop fetal descent','Guide rotation of fetal head','Reduce uterine contractions','Prevent cervical dilatation'],a:1},
    {q:'The final step of the third stage of labour is:',o:['Placental separation','Delivery of placenta and membranes','Uterine contraction','Cervical closure'],a:1},
    {q:'The physiological response immediately after delivery of placenta is:',o:['Uterine atony','Sustained uterine contraction','Cervical dilatation','Increased fetal heart rate'],a:1},
    {q:'The major physiological purpose of uterine contractions during labour is to:',o:['Deliver placenta first','Dilate cervix and expel fetus','Increase maternal blood pressure','Prevent fetal movements'],a:1},
    {q:'A 26-year-old primigravida at 39 weeks presents in labour. Cervix is 5 cm dilated, membranes intact, and contractions occur every 3 minutes lasting 45 seconds. Which phase of the first stage of labour is she most likely in?',o:['Latent phase','Active phase','Transitional phase','Second stage'],a:1},
    {q:'A primigravida in labour has cervical dilation of 3 cm with mild irregular contractions. Which physiological process predominates at this stage?',o:['Rapid fetal descent','Cervical effacement','Placental separation','Shoulder rotation'],a:1},
    {q:'A 30-year-old primigravida has been in labour for 10 hours. Cervical dilation progressed from 4 cm to 6 cm in 2 hours. According to expected physiology of labour, this pattern indicates:',o:['Secondary arrest of labour','Prolonged latent phase','Obstructed labour','Normal progress of labour'],a:3},
    {q:'A multiparous woman in labour suddenly feels an intense urge to push. Vaginal examination shows full cervical dilatation and fetal head at +2 station. Which physiological reflex is responsible?',o:['Hegar reflex','Ferguson reflex','Moro reflex','Valsalva reflex'],a:1},
    {q:'During labour monitoring, uterine contractions are recorded as 3 contractions every 10 minutes, each lasting 60 seconds. Which stage of labour is most consistent with this pattern?',o:['Active phase of first stage','Latent phase','Third stage','Immediate postpartum period'],a:0},
    {q:'A primigravida reaches full cervical dilatation. Despite good contractions, the fetal head remains above the pelvic inlet. Which physiological event must occur before descent?',o:['Engagement','Extension','External rotation','Placental separation'],a:0},
    {q:'During labour, flexion of the fetal head allows the smallest diameter to present. Which diameter is presented in a well-flexed vertex?',o:['Occipitofrontal','Biparietal','Suboccipitobregmatic','Mentovertical'],a:2},
    {q:'A labouring woman suddenly has a gush of blood and the umbilical cord lengthens. Which event most likely occurred?',o:['Placental separation','Uterine rupture','Cervical tear','Amniotic fluid leak'],a:0},
    {q:'After delivery of the baby, the uterus becomes firm, globular, and rises in the abdomen. What physiological event is occurring?',o:['Cervical contraction','Placental separation','Vaginal contraction','Uterine rupture'],a:1},
    {q:'A primigravida in the second stage of labour has the fetal head visible at the introitus during contractions but it disappears between contractions. This sign represents:',o:['Crowning','Engagement','Descent','Caput succedaneum'],a:2},
    {q:'Uterine contractions normally start at the fundus and spread downward toward the cervix. This pattern reflects:',o:['Pelvic floor resistance','Cervical ripening','Uterine polarity','Placental perfusion'],a:2},
    {q:'During labour, the fetal head becomes more flexed to facilitate passage through the pelvis. Which muscle tone contributes most to this movement?',o:['Pelvic floor muscles','Uterine fundal contractions','Abdominal muscles','Cervical muscles'],a:1},
    {q:'During vaginal examination, the sagittal suture lies in the transverse diameter of the pelvis at the pelvic inlet. This finding indicates:',o:['Internal rotation','Engagement','Extension','External rotation'],a:1},
    {q:'A fetus in persistent occipito-posterior position usually rotates during labour to occipito-anterior. Which movement achieves this?',o:['Flexion','Internal rotation','Extension','Restitution'],a:1},
    {q:'A primigravida experiences a prolonged second stage despite full cervical dilatation. Which force most significantly contributes to fetal expulsion at this stage?',o:['Uterine retraction alone','Placental contraction','Maternal bearing-down efforts','Cervical dilation'],a:2},
    {q:'A placenta is delivered with the fetal surface appearing first and minimal external bleeding until expulsion. Which mechanism of separation occurred?',o:['Matthews Duncan','Schultze','Couvelaire','Brandt'],a:1},
    {q:'During labour progression, uterine contractions increase in intensity. Which physiological change facilitates this?',o:['Reduced calcium influx','Increased oxytocin receptor density','Decreased prostaglandin synthesis','Reduced estrogen levels'],a:1},
    {q:'The fetal head rotates from the transverse to the anteroposterior diameter of the pelvis during labour. This movement is called:',o:['Engagement','Flexion','Internal rotation','Restitution'],a:2},
    {q:'As the fetal head passes under the pubic symphysis and the occiput emerges, which cardinal movement occurs?',o:['Flexion','Extension','Descent','Restitution'],a:1},
    {q:'After delivery of the head, it rotates to realign with the fetal shoulders. This movement is known as:',o:['Restitution','Flexion','Descent','Engagement'],a:0},
    {q:'A primigravida in labour shows arrest of cervical dilation at 8 cm despite strong contractions. Which condition is most likely responsible?',o:['Cephalopelvic disproportion','Premature rupture of membranes','Maternal dehydration','Cervical edema'],a:0},
    {q:'The hydrostatic wedge that assists cervical dilation during labour is formed primarily by:',o:['Umbilical cord','Amniotic sac','Placenta','Fetal shoulders'],a:1},
    {q:'A labouring woman develops uterine contractions occurring every minute with little relaxation between them. This abnormal pattern is termed:',o:['Hypotonic uterine dysfunction','Uterine tachysystole','Secondary uterine inertia','Precipitous labour'],a:1},
    {q:'During the second stage of labour, the fetal head becomes permanently visible without receding between contractions. This sign is called:',o:['Engagement','Crowning','Caput formation','Descent'],a:1},
    {q:'During uterine contraction, uteroplacental blood flow temporarily decreases. Which fetal adaptation helps tolerate this?',o:['Increased hemoglobin concentration','High oxygen affinity of fetal hemoglobin','Reduced fetal metabolism','Increased fetal heart rate variability'],a:1},
    {q:'A placenta separates beginning at the margin with early bleeding before expulsion. Which mechanism occurred?',o:['Schultze','Matthews Duncan','Couvelaire','Brandt'],a:1},
    {q:'A primigravida begins pushing before full cervical dilation. Which complication is most likely?',o:['Cervical edema','Placental abruption','Uterine rupture','Shoulder dystocia'],a:0},
    {q:'During the second stage of labour, pelvic floor muscles guide the fetal head anteriorly. Which cardinal movement is facilitated by this?',o:['Engagement','Flexion','Internal rotation','Descent'],a:2},
    {q:'A fetus enters the pelvic inlet with its sagittal suture in the transverse diameter. This indicates:',o:['Flexion','Engagement','Extension','Restitution'],a:1},
    {q:'Multiparous women typically experience shorter second stage of labour due to:',o:['Smaller fetus','Reduced pelvic resistance and effective expulsive efforts','Increased progesterone levels','Reduced uterine contractions'],a:1},
    {q:'During labour, intermittent fetal hypoxia occurs during contractions. Which fetal characteristic provides protection?',o:['Increased fetal hemoglobin oxygen affinity','Reduced placental circulation','Increased fetal metabolism','Umbilical vasoconstriction'],a:0},
    {q:'A primigravida with strong uterine contractions shows no cervical change. Which dysfunction is most likely?',o:['Failure of uterine polarity','Cervical ripening','Placental separation','Membrane rupture'],a:0},
    {q:'The cervix becomes thin and blends with the lower uterine segment during labour. This process is known as:',o:['Effacement','Engagement','Descent','Flexion'],a:0},
    {q:'The occiput rotates anteriorly to lie beneath the pubic symphysis before delivery. Which movement is responsible?',o:['Flexion','Internal rotation','Extension','Restitution'],a:1},
    {q:'In the third stage of labour, the uterus becomes firm and rises in the abdomen. What does this signify?',o:['Placental separation','Cervical contraction','Vaginal dilation','Uterine rupture'],a:0},
    {q:'A fetus delivers its head but shoulders fail to rotate externally. Which movement has failed?',o:['Flexion','Restitution','External rotation','Engagement'],a:2},
    {q:'During labour, myometrial cells communicate through gap junctions. The primary advantage of this is:',o:['Coordinated uterine contractions','Increased placental blood flow','Reduced uterine tone','Cervical stiffening'],a:0},
    {q:'A primigravida has second stage lasting 3 hours despite adequate contractions. Which physiological factor may contribute?',o:['Pelvic floor resistance','Placental separation','Uterine rupture','Cervical ripening'],a:0},
    {q:'During delivery, the fetal head extends around the pubic symphysis. Which structure acts as the pivot point?',o:['Sacral promontory','Pubic symphysis','Ischial spine','Coccyx'],a:1},
    {q:'Descent and rotation of the fetal head during labour are mainly driven by:',o:['Placental pressure','Pelvic ligament contraction','Uterine contractions guided by pelvic floor','Fetal breathing movements'],a:2},
    {q:'Uterine contractions increase in strength during labour due to rising intracellular levels of:',o:['Sodium','Calcium','Potassium','Chloride'],a:1},
    {q:'A pathological retraction ring appears during labour. This is usually a sign of:',o:['Normal labour','Obstructed labour','Placental separation','Uterine relaxation'],a:1},
    {q:'Retraction of uterine muscle fibers during labour mainly ensures:',o:['Progressive fetal descent without reversal','Cervical closure','Increased placental blood flow','Reduced uterine contractions'],a:0},
    {q:'Cervical softening before labour occurs mainly due to:',o:['Increased collagen cross-linking','Collagen breakdown mediated by prostaglandins','Reduced cervical vascularity','Increased progesterone'],a:1},
    {q:'After delivery of the baby, placenta fails to separate despite contractions. Which physiological mechanism has failed?',o:['Uterine retraction','Cervical dilatation','Internal rotation','Pelvic floor relaxation'],a:0},
    {q:'During labour, fetal hemoglobin assists oxygen transfer because it:',o:['Has lower oxygen affinity','Has higher oxygen affinity','Rapidly converts to adult hemoglobin','Does not bind carbon dioxide'],a:1},
    {q:'A woman receiving epidural analgesia develops prolonged second stage of labour. Which physiological factor is reduced?',o:['Uterine contractions','Maternal bearing-down reflex','Cervical ripening','Placental blood flow'],a:1},
    {q:'Moulding of the fetal skull during labour occurs due to:',o:['Overlapping cranial sutures','Fusion of cranial bones','Thickening of skull bones','Expansion of cranial bones'],a:0},
    {q:'During labour, the upper uterine segment becomes thicker while the lower segment thins. This helps:',o:['Initiate placental separation','Promote fetal descent','Prevent uterine contractions','Prevent cervical dilation'],a:1},
    {q:'After placental delivery, sustained uterine contraction primarily prevents postpartum hemorrhage by:',o:['Closing the cervix','Compressing uterine blood vessels','Increasing maternal blood pressure','Expelling retained membranes'],a:1},
    {q:'A 24-year-old primigravida at term is in labour with cervical dilatation of 9 cm and strong contractions every 2 minutes. She suddenly develops an intense urge to push. What is the most appropriate explanation for this physiological event?',o:['Increased progesterone secretion','Sudden placental separation','Stretching of cervix and vagina triggering oxytocin release','Decreased uterine blood flow'],a:2},
    {q:'During the second stage of labour, the fetal head descends and rotates so that the occiput lies beneath the pubic symphysis. Which anatomical structure primarily guides this rotation?',o:['Sacral promontory','Uterine fundus','Amniotic sac','Pelvic floor muscles'],a:3},
    {q:'A primigravida has been in labour for several hours. Despite adequate contractions, the fetal head fails to descend and the sagittal suture remains in the transverse diameter at the level of the ischial spines. Which physiological step has not yet occurred?',o:['Flexion','Engagement','Internal rotation','Extension'],a:2},
    {q:'A woman delivers the baby, and within a few minutes there is a sudden gush of blood with lengthening of the umbilical cord. The uterus becomes firm and rises in the abdomen. Which physiological mechanism explains this finding?',o:['Cervical closure','Vaginal muscle contraction','Separation of placenta from uterine wall','Rupture of fetal membranes'],a:2},
    {q:'During labour, uterine contractions progressively increase in strength and coordination due to formation of numerous gap junctions between myometrial cells. Which physiological advantage does this provide?',o:['Decreased uterine tone','Increased placental perfusion','Coordinated propagation of uterine contractions','Inhibition of oxytocin release'],a:2},
    {q:'A fetus in vertex presentation descends through the pelvis and the head emerges under the pubic symphysis. The face then sweeps over the perineum. Which cardinal movement is occurring at this moment?',o:['Engagement','Internal rotation','Descent','Extension'],a:3},
    {q:'After delivery of the fetal head, the head rotates to one side to align with the shoulders still inside the birth canal. This movement is known as:',o:['Flexion','Engagement','Restitution','Descent'],a:2},
    {q:'A primigravida reaches the second stage of labour. During examination, the fetal head is visible at the vulva even when contractions cease. What physiological stage of delivery does this represent?',o:['Engagement','Descent','Internal rotation','Crowning'],a:3},
    {q:'During the third stage of labour, uterine muscle fibers shorten permanently and compress blood vessels supplying the placental bed. What is this physiological mechanism called?',o:['Relaxation','Dilatation','Retraction','Effacement'],a:2},
    {q:'A labouring woman has effective uterine contractions but poor progress of cervical dilation. Investigation shows inadequate cervical softening due to reduced prostaglandin activity. Which physiological process is primarily impaired?',o:['Uterine polarity','Placental separation','Fetal descent','Cervical ripening'],a:3},
    {q:'A 26-year-old woman on the third postpartum day notices reduction in uterine size and firmness on abdominal examination. Which physiological process is primarily responsible for this change?',o:['Uterine involution due to autolysis of myometrial fibers','Cervical dilatation','Increased placental hormones','Pelvic ligament contraction'],a:0},
    {q:'Immediately after delivery, the uterine fundus is normally palpable at which anatomical level?',o:['At the level of the umbilicus','Two fingerbreadths above the umbilicus','Midway between symphysis pubis and umbilicus','At the level of the xiphisternum'],a:0},
    {q:'A woman on the fifth postpartum day has vaginal discharge that is pinkish-brown. What type of lochia is this?',o:['Lochia rubra','Lochia serosa','Lochia alba','Lochia purulenta'],a:1},
    {q:'During the puerperium, the uterus gradually returns to its nonpregnant size. Approximately how long does complete uterine involution usually take?',o:['1 week','2 weeks','6 weeks','12 weeks'],a:2},
    {q:'A postpartum woman begins breastfeeding within one hour of delivery. Which hormone is primarily responsible for milk ejection during suckling?',o:['Prolactin','Estrogen','Progesterone','Oxytocin'],a:3},
    {q:'On the first postpartum day, the uterus is firm and located one fingerbreadth below the umbilicus. This finding indicates:',o:['Uterine atony','Normal involution','Retained placenta','Subinvolution'],a:1},
    {q:'During puerperium, the endometrial lining regenerates after placental separation. Which layer primarily regenerates the endometrium?',o:['Decidua basalis','Decidua capsularis','Basal layer of endometrium','Chorionic villi'],a:2},
    {q:'The initial postpartum vaginal discharge composed mainly of blood and decidual debris is called:',o:['Lochia rubra','Lochia serosa','Lochia alba','Lochia mucosa'],a:0},
    {q:'A breastfeeding mother experiences uterine cramps during nursing in the early puerperium. This is primarily due to release of:',o:['Estrogen','Oxytocin','Prolactin','Progesterone'],a:1},
    {q:'A postpartum woman complains of excessive lochia lasting beyond two weeks. Which physiological abnormality is most likely responsible?',o:['Cervical incompetence','Uterine subinvolution','Placental calcification','Increased prolactin'],a:1},
    {q:'The cervix after delivery gradually regains tone but usually remains slightly open. Which characteristic is typical of a parous cervix?',o:['Circular external os','Slit-shaped external os','Completely closed os','Funnel-shaped os'],a:1},
    {q:'Which physiological process contributes most to reduction in uterine size during puerperium?',o:['Hyperplasia of muscle fibers','Autolysis of myometrial cells','Increased placental hormones','Cervical shortening'],a:1},
    {q:'The uterine fundus typically descends by approximately how much per day during puerperium?',o:['0.5 cm/day','1 cm/day','2 cm/day','3 cm/day'],a:1},
    {q:'A postpartum woman develops milk secretion 3 days after delivery. Which hormonal change triggers lactogenesis?',o:['Sudden fall in progesterone','Increase in estrogen','Decrease in prolactin','Increase in cortisol'],a:0},
    {q:'During puerperium, thrombosis risk increases due to physiological hypercoagulability. Which factor contributes most?',o:['Reduced fibrinogen levels','Increased clotting factors','Reduced platelet aggregation','Increased fibrinolysis'],a:1},
    {q:'Lochia alba typically appears around which postpartum period?',o:['Days 1-3','Days 4-10','After day 10','After 6 weeks'],a:2},
    {q:'A postpartum woman complains of urinary retention after vaginal delivery. Which physiological factor most commonly contributes to this?',o:['Decreased bladder capacity','Perineal edema and pain','Increased estrogen levels','Urethral shortening'],a:1},
    {q:'During puerperium, ovarian activity usually resumes earliest in which group?',o:['Breastfeeding mothers','Non-breastfeeding mothers','Women with cesarean delivery','Women with anemia'],a:1},
    {q:'The hormone primarily responsible for milk production in the postpartum period is:',o:['Prolactin','Oxytocin','Estrogen','Progesterone'],a:0},
    {q:'Which physiological event prevents excessive bleeding from placental site during puerperium?',o:['Cervical contraction','Myometrial contraction and retraction','Vaginal muscle contraction','Pelvic ligament shortening'],a:1},
    {q:'The placental site typically heals completely by:',o:['1 week','2 weeks','6 weeks','12 weeks'],a:2},
    {q:'During the puerperium, which hormone level remains elevated in breastfeeding women?',o:['Progesterone','Estrogen','Prolactin','Relaxin'],a:2},
    {q:'A postpartum woman complains of excessive sweating during the first few days. What physiological change explains this?',o:['Fluid mobilization from extracellular space','Increased estrogen secretion','Reduced metabolism','Placental hormone release'],a:0},
    {q:'During puerperium, the uterine weight decreases from approximately 1000 g after delivery to about:',o:['50 g','100 g','200 g','500 g'],a:1},
    {q:'The first postpartum ovulation in non-lactating women usually occurs around:',o:['2 weeks','4 weeks','6 weeks','12 weeks'],a:2},
    {q:'Lochia serosa mainly contains:',o:['Fresh blood and clots','Leukocytes and mucus','Serous fluid and leukocytes','Pure mucus'],a:2},
    {q:'Which physiological change occurs in the cardiovascular system during early puerperium?',o:['Decreased cardiac output','Increased blood volume','Mobilization of extravascular fluid','Decreased stroke volume'],a:2},
    {q:'A postpartum woman notices milk secretion from breasts triggered by infant crying. This is due to release of:',o:['Estrogen','Oxytocin','Prolactin','Cortisol'],a:1},
    {q:'The external cervical os typically closes by approximately:',o:['End of first week','End of second week','End of third week','End of sixth week'],a:1},
    {q:'The process of breakdown of enlarged uterine muscle cells after delivery is known as:',o:['Hypertrophy','Hyperplasia','Autolysis','Metaplasia'],a:2},
    {q:'During puerperium, pelvic floor muscles gradually regain tone. Which exercise is commonly recommended to strengthen them?',o:['Valsalva maneuver','Kegel exercises','Abdominal crunches','Squatting'],a:1},
    {q:'The decidua remaining after delivery is gradually shed in the form of:',o:['Placental fragments','Lochial discharge','Cervical mucus','Endometrial polyps'],a:1},
    {q:'Which hormone inhibits ovulation during lactation?',o:['Estrogen','Progesterone','Prolactin','Oxytocin'],a:2},
    {q:'The typical duration of lochia rubra is approximately:',o:['1-3 days','4-10 days','10-14 days','3 weeks'],a:0},
    {q:'A postpartum woman complains of afterpains while breastfeeding. These are caused by:',o:['Estrogen release','Oxytocin-induced uterine contractions','Progesterone withdrawal','Prolactin deficiency'],a:1},
    {q:'The most important mechanism preventing postpartum hemorrhage during puerperium is:',o:['Cervical contraction','Uterine retraction','Vaginal muscle tone','Platelet activation'],a:1},
    {q:'During puerperium, which metabolic change commonly occurs?',o:['Increased insulin resistance','Increased diuresis','Decreased metabolism','Reduced renal filtration'],a:1},
    {q:'A postpartum woman develops breast engorgement on day 3. Which physiological event causes this?',o:['Increase in progesterone','Increased milk secretion and vascular congestion','Reduced prolactin','Decreased blood supply'],a:1},
    {q:'The uterine cavity becomes lined with new endometrium usually by:',o:['5 days','10 days','3 weeks','6 weeks'],a:2},
    {q:'Which physiological change contributes to constipation in early puerperium?',o:['Increased intestinal motility','Decreased progesterone levels','Reduced abdominal tone and pain','Increased estrogen levels'],a:2},
    {q:'The fallopian tubes return to their nonpregnant size approximately by:',o:['1 week','2 weeks','6 weeks','3 months'],a:1},
    {q:'During lactation, which hormone primarily stimulates milk synthesis?',o:['Oxytocin','Prolactin','Estrogen','Progesterone'],a:1},
    {q:'The physiological reason for postpartum bradycardia in some women is:',o:['Reduced blood volume','Increased vagal tone','Decreased cardiac output','Placental hormone release'],a:1},
    {q:'Which physiological change in breasts occurs during early puerperium?',o:['Decreased vascularity','Increased glandular activity','Reduced ductal growth','Fat replacement'],a:1},
    {q:'The most common time for onset of lactogenesis stage II (copious milk secretion) is:',o:['Within 12 hours postpartum','24 hours postpartum','48-72 hours postpartum','After one week'],a:2},
    {q:'During puerperium, the uterine arteries undergo which physiological change?',o:['Complete thrombosis and fibrosis','Immediate disappearance','Progressive narrowing and obliteration','Increased dilation'],a:2},
    {q:'A postpartum woman experiences night sweats during the first week after delivery. This occurs due to:',o:['Estrogen surge','Fluid mobilization and hormonal changes','Increased prolactin','Placental hormone secretion'],a:1},
    {q:'Which physiological factor primarily delays ovulation during exclusive breastfeeding?',o:['Elevated estrogen','High prolactin levels suppressing GnRH','Increased progesterone','Reduced oxytocin'],a:1},
    {q:'During puerperium, the uterus becomes a pelvic organ again approximately by:',o:['1 week','2 weeks','3 weeks','6 weeks'],a:1},
    {q:'The average weight of the uterus immediately after delivery is approximately:',o:['200 g','500 g','1000 g','1500 g'],a:2},
    {q:'The placental implantation site is usually completely healed by:',o:['2 weeks','3 weeks','6 weeks','10 weeks'],a:2},
    {q:'Which physiological event occurs in the cervix during puerperium?',o:['Immediate closure','Gradual shortening and thickening','Permanent dilation','Increased glandular secretion'],a:1},
    {q:'The major physiological stimulus for continued prolactin secretion postpartum is:',o:['Infant suckling','Maternal stress','Increased estrogen','Placental hormones'],a:0},
    {q:'During puerperium, the pelvic ligaments gradually:',o:['Shorten immediately','Regain tone slowly','Undergo fibrosis','Become permanently lax'],a:1},
    {q:'Which metabolic change contributes to postpartum weight loss during the first week?',o:['Increased diuresis and diaphoresis','Reduced metabolism','Increased insulin resistance','Increased appetite'],a:0},
    {q:'The vaginal epithelium during early puerperium becomes:',o:['Thickened due to estrogen','Atrophic due to low estrogen','Hyperplastic','Keratinized'],a:1},
    {q:'Which physiological mechanism contributes to closure of uterine blood vessels after delivery?',o:['Platelet aggregation only','Myometrial contraction compressing vessels','Cervical closure','Vaginal contraction'],a:1},
    {q:'During puerperium, the uterine fundus is no longer palpable abdominally usually by:',o:['5 days','10 days','2 weeks','4 weeks'],a:1},
    {q:'The main physiological cause of breast engorgement during puerperium is:',o:['Reduced milk production','Increased milk production and vascular congestion','Decreased prolactin','Reduced blood flow'],a:1},
    {q:'During puerperium, ovulation in exclusively breastfeeding women is most commonly suppressed due to:',o:['High estrogen levels','Elevated prolactin inhibiting GnRH secretion','Increased progesterone','Increased oxytocin'],a:1},
    {q:'Cardiotocography (CTG) primarily assesses:',o:['Maternal uterine anatomy','Fetal heart rate and uterine contractions','Amniotic fluid volume','Placental blood flow'],a:1},
    {q:'The normal baseline fetal heart rate on CTG is:',o:['90-110 bpm','100-120 bpm','110-160 bpm','160-180 bpm'],a:2},
    {q:'Baseline fetal tachycardia is defined as fetal heart rate greater than:',o:['140 bpm','150 bpm','160 bpm','180 bpm'],a:2},
    {q:'Baseline fetal bradycardia is defined as fetal heart rate less than:',o:['120 bpm','110 bpm','100 bpm','90 bpm'],a:1},
    {q:'Baseline variability in CTG represents:',o:['Maternal heart rate changes','Uterine contraction intensity','Fluctuations in fetal heart rate baseline','Fetal breathing movements'],a:2},
    {q:'Normal baseline variability on CTG is:',o:['1-5 bpm','5-25 bpm','30-40 bpm','>40 bpm'],a:1},
    {q:'Reduced baseline variability may indicate:',o:['Fetal sleep','Fetal hypoxia','Maternal sedation','All of the above'],a:3},
    {q:'Accelerations in CTG are defined as:',o:['Temporary increases in fetal heart rate','Decreases in fetal heart rate','Absence of variability','Persistent tachycardia'],a:0},
    {q:'The presence of accelerations on CTG usually indicates:',o:['Fetal distress','Fetal well-being','Placental insufficiency','Cord compression'],a:1},
    {q:'Early decelerations in CTG are most commonly caused by:',o:['Placental insufficiency','Umbilical cord compression','Fetal head compression','Uterine rupture'],a:2},
    {q:'Variable decelerations are most commonly associated with:',o:['Cord compression','Maternal hypertension','Placental abruption','Fetal anemia'],a:0},
    {q:'Late decelerations are typically associated with:',o:['Cord compression','Placental insufficiency','Fetal movement','Head compression'],a:1},
    {q:'Recurrent late decelerations on CTG suggest:',o:['Normal fetal response','Uterine rupture','Fetal hypoxia','Fetal arrhythmia'],a:2},
    {q:'A sinusoidal pattern on CTG is most strongly associated with:',o:['Fetal anemia','Maternal hypotension','Placental abruption','Fetal sleep cycle'],a:0},
    {q:'Which investigation is commonly used along with CTG to assess fetal well-being?',o:['Biophysical profile','CT scan','Chest X-ray','Liver function test'],a:0},
    {q:'A reactive CTG trace typically shows:',o:['No accelerations','Persistent tachycardia','Two or more accelerations within 20 minutes','Absent variability'],a:2},
    {q:'Non-reactive CTG suggests:',o:['Normal fetal status','Possible fetal compromise','Fetal macrosomia','Maternal infection'],a:1},
    {q:'Which parameter is NOT part of CTG interpretation?',o:['Baseline heart rate','Variability','Accelerations','Amniotic fluid index'],a:3},
    {q:'CTG monitoring is most useful in:',o:['High-risk pregnancies','Normal pregnancies only','Postnatal period','Neonatal care'],a:0},
    {q:'The most common cause of variable decelerations during labor is:',o:['Placental insufficiency','Umbilical cord compression','Maternal fever','Fetal anemia'],a:1},
    {q:'Persistent fetal tachycardia on CTG may be caused by:',o:['Maternal fever','Fetal infection','Maternal dehydration','All of the above'],a:3},
    {q:'CTG monitoring during labor primarily aims to detect:',o:['Maternal hypertension','Fetal hypoxia','Maternal anemia','Placental position'],a:1},
    {q:'Which feature indicates a reassuring CTG trace?',o:['Absent variability','Late decelerations','Moderate variability','Sinusoidal pattern'],a:2},
    {q:'A prolonged deceleration in CTG is defined as a drop in fetal heart rate lasting:',o:['Less than 30 seconds','Less than 1 minute','More than 2 minutes','More than 10 minutes'],a:2},
    {q:'Continuous CTG monitoring is recommended in:',o:['Low-risk labor','High-risk labor','Postpartum period','Neonatal care'],a:1},
    {q:'A CTG showing recurrent late decelerations with reduced variability suggests:',o:['Normal labor pattern','Fetal hypoxia and acidosis','Fetal sleep cycle','Maternal dehydration'],a:1},
    {q:'The sinusoidal CTG pattern is characterized by:',o:['Smooth wave-like oscillations of fetal heart rate','Random accelerations','Rapid tachycardia','Irregular baseline variability'],a:0},
    {q:'CTG trace showing normal baseline, normal variability, and accelerations without decelerations is classified as:',o:['Pathological','Suspicious','Normal','Abnormal'],a:2},
    {q:'Which intervention is most appropriate when CTG shows persistent late decelerations?',o:['Immediate delivery if unresolved','Continue routine monitoring only','Ignore CTG findings','Delay labor'],a:0},
    {q:'Fetal scalp blood sampling during labor is used to assess:',o:['Maternal oxygenation','Fetal acid-base status','Amniotic fluid composition','Placental hormones'],a:1}
  ];
})();