window.MM=window.MM||{};
window.MM.med_p2_pulmo=[
{"t":"Pulmonology","q":"A patient with pulmonary tuberculosis remains sputum smear positive after 5 months of compliant first-line therapy. What is the most likely diagnosis?","a":"Treatment failure","b":"Relapse","c":"Reinfection","d":"Latent TB","ans":"A"},
{"t":"Pulmonology","q":"Which test rapidly detects rifampicin resistance in tuberculosis?","a":"Mantoux test","b":"GeneXpert MTB/RIF","c":"Ziehl-Neelsen stain","d":"Chest X-ray","ans":"B"},
{"t":"Pulmonology","q":"The most important drug defining MDR-TB is resistance to which combination?","a":"Isoniazid and rifampicin","b":"Ethambutol and pyrazinamide","c":"Streptomycin and ethambutol","d":"Rifampicin and pyrazinamide","ans":"A"},
{"t":"Pulmonology","q":"Which first-line anti-TB drug causes red-orange discoloration of body fluids?","a":"Isoniazid","b":"Ethambutol","c":"Rifampicin","d":"Pyrazinamide","ans":"C"},
{"t":"Pulmonology","q":"Peripheral neuropathy due to isoniazid therapy is prevented by giving:","a":"Vitamin C","b":"Vitamin B6","c":"Vitamin B12","d":"Folic acid","ans":"B"},
{"t":"Pulmonology","q":"Optic neuritis with loss of red-green color vision is caused by:","a":"Rifampicin","b":"Ethambutol","c":"Pyrazinamide","d":"Streptomycin","ans":"B"},
{"t":"Pulmonology","q":"Hyperuricemia is a common side effect of which anti-tuberculous drug?","a":"Pyrazinamide","b":"Isoniazid","c":"Rifampicin","d":"Ethambutol","ans":"A"},
{"t":"Pulmonology","q":"The most common serious complication of anti-TB therapy is:","a":"Nephrotoxicity","b":"Hepatotoxicity","c":"Ototoxicity","d":"Neurotoxicity","ans":"B"},
{"t":"Pulmonology","q":"Which investigation confirms drug susceptibility in tuberculosis?","a":"AFB smear","b":"Culture and sensitivity","c":"Chest X-ray","d":"ESR","ans":"B"},
{"t":"Pulmonology","q":"Which anti-TB drug interacts with oral contraceptive pills causing failure?","a":"Rifampicin","b":"Ethambutol","c":"Pyrazinamide","d":"Isoniazid","ans":"A"},
{"t":"Pulmonology","q":"A patient develops jaundice during intensive phase ATT. Which drug should be stopped first?","a":"Ethambutol","b":"Streptomycin","c":"Rifampicin","d":"Isoniazid","ans":"D"},
{"t":"Pulmonology","q":"Resistance detected to rifampicin alone on GeneXpert should be treated as:","a":"Mono-resistant TB","b":"MDR-TB","c":"XDR-TB","d":"Latent TB","ans":"B"},
{"t":"Pulmonology","q":"The gold standard for diagnosis of MDR-TB is:","a":"CBNAAT","b":"Line probe assay","c":"Liquid culture drug susceptibility testing","d":"Mantoux test","ans":"C"},
{"t":"Pulmonology","q":"Which drug causes hearing loss in TB treatment?","a":"Streptomycin","b":"Ethambutol","c":"Rifampicin","d":"Isoniazid","ans":"A"},
{"t":"Pulmonology","q":"Pyridoxine supplementation is particularly important in TB patients with:","a":"Diabetes","b":"Pregnancy","c":"Renal failure","d":"Hypertension","ans":"B"},
{"t":"Pulmonology","q":"The most common complication of pulmonary tuberculosis is:","a":"Pneumothorax","b":"Hemoptysis","c":"Pleural effusion","d":"Bronchiectasis","ans":"B"},
{"t":"Pulmonology","q":"Which drug interaction increases phenytoin toxicity?","a":"Rifampicin","b":"Isoniazid","c":"Ethambutol","d":"Pyrazinamide","ans":"B"},
{"t":"Pulmonology","q":"A patient on ATT develops acute visual blurring. Next step:","a":"Continue therapy","b":"Stop ethambutol","c":"Stop rifampicin","d":"Give steroids","ans":"B"},
{"t":"Pulmonology","q":"The earliest bacteriological indicator of treatment response in TB is:","a":"Weight gain","b":"Sputum smear conversion","c":"ESR normalization","d":"Symptom relief","ans":"B"},
{"t":"Pulmonology","q":"Which drug reduces effectiveness of warfarin?","a":"Isoniazid","b":"Rifampicin","c":"Ethambutol","d":"Pyrazinamide","ans":"B"},
{"t":"Pulmonology","q":"A patient with MDR-TB is resistant to fluoroquinolone as well. This is classified as:","a":"Mono-resistant TB","b":"Poly-resistant TB","c":"Pre-XDR TB","d":"Latent TB","ans":"C"},
{"t":"Pulmonology","q":"Which test detects both isoniazid and rifampicin resistance mutations?","a":"Mantoux","b":"Line probe assay","c":"Chest CT","d":"ELISA","ans":"B"},
{"t":"Pulmonology","q":"The most common site of extrapulmonary TB is:","a":"Lymph nodes","b":"Spine","c":"Pleura","d":"Abdomen","ans":"A"},
{"t":"Pulmonology","q":"Paradoxical worsening after starting ATT in HIV patients is due to:","a":"Drug resistance","b":"Treatment failure","c":"Immune reconstitution inflammatory syndrome","d":"Superinfection","ans":"C"},
{"t":"Pulmonology","q":"Which anti-TB drug causes lupus-like syndrome?","a":"Isoniazid","b":"Rifampicin","c":"Ethambutol","d":"Pyrazinamide","ans":"A"},
{"t":"Pulmonology","q":"The main mechanism of rifampicin resistance is mutation in:","a":"katG gene","b":"rpoB gene","c":"inhA gene","d":"gyrA gene","ans":"B"},
{"t":"Pulmonology","q":"A TB patient on ART develops severe hepatitis. Most hepatotoxic drug combination:","a":"HRZE","b":"HRE","c":"HE","d":"RE","ans":"A"},
{"t":"Pulmonology","q":"Which drug must never be added alone to a failing TB regimen?","a":"Ethambutol","b":"Any single drug","c":"Pyrazinamide","d":"Streptomycin","ans":"B"},
{"t":"Pulmonology","q":"Cold abscess formation in spine TB is due to:","a":"Acute inflammation","b":"Caseous necrosis","c":"Fibrosis","d":"Vascular thrombosis","ans":"B"},
{"t":"Pulmonology","q":"Most important predictor of TB transmission risk:","a":"Fever","b":"Cavitary disease with smear positivity","c":"Weight loss","d":"ESR level","ans":"B"},
{"t":"Pulmonology","q":"A patient on ATT develops platelets 20,000/mm³ with purpura. Responsible drug:","a":"Rifampicin","b":"Ethambutol","c":"Isoniazid","d":"Pyrazinamide","ans":"A"},
{"t":"Pulmonology","q":"Persistent positive culture after adequate MDR regimen suggests:","a":"Treatment success","b":"XDR-TB","c":"Relapse","d":"Non-adherence only","ans":"B"},
{"t":"Pulmonology","q":"In renal failure, which anti-TB drug dose adjustment is required most?","a":"Rifampicin","b":"Isoniazid","c":"Ethambutol","d":"Pyrazinamide","ans":"C"},
{"t":"Pulmonology","q":"Best indicator of treatment failure in MDR-TB:","a":"Persistent symptoms","b":"Persistent positive culture","c":"Weight loss","d":"ESR elevation","ans":"B"},
{"t":"Pulmonology","q":"Which anti-TB drug causes severe flu-like syndrome on intermittent therapy?","a":"Rifampicin","b":"Isoniazid","c":"Ethambutol","d":"Pyrazinamide","ans":"A"},
{"t":"Pulmonology","q":"A patient with TB meningitis — most important adjunctive therapy:","a":"Anticoagulation","b":"Steroids","c":"Diuretics","d":"Oxygen","ans":"B"},
{"t":"Pulmonology","q":"Major mechanism of isoniazid resistance:","a":"rpoB mutation","b":"katG mutation","c":"gyrA mutation","d":"pncA mutation","ans":"B"},
{"t":"Pulmonology","q":"Drug causing severe arthralgia during ATT:","a":"Pyrazinamide","b":"Ethambutol","c":"Rifampicin","d":"Isoniazid","ans":"A"},
{"t":"Pulmonology","q":"Most common cause of massive hemoptysis in old treated TB:","a":"Bronchitis","b":"Rasmussen aneurysm","c":"Pulmonary embolism","d":"Lung cancer","ans":"B"},
{"t":"Pulmonology","q":"ATT induced hepatitis — safest drug to restart first after recovery:","a":"Rifampicin","b":"Isoniazid","c":"Pyrazinamide","d":"All together","ans":"A"},
{"t":"Pulmonology","q":"A patient on MDR-TB regimen develops psychosis. Likely drug:","a":"Cycloserine","b":"Linezolid","c":"Levofloxacin","d":"Clofazimine","ans":"A"},
{"t":"Pulmonology","q":"The hallmark radiological feature suggesting active pulmonary TB:","a":"Lower lobe consolidation","b":"Upper lobe cavitation","c":"Pleural plaque","d":"Ground glass opacity","ans":"B"},
{"t":"Pulmonology","q":"Primary mechanism of pyrazinamide resistance mutation:","a":"pncA gene","b":"katG gene","c":"rpoB gene","d":"gyrA gene","ans":"A"},
{"t":"Pulmonology","q":"TB patient on ART — rifampicin preferred substitute when contraindicated:","a":"Rifabutin","b":"Ethambutol","c":"Amikacin","d":"Cycloserine","ans":"A"},
{"t":"Pulmonology","q":"Most sensitive specimen for diagnosis of TB meningitis:","a":"CSF smear","b":"CSF culture","c":"CSF GeneXpert","d":"CSF protein","ans":"C"},
{"t":"Pulmonology","q":"Cause of sudden respiratory distress during TB treatment due to rupture cavity:","a":"Pleural effusion","b":"Pneumothorax","c":"ARDS","d":"Atelectasis","ans":"B"},
{"t":"Pulmonology","q":"In MDR-TB, duration of therapy is approximately:","a":"6 months","b":"9–12 months","c":"18–24 months","d":"3 months","ans":"C"},
{"t":"Pulmonology","q":"Which complication suggests hematogenous dissemination of TB?","a":"Miliary mottling","b":"Lobar consolidation","c":"Bronchiectasis","d":"Empyema","ans":"A"},
{"t":"Pulmonology","q":"Linezolid toxicity most characteristic finding:","a":"Optic neuropathy","b":"Myelosuppression","c":"Hyperglycemia","d":"Nephrolithiasis","ans":"B"},
{"t":"Pulmonology","q":"Failure of TB patient to improve despite negative smear — most likely explanation:","a":"Drug toxicity","b":"Post-TB bronchiectasis","c":"Active MDR disease excluded","d":"Always relapse","ans":"B"},
{"t":"Pulmonology","q":"A known asthmatic presents with severe breathlessness, unable to complete sentences, RR 34/min, SpO₂ 88%. Initial management?","a":"Oral steroids only","b":"Antibiotics","c":"High-flow oxygen + nebulized salbutamol","d":"Cough suppressant","ans":"C"},
{"t":"Pulmonology","q":"A patient with acute asthma has PEFR 40% predicted. Severity classification?","a":"Mild","b":"Severe","c":"Moderate","d":"Life-threatening","ans":"B"},
{"t":"Pulmonology","q":"A silent chest in acute asthma indicates?","a":"Recovery phase","b":"Mild disease","c":"Bronchitis","d":"Life-threatening asthma","ans":"D"},
{"t":"Pulmonology","q":"A patient not responding to initial nebulized SABA — next drug?","a":"Montelukast","b":"Oral antihistamine","c":"Ipratropium bromide nebulization","d":"Theophylline tablet","ans":"C"},
{"t":"Pulmonology","q":"Best systemic steroid in acute severe asthma in ER?","a":"Inhaled budesonide only","b":"IV hydrocortisone","c":"Oral prednisolone","d":"Dexamethasone nasal spray","ans":"B"},
{"t":"Pulmonology","q":"A patient with acute asthma has PaCO₂ rising to normal level. Interpretation?","a":"Improvement","b":"Hyperventilation","c":"Respiratory fatigue","d":"Anxiety","ans":"C"},
{"t":"Pulmonology","q":"Child with severe asthma not responding to nebulization — next step?","a":"Oral antibiotics","b":"Steam inhalation","c":"IV magnesium sulfate","d":"Cough syrup","ans":"C"},
{"t":"Pulmonology","q":"Most important target oxygen saturation in acute asthma?","a":"85–88%","b":"88–92%","c":"100%","d":"94–98%","ans":"D"},
{"t":"Pulmonology","q":"Patient develops drowsiness in status asthmaticus. Meaning?","a":"Drug reaction","b":"CO₂ retention","c":"Hypoglycemia","d":"Improvement","ans":"B"},
{"t":"Pulmonology","q":"Indication for intubation in asthma?","a":"Wheeze","b":"Tachycardia","c":"Altered consciousness","d":"Mild hypoxia","ans":"C"},
{"t":"Pulmonology","q":"A severe asthmatic has PEFR 25% and exhaustion despite treatment. Next step?","a":"Discharge home","b":"Oral montelukast","c":"Intubation and ventilation","d":"Antibiotics","ans":"C"},
{"t":"Pulmonology","q":"Continuous nebulization drug of choice in status asthmaticus?","a":"Ipratropium alone","b":"Budesonide","c":"Salbutamol","d":"Theophylline","ans":"C"},
{"t":"Pulmonology","q":"Which ABG finding suggests impending respiratory failure?","a":"Low PaCO₂","b":"High PaO₂","c":"Normal PaCO₂","d":"Rising PaCO₂","ans":"D"},
{"t":"Pulmonology","q":"Best monitoring parameter in acute asthma in ER?","a":"Chest X-ray","b":"PEFR","c":"Hemoglobin","d":"ESR","ans":"B"},
{"t":"Pulmonology","q":"A patient improves after bronchodilator but relapses within 1 hour. Cause?","a":"Infection","b":"Short-acting drug duration","c":"Allergy cured","d":"Wrong diagnosis","ans":"B"},
{"t":"Pulmonology","q":"Drug avoided due to respiratory depression in status asthmaticus?","a":"Salbutamol","b":"Steroids","c":"Morphine","d":"Oxygen","ans":"C"},
{"t":"Pulmonology","q":"Best route of bronchodilator in severe acute asthma?","a":"Oral","b":"Intramuscular","c":"Nebulized","d":"Subcutaneous","ans":"C"},
{"t":"Pulmonology","q":"Which drug reduces hospitalization in acute asthma?","a":"Antibiotics","b":"Early systemic steroids","c":"Antihistamines","d":"Cough suppressants","ans":"B"},
{"t":"Pulmonology","q":"Patient with life-threatening asthma — auscultation finding?","a":"Loud wheeze","b":"Silent chest","c":"Crackles","d":"Pleural rub","ans":"B"},
{"t":"Pulmonology","q":"Best positioning for acute asthma patient?","a":"Supine","b":"Lateral","c":"Trendelenburg","d":"Sitting upright","ans":"D"},
{"t":"Pulmonology","q":"Pregnant woman in status asthmaticus — safest bronchodilator?","a":"Adrenaline IV","b":"Salbutamol","c":"Morphine","d":"Theophylline infusion","ans":"B"},
{"t":"Pulmonology","q":"Patient with acute asthma and potassium 2.8 mmol/L. Cause?","a":"Steroids","b":"Hypoxia","c":"Infection","d":"Salbutamol therapy","ans":"D"},
{"t":"Pulmonology","q":"A patient suddenly deteriorates after improvement — unilateral absent breath sounds. Diagnosis?","a":"Pneumonia","b":"Pulmonary edema","c":"Pneumothorax","d":"Bronchitis","ans":"C"},
{"t":"Pulmonology","q":"Which drug is second-line bronchodilator IV in refractory asthma?","a":"Cetirizine","b":"Aminophylline","c":"Montelukast","d":"Codeine","ans":"B"},
{"t":"Pulmonology","q":"Asthma patient exhausted, RR falling from 40 to 18/min. Meaning?","a":"Recovery","b":"Treatment working","c":"Respiratory arrest impending","d":"Anxiety relieved","ans":"C"},
{"t":"Pulmonology","q":"Which medication decreases airway inflammation in acute attack?","a":"SABA","b":"Steroids","c":"Anticholinergic","d":"Oxygen","ans":"B"},
{"t":"Pulmonology","q":"First investigation after stabilization in severe asthma attack?","a":"Spirometry","b":"CT chest","c":"ABG","d":"Bronchoscopy","ans":"C"},
{"t":"Pulmonology","q":"Life-threatening asthma PEFR value?","a":">75%","b":"50–75%","c":"40–50%","d":"<33%","ans":"D"},
{"t":"Pulmonology","q":"Most common trigger of status asthmaticus?","a":"TB","b":"Viral infection","c":"Hypertension","d":"Diabetes","ans":"B"},
{"t":"Pulmonology","q":"Patient repeatedly using SABA every 15 min at home — implication?","a":"Well controlled asthma","b":"Cure","c":"Impending severe attack","d":"Allergy resolved","ans":"C"},
{"t":"Pulmonology","q":"Nebulization frequency in severe attack initially?","a":"Every 8 hr","b":"Every 20 minutes","c":"Every 6 hr","d":"Once daily","ans":"B"},
{"t":"Pulmonology","q":"Primary goal of ventilation in intubated asthma?","a":"High tidal volume","b":"Normalize PaCO₂ rapidly","c":"Prevent dynamic hyperinflation","d":"Increase respiratory rate","ans":"C"},
{"t":"Pulmonology","q":"Most dangerous complication during mechanical ventilation in asthma?","a":"Hypoglycemia","b":"Barotrauma","c":"Bradycardia","d":"Hypertension","ans":"B"},
{"t":"Pulmonology","q":"Permissive hypercapnia means?","a":"Correct CO₂ aggressively","b":"Hyperventilate patient","c":"Allow moderate CO₂ rise","d":"Maintain hypocapnia","ans":"C"},
{"t":"Pulmonology","q":"Best indicator of response after therapy in acute asthma?","a":"Reduced wheeze","b":"Normal X-ray","c":"Reduced cough","d":"Improved PEFR","ans":"D"},
{"t":"Pulmonology","q":"Which inhaled drug combination improves bronchodilation in severe attack?","a":"Steroid + antibiotic","b":"Salbutamol + ipratropium","c":"Antihistamine + steroid","d":"Montelukast + antihistamine","ans":"B"},
{"t":"Pulmonology","q":"A patient with asthma becomes hypotensive during attack. Likely cause?","a":"Sepsis","b":"Dynamic hyperinflation reducing venous return","c":"MI","d":"Stroke","ans":"B"},
{"t":"Pulmonology","q":"Most important discharge medication after acute severe asthma?","a":"Antibiotic","b":"Antitussive","c":"Inhaled corticosteroid","d":"Antacid","ans":"C"},
{"t":"Pulmonology","q":"Repeated intubations in asthma predispose to?","a":"Bronchiectasis","b":"Pleural effusion","c":"Fibrosis","d":"Tracheal stenosis","ans":"D"},
{"t":"Pulmonology","q":"Severe asthma with agitation and sweating indicates?","a":"Recovery","b":"Drug reaction","c":"Hypoxia","d":"Anxiety disorder","ans":"C"},
{"t":"Pulmonology","q":"Which ventilator strategy is preferred in status asthmaticus?","a":"High RR high VT","b":"Normal ventilation","c":"Low RR low VT long expiratory time","d":"CPAP only","ans":"C"},
{"t":"Pulmonology","q":"Asthma patient develops sudden cardiac arrest during ventilation — cause?","a":"Hypoglycemia","b":"MI","c":"Tension pneumothorax","d":"Stroke","ans":"C"},
{"t":"Pulmonology","q":"Best pharmacologic therapy for refractory bronchospasm after intubation?","a":"Diazepam","b":"Ketamine","c":"Haloperidol","d":"Morphine","ans":"B"},
{"t":"Pulmonology","q":"Severe asthma ABG: pH 7.25, PaCO₂ 60, PaO₂ 55 — interpretation?","a":"Respiratory alkalosis","b":"Metabolic acidosis","c":"Normal","d":"Respiratory acidosis with hypoxemia","ans":"D"},
{"t":"Pulmonology","q":"Which finding mandates ICU admission in asthma?","a":"Mild wheeze","b":"Night cough","c":"PEFR <33%","d":"Rhinitis","ans":"C"},
{"t":"Pulmonology","q":"Inhaled anesthetic occasionally used in refractory status asthmaticus?","a":"Ether","b":"Nitrous oxide","c":"Halothane","d":"Oxygen","ans":"C"},
{"t":"Pulmonology","q":"Most appropriate fluid strategy in severe asthma?","a":"Fluid overload","b":"Restrict completely","c":"Moderate hydration","d":"Diuretics","ans":"C"},
{"t":"Pulmonology","q":"A ventilated asthma patient develops rising airway pressures and hypotension — immediate step?","a":"Increase rate","b":"Give diuretics","c":"Sedate","d":"Disconnect ventilator and manually ventilate","ans":"D"},
{"t":"Pulmonology","q":"Which marker suggests near fatal asthma episode?","a":"Bradycardia","b":"Hypocapnia","c":"Hypercapnia","d":"Normal ABG","ans":"C"},
{"t":"Pulmonology","q":"After recovery from status asthmaticus, long-term controller therapy must include?","a":"LABA alone","b":"Inhaled corticosteroid","c":"Antibiotic prophylaxis","d":"Antihistamine only","ans":"B"},
{"t":"Pulmonology","q":"A 60-year-old smoker with chronic cough and dyspnea has post-bronchodilator FEV₁/FVC 0.6. Diagnosis?","a":"Asthma","b":"Bronchiectasis","c":"COPD","d":"ILD","ans":"C"},
{"t":"Pulmonology","q":"First step in management of all COPD patients?","a":"Inhaled steroids","b":"Antibiotics","c":"Smoking cessation","d":"Oxygen therapy","ans":"C"},
{"t":"Pulmonology","q":"Initial pharmacologic therapy in mild COPD?","a":"LABA + ICS","b":"Oral steroids","c":"SABA as needed","d":"Roflumilast","ans":"C"},
{"t":"Pulmonology","q":"Most important intervention to slow COPD progression?","a":"Bronchodilators","b":"Smoking cessation","c":"Oxygen","d":"Steroids","ans":"B"},
{"t":"Pulmonology","q":"COPD with persistent symptoms — next step after SABA?","a":"Add antibiotic","b":"Add LABA or LAMA","c":"Add diuretics","d":"Add antihistamine","ans":"B"},
{"t":"Pulmonology","q":"Which drug reduces exacerbations most effectively in COPD?","a":"Antihistamines","b":"Inhaled corticosteroid combination therapy","c":"Antitussives","d":"Proton pump inhibitors","ans":"B"},
{"t":"Pulmonology","q":"Indication of long-term oxygen therapy in COPD?","a":"SpO₂ 95%","b":"PaO₂ 80 mmHg","c":"Normal ABG","d":"PaO₂ ≤55 mmHg","ans":"D"},
{"t":"Pulmonology","q":"Most useful bronchodilator in COPD maintenance?","a":"Antihistamine","b":"Steroid tablet","c":"Anticholinergic (LAMA)","d":"Leukotriene inhibitor","ans":"C"},
{"t":"Pulmonology","q":"Vaccination recommended in COPD patients?","a":"Rabies","b":"Typhoid","c":"Hepatitis A","d":"Influenza","ans":"D"},
{"t":"Pulmonology","q":"Pulmonary rehabilitation mainly improves?","a":"FEV₁","b":"Exercise tolerance","c":"Cure disease","d":"Oxygenation permanently","ans":"B"},
{"t":"Pulmonology","q":"A 65-year-old COPD patient using SABA frequently has daily symptoms. Next step in stepwise therapy?","a":"Add antibiotics","b":"Add mucolytic only","c":"Add LAMA","d":"Start oxygen","ans":"C"},
{"t":"Pulmonology","q":"COPD patient with repeated exacerbations despite LABA — add?","a":"Antihistamine","b":"ICS","c":"Antitussive","d":"Diuretic","ans":"B"},
{"t":"Pulmonology","q":"A COPD patient with eosinophils >300 cells/µL benefits most from?","a":"Antibiotics","b":"Diuretics","c":"ICS therapy","d":"Anticoagulants","ans":"C"},
{"t":"Pulmonology","q":"Preferred bronchodilator class in COPD vs asthma?","a":"Steroids","b":"Beta agonists only","c":"Leukotriene blockers","d":"Anticholinergics","ans":"D"},
{"t":"Pulmonology","q":"Drug used to reduce chronic bronchitis exacerbations in severe COPD?","a":"Montelukast","b":"Roflumilast","c":"Cetirizine","d":"Salbutamol","ans":"B"},
{"t":"Pulmonology","q":"Which parameter determines COPD severity grading?","a":"ESR","b":"FEV₁ % predicted","c":"Hemoglobin","d":"Pulse","ans":"B"},
{"t":"Pulmonology","q":"COPD patient develops ankle edema and raised JVP — cause?","a":"Left heart failure","b":"Pneumonia","c":"Cor pulmonale","d":"PE","ans":"C"},
{"t":"Pulmonology","q":"Target oxygen saturation in COPD exacerbation?","a":"100%","b":"94–98%","c":"88–92%","d":"80–85%","ans":"C"},
{"t":"Pulmonology","q":"Most important ABG abnormality in advanced COPD?","a":"Respiratory alkalosis","b":"Chronic respiratory acidosis","c":"Metabolic alkalosis","d":"Normal","ans":"B"},
{"t":"Pulmonology","q":"Drug contraindicated due to respiratory depression in COPD exacerbation?","a":"Bronchodilators","b":"Opioids","c":"Steroids","d":"Oxygen","ans":"B"},
{"t":"Pulmonology","q":"A 70-year-old chronic smoker presents with progressive dyspnea, productive cough for 10 years, FEV₁ 45% predicted, frequent exacerbations requiring steroids twice yearly. Currently on SABA and LAMA but still symptomatic. What is the next step?","a":"Stop bronchodilators","b":"Add LABA + ICS combination","c":"Start antifungal therapy","d":"Add antihistamines","ans":"B"},
{"t":"Pulmonology","q":"A COPD patient arrives in ER with worsening dyspnea, wheeze and purulent sputum. ABG shows pH 7.30, PaCO₂ 60 mmHg, PaO₂ 55 mmHg. Most appropriate immediate ventilatory management?","a":"Intubation immediately","b":"CPAP for sleep apnea","c":"Non-invasive ventilation","d":"Discharge home","ans":"C"},
{"t":"Pulmonology","q":"A 68-year-old COPD patient with chronic hypoxemia PaO₂ 52 mmHg at rest on room air. What outcome improves most with long-term oxygen therapy?","a":"Lung function","b":"FEV₁ normalization","c":"Survival","d":"Cure disease","ans":"C"},
{"t":"Pulmonology","q":"A chronic bronchitis phenotype patient with persistent sputum and frequent exacerbations despite triple inhaler therapy is evaluated for add-on therapy targeting PDE-4 inhibition. Which drug is indicated?","a":"Montelukast","b":"Omalizumab","c":"Roflumilast","d":"Ipratropium","ans":"C"},
{"t":"Pulmonology","q":"A COPD patient started high-flow oxygen develops drowsiness and rising PaCO₂. Mechanism?","a":"Increased metabolism","b":"Cardiac failure","c":"Hypoxic drive suppression and V/Q mismatch","d":"Renal compensation","ans":"C"},
{"t":"Pulmonology","q":"A patient with severe COPD (FEV₁ 28%) and repeated hospitalizations remains dyspneic despite maximal inhaled therapy. He has upper-lobe predominant emphysema and low exercise capacity. Next advanced management option?","a":"Antibiotics lifelong","b":"Antihistamines","c":"Lung volume reduction surgery","d":"No therapy","ans":"C"},
{"t":"Pulmonology","q":"A COPD patient with acute exacerbation has increased sputum purulence, volume, and dyspnea. Which treatment addition is indicated besides bronchodilators and steroids?","a":"Anticoagulants","b":"Antibiotics","c":"Antidepressants","d":"Antihistamines","ans":"B"},
{"t":"Pulmonology","q":"A 62-year-old COPD patient with severe airflow limitation develops morning headache and daytime somnolence. ABG shows chronic hypercapnia. Long-term management to improve ventilation?","a":"High dose diuretics","b":"Nocturnal NIV","c":"Bed rest","d":"Oxygen only intermittently","ans":"B"},
{"t":"Pulmonology","q":"A COPD patient on LABA+LAMA+ICS develops repeated pneumonia episodes. Which drug component most responsible?","a":"LABA","b":"Inhaled corticosteroid","c":"LAMA","d":"Oxygen","ans":"B"},
{"t":"Pulmonology","q":"A patient with COPD presents with sudden worsening dyspnea and pleuritic chest pain; suspicion pulmonary embolism. Most appropriate initial test?","a":"Spirometry","b":"CT pulmonary angiography","c":"Sputum culture","d":"Bronchoscopy","ans":"B"},
{"t":"Pulmonology","q":"A 64-year-old COPD patient with BMI 18, severe dyspnea and muscle wasting asks supportive therapy improving quality of life and reducing hospitalizations. Best option?","a":"Bed rest","b":"Pulmonary rehabilitation","c":"Antibiotics monthly","d":"Sedatives","ans":"B"},
{"t":"Pulmonology","q":"A COPD patient with acute exacerbation has pH 7.20 and altered consciousness despite NIV. Next step?","a":"Continue NIV","b":"Discharge","c":"Intubation and invasive ventilation","d":"Nebulization only","ans":"C"},
{"t":"Pulmonology","q":"A chronic smoker with COPD continues smoking while on oxygen therapy at home. Most dangerous complication?","a":"Hyperkalemia","b":"Pneumonia","c":"Fire hazard","d":"Renal failure","ans":"C"},
{"t":"Pulmonology","q":"A COPD patient with cor pulmonale presents with edema. Preferred treatment addition?","a":"High IV fluids","b":"Steroids lifelong","c":"Diuretics cautiously","d":"Anticoagulants","ans":"C"},
{"t":"Pulmonology","q":"A COPD patient with chronic hypercapnia develops metabolic alkalosis after diuretic therapy. Effect on ventilation?","a":"Improves ventilation","b":"No effect","c":"Worsens CO₂ retention","d":"Causes alkalosis cure","ans":"C"},
{"t":"Pulmonology","q":"A severe COPD patient asks vaccination schedule. Which combination recommended?","a":"BCG + polio","b":"Rabies + tetanus","c":"Measles only","d":"Influenza + pneumococcal vaccines","ans":"D"},
{"t":"Pulmonology","q":"A patient on chronic steroid tablets for COPD — most important adverse effect to monitor long term?","a":"Hearing loss","b":"Hypernatremia","c":"Osteoporosis","d":"Cataract only","ans":"C"},
{"t":"Pulmonology","q":"A COPD patient presents with polycythemia. Underlying mechanism?","a":"Infection","b":"Chronic hypoxia","c":"Bleeding","d":"Drug effect","ans":"B"},
{"t":"Pulmonology","q":"A COPD patient develops sudden increase dyspnea with unilateral absent breath sounds. Most likely complication?","a":"Pleural effusion","b":"Secondary spontaneous pneumothorax","c":"Pneumonia","d":"MI","ans":"B"},
{"t":"Pulmonology","q":"A patient with emphysema phenotype thin body and hyperinflated chest — dominant pathology?","a":"Bronchial mucus","b":"Fibrosis","c":"Alveolar wall destruction","d":"Infection","ans":"C"},
{"t":"Pulmonology","q":"A COPD exacerbation treated with systemic steroids — recommended duration?","a":"30 days","b":"5–7 days","c":"3 months","d":"Lifetime","ans":"B"},
{"t":"Pulmonology","q":"A COPD patient discharged after exacerbation — most important follow-up plan?","a":"Bed rest","b":"Stop therapy","c":"Inhaler technique assessment","d":"Antibiotics lifelong","ans":"C"},
{"t":"Pulmonology","q":"A COPD patient using only SABA presents with daily symptoms and night awakening — step escalation?","a":"Add antihistamine","b":"Oxygen only","c":"Add LAMA","d":"Stop therapy","ans":"C"},
{"t":"Pulmonology","q":"A COPD patient on oxygen therapy with saturation 97% becomes confused. Likely cause?","a":"Hypoglycemia","b":"Stroke","c":"CO₂ narcosis","d":"Infection","ans":"C"},
{"t":"Pulmonology","q":"A patient with COPD and atrial fibrillation — preferred bronchodilator safer option?","a":"High dose beta agonist","b":"Adrenaline","c":"Anticholinergic","d":"Theophylline","ans":"C"},
{"t":"Pulmonology","q":"A COPD patient with chronic cough produces large sputum daily — phenotype?","a":"Emphysema","b":"Asthma","c":"Chronic bronchitis","d":"ILD","ans":"C"},
{"t":"Pulmonology","q":"A COPD patient with worsening dyspnea during sleep and morning headache — complication?","a":"Pneumonia","b":"Nocturnal hypoventilation","c":"Asthma","d":"PE","ans":"B"},
{"t":"Pulmonology","q":"Ultimate curative option for end-stage COPD in selected patients?","a":"Antibiotics","b":"Steroids","c":"Lung transplantation","d":"Oxygen alone","ans":"C"},
{"t":"Pulmonology","q":"A patient presents with dyspnea and ABG shows PaO₂ 55 mmHg on room air. Type of respiratory failure?","a":"Normal","b":"Metabolic acidosis","c":"Type II hypercapnic","d":"Type I hypoxemic","ans":"D"},
{"t":"Pulmonology","q":"ABG: PaCO₂ 65 mmHg with pH 7.28 indicates:","a":"Acute respiratory acidosis","b":"Metabolic alkalosis","c":"Chronic respiratory alkalosis","d":"Metabolic acidosis","ans":"A"},
{"t":"Pulmonology","q":"Most common cause of type II respiratory failure:","a":"Pulmonary fibrosis","b":"Pneumothorax","c":"Pulmonary embolism","d":"COPD exacerbation","ans":"D"},
{"t":"Pulmonology","q":"Initial management of hypoxemia in respiratory failure:","a":"Antibiotics","b":"Oxygen therapy","c":"Steroids","d":"Diuretics","ans":"B"},
{"t":"Pulmonology","q":"Indication for non-invasive ventilation:","a":"Massive hemoptysis","b":"Cardiac arrest","c":"COPD with hypercapnia","d":"GCS 6","ans":"C"},
{"t":"Pulmonology","q":"A patient on oxygen becomes drowsy with rising CO₂. Mechanism?","a":"Drug allergy","b":"Sepsis","c":"Oxygen toxicity","d":"CO₂ retention","ans":"D"},
{"t":"Pulmonology","q":"PaO₂/FiO₂ ratio <300 suggests:","a":"Bronchitis","b":"ARDS","c":"Asthma","d":"Pneumonia","ans":"B"},
{"t":"Pulmonology","q":"Best monitoring parameter in ventilated patient:","a":"Hb","b":"ESR","c":"Pulse","d":"ABG","ans":"D"},
{"t":"Pulmonology","q":"Complication of prolonged intubation:","a":"Pleural plaque","b":"Tracheal stenosis","c":"Pneumonia","d":"Asthma","ans":"B"},
{"t":"Pulmonology","q":"Target oxygen saturation in chronic CO₂ retainers:","a":"70–80%","b":"100%","c":"88–92%","d":"95–100%","ans":"C"},
{"t":"Pulmonology","q":"A COPD patient presents with worsening dyspnea, ABG pH 7.32, PaCO₂ 58 mmHg, PaO₂ 54 mmHg despite oxygen. Next step?","a":"Sedation","b":"NIV","c":"Intubation","d":"Diuretics","ans":"B"},
{"t":"Pulmonology","q":"Patient with severe pneumonia suddenly deteriorates, refractory hypoxemia despite oxygen. Diagnosis?","a":"Bronchitis","b":"Pleural effusion","c":"ARDS","d":"Asthma","ans":"C"},
{"t":"Pulmonology","q":"Ventilator complication causing hypotension and absent breath sounds:","a":"Tension pneumothorax","b":"Bronchitis","c":"Pulmonary edema","d":"Atelectasis","ans":"A"},
{"t":"Pulmonology","q":"Most important step in suspected ventilator associated pneumonia:","a":"Steroids","b":"Extubate immediately","c":"Stop oxygen","d":"Start broad spectrum antibiotics","ans":"D"},
{"t":"Pulmonology","q":"Patient with ARDS — preferred ventilation strategy:","a":"Hyperventilation","b":"CPAP only","c":"Low tidal volume ventilation","d":"High tidal volume","ans":"C"},
{"t":"Pulmonology","q":"Rising plateau pressure on ventilator suggests:","a":"Recovery","b":"Hypoglycemia","c":"Improved compliance","d":"Barotrauma risk","ans":"D"},
{"t":"Pulmonology","q":"A patient develops alkalosis after ventilation. Cause?","a":"Infection","b":"Hyperventilation","c":"Hypoxia","d":"Hypoventilation","ans":"B"},
{"t":"Pulmonology","q":"Best method to improve oxygenation in ARDS:","a":"Supine","b":"Trendelenburg","c":"Prone positioning","d":"Sitting position","ans":"C"},
{"t":"Pulmonology","q":"High PEEP main benefit:","a":"Cause acidosis","b":"Prevent alveolar collapse","c":"Reduce heart rate","d":"Increase CO₂","ans":"B"},
{"t":"Pulmonology","q":"Permissive hypercapnia goal:","a":"Remove oxygen","b":"Cure disease","c":"Normalize ABG","d":"Prevent ventilator injury","ans":"D"},
{"t":"Pulmonology","q":"A 55-year-old septic patient develops tachypnea and confusion. ABG: PaO₂ 48 mmHg on high flow oxygen, bilateral infiltrates, no cardiac failure. Most appropriate management?","a":"Bronchodilators","b":"Antihistamines","c":"Low tidal volume mechanical ventilation","d":"Diuretics","ans":"C"},
{"t":"Pulmonology","q":"A COPD patient on NIV becomes increasingly drowsy, ABG pH 7.18 PaCO₂ 85. Next step?","a":"Sedation","b":"Intubation","c":"Oxygen mask","d":"Continue NIV","ans":"B"},
{"t":"Pulmonology","q":"Patient intubated for respiratory failure develops fever, purulent secretions after 72 hrs. Diagnosis?","a":"Pneumothorax","b":"ARDS","c":"VAP","d":"Atelectasis","ans":"C"},
{"t":"Pulmonology","q":"Ventilated patient sudden drop saturation after suctioning with crackles. Cause?","a":"MI","b":"PE","c":"Asthma","d":"Atelectasis","ans":"D"},
{"t":"Pulmonology","q":"High FiO₂ prolonged complication:","a":"Bradycardia","b":"Oxygen toxicity","c":"Hypoglycemia","d":"Hypertension","ans":"B"},
{"t":"Pulmonology","q":"ARDS Berlin criteria severity based on:","a":"Hemoglobin","b":"BP","c":"PaCO₂","d":"PaO₂/FiO₂ ratio","ans":"D"},
{"t":"Pulmonology","q":"Best initial management of pulmonary edema respiratory failure:","a":"Anticoagulant","b":"Antibiotics","c":"Diuretics","d":"Antihistamine","ans":"C"},
{"t":"Pulmonology","q":"A patient with neuromuscular disease develops hypercapnia without hypoxia. Failure type?","a":"Mixed","b":"Type I","c":"Metabolic","d":"Type II","ans":"D"},
{"t":"Pulmonology","q":"Patient on ventilator high peak pressure but normal plateau pressure. Cause?","a":"Fibrosis","b":"Airway obstruction","c":"ARDS","d":"Edema","ans":"B"},
{"t":"Pulmonology","q":"Sudden bradycardia during suctioning ventilated patient due to:","a":"Hypercapnia","b":"Hypoxia","c":"Vagal stimulation","d":"Sepsis","ans":"C"},
{"t":"Pulmonology","q":"A 62-year-old trauma patient develops progressive hypoxemia 24 hours after transfusion, bilateral infiltrates and normal cardiac function. Most likely complication and management?","a":"MI — thrombolysis","b":"TRALI — supportive ventilation","c":"Pneumonia — antibiotics","d":"PE — anticoagulation","ans":"B"},
{"t":"Pulmonology","q":"A ventilated patient suddenly becomes hypotensive, distended neck veins, absent breath sounds one side. Immediate step?","a":"Sedation","b":"Antibiotics","c":"Needle decompression","d":"Fluids","ans":"C"},
{"t":"Pulmonology","q":"A septic ICU patient develops refractory hypoxemia despite PEEP and FiO₂ 100%. Rescue therapy?","a":"Nebulization","b":"Antihistamines","c":"Diuretics","d":"Prone ventilation","ans":"D"},
{"t":"Pulmonology","q":"A patient with status asthmaticus ventilated shows rising CO₂ but stable pH. Strategy?","a":"Stop ventilator","b":"Permissive hypercapnia","c":"Extubate","d":"Hyperventilate","ans":"B"},
{"t":"Pulmonology","q":"A COPD patient after intubation has difficulty weaning due to weak muscles. Best support?","a":"Gradual weaning with pressure support","b":"Sedation","c":"Oxygen only","d":"Immediate extubation","ans":"A"},
{"t":"Pulmonology","q":"Long ventilated patient develops alkalosis and low CO₂. Adjustment?","a":"Increase FiO₂","b":"Stop PEEP","c":"Reduce respiratory rate","d":"Increase rate","ans":"C"},
{"t":"Pulmonology","q":"A ventilated ARDS patient develops subcutaneous emphysema. Cause?","a":"Pneumonia","b":"Hypoxia","c":"Barotrauma","d":"Sepsis","ans":"C"},
{"t":"Pulmonology","q":"Patient post extubation develops stridor. Immediate management?","a":"Anticoagulant","b":"Diuretics","c":"Antibiotics","d":"Nebulized adrenaline","ans":"D"},
{"t":"Pulmonology","q":"A patient with metabolic acidosis develops respiratory muscle fatigue. Outcome?","a":"Asthma","b":"Pneumonia","c":"Secondary respiratory failure","d":"Recovery","ans":"C"},
{"t":"Pulmonology","q":"Best indicator of readiness for extubation:","a":"Normal WBC","b":"Adequate spontaneous tidal volume","c":"Normal X-ray","d":"Fever absence","ans":"B"},
{"t":"Pulmonology","q":"A 48-year-old pancreatitis patient develops tachypnea and hypoxemia, PaO₂/FiO₂ 120, diffuse infiltrates, requires ventilation. Optimal PEEP strategy rationale?","a":"Sedation","b":"Reduce BP","c":"Increase CO₂ elimination","d":"Recruit collapsed alveoli and improve oxygenation","ans":"D"},
{"t":"Pulmonology","q":"A patient ventilated for ARDS develops acute kidney injury due to high intrathoracic pressure. Mechanism?","a":"Drug toxicity","b":"Dehydration","c":"Reduced venous return","d":"Infection","ans":"C"},
{"t":"Pulmonology","q":"Severe ARDS refractory to ventilation — advanced therapy?","a":"Steroids","b":"ECMO","c":"Antibiotics","d":"Diuretics","ans":"B"},
{"t":"Pulmonology","q":"A patient with obesity hypoventilation syndrome develops chronic hypercapnia. Best long term treatment?","a":"Antibiotic","b":"Bronchodilator","c":"Nocturnal BiPAP","d":"Oxygen only","ans":"C"},
{"t":"Pulmonology","q":"A ventilated patient develops metabolic alkalosis impairing weaning. Treatment?","a":"Increase ventilation","b":"Oxygen","c":"Correct electrolytes","d":"Increase sedation","ans":"C"},
{"t":"Pulmonology","q":"ARDS patient FiO₂ 1.0 for prolonged time risk:","a":"Bradycardia","b":"Renal failure","c":"Hypoglycemia","d":"Oxygen toxicity lung injury","ans":"D"},
{"t":"Pulmonology","q":"Sudden drop EtCO₂ during ventilation indicates:","a":"Hyperventilation","b":"Asthma","c":"Pulmonary embolism","d":"Recovery","ans":"C"},
{"t":"Pulmonology","q":"Ventilator dyssynchrony causing agitation — best management:","a":"Stop oxygen","b":"Sedation optimization","c":"Extubation","d":"Antibiotics","ans":"B"},
{"t":"Pulmonology","q":"ARDS complication causing pulmonary hypertension:","a":"Anemia","b":"Hyperglycemia","c":"Hypoxic vasoconstriction","d":"Infection","ans":"C"},
{"t":"Pulmonology","q":"Most common cause of death in severe respiratory failure ICU patients:","a":"Pneumothorax","b":"Bronchospasm","c":"Asthma","d":"Multiorgan failure","ans":"D"},
{"t":"Pulmonology","q":"Most common cause of atypical pneumonia in young adults?","a":"Klebsiella pneumoniae","b":"Staphylococcus aureus","c":"Mycoplasma pneumoniae","d":"Streptococcus pneumoniae","ans":"C"},
{"t":"Pulmonology","q":"Dry cough with bilateral patchy infiltrates suggests:","a":"TB","b":"Typical pneumonia","c":"Lung abscess","d":"Atypical pneumonia","ans":"D"},
{"t":"Pulmonology","q":"Drug of choice for Mycoplasma pneumonia:","a":"Ceftriaxone","b":"Azithromycin","c":"Vancomycin","d":"Penicillin","ans":"B"},
{"t":"Pulmonology","q":"Legionella pneumonia commonly associated with:","a":"Bird droppings","b":"Hospital ventilators only","c":"Contaminated water sources","d":"Soil exposure","ans":"C"},
{"t":"Pulmonology","q":"Hyponatremia is characteristic of:","a":"Mycoplasma","b":"Pneumococcal pneumonia","c":"Legionella","d":"Viral pneumonia","ans":"C"},
{"t":"Pulmonology","q":"Cold agglutinins positive in:","a":"TB","b":"Legionella","c":"Klebsiella","d":"Mycoplasma pneumonia","ans":"D"},
{"t":"Pulmonology","q":"Most common organism causing lung abscess:","a":"Viruses","b":"Anaerobes","c":"Fungi","d":"Mycoplasma","ans":"B"},
{"t":"Pulmonology","q":"Risk factor for lung abscess:","a":"Diabetes only","b":"Hypertension","c":"Asthma","d":"Aspiration","ans":"D"},
{"t":"Pulmonology","q":"Foul smelling sputum suggests:","a":"Viral pneumonia","b":"Pulmonary embolism","c":"Lung abscess","d":"Asthma","ans":"C"},
{"t":"Pulmonology","q":"Best initial imaging for pneumonia diagnosis:","a":"CT chest","b":"Chest X-ray","c":"MRI","d":"Ultrasound","ans":"B"},
{"t":"Pulmonology","q":"A young adult presents with low grade fever, headache, dry cough and normal leukocyte count. Most likely diagnosis?","a":"Lung abscess","b":"Atypical pneumonia","c":"TB","d":"Typical pneumonia","ans":"B"},
{"t":"Pulmonology","q":"Atypical pneumonia not responding to beta lactam therapy — reason?","a":"Drug resistance only","b":"Allergy","c":"Lack of cell wall organism","d":"Viral infection","ans":"C"},
{"t":"Pulmonology","q":"Most accurate diagnostic test for Legionella:","a":"Blood culture","b":"Urinary antigen test","c":"Mantoux","d":"Sputum Gram stain","ans":"B"},
{"t":"Pulmonology","q":"A patient with aspiration pneumonia develops cavitary lesion with air-fluid level. Diagnosis?","a":"Fungal ball","b":"TB","c":"Bronchiectasis","d":"Lung abscess","ans":"D"},
{"t":"Pulmonology","q":"Drug of choice for lung abscess:","a":"Isoniazid","b":"Amoxicillin-clavulanate","c":"Fluconazole","d":"Oseltamivir","ans":"B"},
{"t":"Pulmonology","q":"Most common lobe affected in aspiration lung abscess:","a":"Apex only","b":"Middle lobe","c":"Upper lobe posterior segment","d":"Lingula","ans":"C"},
{"t":"Pulmonology","q":"Pleural complication of pneumonia:","a":"Asthma","b":"Pneumothorax only","c":"Fibrosis only","d":"Empyema","ans":"D"},
{"t":"Pulmonology","q":"CURB-65 score used to assess:","a":"TB severity","b":"Severity of pneumonia","c":"COPD grading","d":"Asthma severity","ans":"B"},
{"t":"Pulmonology","q":"Indication for hospital admission pneumonia:","a":"No fever","b":"Mild cough","c":"Young age","d":"CURB-65 ≥2","ans":"D"},
{"t":"Pulmonology","q":"Parapneumonic effusion requires drainage when:","a":"Clear fluid","b":"pH <7.2","c":"Mild fever","d":"Small size","ans":"B"},
{"t":"Pulmonology","q":"A 40-year-old smoker presents with high fever, productive cough with rusty sputum and lobar consolidation. Likely organism?","a":"Chlamydia","b":"Legionella","c":"Streptococcus pneumoniae","d":"Mycoplasma","ans":"C"},
{"t":"Pulmonology","q":"A patient with diarrhea, confusion, and pneumonia after hotel stay. Most probable pathogen?","a":"Klebsiella","b":"Pneumococcus","c":"Legionella","d":"Mycoplasma","ans":"C"},
{"t":"Pulmonology","q":"Severe necrotizing pneumonia after influenza infection — organism?","a":"Chlamydia","b":"Mycoplasma","c":"TB","d":"Staphylococcus aureus","ans":"D"},
{"t":"Pulmonology","q":"Aspiration pneumonia in alcoholic unconscious patient — initial therapy?","a":"Antifungal","b":"Clindamycin","c":"Steroids","d":"Antiviral","ans":"B"},
{"t":"Pulmonology","q":"Persistent cavity after pneumonia with foul sputum and weight loss — next investigation?","a":"Echo","b":"MRI brain","c":"CT chest","d":"ECG","ans":"C"},
{"t":"Pulmonology","q":"Non resolving pneumonia suspicion malignancy — best step?","a":"Steroids","b":"Bronchoscopy","c":"Oxygen","d":"Antibiotics repeat","ans":"B"},
{"t":"Pulmonology","q":"Most common complication of lung abscess:","a":"COPD","b":"PE","c":"Asthma","d":"Empyema","ans":"D"},
{"t":"Pulmonology","q":"Treatment duration lung abscess:","a":"Lifetime","b":"1 day","c":"4–6 weeks","d":"3–5 days","ans":"C"},
{"t":"Pulmonology","q":"Hospital acquired pneumonia common organism:","a":"Mycoplasma","b":"Pseudomonas","c":"Chlamydia","d":"Viruses","ans":"B"},
{"t":"Pulmonology","q":"Most sensitive test detecting atypical pneumonia:","a":"Hemoglobin","b":"ESR","c":"Mantoux","d":"PCR","ans":"D"},
{"t":"Pulmonology","q":"A 65-year-old diabetic presents with severe pneumonia and bulging fissure sign on X-ray. Etiology?","a":"TB","b":"Klebsiella pneumoniae","c":"Viral","d":"Mycoplasma","ans":"B"},
{"t":"Pulmonology","q":"A patient with pneumonia develops pleuritic chest pain and pleural effusion. Fluid glucose low. Diagnosis?","a":"Edema","b":"Transudate","c":"Empyema","d":"Asthma","ans":"C"},
{"t":"Pulmonology","q":"Young adult with persistent cough and ear pain plus walking pneumonia symptoms — organism?","a":"TB","b":"Staph","c":"Mycoplasma","d":"Klebsiella","ans":"C"},
{"t":"Pulmonology","q":"Immunocompromised patient with bilateral interstitial infiltrates and hypoxia — suspect?","a":"Mycoplasma","b":"Legionella","c":"Pneumococcus","d":"Pneumocystis jirovecii","ans":"D"},
{"t":"Pulmonology","q":"Drug of choice Pneumocystis pneumonia:","a":"Amoxicillin","b":"Ceftriaxone","c":"TMP-SMX","d":"Azithromycin","ans":"C"},
{"t":"Pulmonology","q":"Lung abscess not responding to antibiotics — next management?","a":"Antihistamine","b":"Percutaneous drainage","c":"Steroids","d":"Oxygen only","ans":"B"},
{"t":"Pulmonology","q":"Atypical pneumonia extrapulmonary manifestation hemolytic anemia — organism?","a":"Viral","b":"Mycoplasma","c":"TB","d":"Klebsiella","ans":"B"},
{"t":"Pulmonology","q":"Most common cause recurrent aspiration lung abscess:","a":"Hypertension","b":"Diabetes","c":"Seizures","d":"Asthma","ans":"C"},
{"t":"Pulmonology","q":"Radiological hallmark lung abscess:","a":"Diffuse reticular shadow","b":"Air-fluid level cavity","c":"Pleural plaque","d":"Mass lesion","ans":"B"},
{"t":"Pulmonology","q":"Community acquired pneumonia first line outpatient therapy healthy adult:","a":"Meropenem","b":"Vancomycin","c":"Amphotericin","d":"Amoxicillin","ans":"D"},
{"t":"Pulmonology","q":"A 58-year-old alcoholic presents with fever, productive cough and currant jelly sputum. Most likely pathogen?","a":"Chlamydia","b":"Legionella","c":"Klebsiella pneumoniae","d":"Mycoplasma","ans":"C"},
{"t":"Pulmonology","q":"A pneumonia patient develops acute confusion, hyponatremia, diarrhea and elevated liver enzymes. Best treatment?","a":"Anti-TB therapy","b":"Macrolide or fluoroquinolone","c":"Antifungal","d":"Penicillin","ans":"B"},
{"t":"Pulmonology","q":"A patient aspirated during anesthesia now febrile with infiltrate in dependent lung. Diagnosis?","a":"Viral pneumonia","b":"ARDS","c":"Aspiration pneumonia","d":"TB","ans":"C"},
{"t":"Pulmonology","q":"Complication lung abscess causing hemoptysis mechanism:","a":"Edema","b":"Bronchospasm","c":"Hypoxia","d":"Vessel erosion","ans":"D"},
{"t":"Pulmonology","q":"Post obstructive pneumonia suspicion — next investigation?","a":"Echo","b":"CT chest","c":"ECG","d":"ABG","ans":"B"},
{"t":"Pulmonology","q":"Severe pneumonia requiring ICU with MRSA risk — add:","a":"Amoxicillin","b":"Macrolide only","c":"Vancomycin","d":"Steroids","ans":"C"},
{"t":"Pulmonology","q":"Non productive cough, normal WBC, diffuse infiltrates — best empiric therapy?","a":"Anti TB","b":"Penicillin","c":"Antifungal","d":"Macrolide","ans":"D"},
{"t":"Pulmonology","q":"Lung abscess rupture into pleura causes:","a":"Empyema","b":"Edema","c":"Asthma","d":"Pneumothorax","ans":"A"},
{"t":"Pulmonology","q":"Most important prevention aspiration pneumonia:","a":"Steroids","b":"Elevate head end","c":"Oxygen","d":"Antibiotics prophylaxis","ans":"B"},
{"t":"Pulmonology","q":"Definitive diagnosis atypical pneumonia organism:","a":"WBC count","b":"PCR testing","c":"ESR","d":"X-ray only","ans":"B"},
{"t":"Pulmonology","q":"A 32-year-old woman on oral contraceptives presents with sudden pleuritic chest pain, tachycardia and normal chest X-ray. Wells score = 2. Next best step?","a":"Coronary angiography","b":"D-dimer testing","c":"Start thrombolysis","d":"Immediate anticoagulation lifelong","ans":"B"},
{"t":"Pulmonology","q":"A 70-year-old postoperative patient develops syncope, hypotension 80/50 mmHg, raised JVP and clear lungs. Most appropriate immediate therapy?","a":"Diuretics","b":"LMWH only","c":"IV antibiotics","d":"Systemic thrombolysis","ans":"D"},
{"t":"Pulmonology","q":"A patient with suspected PE has low Wells score and negative D-dimer. Interpretation?","a":"Repeat CT scan","b":"Start anticoagulation","c":"PE ruled out","d":"Perform echo","ans":"C"},
{"t":"Pulmonology","q":"A pregnant woman at 28 weeks presents with suspected PE. Initial imaging modality?","a":"MRI chest","b":"V/Q scan","c":"CT pulmonary angiography","d":"Coronary angiography","ans":"B"},
{"t":"Pulmonology","q":"A stable PE patient has RV dilation on echo but normal BP. Risk category?","a":"Chronic","b":"Massive","c":"Low risk","d":"Submassive (intermediate risk)","ans":"D"},
{"t":"Pulmonology","q":"A patient develops PE while on therapeutic warfarin INR 2.5. Next step?","a":"Add aspirin only","b":"Stop treatment","c":"Switch to LMWH/DOAC","d":"Observe","ans":"C"},
{"t":"Pulmonology","q":"A 40-year-old man presents with sudden dyspnea after long flight; ABG shows respiratory alkalosis and hypoxemia. Most likely diagnosis?","a":"Asthma","b":"Pulmonary embolism","c":"Pneumothorax","d":"Pneumonia","ans":"B"},
{"t":"Pulmonology","q":"Hemodynamically unstable PE with contraindication to thrombolysis — best option?","a":"Aspirin","b":"IVC filter only","c":"Surgical embolectomy","d":"Oxygen only","ans":"C"},
{"t":"Pulmonology","q":"A cancer patient diagnosed with acute PE. Preferred long-term therapy?","a":"Warfarin only","b":"Aspirin","c":"No treatment","d":"DOAC or LMWH","ans":"D"},
{"t":"Pulmonology","q":"Sudden drop in EtCO₂ during anesthesia with hypotension most suggests:","a":"Bronchospasm","b":"Pneumonia","c":"Pulmonary embolism","d":"MI","ans":"C"},
{"t":"Pulmonology","q":"A 55-year-old obese smoker presents with pleuritic chest pain and hemoptysis; CT confirms segmental PE. Hemodynamically stable. Best management?","a":"Surgery","b":"Antibiotics","c":"Anticoagulation with DOAC","d":"Thrombolysis","ans":"C"},
{"t":"Pulmonology","q":"A PE patient with severe renal failure (eGFR <15). Preferred anticoagulant?","a":"Dabigatran","b":"Rivaroxaban","c":"Apixaban","d":"Unfractionated heparin","ans":"D"},
{"t":"Pulmonology","q":"A young patient with PE has history of HIT. Best therapy?","a":"Warfarin loading","b":"Heparin infusion","c":"Argatroban or DOAC","d":"Aspirin","ans":"C"},
{"t":"Pulmonology","q":"A patient collapses from massive PE causing cardiac arrest. Immediate management?","a":"Diuretics","b":"Defibrillation only","c":"CPR and thrombolysis","d":"Antibiotics","ans":"C"},
{"t":"Pulmonology","q":"CT shows saddle embolus but vitals stable. Next step?","a":"Surgery always","b":"Anticoagulation alone","c":"No therapy","d":"Thrombolysis mandatory","ans":"B"},
{"t":"Pulmonology","q":"Patient on rivaroxaban misses two doses. Advice?","a":"Stop permanently","b":"Double lifelong dose","c":"Skip completely","d":"Take next scheduled dose and ensure adherence","ans":"D"},
{"t":"Pulmonology","q":"Echo showing McConnell sign indicates:","a":"MI","b":"Pneumonia","c":"Pulmonary embolism","d":"Asthma","ans":"C"},
{"t":"Pulmonology","q":"Recurrent unprovoked PE recommended treatment duration:","a":"6 months","b":"Lifelong anticoagulation","c":"3 months","d":"1 week","ans":"B"},
{"t":"Pulmonology","q":"Patient with PE develops hematuria on DOAC. Next step?","a":"Increase dose","b":"Ignore","c":"Add antiplatelet","d":"Assess bleeding risk and adjust therapy","ans":"D"},
{"t":"Pulmonology","q":"Primary prevention hospitalized high-risk patient:","a":"Steroids","b":"Oxygen therapy","c":"Early mobilization and prophylactic anticoagulation","d":"Antibiotics","ans":"C"},
{"t":"Pulmonology","q":"A 62-year-old bedridden stroke patient develops tachycardia, hypoxia, and normal chest X-ray. D-dimer elevated. Next diagnostic step?","a":"Spirometry","b":"CT pulmonary angiography","c":"Bronchoscopy","d":"Repeat X-ray","ans":"B"},
{"t":"Pulmonology","q":"A patient with PE and hypotension but recent intracranial hemorrhage. Best management?","a":"Aspirin","b":"No therapy","c":"Thrombolysis","d":"Surgical embolectomy","ans":"D"},
{"t":"Pulmonology","q":"Mechanism of syncope in massive PE:","a":"Hypoglycemia","b":"Bronchospasm","c":"Acute RV failure reducing cardiac output","d":"Infection","ans":"C"},
{"t":"Pulmonology","q":"A patient treated with apixaban asks monitoring requirement. Correct advice?","a":"Weekly PT","b":"No routine lab monitoring","c":"Platelet count only","d":"Daily INR","ans":"B"},
{"t":"Pulmonology","q":"Post PE persistent dyspnea months later suggests:","a":"TB","b":"Chronic thromboembolic pulmonary hypertension","c":"Pneumonia","d":"Asthma","ans":"B"},
{"t":"Pulmonology","q":"Elevated BNP and troponin in PE indicates:","a":"Renal failure","b":"Right ventricular strain","c":"Liver disease","d":"Infection","ans":"B"},
{"t":"Pulmonology","q":"A 45-year-old woman postpartum develops sudden dyspnea. First bedside test?","a":"Colonoscopy","b":"Endoscopy","c":"MRI brain","d":"Compression ultrasound legs","ans":"D"},
{"t":"Pulmonology","q":"Small distal PE asymptomatic management:","a":"Surgery","b":"Mandatory thrombolysis","c":"Clinical surveillance or anticoagulation based on risk","d":"Antibiotics","ans":"C"},
{"t":"Pulmonology","q":"Warfarin overlap with heparin required because:","a":"No effect","b":"Rapid action","c":"Toxicity","d":"Protein C depletion early hypercoagulability","ans":"D"},
{"t":"Pulmonology","q":"Major complication thrombolysis:","a":"Pneumonia","b":"Intracranial hemorrhage","c":"Hypertension","d":"Asthma","ans":"B"},
{"t":"Pulmonology","q":"A young athlete presents with pleuritic chest pain after dehydration and long travel; CT confirms PE. No provoking factors otherwise. Recommended duration anticoagulation?","a":"1 week","b":"3 months","c":"Extended or lifelong depending risk","d":"6 months","ans":"C"},
{"t":"Pulmonology","q":"A patient with DVT signs and PE symptoms — first step before CT?","a":"Discharge","b":"Antibiotics","c":"Wait imaging","d":"Start anticoagulation if high probability","ans":"D"},
{"t":"Pulmonology","q":"PE causing wedge-shaped opacity on X-ray called:","a":"Air bronchogram","b":"Hampton hump","c":"Bat wing pattern","d":"Kerley B lines","ans":"B"},
{"t":"Pulmonology","q":"Preferred anticoagulant in pregnancy PE treatment duration?","a":"Aspirin","b":"LMWH throughout pregnancy","c":"DOAC","d":"Warfarin","ans":"B"},
{"t":"Pulmonology","q":"A patient with massive PE stabilized after thrombolysis. Next long-term therapy?","a":"Steroids","b":"Stop all drugs","c":"Continue anticoagulation","d":"Antibiotics","ans":"C"},
{"t":"Pulmonology","q":"Mechanism hypoxemia in PE:","a":"Shunt only","b":"Hypoventilation","c":"V/Q mismatch","d":"Diffusion defect only","ans":"C"},
{"t":"Pulmonology","q":"DOAC contraindicated condition:","a":"Diabetes","b":"Asthma","c":"Hypertension","d":"Mechanical heart valve","ans":"D"},
{"t":"Pulmonology","q":"A patient develops PE despite prophylaxis after surgery. Reason?","a":"Drug allergy","b":"High thrombosis risk","c":"Infection","d":"Oxygen therapy","ans":"B"},
{"t":"Pulmonology","q":"First sign massive PE on capnography:","a":"Rise EtCO₂","b":"Hypercapnia","c":"Sudden fall EtCO₂","d":"Normal","ans":"C"},
{"t":"Pulmonology","q":"Most common immediate cause death acute PE:","a":"TB","b":"Asthma","c":"Pneumonia","d":"Cardiogenic shock from RV failure","ans":"D"},
{"t":"Pulmonology","q":"A 50-year-old ICU patient immobilized for 10 days suddenly develops unexplained hypoxia and tachycardia with normal auscultation. ABG shows respiratory alkalosis. Next best investigation?","a":"Bronchoscopy","b":"Spirometry","c":"CT pulmonary angiography","d":"Chest X-ray repeat","ans":"C"},
{"t":"Pulmonology","q":"A patient with submassive PE deteriorates hemodynamically. Management escalation?","a":"Oxygen only","b":"Rescue thrombolysis","c":"Antibiotics","d":"Stop anticoagulation","ans":"B"},
{"t":"Pulmonology","q":"A PE patient develops severe hypotension after intubation due to:","a":"Allergy","b":"Infection","c":"Hypoglycemia","d":"Reduced venous return from RV failure","ans":"D"},
{"t":"Pulmonology","q":"IVC filter indication:","a":"Stable patient","b":"Routine use","c":"Contraindication to anticoagulation","d":"Mild PE","ans":"C"},
{"t":"Pulmonology","q":"A young woman with recurrent miscarriages develops PE. Underlying disorder?","a":"Asthma","b":"COPD","c":"Antiphospholipid syndrome","d":"Pneumonia","ans":"C"},
{"t":"Pulmonology","q":"Best marker prognosis PE severity:","a":"WBC","b":"Hemoglobin","c":"Sodium","d":"Troponin/BNP elevation","ans":"D"},
{"t":"Pulmonology","q":"A stable outpatient PE started on DOAC. When anticoagulation begins acting?","a":"After 1 week","b":"After 3 days","c":"After 1 month","d":"Immediately","ans":"D"},
{"t":"Pulmonology","q":"Patient with PE complains pleuritic pain due to:","a":"Edema","b":"Pulmonary infarction","c":"Bronchospasm","d":"Infection","ans":"B"},
{"t":"Pulmonology","q":"Heparin induced thrombocytopenia suspected — platelet drop 50%. Action?","a":"Continue same","b":"Stop heparin and start alternative anticoagulant","c":"Add aspirin","d":"Observe","ans":"B"},
{"t":"Pulmonology","q":"Most effective hospital PE prevention strategy:","a":"Risk stratification and prophylaxis protocol","b":"Antibiotics","c":"Steroids","d":"Oxygen therapy","ans":"A"},
{"t":"Pulmonology","q":"A 26-year-old female presents with 3 months history of persistent dry cough, exertional dyspnea and fatigue. Chest X-ray shows bilateral symmetrical hilar enlargement without parenchymal infiltrates. Most likely radiological diagnosis?","a":"Pleural effusion","b":"Pneumothorax","c":"Bilateral hilar lymphadenopathy","d":"Upper lobe cavitation","ans":"C"},
{"t":"Pulmonology","q":"Which biochemical marker is typically elevated due to increased macrophage activity in sarcoidosis?","a":"Elevated ACE level","b":"Absent ACE level","c":"Decreased ACE level","d":"Persistently normal ACE level","ans":"A"},
{"t":"Pulmonology","q":"Among extra-pulmonary manifestations of systemic sarcoidosis, which organ system is most frequently affected clinically?","a":"Liver","b":"Skin","c":"Heart","d":"Kidney","ans":"B"},
{"t":"Pulmonology","q":"A young woman presents with painful red nodules over the shins, fever and ankle pain with hilar lymphadenopathy. What prognostic implication does erythema nodosum suggest?","a":"Bacterial infection","b":"Chronic progressive disease","c":"Malignancy transformation","d":"Favorable prognosis","ans":"D"},
{"t":"Pulmonology","q":"Transbronchial biopsy histology shows tight aggregates of epithelioid histiocytes without central necrosis. Which pathological hallmark does this represent?","a":"Fibrosis only","b":"Caseating granuloma","c":"Non-caseating granuloma","d":"Necrotizing inflammation","ans":"C"},
{"t":"Pulmonology","q":"Which of the following is the most typical presenting pulmonary complaint in sarcoidosis?","a":"Isolated wheezing","b":"Copious purulent sputum","c":"Persistent dry cough","d":"Massive hemoptysis","ans":"C"},
{"t":"Pulmonology","q":"A patient with symptomatic pulmonary sarcoidosis has worsening dyspnea and cough affecting daily activities. What is first-line pharmacologic treatment?","a":"Anticoagulation","b":"Antifungal therapy","c":"Broad spectrum antibiotics","d":"Systemic corticosteroids","ans":"D"},
{"t":"Pulmonology","q":"Hypercalcemia is detected in a sarcoidosis patient despite normal PTH levels. What is the underlying mechanism?","a":"Drug induced toxicity","b":"Extrarenal activation of vitamin D by macrophages","c":"Renal tubular failure","d":"Primary hyperparathyroidism","ans":"B"},
{"t":"Pulmonology","q":"A sarcoidosis patient complains of eye pain, photophobia and blurred vision. Which ocular manifestation is most commonly associated?","a":"Retinal detachment","b":"Glaucoma","c":"Uveitis","d":"Cataract","ans":"C"},
{"t":"Pulmonology","q":"Chest radiograph shows symmetrical enlargement of both hilar regions with otherwise clear lung fields. This corresponds to which stage of pulmonary sarcoidosis?","a":"Nodular infiltrative stage","b":"Stage I disease","c":"Pulmonary fibrosis stage","d":"Pleural stage","ans":"B"},
{"t":"Pulmonology","q":"A 28-year-old female presents with fever, bilateral ankle swelling, erythema nodosum and bilateral hilar lymphadenopathy without respiratory compromise. What clinical syndrome does this represent?","a":"Tuberculosis","b":"Rheumatoid arthritis","c":"Lofgren syndrome","d":"Systemic lupus erythematosus","ans":"C"},
{"t":"Pulmonology","q":"A sarcoidosis patient reports syncope and palpitations. ECG reveals conduction abnormalities. Which complication should be suspected?","a":"Pulmonary embolism","b":"Bronchial asthma","c":"Community acquired pneumonia","d":"Cardiac conduction block due to cardiac sarcoidosis","ans":"D"},
{"t":"Pulmonology","q":"A patient develops facial nerve palsy, parotid enlargement and uveitis along with fever and hilar lymphadenopathy. What specific sarcoidosis presentation is this?","a":"Heerfordt syndrome","b":"Lambert Eaton syndrome","c":"Horner syndrome","d":"Sjogren syndrome","ans":"A"},
{"t":"Pulmonology","q":"A sarcoidosis patient develops recurrent kidney stones and elevated serum calcium. What is the pathophysiological cause?","a":"Metabolic acidosis","b":"Hyperkalemia","c":"Hypercalcemia due to vitamin D activation","d":"Hypocalcemia","ans":"C"},
{"t":"Pulmonology","q":"An asymptomatic patient with incidentally discovered bilateral hilar lymphadenopathy consistent with stage I sarcoidosis has normal PFTs. Most appropriate management?","a":"Chemotherapy","b":"Observation and follow-up","c":"Surgical intervention","d":"Immediate steroid therapy","ans":"B"},
{"t":"Pulmonology","q":"Which investigation is required to confirm sarcoidosis definitively in a compatible clinical and imaging context?","a":"Spirometry","b":"Chest X-ray alone","c":"ESR level","d":"Tissue biopsy demonstrating granulomas","ans":"D"},
{"t":"Pulmonology","q":"Pulmonary function testing in sarcoidosis with interstitial involvement typically demonstrates which pattern?","a":"Always normal","b":"Restrictive ventilatory defect","c":"Mixed purely obstructive","d":"Obstructive pattern","ans":"B"},
{"t":"Pulmonology","q":"A patient with stage II sarcoidosis presents with progressive dyspnea and persistent cough affecting daily activity. Recommended therapy?","a":"Oral corticosteroids","b":"Oxygen alone","c":"Anticoagulation","d":"Antibiotics","ans":"A"},
{"t":"Pulmonology","q":"A patient fails to improve with prolonged steroid therapy and develops steroid toxicity. Which medication is commonly used as a steroid-sparing agent?","a":"Antihistamine","b":"Methotrexate","c":"Diuretic","d":"Penicillin","ans":"B"},
{"t":"Pulmonology","q":"In chronic progressive sarcoidosis, what is the leading cause of mortality due to pulmonary involvement?","a":"Infection","b":"Renal failure","c":"Pulmonary fibrosis","d":"Liver cirrhosis","ans":"C"},
{"t":"Pulmonology","q":"A 42-year-old non-smoker presents with persistent fatigue, dry cough, mild hypercalcemia and bilateral hilar lymphadenopathy while TB workup is negative. Most appropriate next diagnostic step?","a":"Empirical antibiotics","b":"Discharge with reassurance","c":"Bronchoscopy with tissue biopsy","d":"Start anti-tuberculous therapy empirically","ans":"C"},
{"t":"Pulmonology","q":"A sarcoidosis patient reports progressive blurred vision, photophobia and eye redness. Which specialty referral is most urgent?","a":"Surgery","b":"Ophthalmology","c":"ENT","d":"Cardiology","ans":"B"},
{"t":"Pulmonology","q":"A patient with suspected cardiac sarcoidosis develops arrhythmias and unexplained syncope. Which imaging modality best evaluates myocardial granulomatous infiltration?","a":"Spirometry","b":"Chest X-ray","c":"Cardiac MRI","d":"ECG alone","ans":"C"},
{"t":"Pulmonology","q":"A patient with neurosarcoidosis presents with unilateral facial weakness and inability to close the eye. Which cranial nerve is most commonly involved?","a":"CN XII","b":"CN III","c":"CN VII","d":"CN V","ans":"C"},
{"t":"Pulmonology","q":"A sarcoidosis patient presents with symptomatic hypercalcemia including nausea, confusion and polyuria. Most appropriate first-line treatment?","a":"Anticoagulation","b":"Systemic corticosteroids","c":"Potassium replacement","d":"Insulin therapy","ans":"B"},
{"t":"Pulmonology","q":"Bronchoalveolar lavage in suspected sarcoidosis reveals lymphocytosis with significantly elevated CD4/CD8 ratio. What does this finding suggest?","a":"Alveolar hemorrhage","b":"Eosinophilic pneumonia","c":"Neutrophilic infection","d":"Sarcoidosis supportive finding","ans":"D"},
{"t":"Pulmonology","q":"A patient develops chronic violaceous plaques over nose and cheeks along with pulmonary sarcoidosis. Which specific dermatologic lesion is this?","a":"Lupus pernio","b":"Psoriasis","c":"Vitiligo","d":"Melanoma","ans":"A"},
{"t":"Pulmonology","q":"Chest imaging in a sarcoidosis patient shows diffuse pulmonary infiltrates without hilar lymphadenopathy. Which stage does this represent?","a":"Stage 0","b":"Pleural stage","c":"Stage I","d":"Stage III","ans":"D"},
{"t":"Pulmonology","q":"Which clinical manifestation in sarcoidosis mandates initiation of corticosteroid therapy even if pulmonary symptoms are mild?","a":"Normal labs","b":"Mild cough only","c":"Ocular involvement","d":"Asymptomatic lymphadenopathy","ans":"C"},
{"t":"Pulmonology","q":"A sarcoidosis patient self-medicates with vitamin D supplements and develops worsening hypercalcemia. Why should vitamin D be avoided?","a":"Causes hypokalemia","b":"Leads to infection","c":"Causes anemia","d":"It increases macrophage-mediated calcium absorption","ans":"D"},
{"t":"Pulmonology","q":"A long-standing sarcoidosis patient develops progressive exertional dyspnea and imaging reveals honeycombing and architectural distortion. What complication has occurred?","a":"Asthma","b":"Pulmonary fibrosis","c":"Tuberculosis","d":"Pneumonia","ans":"B"},
{"t":"Pulmonology","q":"A patient with hepatic sarcoidosis is investigated for abnormal liver tests. Which laboratory abnormality is most characteristic?","a":"Hyperkalemia","b":"Elevated alkaline phosphatase","c":"Hyponatremia","d":"Low hemoglobin","ans":"B"},
{"t":"Pulmonology","q":"Sarcoid arthritis typically presents with painful swelling in which joints?","a":"Hip","b":"Small hand joints","c":"Spine","d":"Ankles","ans":"D"},
{"t":"Pulmonology","q":"Which histological finding helps differentiate sarcoidosis from tuberculosis?","a":"Fever","b":"Hemoptysis","c":"Non-caseating granulomas","d":"Cavitation","ans":"C"},
{"t":"Pulmonology","q":"Persistent cough in pulmonary sarcoidosis is most commonly due to which mechanism?","a":"Tumor obstruction","b":"Pulmonary edema","c":"Airway granulomatous inflammation","d":"Infection","ans":"C"},
{"t":"Pulmonology","q":"Serum ACE levels are mainly useful in sarcoidosis for which purpose?","a":"Confirming diagnosis alone","b":"Prognosis only","c":"Monitoring disease activity","d":"Screening general population","ans":"C"},
{"t":"Pulmonology","q":"Radiological stage IV sarcoidosis corresponds to which structural change?","a":"Effusion","b":"Normal lung","c":"Lymphadenopathy","d":"Pulmonary fibrosis","ans":"D"},
{"t":"Pulmonology","q":"A patient with severe refractory neurosarcoidosis not responding to steroids and methotrexate requires advanced therapy. Which drug is most appropriate?","a":"Anticoagulants","b":"Infliximab","c":"Oxygen","d":"Antibiotics","ans":"B"},
{"t":"Pulmonology","q":"Which hematological abnormality may occur due to splenic involvement in sarcoidosis?","a":"Hemophilia","b":"Thrombocytosis","c":"Leukopenia","d":"Polycythemia","ans":"C"},
{"t":"Pulmonology","q":"Gallium scan showing “panda sign” uptake in lacrimal and parotid glands is characteristic of which disease?","a":"Asthma","b":"Cancer","c":"Sarcoidosis","d":"Tuberculosis","ans":"C"},
{"t":"Pulmonology","q":"A patient presents with fever, parotid enlargement, facial nerve palsy and uveitis with bilateral hilar lymphadenopathy. What syndrome is this?","a":"SLE","b":"Heerfordt syndrome","c":"Lymphoma","d":"Tuberculosis","ans":"B"},
{"t":"Pulmonology","q":"A sarcoidosis patient develops ventricular arrhythmias during follow-up. Which organ involvement must be urgently evaluated?","a":"Pulmonary embolism","b":"Lung infection","c":"Asthma","d":"Cardiac involvement","ans":"D"},
{"t":"Pulmonology","q":"A patient requires steroid-sparing therapy due to severe steroid adverse effects in chronic sarcoidosis. Which drug is appropriate?","a":"Diuretic","b":"Antihistamine","c":"Methotrexate","d":"Penicillin","ans":"C"},
{"t":"Pulmonology","q":"The abnormal vitamin D metabolism in sarcoidosis most commonly results in which metabolic abnormality?","a":"Hypokalemia","b":"Hypernatremia","c":"Hypocalcemia","d":"Hypercalcemia","ans":"D"},
{"t":"Pulmonology","q":"A patient initially improves on steroids but relapses after dose tapering. What is the best next management approach?","a":"Stop therapy","b":"Restart higher steroid dose or add immunosuppressant","c":"Antibiotics","d":"Oxygen only","ans":"B"},
{"t":"Pulmonology","q":"The definitive diagnosis of sarcoidosis requires demonstration of which pathological finding?","a":"Clinical symptoms only","b":"Elevated ACE alone","c":"Biopsy showing non-caseating granulomas","d":"Imaging abnormalities only","ans":"C"},
{"t":"Pulmonology","q":"Chronic pulmonary sarcoidosis most commonly progresses to which complication?","a":"Pulmonary fibrosis","b":"Effusion","c":"Asthma","d":"Bronchiectasis","ans":"A"},
{"t":"Pulmonology","q":"Kidney stones in sarcoidosis occur primarily due to which metabolic disturbance?","a":"Hyperkalemia","b":"Hypercalciuria","c":"Hypocalcemia","d":"Infection","ans":"B"},
{"t":"Pulmonology","q":"During follow-up of treated sarcoidosis patients, which monitoring strategy is most appropriate?","a":"ECG only","b":"Hemoglobin only","c":"Serial imaging and ACE levels","d":"WBC count only","ans":"C"},
{"t":"Pulmonology","q":"Spontaneous remission of sarcoidosis most frequently occurs in which stage of pulmonary disease?","a":"Stage IV disease","b":"Neurosarcoidosis","c":"Cardiac sarcoidosis","d":"Stage I disease","ans":"D"},
{"t":"Pulmonology","q":"Pulmonary hypertension is defined as mean pulmonary artery pressure ≥ ___ mmHg at rest on right heart catheterization.","a":"25","b":"30","c":"15","d":"20","ans":"D"},
{"t":"Pulmonology","q":"Most common cause of pulmonary hypertension worldwide?","a":"Idiopathic","b":"Left heart disease","c":"Lung cancer","d":"Congenital heart disease","ans":"B"},
{"t":"Pulmonology","q":"Pulmonary hypertension due to COPD belongs to which WHO group?","a":"Group 4","b":"Group 1","c":"Group 3","d":"Group 2","ans":"C"},
{"t":"Pulmonology","q":"Classic ECG finding in pulmonary hypertension?","a":"ST elevation anterior leads","b":"Right axis deviation","c":"AV block","d":"Left axis deviation","ans":"B"},
{"t":"Pulmonology","q":"P pulmonale on ECG represents:","a":"LV hypertrophy","b":"Pericarditis","c":"Right atrial enlargement","d":"Left atrial enlargement","ans":"C"},
{"t":"Pulmonology","q":"Most definitive diagnostic test for pulmonary hypertension?","a":"CT scan","b":"Chest X-ray","c":"Echocardiography","d":"Right heart catheterization","ans":"D"},
{"t":"Pulmonology","q":"Drug improving survival in idiopathic pulmonary arterial hypertension?","a":"Antihistamines","b":"Endothelin receptor antagonists","c":"Diuretics","d":"Antibiotics","ans":"B"},
{"t":"Pulmonology","q":"Most common symptom of pulmonary hypertension?","a":"Hemoptysis","b":"Fever","c":"Dyspnea on exertion","d":"Chest trauma","ans":"C"},
{"t":"Pulmonology","q":"Echocardiography in pulmonary hypertension primarily estimates:","a":"Renal function","b":"Pulmonary artery pressure","c":"Liver function","d":"Brain perfusion","ans":"B"},
{"t":"Pulmonology","q":"Chest X-ray typical finding in pulmonary hypertension?","a":"Cavitation","b":"Pleural effusion","c":"Small hilum","d":"Enlarged pulmonary arteries","ans":"D"},
{"t":"Pulmonology","q":"A patient with systemic sclerosis develops progressive exertional dyspnea and syncope. Echo suggests pulmonary hypertension. Most likely etiology group?","a":"Group 5","b":"Group 3","c":"Group 1 PAH","d":"Group 2","ans":"C"},
{"t":"Pulmonology","q":"A COPD patient with chronic hypoxia develops pulmonary hypertension. Primary mechanism?","a":"Infection","b":"Hypoxic vasoconstriction","c":"Hypervolemia","d":"Vasodilation","ans":"B"},
{"t":"Pulmonology","q":"ECG shows tall peaked P waves in lead II and V1 in suspected PH patient. Interpretation?","a":"MI","b":"Left atrial enlargement","c":"Ventricular tachycardia","d":"Right atrial enlargement","ans":"D"},
{"t":"Pulmonology","q":"Right ventricular hypertrophy ECG feature:","a":"Deep S in V1","b":"T inversion lateral","c":"Tall R in V1","d":"ST elevation inferior","ans":"C"},
{"t":"Pulmonology","q":"Chronic thromboembolic pulmonary hypertension treatment of choice?","a":"Steroids","b":"Pulmonary endarterectomy","c":"Lifelong oxygen","d":"Antibiotics","ans":"B"},
{"t":"Pulmonology","q":"Initial supportive therapy in pulmonary hypertension with edema?","a":"Antihistamine","b":"Diuretics","c":"Anticoagulant only","d":"Antibiotic","ans":"B"},
{"t":"Pulmonology","q":"Drug class causing pulmonary vasodilation via nitric oxide pathway?","a":"Calcium supplements","b":"Beta blockers","c":"Insulin","d":"PDE-5 inhibitors","ans":"D"},
{"t":"Pulmonology","q":"Syncope in pulmonary hypertension indicates:","a":"Recovery","b":"Infection","c":"Advanced disease","d":"Mild disease","ans":"C"},
{"t":"Pulmonology","q":"Best screening test for suspected pulmonary hypertension?","a":"Lung biopsy","b":"Echocardiography","c":"MRI brain","d":"Right heart catheterization","ans":"B"},
{"t":"Pulmonology","q":"Which drug is contraindicated in pregnancy but used in PAH treatment?","a":"Diuretics","b":"Iron","c":"Oxygen","d":"Bosentan","ans":"D"},
{"t":"Pulmonology","q":"A 35-year-old woman presents with fatigue and exertional dyspnea; ECG shows right axis deviation and RV hypertrophy. Next confirmatory test?","a":"CT brain","b":"Endoscopy","c":"Right heart catheterization","d":"Spirometry","ans":"C"},
{"t":"Pulmonology","q":"A patient with PH develops worsening hypoxia at night due to sleep apnea. Management?","a":"Surgery","b":"Steroids","c":"CPAP therapy","d":"Antibiotics","ans":"C"},
{"t":"Pulmonology","q":"Which auscultatory finding is typical in pulmonary hypertension?","a":"S3 gallop left","b":"Continuous murmur","c":"Opening snap","d":"Loud P2","ans":"D"},
{"t":"Pulmonology","q":"A patient with congenital heart disease develops Eisenmenger syndrome. Cause of PH?","a":"Drug reaction","b":"Hypoglycemia","c":"Left to right shunt reversal","d":"Infection","ans":"C"},
{"t":"Pulmonology","q":"Most important lifestyle advice in pulmonary hypertension?","a":"High altitude travel","b":"High salt diet","c":"Avoid strenuous exertion","d":"Bed rest always","ans":"C"},
{"t":"Pulmonology","q":"Which anticoagulation indication in PH?","a":"Only mild disease","b":"None","c":"All patients","d":"Idiopathic PAH selected cases","ans":"D"},
{"t":"Pulmonology","q":"Mechanism of endothelin receptor antagonist benefit in PH?","a":"Antibiotic effect","b":"Bronchodilation","c":"Vasodilation and antiproliferative","d":"Increase BP","ans":"C"},
{"t":"Pulmonology","q":"Which sign indicates right heart failure in PH?","a":"Jaundice only","b":"Pedal edema","c":"Hematemesis","d":"Hematuria","ans":"B"},
{"t":"Pulmonology","q":"Prostacyclin analog main effect?","a":"Diuresis","b":"Vasoconstriction","c":"Sedation","d":"Vasodilation and platelet inhibition","ans":"D"},
{"t":"Pulmonology","q":"Severe PH refractory to medical therapy — definitive option?","a":"Chemotherapy","b":"Dialysis","c":"Lung transplantation","d":"Antibiotics","ans":"C"},
{"t":"Pulmonology","q":"A patient with progressive dyspnea has ECG showing R/S ratio >1 in V1 and right axis deviation. What does this suggest?","a":"MI","b":"Left ventricular failure","c":"Right ventricular hypertrophy due to pulmonary hypertension","d":"Pericarditis","ans":"C"},
{"t":"Pulmonology","q":"A patient with portal hypertension develops pulmonary hypertension. Condition name?","a":"COPD","b":"Hepatorenal syndrome","c":"Portopulmonary hypertension","d":"Asthma","ans":"C"},
{"t":"Pulmonology","q":"Which WHO group is pulmonary hypertension due to left heart failure?","a":"Group 3","b":"Group 4","c":"Group 1","d":"Group 2","ans":"D"},
{"t":"Pulmonology","q":"PH due to chronic pulmonary emboli — mechanism?","a":"Bronchospasm","b":"Mechanical obstruction of pulmonary vessels","c":"Vasodilation","d":"Hyperventilation","ans":"B"},
{"t":"Pulmonology","q":"Drug improving exercise capacity in PAH?","a":"Iron","b":"Insulin","c":"Sildenafil","d":"Amoxicillin","ans":"C"},
{"t":"Pulmonology","q":"ECG S1Q3T3 pattern indicates:","a":"Pneumonia","b":"Asthma","c":"Acute pulmonary embolism causing PH","d":"MI","ans":"C"},
{"t":"Pulmonology","q":"Main cause of death in pulmonary hypertension?","a":"Stroke","b":"Renal failure","c":"Right heart failure","d":"Liver failure","ans":"C"},
{"t":"Pulmonology","q":"Which oxygen therapy role in PH due to COPD?","a":"Worsens disease","b":"No effect","c":"Reduces pulmonary vasoconstriction","d":"Causes vasoconstriction","ans":"C"},
{"t":"Pulmonology","q":"NT-proBNP elevation in PH indicates:","a":"Anemia","b":"Right ventricular strain","c":"Infection","d":"Liver disease","ans":"B"},
{"t":"Pulmonology","q":"Vasoreactivity testing positive PAH — treatment?","a":"Steroids","b":"Antibiotics","c":"High dose calcium channel blockers","d":"Insulin","ans":"C"},
{"t":"Pulmonology","q":"A young woman with idiopathic PAH deteriorates despite oral therapy. Next escalation?","a":"Antihistamine","b":"IV prostacyclin infusion","c":"Oxygen only","d":"Antibiotics","ans":"B"},
{"t":"Pulmonology","q":"Which finding predicts poor prognosis in PH?","a":"Mild cough","b":"Normal BNP","c":"Syncope","d":"Mild dyspnea","ans":"C"},
{"t":"Pulmonology","q":"PH associated connective tissue disease — commonest?","a":"Gout","b":"Systemic sclerosis","c":"RA","d":"SLE","ans":"B"},
{"t":"Pulmonology","q":"Right ventricular heave location?","a":"Epigastrium","b":"Back","c":"Left parasternal border","d":"Apex","ans":"C"},
{"t":"Pulmonology","q":"Which lab abnormality causes secondary erythrocytosis in PH?","a":"Drug reaction","b":"Bleeding","c":"Infection","d":"Chronic hypoxia","ans":"D"},
{"t":"Pulmonology","q":"PH patient develops hemoptysis — mechanism?","a":"Edema","b":"Rupture bronchial collaterals","c":"Asthma","d":"Infection","ans":"B"},
{"t":"Pulmonology","q":"Which drug improves survival in advanced PAH by continuous infusion?","a":"Digoxin","b":"Aspirin","c":"Epoprostenol","d":"Paracetamol","ans":"C"},
{"t":"Pulmonology","q":"Key investigation before starting advanced therapy in PH?","a":"LFT","b":"CBC","c":"Urine test","d":"Right heart catheterization","ans":"D"},
{"t":"Pulmonology","q":"Functional class assessment in PH commonly uses:","a":"GCS","b":"WHO functional classification","c":"MELD","d":"APGAR","ans":"B"},
{"t":"Pulmonology","q":"Most specific sign of severe pulmonary hypertension on examination?","a":"Stridor","b":"Crackles","c":"Loud P2","d":"Wheeze","ans":"C"},
{"t":"Pulmonology","q":"Most common occupational ILD worldwide due to inhalation of crystalline silica in miners, sandblasters and quarry workers leading to upper lobe nodular fibrosis and eggshell calcification?","a":"Siderosis","b":"Byssinosis","c":"Silicosis","d":"Asbestosis","ans":"C"},
{"t":"Pulmonology","q":"Shipyard worker with progressive dyspnea and pleural plaques on CT chest — most likely exposure?","a":"Iron particles","b":"Asbestos fibers","c":"Cotton dust","d":"Coal dust","ans":"B"},
{"t":"Pulmonology","q":"Farmer exposed to moldy hay presenting with fever, cough and diffuse ground glass opacities — likely diagnosis?","a":"Asthma","b":"COPD","c":"Hypersensitivity pneumonitis","d":"Silicosis","ans":"C"},
{"t":"Pulmonology","q":"Eggshell calcification of hilar lymph nodes is classically seen in:","a":"Talcosis","b":"Silicosis","c":"Asbestosis","d":"Coal workers pneumoconiosis","ans":"B"},
{"t":"Pulmonology","q":"Lower lobe predominant fibrosis with honeycombing in occupational lung disease suggests:","a":"Byssinosis","b":"Silicosis","c":"Siderosis","d":"Asbestosis","ans":"D"},
{"t":"Pulmonology","q":"Most important step in management of occupational ILD?","a":"Bronchodilators only","b":"Remove exposure","c":"Chemotherapy","d":"Antibiotics","ans":"B"},
{"t":"Pulmonology","q":"Asbestos exposure is strongly associated with which malignancy?","a":"Adenoma","b":"Squamous papilloma","c":"Mesothelioma","d":"Small cell carcinoma","ans":"C"},
{"t":"Pulmonology","q":"Coal worker with upper lobe nodules progressing to massive fibrosis — diagnosis?","a":"Emphysema","b":"Progressive massive fibrosis","c":"TB","d":"Asthma","ans":"B"},
{"t":"Pulmonology","q":"Diagnostic test best evaluating interstitial lung disease pattern?","a":"ECG","b":"Ultrasound","c":"Chest X-ray","d":"HRCT chest","ans":"D"},
{"t":"Pulmonology","q":"PFT finding typical in ILD?","a":"Mixed obstructive severe","b":"Normal","c":"Restrictive pattern","d":"Obstructive pattern","ans":"C"},
{"t":"Pulmonology","q":"A 45-year-old stone crusher worker presents with progressive dyspnea, dry cough, reduced DLCO and upper lobe rounded opacities with calcified hilar nodes on HRCT. What complication is he particularly predisposed to?","a":"Bronchiectasis","b":"Tuberculosis","c":"Lung abscess","d":"Asthma","ans":"B"},
{"t":"Pulmonology","q":"A retired insulation factory employee with decades of asbestos exposure presents with pleuritic chest pain, weight loss and unilateral pleural effusion. Most appropriate investigation to confirm suspected malignancy?","a":"ECG","b":"Spirometry","c":"Sputum culture","d":"Pleural biopsy","ans":"D"},
{"t":"Pulmonology","q":"Cotton mill worker experiencing chest tightness and breathlessness worse on first day of work week — disease?","a":"Farmer lung","b":"Asbestosis","c":"Byssinosis","d":"Silicosis","ans":"C"},
{"t":"Pulmonology","q":"Iron worker with metallic dust deposition but no fibrosis — diagnosis?","a":"Talcosis","b":"Asbestosis","c":"Siderosis","d":"Silicosis","ans":"C"},
{"t":"Pulmonology","q":"Most sensitive test for early detection of occupational ILD?","a":"Chest X-ray","b":"HRCT chest","c":"ABG","d":"CBC","ans":"B"},
{"t":"Pulmonology","q":"Asbestosis increases risk of lung cancer especially in:","a":"Non smokers","b":"Children","c":"Women only","d":"Smokers","ans":"D"},
{"t":"Pulmonology","q":"Hypersensitivity pneumonitis acute management?","a":"Anticoagulants","b":"Surgery","c":"Remove antigen exposure","d":"Chemotherapy","ans":"C"},
{"t":"Pulmonology","q":"Most characteristic pleural manifestation of asbestos exposure?","a":"Hemothorax","b":"Effusion only","c":"Pleural plaques","d":"Pneumothorax","ans":"C"},
{"t":"Pulmonology","q":"DLCO in interstitial lung disease typically:","a":"Variable high","b":"Normal high","c":"Increased","d":"Decreased","ans":"D"},
{"t":"Pulmonology","q":"Drug used in progressive fibrosing ILD to slow decline?","a":"Salbutamol","b":"Furosemide","c":"Nintedanib","d":"Amoxicillin","ans":"C"},
{"t":"Pulmonology","q":"A farmer presents with repeated episodes of fever, malaise, cough and dyspnea hours after entering a barn with moldy hay; symptoms improve on weekends. Most appropriate long-term management?","a":"Anticoagulation","b":"Lung resection","c":"Permanent antigen avoidance and corticosteroids if needed","d":"Lifelong antibiotics","ans":"C"},
{"t":"Pulmonology","q":"A welder exposed to iron dust develops benign radiographic opacities without functional impairment. Best management?","a":"Oxygen therapy","b":"Reassurance and exposure control","c":"Steroids lifelong","d":"Chemotherapy","ans":"B"},
{"t":"Pulmonology","q":"Beryllium exposure disease resembling sarcoidosis is called:","a":"Farmer lung","b":"Talcosis","c":"Chronic berylliosis","d":"Silicosis","ans":"C"},
{"t":"Pulmonology","q":"Which occupational lung disease causes restrictive defect and pleural plaques?","a":"Bronchitis","b":"Asthma","c":"Asbestosis","d":"COPD","ans":"C"},
{"t":"Pulmonology","q":"Complication of progressive massive fibrosis leads to:","a":"Pancreatitis","b":"Stroke","c":"Pulmonary hypertension","d":"Renal failure","ans":"C"},
{"t":"Pulmonology","q":"A sandblaster with acute respiratory distress weeks after massive silica exposure — condition?","a":"Byssinosis","b":"Talcosis","c":"Chronic silicosis","d":"Acute silicosis","ans":"D"},
{"t":"Pulmonology","q":"Most common radiologic zone affected in silicosis?","a":"Middle lobe","b":"Upper lobes","c":"Pleura only","d":"Lower lobes","ans":"B"},
{"t":"Pulmonology","q":"Bronchoalveolar lavage in hypersensitivity pneumonitis shows:","a":"RBC predominance","b":"Eosinophilia","c":"Lymphocytosis","d":"Neutrophilia","ans":"C"},
{"t":"Pulmonology","q":"Asbestosis latency period typically:","a":"Months","b":"Weeks","c":"Days","d":"Decades","ans":"D"},
{"t":"Pulmonology","q":"Primary prevention of occupational lung disease:","a":"Vaccination only","b":"Steroids","c":"PPE and ventilation control","d":"Antibiotics","ans":"C"},
{"t":"Pulmonology","q":"A 58-year-old construction worker with 30 years asbestos exposure presents with progressive dyspnea, basal crackles, clubbing, restrictive PFT and lower lobe honeycombing on HRCT. Most appropriate counseling?","a":"No follow up needed","b":"Acute infection","c":"Disease reversible with bronchodilators","d":"Progressive fibrosis; smoking cessation and monitoring malignancy risk","ans":"D"},
{"t":"Pulmonology","q":"Talcosis is commonly seen in:","a":"Farmers","b":"IV drug users","c":"Teachers","d":"Bakers","ans":"B"},
{"t":"Pulmonology","q":"Key diagnostic feature of hypersensitivity pneumonitis on HRCT:","a":"Pleural effusion","b":"Centrilobular nodules","c":"Mass lesion","d":"Cavitation","ans":"B"},
{"t":"Pulmonology","q":"Which occupational exposure causes hard metal lung disease?","a":"Zinc","b":"Lead","c":"Cobalt","d":"Copper","ans":"C"},
{"t":"Pulmonology","q":"End stage ILD definitive treatment?","a":"Steroids only","b":"Lung transplantation","c":"Oxygen only","d":"Antibiotics","ans":"B"},
{"t":"Pulmonology","q":"Chronic hypersensitivity pneumonitis leads to:","a":"Bronchitis","b":"Asthma cure","c":"Fibrosis","d":"Pneumothorax only","ans":"C"},
{"t":"Pulmonology","q":"Most useful occupational history element?","a":"Family income","b":"Travel history","c":"Duration and exposure intensity","d":"Diet history","ans":"C"},
{"t":"Pulmonology","q":"Pleural plaques significance?","a":"Pneumonia","b":"Cancer metastasis","c":"TB infection","d":"Marker of asbestos exposure","ans":"D"},
{"t":"Pulmonology","q":"Restrictive PFT shows:","a":"Increased RV","b":"Normal DLCO","c":"Reduced TLC","d":"Increased TLC","ans":"C"},
{"t":"Pulmonology","q":"Chronic silicosis increases risk of:","a":"Bronchitis","b":"Asthma","c":"Pneumonia only","d":"Tuberculosis","ans":"D"},
{"t":"Pulmonology","q":"A poultry worker develops progressive dyspnea and fibrosis after years of antigen exposure. Which stage has developed and what is main management?","a":"Subacute; antibiotics","b":"Asthma stage","c":"Chronic fibrotic stage; avoid exposure and consider antifibrotic therapy","d":"Acute stage; bronchodilator","ans":"C"},
{"t":"Pulmonology","q":"Occupational asthma vs hypersensitivity pneumonitis — key difference?","a":"Asthma causes nodules","b":"HP causes systemic symptoms","c":"HP reversible instantly","d":"Asthma causes fibrosis","ans":"B"},
{"t":"Pulmonology","q":"Radiologic honeycombing indicates:","a":"Infection","b":"End stage fibrosis","c":"Edema","d":"Acute inflammation","ans":"B"},
{"t":"Pulmonology","q":"Which occupation has the highest asbestos exposure risk?","a":"Farmers","b":"Drivers","c":"Teachers","d":"Shipyard workers","ans":"D"},
{"t":"Pulmonology","q":"Most common symptom in ILD overall?","a":"Syncope","b":"Diarrhea","c":"Progressive dyspnea","d":"Hematemesis","ans":"C"},
{"t":"Pulmonology","q":"Early detection surveillance for exposed workers includes:","a":"Colonoscopy","b":"ECG only","c":"MRI brain","d":"Periodic spirometry and imaging","ans":"D"},
{"t":"Pulmonology","q":"Chronic berylliosis diagnostic test:","a":"Troponin","b":"D-dimer","c":"Beryllium lymphocyte proliferation test","d":"Mantoux","ans":"C"},
{"t":"Pulmonology","q":"Oxygen therapy indication in ILD:","a":"Mild cough","b":"Headache","c":"Resting hypoxemia","d":"Fever","ans":"C"},
{"t":"Pulmonology","q":"Major cause of death in advanced ILD:","a":"Liver disease","b":"Stroke","c":"Respiratory failure","d":"Renal failure","ans":"C"},
{"t":"Pulmonology","q":"Key management principle in occupational lung disease programs:","a":"Surgery","b":"Prevention and workplace control","c":"Chemotherapy","d":"Antibiotics","ans":"B"},
{"t":"Pulmonology","q":"Most common cause of chronic cough in non-smoker with normal chest X-ray?","a":"Upper airway cough syndrome","b":"TB","c":"Bronchiectasis","d":"Lung cancer","ans":"A"},
{"t":"Pulmonology","q":"Clubbing is classically seen in:","a":"Acute bronchitis","b":"URTI","c":"Asthma","d":"Bronchiectasis","ans":"D"},
{"t":"Pulmonology","q":"Gold standard test for diagnosing obstructive sleep apnea?","a":"Chest X-ray","b":"Spirometry","c":"Polysomnography","d":"ABG","ans":"C"},
{"t":"Pulmonology","q":"Blue bloater phenotype belongs to:","a":"Asthma","b":"ILD","c":"Chronic bronchitis","d":"Emphysema","ans":"C"},
{"t":"Pulmonology","q":"Primary mechanism of hypoxemia in pneumonia:","a":"Decreased perfusion","b":"Hypoventilation","c":"V/Q mismatch","d":"Diffusion defect only","ans":"C"},
{"t":"Pulmonology","q":"Massive hemoptysis definition approximately:","a":">10 ml/day","b":">300 ml/day","c":">50 ml/day","d":">100 ml/day","ans":"B"},
{"t":"Pulmonology","q":"First investigation in suspected lung cancer:","a":"MRI brain","b":"Bronchoscopy","c":"Chest X-ray","d":"PET scan","ans":"C"},
{"t":"Pulmonology","q":"Reversible airflow limitation hallmark disease:","a":"Fibrosis","b":"Bronchiectasis","c":"Asthma","d":"COPD","ans":"C"},
{"t":"Pulmonology","q":"Most common organism in community acquired pneumonia:","a":"Pseudomonas","b":"Streptococcus pneumoniae","c":"Klebsiella","d":"Mycoplasma","ans":"B"},
{"t":"Pulmonology","q":"Hyperresonant percussion note suggests:","a":"Pleural effusion","b":"Fibrosis","c":"Consolidation","d":"Pneumothorax","ans":"D"},
{"t":"Pulmonology","q":"Indication for long-term oxygen therapy in COPD:","a":"Normal saturation","b":"Mild cough","c":"PaO₂ ≤55 mmHg","d":"PaO₂ 90 mmHg","ans":"C"},
{"t":"Pulmonology","q":"Most sensitive test for pulmonary embolism:","a":"ECG","b":"D-dimer","c":"Chest X-ray","d":"CT pulmonary angiography","ans":"D"},
{"t":"Pulmonology","q":"Most common complication of pneumonia:","a":"PE","b":"Asthma","c":"Empyema","d":"Pneumothorax","ans":"C"},
{"t":"Pulmonology","q":"Bronchial breath sounds indicate:","a":"COPD","b":"Pneumothorax","c":"Consolidation","d":"Pleural effusion","ans":"C"},
{"t":"Pulmonology","q":"Drug of choice in acute anaphylaxis with bronchospasm:","a":"Antihistamine","b":"Adrenaline IM","c":"Steroids only","d":"Salbutamol","ans":"B"},
{"t":"Pulmonology","q":"Primary pathology in emphysema:","a":"Infection","b":"Bronchial mucus","c":"Fibrosis","d":"Alveolar wall destruction","ans":"D"},
{"t":"Pulmonology","q":"DLCO decreased markedly in:","a":"URTI","b":"Bronchitis","c":"Emphysema","d":"Asthma","ans":"C"},
{"t":"Pulmonology","q":"Pleural effusion best initial investigation:","a":"Bronchoscopy","b":"Spirometry","c":"CT chest","d":"Diagnostic thoracentesis","ans":"D"},
{"t":"Pulmonology","q":"Most common cause of secondary spontaneous pneumothorax:","a":"TB","b":"COPD","c":"Asthma","d":"Pneumonia","ans":"B"},
{"t":"Pulmonology","q":"Hoarseness in lung cancer indicates involvement of:","a":"Phrenic nerve","b":"Intercostal nerve","c":"Recurrent laryngeal nerve","d":"Vagus nerve","ans":"C"},
{"t":"Pulmonology","q":"A 65-year-old smoker presents with chronic cough, weight loss and hemoptysis. Chest X-ray shows hilar mass. Most likely diagnosis?","a":"Asthma","b":"TB","c":"Bronchiectasis","d":"Lung carcinoma","ans":"D"},
{"t":"Pulmonology","q":"A young tall thin male presents with sudden chest pain and dyspnea after exercise; hyperresonance on exam. Diagnosis?","a":"Asthma","b":"Pleural effusion","c":"Primary spontaneous pneumothorax","d":"Pneumonia","ans":"C"},
{"t":"Pulmonology","q":"A COPD patient develops drowsiness after oxygen therapy. Mechanism?","a":"CO₂ retention","b":"Drug allergy","c":"Metabolic acidosis","d":"Infection","ans":"A"},
{"t":"Pulmonology","q":"A patient with fever and productive cough shows lobar consolidation. Most likely pathology?","a":"Fibrosis","b":"Bronchospasm","c":"Alveolar filling","d":"Interstitial inflammation","ans":"C"},
{"t":"Pulmonology","q":"A TB patient develops sudden breathlessness and absent breath sounds. Complication?","a":"PE","b":"Bronchitis","c":"Pneumothorax","d":"Asthma","ans":"C"},
{"t":"Pulmonology","q":"A child with barking cough and stridor — likely disease?","a":"Pneumonia","b":"Asthma","c":"Bronchiolitis","d":"Croup","ans":"D"},
{"t":"Pulmonology","q":"A patient with morning headache, obesity and daytime sleepiness — diagnosis?","a":"ILD","b":"OSA","c":"TB","d":"COPD","ans":"B"},
{"t":"Pulmonology","q":"A pneumonia patient with confusion and hypotension — high mortality score used?","a":"GCS","b":"APGAR","c":"CURB-65","d":"CHADS2","ans":"C"},
{"t":"Pulmonology","q":"A worker exposed to birds develops granulomatous lung disease — diagnosis?","a":"Cancer","b":"COPD","c":"Hypersensitivity pneumonitis","d":"Silicosis","ans":"C"},
{"t":"Pulmonology","q":"A patient with chest trauma develops tracheal deviation and hypotension — cause?","a":"Bronchitis","b":"Asthma","c":"Tension pneumothorax","d":"Pleural effusion","ans":"C"},
{"t":"Pulmonology","q":"A 58-year-old heavy smoker presents with progressive dyspnea, barrel chest, decreased breath sounds and FEV1/FVC 0.5 with increased TLC. Which pathophysiologic change best explains his symptoms?","a":"Pleural thickening","b":"Restrictive fibrosis","c":"Acute infection","d":"Air trapping due to loss of elastic recoil","ans":"D"},
{"t":"Pulmonology","q":"A hospitalized patient suddenly develops tachycardia, hypoxia and pleuritic chest pain; ECG sinus tachycardia and ABG respiratory alkalosis. Most appropriate immediate diagnostic step?","a":"Bronchoscopy","b":"CT pulmonary angiography","c":"MRI brain","d":"Sputum culture","ans":"B"},
{"t":"Pulmonology","q":"A patient treated for pneumonia continues fever after 72 hours and ultrasound reveals loculated pleural fluid. Best management?","a":"Oxygen","b":"Bronchodilator","c":"Chest tube drainage","d":"Antibiotics only","ans":"C"},
{"t":"Pulmonology","q":"A 30-year-old with acute asthma shows rising PaCO₂ after initial hypocapnia. Significance?","a":"Hyperventilation","b":"Anxiety","c":"Recovery","d":"Respiratory fatigue impending failure","ans":"D"},
{"t":"Pulmonology","q":"A COPD patient with PaO₂ 50 mmHg — which therapy improves survival?","a":"Diuretics","b":"Steroids","c":"Long-term oxygen therapy","d":"Antibiotics","ans":"C"},
{"t":"Pulmonology","q":"A lung cancer patient develops hypercalcemia due to PTHrP secretion — tumor type?","a":"Small cell carcinoma","b":"Carcinoid","c":"Squamous cell carcinoma","d":"Adenocarcinoma","ans":"C"},
{"t":"Pulmonology","q":"A patient aspirates gastric contents during anesthesia and develops hypoxia within hours. Pathology?","a":"Bronchiectasis","b":"Chemical pneumonitis","c":"Asthma","d":"TB","ans":"B"},
{"t":"Pulmonology","q":"A 40-year-old presents with chronic productive cough and recurrent infections since childhood; HRCT shows dilated bronchi. Diagnosis?","a":"ILD","b":"COPD","c":"Bronchiectasis","d":"Asthma","ans":"C"},
{"t":"Pulmonology","q":"A patient with pulmonary fibrosis develops loud P2 and edema. Mechanism?","a":"Asthma","b":"MI","c":"Pulmonary hypertension causing cor pulmonale","d":"Pneumonia","ans":"C"},
{"t":"Pulmonology","q":"A ventilated patient suddenly becomes hypotensive with absent breath sounds one side and high airway pressure. Immediate action?","a":"Sedation","b":"Increase oxygen","c":"Antibiotics","d":"Needle decompression","ans":"D"},
{"t":"Pulmonology","q":"A 63-year-old smoker presents with apical lung mass, shoulder pain radiating to arm with ptosis and miosis. Which syndrome is present?","a":"TB — apical fibrosis","b":"Superior vena cava syndrome — venous obstruction","c":"Asthma — bronchospasm","d":"Pancoast tumor — brachial plexus and sympathetic chain involvement","ans":"D"},
{"t":"Pulmonology","q":"A patient with pancreatitis develops refractory hypoxemia, bilateral infiltrates and PaO₂/FiO₂ ratio 120. Which ventilatory strategy improves survival?","a":"Hyperventilation","b":"Low tidal volume lung protective ventilation","c":"Oxygen by mask only","d":"High tidal volume ventilation","ans":"B"},
{"t":"Pulmonology","q":"A young adult with fever, dry cough, minimal CXR changes, normal WBC and hemolytic anemia due to cold agglutinins. Most appropriate therapy?","a":"Antifungal","b":"Anti TB drugs","c":"Macrolide antibiotic","d":"Penicillin","ans":"C"},
{"t":"Pulmonology","q":"A 70-year-old COPD patient develops confusion after high flow oxygen; ABG shows pH 7.28 PaCO₂ 70. Best immediate management?","a":"Intubate immediately all cases","b":"Diuretics","c":"Stop oxygen completely","d":"Controlled oxygen and non-invasive ventilation","ans":"D"},
{"t":"Pulmonology","q":"A patient with longstanding rheumatoid arthritis develops progressive dyspnea, dry cough and bibasal crackles; HRCT honeycombing and restrictive PFT. Diagnosis?","a":"Pneumonia","b":"Asthma","c":"Interstitial lung disease secondary to connective tissue disease","d":"COPD","ans":"C"},
{"t":"Pulmonology","q":"A trauma patient immobilized for 2 weeks develops sudden collapse; echo shows RV dilation and hypotension. Immediate lifesaving therapy?","a":"Diuretics","b":"Systemic thrombolysis","c":"Bronchodilator","d":"Antibiotics","ans":"B"},
{"t":"Pulmonology","q":"A patient with severe pneumonia becomes hypotensive, febrile and hypoxic requiring vasopressors; lactate elevated. Underlying cause of respiratory failure?","a":"COPD exacerbation","b":"Asthma","c":"Pneumothorax","d":"Septic shock with ARDS","ans":"D"},
{"t":"Pulmonology","q":"A middle-aged man with untreated OSA develops daytime somnolence, polycythemia and pulmonary hypertension. Mechanism causing erythrocytosis?","a":"Drug toxicity","b":"Hemolysis","c":"Chronic hypoxia stimulating erythropoietin","d":"Infection","ans":"C"},
{"t":"Pulmonology","q":"A patient with massive hemoptysis from bronchiectasis arrives unstable. First priority management?","a":"Antibiotics","b":"CT scan","c":"Airway protection and positioning bleeding lung down","d":"Bronchodilator","ans":"C"},
{"t":"Pulmonology","q":"A critically ill ventilated patient develops increasing plateau pressure and subcutaneous emphysema after high PEEP therapy. Most likely complication and management?","a":"Pulmonary edema — diuretics","b":"Asthma — bronchodilator","c":"Barotrauma pneumothorax — reduce pressure and decompress","d":"Pneumonia — antibiotics","ans":"C"},
{"t":"Pulmonology","q":"A 45-year-old woman with systemic sclerosis develops progressive exertional dyspnoea and a loud P2 on auscultation. Most likely diagnosis:","a":"Pulmonary fibrosis","b":"Pleural effusion","c":"Pulmonary arterial hypertension","d":"COPD","ans":"C"},
{"t":"Pulmonology","q":"A ventilated ARDS patient has PaO2/FiO2 ratio of 90 mmHg despite optimised settings. Next best step:","a":"Increase FiO2 to 100%","b":"Increase tidal volume","c":"Add vasopressors","d":"Prone positioning for 16 hours","ans":"D"}
];