window.MM=window.MM||{};
window.MM.med_p2_hepato=[
{"t":"Hepatology","q":"Predominant bilirubin raised in hemolytic jaundice is","a":"Conjugated","b":"Unconjugated","c":"Delta bilirubin","d":"Biliverdin","ans":"B"},
{"t":"Hepatology","q":"Gilbert syndrome is caused by","a":"Complete absence of UGT","b":"Mild reduction of UGT activity","c":"Bile duct obstruction","d":"Hemolysis","ans":"B"},
{"t":"Hepatology","q":"Patient with jaundice, dark urine and pale stool most likely has","a":"Hemolysis","b":"Obstructive jaundice","c":"Gilbert syndrome","d":"Neonatal physiologic jaundice","ans":"B"},
{"t":"Hepatology","q":"Dubin-Johnson syndrome involves defect in","a":"Conjugation","b":"Uptake","c":"Canalicular excretion","d":"Hemoglobin breakdown","ans":"C"},
{"t":"Hepatology","q":"Liver appearance in Dubin-Johnson syndrome","a":"Fatty yellow","b":"Greenish","c":"Black pigmented","d":"Nodular cirrhotic","ans":"C"},
{"t":"Hepatology","q":"Rotor syndrome differs from Dubin-Johnson because","a":"No pigmentation","b":"Severe hemolysis","c":"Biliary atresia","d":"Increased ALP","ans":"A"},
{"t":"Hepatology","q":"Increased urinary urobilinogen occurs in","a":"Obstructive jaundice","b":"Hemolytic jaundice","c":"Dubin-Johnson syndrome","d":"Rotor syndrome","ans":"B"},
{"t":"Hepatology","q":"Absent urobilinogen in urine suggests","a":"Hepatitis","b":"Hemolysis","c":"Biliary obstruction","d":"Gilbert syndrome","ans":"C"},
{"t":"Hepatology","q":"Kernicterus occurs due to increase in","a":"Conjugated bilirubin","b":"Unconjugated bilirubin","c":"Bile salts","d":"Urobilinogen","ans":"B"},
{"t":"Hepatology","q":"Most sensitive enzyme for cholestasis","a":"AST","b":"ALT","c":"ALP","d":"CK","ans":"C"},
{"t":"Hepatology","q":"A young man develops jaundice during fasting; labs normal except mild indirect bilirubin rise. Diagnosis","a":"Hemolysis","b":"Gilbert syndrome","c":"Rotor syndrome","d":"Biliary stone","ans":"B"},
{"t":"Hepatology","q":"Hemolytic jaundice lab profile shows","a":"High conjugated bilirubin","b":"High indirect bilirubin","c":"Low LDH","d":"Low reticulocyte count","ans":"B"},
{"t":"Hepatology","q":"Pale stool occurs due to absence of","a":"Urobilinogen","b":"Stercobilin","c":"Biliverdin","d":"Albumin","ans":"B"},
{"t":"Hepatology","q":"Dark urine in jaundice indicates presence of","a":"Unconjugated bilirubin","b":"Conjugated bilirubin","c":"Hemoglobin only","d":"Myoglobin","ans":"B"},
{"t":"Hepatology","q":"Newborn with severe unconjugated hyperbilirubinemia due to absent UGT has","a":"Crigler-Najjar type I","b":"Gilbert syndrome","c":"Rotor syndrome","d":"Dubin-Johnson syndrome","ans":"A"},
{"t":"Hepatology","q":"A patient has conjugated hyperbilirubinemia but normal liver enzymes and black liver on biopsy. Diagnosis","a":"Rotor syndrome","b":"Dubin-Johnson syndrome","c":"Hemolysis","d":"Viral hepatitis","ans":"B"},
{"t":"Hepatology","q":"Increased LDH and reticulocyte count suggest","a":"Obstructive jaundice","b":"Hemolytic jaundice","c":"Gilbert syndrome","d":"Rotor syndrome","ans":"B"},
{"t":"Hepatology","q":"Pruritus is most prominent in","a":"Hemolytic jaundice","b":"Obstructive jaundice","c":"Gilbert syndrome","d":"Neonatal jaundice","ans":"B"},
{"t":"Hepatology","q":"Fat malabsorption occurs in","a":"Hemolytic jaundice","b":"Obstructive jaundice","c":"Gilbert syndrome","d":"Rotor syndrome","ans":"B"},
{"t":"Hepatology","q":"Clay colored stool is due to lack of","a":"Bile salts in intestine","b":"Bilirubin production","c":"Hemoglobin breakdown","d":"Albumin synthesis","ans":"A"},
{"t":"Hepatology","q":"A student notices mild scleral icterus during stress, labs normal. Best management","a":"Surgery","b":"Reassurance","c":"Steroids","d":"Antibiotics","ans":"B"},
{"t":"Hepatology","q":"Conjugated bilirubin is water soluble therefore","a":"Not filtered in kidney","b":"Appears in urine","c":"Causes kernicterus","d":"Binds albumin tightly","ans":"B"},
{"t":"Hepatology","q":"Major cause of increased indirect bilirubin in adults","a":"Hemolysis","b":"Gallstones","c":"Cholangiocarcinoma","d":"Pancreatic cancer","ans":"A"},
{"t":"Hepatology","q":"A patient with jaundice has high ALP and GGT. Likely pathology","a":"Hemolysis","b":"Cholestasis","c":"Gilbert syndrome","d":"Rotor syndrome","ans":"B"},
{"t":"Hepatology","q":"Urobilinogen formation occurs in","a":"Liver","b":"Intestine","c":"Kidney","d":"Pancreas","ans":"B"},
{"t":"Hepatology","q":"Dubin-Johnson syndrome inheritance pattern","a":"Autosomal recessive","b":"Autosomal dominant","c":"X-linked","d":"Mitochondrial","ans":"A"},
{"t":"Hepatology","q":"Rotor syndrome bilirubin pattern","a":"Only indirect","b":"Only direct","c":"Mixed conjugated","d":"No bilirubin rise","ans":"C"},
{"t":"Hepatology","q":"Obstructive jaundice causes deficiency of","a":"Vitamin C","b":"Fat soluble vitamins","c":"Iron","d":"Folate","ans":"B"},
{"t":"Hepatology","q":"A child with anemia, splenomegaly and jaundice most likely has","a":"Hemolytic jaundice","b":"Obstructive jaundice","c":"Gilbert syndrome","d":"Rotor syndrome","ans":"A"},
{"t":"Hepatology","q":"Best initial imaging for obstructive jaundice","a":"Ultrasound","b":"MRI brain","c":"CT chest","d":"Colonoscopy","ans":"A"},
{"t":"Hepatology","q":"Conjugation of bilirubin occurs in","a":"Kupffer cells","b":"Hepatocytes smooth ER","c":"Kidney tubules","d":"RBCs","ans":"B"},
{"t":"Hepatology","q":"A patient has painless jaundice and pruritus with high ALP. Most probable cause","a":"Hemolysis","b":"Biliary obstruction","c":"Gilbert syndrome","d":"Viral infection only","ans":"B"},
{"t":"Hepatology","q":"Indirect bilirubin binds strongly to","a":"Albumin","b":"Globulin","c":"Hemoglobin","d":"Fibrinogen","ans":"A"},
{"t":"Hepatology","q":"Main complication of prolonged obstructive jaundice","a":"Polycythemia","b":"Bleeding tendency","c":"Hypernatremia","d":"Hypercalcemia","ans":"B"},
{"t":"Hepatology","q":"Neonatal physiologic jaundice due to","a":"Increased RBC turnover","b":"Gallstones","c":"Pancreatitis","d":"Hepatic tumor","ans":"A"},
{"t":"Hepatology","q":"A patient has conjugated bilirubin in urine but normal colored stool. Likely condition","a":"Dubin-Johnson","b":"Complete obstruction","c":"Hemolysis","d":"Crigler-Najjar","ans":"A"},
{"t":"Hepatology","q":"Elevated stercobilinogen in stool occurs in","a":"Hemolysis","b":"Obstruction","c":"Rotor syndrome","d":"Neonatal cholestasis","ans":"A"},
{"t":"Hepatology","q":"Phototherapy works by","a":"Increasing conjugation","b":"Converting bilirubin to soluble isomers","c":"Increasing ALP","d":"Blocking hemolysis","ans":"B"},
{"t":"Hepatology","q":"Main pigment responsible for yellow discoloration in jaundice","a":"Bilirubin","b":"Hemoglobin","c":"Iron","d":"Melanin","ans":"A"},
{"t":"Hepatology","q":"A patient with fever, RUQ pain and jaundice has","a":"Charcot triad cholangitis","b":"Hemolysis","c":"Gilbert syndrome","d":"Rotor syndrome","ans":"A"},
{"t":"Hepatology","q":"High conjugated bilirubin with normal AST/ALT suggests","a":"Hemolysis","b":"Hereditary excretion defect","c":"Viral hepatitis","d":"Muscle injury","ans":"B"},
{"t":"Hepatology","q":"Gallstones commonly cause","a":"Prehepatic jaundice","b":"Posthepatic jaundice","c":"Physiologic jaundice","d":"Hemolytic crisis","ans":"B"},
{"t":"Hepatology","q":"In hemolysis stool color becomes","a":"Pale","b":"Dark","c":"White","d":"Clay","ans":"B"},
{"t":"Hepatology","q":"A fasting-induced bilirubin rise with normal labs indicates","a":"Gilbert syndrome","b":"Pancreatic cancer","c":"Obstruction","d":"Hepatitis","ans":"A"},
{"t":"Hepatology","q":"Cholestatic enzymes include","a":"ALP and GGT","b":"CK and LDH","c":"Troponin and CKMB","d":"Amylase and lipase","ans":"A"},
{"t":"Hepatology","q":"Indirect bilirubin cannot appear in urine because","a":"Insoluble in water","b":"Bound to bile salts","c":"Metabolized in kidney","d":"Converted to urea","ans":"A"},
{"t":"Hepatology","q":"A neonate with severe kernicterus risk should receive","a":"Phototherapy","b":"Antihistamine","c":"Antacid","d":"Insulin","ans":"A"},
{"t":"Hepatology","q":"Rotor syndrome liver histology is","a":"Normal","b":"Fatty","c":"Necrotic","d":"Fibrotic","ans":"A"},
{"t":"Hepatology","q":"Jaundice appearing first in sclera occurs because","a":"High elastin affinity","b":"High collagen","c":"High fat","d":"High keratin","ans":"A"},
{"t":"Hepatology","q":"A patient with pruritus, steatorrhea, pale stool and high ALP most likely has","a":"Hemolytic jaundice","b":"Obstructive jaundice","c":"Gilbert syndrome","d":"Crigler-Najjar type II","ans":"B"},
{"t":"Hepatology","q":"Hepatitis A is primarily transmitted by","a":"Blood transfusion","b":"Feco-oral route","c":"Sexual contact only","d":"Needle sharing only","ans":"B"},
{"t":"Hepatology","q":"Marker of acute Hepatitis B infection","a":"Anti-HBs","b":"HBsAg","c":"Anti-HBc IgM","d":"Anti-HBe","ans":"C"},
{"t":"Hepatology","q":"Chronic hepatitis is defined as inflammation lasting more than","a":"2 weeks","b":"1 month","c":"3 months","d":"6 months","ans":"D"},
{"t":"Hepatology","q":"Hepatitis D virus requires presence of","a":"HAV","b":"HBV","c":"HCV","d":"HEV","ans":"B"},
{"t":"Hepatology","q":"Most common cause of post-transfusion hepatitis worldwide","a":"HAV","b":"HBV","c":"HCV","d":"HEV","ans":"C"},
{"t":"Hepatology","q":"Fulminant hepatic failure is most commonly associated with","a":"Hepatitis A","b":"Hepatitis E (pregnancy)","c":"Hepatitis C","d":"Alcoholic hepatitis","ans":"B"},
{"t":"Hepatology","q":"Drug classically causing dose-dependent hepatic necrosis","a":"Isoniazid","b":"Paracetamol","c":"Methotrexate","d":"Valproate","ans":"B"},
{"t":"Hepatology","q":"Antidote for paracetamol toxicity","a":"Atropine","b":"Naloxone","c":"N-acetylcysteine","d":"Flumazenil","ans":"C"},
{"t":"Hepatology","q":"Wilson disease involves abnormal accumulation of","a":"Iron","b":"Copper","c":"Zinc","d":"Lead","ans":"B"},
{"t":"Hepatology","q":"Hemochromatosis leads to deposition of","a":"Glycogen","b":"Iron","c":"Calcium","d":"Copper","ans":"B"},
{"t":"Hepatology","q":"A child presents with acute jaundice, fever and markedly raised ALT after contaminated water exposure. Diagnosis","a":"Hepatitis A","b":"Hepatitis B","c":"Hepatitis C","d":"Autoimmune hepatitis","ans":"A"},
{"t":"Hepatology","q":"A nurse has needle-stick injury from HBV positive patient. First investigation","a":"ALT","b":"HBsAg","c":"Anti-HBs titer","d":"Bilirubin","ans":"C"},
{"t":"Hepatology","q":"Patient has HBsAg positive >6 months and HBV DNA positive. Diagnosis","a":"Acute hepatitis B","b":"Chronic hepatitis B","c":"Carrier state","d":"Resolved infection","ans":"B"},
{"t":"Hepatology","q":"Which antibody indicates recovery and immunity in HBV","a":"Anti-HBs","b":"Anti-HBc IgM","c":"HBeAg","d":"HBsAg","ans":"A"},
{"t":"Hepatology","q":"A dialysis patient develops chronic hepatitis with mild symptoms. Most probable virus","a":"HAV","b":"HBV","c":"HCV","d":"HEV","ans":"C"},
{"t":"Hepatology","q":"Young female with jaundice, arthralgia and ANA positive most likely has","a":"Viral hepatitis","b":"Autoimmune hepatitis","c":"Wilson disease","d":"Alcoholic hepatitis","ans":"B"},
{"t":"Hepatology","q":"Kayser-Fleischer rings are seen in","a":"Hemochromatosis","b":"Wilson disease","c":"Hepatitis B","d":"Hepatitis A","ans":"B"},
{"t":"Hepatology","q":"Low ceruloplasmin suggests","a":"Hemochromatosis","b":"Wilson disease","c":"Autoimmune hepatitis","d":"Alcoholic liver disease","ans":"B"},
{"t":"Hepatology","q":"Bronze diabetes occurs in","a":"Wilson disease","b":"Hemochromatosis","c":"Hepatitis C","d":"Autoimmune hepatitis","ans":"B"},
{"t":"Hepatology","q":"Treatment of hemochromatosis","a":"Chelation with penicillamine","b":"Phlebotomy","c":"Steroids","d":"Antivirals","ans":"B"},
{"t":"Hepatology","q":"A pregnant woman develops fulminant hepatic failure after travel to endemic area. Virus","a":"HAV","b":"HBV","c":"HCV","d":"HEV","ans":"D"},
{"t":"Hepatology","q":"HBeAg positivity indicates","a":"Immunity","b":"High infectivity","c":"Recovery","d":"Vaccination","ans":"B"},
{"t":"Hepatology","q":"A patient has anti-HCV antibodies positive. Next step","a":"Start treatment immediately","b":"Check HCV RNA PCR","c":"Repeat antibody after 1 year","d":"Liver biopsy first","ans":"B"},
{"t":"Hepatology","q":"Chronic hepatitis C major complication","a":"Acute pancreatitis","b":"Cirrhosis","c":"Nephrotic syndrome only","d":"Peptic ulcer","ans":"B"},
{"t":"Hepatology","q":"Drug causing autoimmune-like hepatitis","a":"Nitrofurantoin","b":"Paracetamol","c":"Aspirin","d":"Omeprazole","ans":"A"},
{"t":"Hepatology","q":"AST:ALT ratio >2 suggests","a":"Viral hepatitis","b":"Alcoholic hepatitis","c":"Wilson disease","d":"Hemochromatosis","ans":"B"},
{"t":"Hepatology","q":"A young man has tremors, psychiatric symptoms and hepatitis. Diagnosis","a":"Autoimmune hepatitis","b":"Wilson disease","c":"Hemochromatosis","d":"Hepatitis A","ans":"B"},
{"t":"Hepatology","q":"Penicillamine is treatment for","a":"Hemochromatosis","b":"Wilson disease","c":"Hepatitis C","d":"Autoimmune hepatitis","ans":"B"},
{"t":"Hepatology","q":"Anti-smooth muscle antibody is associated with","a":"Hepatitis A","b":"Hepatitis B","c":"Autoimmune hepatitis","d":"Hemochromatosis","ans":"C"},
{"t":"Hepatology","q":"Steroids are treatment of choice in","a":"Viral hepatitis","b":"Autoimmune hepatitis","c":"Wilson disease","d":"Drug toxicity","ans":"B"},
{"t":"Hepatology","q":"A 24-year-old medical student received complete HBV vaccination in childhood. After needle stick injury from HBsAg positive patient his labs show: HBsAg negative, Anti-HBc negative, Anti-HBs 150 IU/L, normal ALT. What is the most appropriate management?","a":"Start tenofovir immediately","b":"Give hepatitis B immunoglobulin","c":"No treatment required","d":"Repeat vaccine series","ans":"C"},
{"t":"Hepatology","q":"A 32-year-old IV drug user has fatigue. Labs: Anti-HCV positive, HCV RNA positive, ALT mildly elevated for 8 months, ultrasound normal. Which mechanism explains chronicity of his infection?","a":"Viral latency in bile ducts","b":"Integration into host DNA","c":"High mutation rate causing immune escape","d":"Infection limited to Kupffer cells only","ans":"C"},
{"t":"Hepatology","q":"A pregnant woman in third trimester returns from flood-affected region and develops jaundice, coagulopathy and encephalopathy within days. Most likely cause of severe disease?","a":"Immune complex deposition","b":"Massive viral cytopathic effect","c":"Hormonal enhancement of viral replication","d":"Increased susceptibility to Hepatitis E fulminant failure","ans":"D"},
{"t":"Hepatology","q":"A 19-year-old male presents with tremors, depression and hepatitis. Labs: AST>ALT, low ALP, low ceruloplasmin, Coombs negative hemolysis. Which is the best initial treatment?","a":"Phlebotomy","b":"Zinc therapy","c":"Tenofovir","d":"Prednisolone","ans":"B"},
{"t":"Hepatology","q":"A 52-year-old diabetic man with bronze skin and hepatomegaly has ferritin 1400 ng/ml and transferrin saturation 85%. What is the major long-term risk if untreated?","a":"Acute liver failure","b":"Hepatocellular carcinoma","c":"Cholangiocarcinoma","d":"Acute pancreatitis","ans":"B"},
{"t":"Hepatology","q":"A patient presents with jaundice after starting anti-TB therapy 6 weeks ago. ALT 1200, ALP mildly raised, viral markers negative. Which drug most likely responsible?","a":"Ethambutol","b":"Isoniazid","c":"Streptomycin","d":"Pyridoxine","ans":"B"},
{"t":"Hepatology","q":"A 28-year-old woman has fatigue, amenorrhea and jaundice. Labs: ANA positive, anti-smooth muscle antibody positive, IgG high, viral serology negative. Liver biopsy shows interface hepatitis. Preferred treatment?","a":"Interferon","b":"Steroids with azathioprine","c":"Ribavirin","d":"Ursodeoxycholic acid only","ans":"B"},
{"t":"Hepatology","q":"A patient with chronic HBV infection suddenly develops severe hepatitis after acquiring HDV infection. This is called","a":"Coinfection leading to mild disease","b":"Superinfection causing severe hepatitis","c":"Reactivation hepatitis","d":"Window period hepatitis","ans":"B"},
{"t":"Hepatology","q":"A transfusion recipient has anti-HCV antibodies but repeatedly negative HCV RNA PCR. Interpretation?","a":"Chronic hepatitis C","b":"Acute infection","c":"False positive antibody","d":"Resolved past infection","ans":"D"},
{"t":"Hepatology","q":"A 40-year-old alcoholic presents with AST 240, ALT 90, bilirubin elevated and tender hepatomegaly. The AST predominance is due to","a":"Cytosolic enzyme inhibition","b":"Pyridoxal phosphate deficiency","c":"Viral replication","d":"Iron toxicity","ans":"B"},
{"t":"Hepatology","q":"A newborn of HBsAg positive mother did not receive prophylaxis and at 6 months has HBsAg positive, HBeAg positive, normal ALT. This state represents","a":"Acute hepatitis","b":"Immune tolerant chronic infection","c":"Fulminant hepatitis","d":"Recovery phase","ans":"B"},
{"t":"Hepatology","q":"A patient presents with severe liver injury after eating wild mushrooms containing amatoxin. Pathogenesis involves","a":"RNA polymerase II inhibition","b":"DNA cross-linking","c":"Bile duct obstruction","d":"Immune complex deposition","ans":"A"},
{"t":"Hepatology","q":"A 34-year-old man has chronic hepatitis B: HBsAg positive, HBeAg negative, anti-HBe positive, HBV DNA high, ALT elevated. Diagnosis","a":"Inactive carrier","b":"Pre-core mutant chronic hepatitis","c":"Acute resolving infection","d":"Vaccinated state","ans":"B"},
{"t":"Hepatology","q":"A patient with chronic HCV develops palpable purpura, arthralgia and renal disease. Mechanism","a":"Direct viral cytotoxicity","b":"Cryoglobulinemia immune complexes","c":"Iron deposition","d":"Copper toxicity","ans":"B"},
{"t":"Hepatology","q":"A woman taking oral contraceptives develops acute hepatic injury after overdose of acetaminophen 12 hours earlier. Most sensitive early lab marker?","a":"Rising bilirubin","b":"Elevated INR","c":"Elevated ALT","d":"Elevated ALP","ans":"C"},
{"t":"Hepatology","q":"A patient has hepatitis with low ceruloplasmin but also high ferritin and diabetes. Which investigation differentiates Wilson from hemochromatosis?","a":"Serum iron","b":"24-hour urinary copper","c":"Transferrin saturation","d":"AST level","ans":"B"},
{"t":"Hepatology","q":"A 29-year-old healthcare worker has HBsAg negative, Anti-HBc IgG positive, Anti-HBs positive. Interpretation","a":"Vaccinated only","b":"Past natural infection with immunity","c":"Acute infection","d":"Chronic carrier","ans":"B"},
{"t":"Hepatology","q":"Patient with chronic hepatitis develops sudden rise in ALT and jaundice after starting chemotherapy. Mechanism","a":"Autoimmune hepatitis","b":"Viral reactivation due to immunosuppression","c":"Drug allergy","d":"Biliary obstruction","ans":"B"},
{"t":"Hepatology","q":"A cirrhotic patient with chronic HBV is screened for cancer. Best surveillance test combination","a":"AFP + ultrasound every 6 months","b":"CT yearly","c":"MRI every 5 years","d":"Liver biopsy annually","ans":"A"},
{"t":"Hepatology","q":"A patient with chronic hepatitis presents with confusion, asterixis and high ammonia but bilirubin only mildly elevated. Immediate management priority","a":"Start antivirals","b":"Lactulose therapy","c":"Steroids","d":"Iron chelation","ans":"B"},
{"t":"Hepatology","q":"A cirrhotic patient presents with progressive abdominal distension and shifting dullness. First-line management of uncomplicated ascites is","a":"Immediate paracentesis only","b":"Spironolactone therapy with salt restriction","c":"High protein diet alone","d":"Propranolol therapy","ans":"A"},
{"t":"Hepatology","q":"A patient with chronic liver disease becomes confused and has asterixis after constipation. Most likely precipitating factor","a":"Hypernatremia","b":"Hypoglycemia","c":"Increased ammonia absorption","d":"Vitamin deficiency","ans":"D"},
{"t":"Hepatology","q":"A cirrhotic patient presents with hematemesis and hypotension. Initial priority management","a":"Endoscopy immediately","b":"IV fluids and resuscitation","c":"Oral beta blockers","d":"CT scan abdomen","ans":"C"},
{"t":"Hepatology","q":"Best screening test for hepatocellular carcinoma in cirrhosis","a":"AFP + ultrasound","b":"CT abdomen yearly","c":"Liver biopsy","d":"MRI brain","ans":"B"},
{"t":"Hepatology","q":"Drug contraindicated in advanced liver failure due to risk of encephalopathy","a":"Lactulose","b":"Benzodiazepines","c":"Spironolactone","d":"Rifaximin","ans":"D"},
{"t":"Hepatology","q":"A patient with ascites undergoes paracentesis showing SAAG >1.1. Interpretation","a":"Malignancy ascites","b":"Tuberculous ascites","c":"Portal hypertension","d":"Pancreatic ascites","ans":"A"},
{"t":"Hepatology","q":"First-line treatment of hepatic encephalopathy","a":"Metronidazole","b":"Lactulose","c":"Omeprazole","d":"Albumin infusion","ans":"C"},
{"t":"Hepatology","q":"Cirrhotic patient develops fever and abdominal pain. Ascitic neutrophils 400/mm³. Diagnosis","a":"Secondary peritonitis","b":"Spontaneous bacterial peritonitis","c":"Pancreatitis","d":"Perforation","ans":"D"},
{"t":"Hepatology","q":"Drug used for primary prophylaxis of variceal bleeding","a":"Propranolol","b":"Furosemide","c":"Prednisolone","d":"Atropine","ans":"B"},
{"t":"Hepatology","q":"Best immediate treatment during acute variceal bleed after resuscitation","a":"Octreotide infusion","b":"Aspirin","c":"Warfarin","d":"Insulin","ans":"D"},
{"t":"Hepatology","q":"A cirrhotic patient has day-night reversal sleep and irritability but oriented. Encephalopathy stage","a":"Grade I","b":"Grade II","c":"Grade III","d":"Grade IV","ans":"B"},
{"t":"Hepatology","q":"Most common cause of ascites worldwide","a":"Tuberculosis","b":"Cirrhosis","c":"Malignancy","d":"Nephrotic syndrome","ans":"D"},
{"t":"Hepatology","q":"Refractory ascites not responding to diuretics best next management","a":"Repeated large volume paracentesis","b":"Antibiotics","c":"Insulin therapy","d":"Iron therapy","ans":"B"},
{"t":"Hepatology","q":"TIPS procedure primarily reduces","a":"Portal pressure","b":"Systemic pressure","c":"Renal perfusion","d":"Cardiac output","ans":"C"},
{"t":"Hepatology","q":"A cirrhotic patient with melena but stable vitals likely source","a":"Varices","b":"Hemorrhoids","c":"Peptic ulcer","d":"Mallory Weiss tear","ans":"A"},
{"t":"Hepatology","q":"A patient with cirrhosis develops confusion after high protein meal. Mechanism","a":"Increased ammonia production","b":"Hypocalcemia","c":"Hyperglycemia","d":"Increased bile salts","ans":"D"},
{"t":"Hepatology","q":"Most specific sign of hepatic encephalopathy","a":"Tremor","b":"Asterixis","c":"Rigidity","d":"Hyperreflexia","ans":"A"},
{"t":"Hepatology","q":"A patient with chronic liver disease has platelets 70,000. Cause","a":"Bone marrow failure","b":"Hypersplenism","c":"Iron deficiency","d":"Hemolysis","ans":"C"},
{"t":"Hepatology","q":"First investigation in suspected ascites","a":"Diagnostic paracentesis","b":"MRI abdomen","c":"Colonoscopy","d":"ERCP","ans":"D"},
{"t":"Hepatology","q":"Liver transplant indicated when score high in","a":"MELD score","b":"APGAR score","c":"Glasgow score","d":"CHADS score","ans":"C"},
{"t":"Hepatology","q":"A cirrhotic patient presents with hematemesis, tachycardia and low Hb. After fluids, next step","a":"Start IV PPI only","b":"Urgent endoscopic band ligation","c":"Colonoscopy","d":"CT angiography","ans":"A"},
{"t":"Hepatology","q":"Ascitic fluid protein low and SAAG high suggests","a":"Portal hypertension ascites","b":"Malignant ascites","c":"Pancreatic ascites","d":"Tuberculous ascites","ans":"C"},
{"t":"Hepatology","q":"Lactulose works by","a":"Increasing protein digestion","b":"Acidifying colon trapping ammonia","c":"Increasing bile secretion","d":"Blocking GABA receptors","ans":"D"},
{"t":"Hepatology","q":"Rifaximin role in cirrhosis","a":"Diuretic","b":"Reduce ammonia producing bacteria","c":"Reduce portal pressure","d":"Increase albumin","ans":"A"},
{"t":"Hepatology","q":"A cirrhotic patient with sudden renal failure without shock likely has","a":"ATN","b":"Hepatorenal syndrome","c":"Pyelonephritis","d":"Renal stones","ans":"C"},
{"t":"Hepatology","q":"Management of spontaneous bacterial peritonitis","a":"Cefotaxime","b":"Penicillin V","c":"Acyclovir","d":"Amphotericin","ans":"B"},
{"t":"Hepatology","q":"Contraindicated drug in severe cirrhosis due to bleeding risk","a":"NSAIDs","b":"Lactulose","c":"Vitamin K","d":"Albumin","ans":"C"},
{"t":"Hepatology","q":"Most common primary liver cancer","a":"Cholangiocarcinoma","b":"Hepatocellular carcinoma","c":"Metastasis","d":"Hemangioma","ans":"D"},
{"t":"Hepatology","q":"AFP markedly elevated suggests","a":"Hemangioma","b":"HCC","c":"Hepatitis A","d":"Gallstones","ans":"C"},
{"t":"Hepatology","q":"A cirrhotic with tense ascites undergoes large volume paracentesis. To prevent circulatory dysfunction give","a":"Albumin","b":"Insulin","c":"Calcium","d":"Vitamin C","ans":"B"},
{"t":"Hepatology","q":"Lower GI bleeding commonly presents with","a":"Hematemesis","b":"Hematochezia","c":"Melena only","d":"Coffee ground vomiting","ans":"A"},
{"t":"Hepatology","q":"Most common cause of lower GI bleed in elderly","a":"Hemorrhoids","b":"Diverticulosis","c":"Polyps","d":"Ulcerative colitis","ans":"D"},
{"t":"Hepatology","q":"Variceal bleeding mortality reduced by","a":"Antibiotic prophylaxis","b":"Steroids","c":"Anticoagulation","d":"Antacids","ans":"B"},
{"t":"Hepatology","q":"Hepatic encephalopathy worsened by","a":"Constipation","b":"Lactulose","c":"Rifaximin","d":"Low protein diet","ans":"C"},
{"t":"Hepatology","q":"Most common precipitant of encephalopathy","a":"Infection","b":"Exercise","c":"Hypertension","d":"Hyperlipidemia","ans":"D"},
{"t":"Hepatology","q":"Child-Pugh score assesses","a":"Severity of cirrhosis","b":"Renal failure","c":"Pancreatitis","d":"Cardiac disease","ans":"B"},
{"t":"Hepatology","q":"A cirrhotic patient with progressive jaundice, weight loss and liver mass likely has","a":"Abscess","b":"Hepatocellular carcinoma","c":"Hemangioma","d":"Cyst","ans":"A"},
{"t":"Hepatology","q":"Best imaging to confirm HCC after ultrasound","a":"Triple phase CT","b":"X-ray","c":"ECG","d":"Endoscopy","ans":"D"},
{"t":"Hepatology","q":"Recurrent encephalopathy despite lactulose add","a":"Rifaximin","b":"Aspirin","c":"Morphine","d":"Diazepam","ans":"B"},
{"t":"Hepatology","q":"Cirrhotic patient develops umbilical hernia due to","a":"Ascites pressure","b":"Infection","c":"Tumor","d":"Trauma","ans":"C"},
{"t":"Hepatology","q":"A patient with liver failure requires transplant. Absolute contraindication","a":"Active alcohol abuse","b":"Ascites","c":"Varices","d":"Splenomegaly","ans":"B"},
{"t":"Hepatology","q":"Earliest sign of portal hypertension","a":"Splenomegaly","b":"Ascites","c":"Encephalopathy","d":"Jaundice","ans":"D"},
{"t":"Hepatology","q":"Hepatorenal syndrome treated with","a":"Albumin + vasoconstrictors","b":"Diuretics only","c":"Insulin","d":"ACE inhibitors","ans":"C"},
{"t":"Hepatology","q":"A cirrhotic with fever and GI bleed risk of encephalopathy increases due to","a":"Nitrogen load from blood","b":"Hypoglycemia","c":"Hypocalcemia","d":"Vitamin deficiency","ans":"B"},
{"t":"Hepatology","q":"Best prevention of recurrent variceal bleeding","a":"Band ligation + beta blockers","b":"Antacids","c":"Insulin","d":"Steroids","ans":"D"},
{"t":"Hepatology","q":"A patient with cirrhosis has prolonged PT corrected by vitamin K. Cause","a":"Vitamin K deficiency","b":"Liver failure","c":"Hemophilia","d":"DIC","ans":"B"},
{"t":"Hepatology","q":"Ascites with SAAG <1.1 suggests","a":"Malignancy","b":"Portal hypertension","c":"Heart failure","d":"Cirrhosis","ans":"C"},
{"t":"Hepatology","q":"Flapping tremor indicates","a":"Hepatic encephalopathy","b":"Parkinson disease","c":"Cerebellar lesion","d":"Stroke","ans":"D"},
{"t":"Hepatology","q":"First step in suspected spontaneous bacterial peritonitis in ER","a":"Diagnostic tap before antibiotics","b":"Start diuretics","c":"CT scan first","d":"Endoscopy","ans":"B"},
{"t":"Hepatology","q":"Most definitive treatment of decompensated cirrhosis","a":"Long term antibiotics","b":"Liver transplantation","c":"TIPS only","d":"Beta blockers lifelong","ans":"C"},
{"t":"Hepatology","q":"Most common cause of acute pancreatitis worldwide is","a":"Alcohol","b":"Gallstones","c":"Hypercalcemia","d":"Trauma","ans":"A"},
{"t":"Hepatology","q":"Enzyme most specific for diagnosis of acute pancreatitis","a":"Amylase","b":"Elastase","c":"Lipase","d":"Trypsinogen","ans":"B"},
{"t":"Hepatology","q":"Severe epigastric pain radiating to back relieved by leaning forward suggests","a":"Peptic ulcer","b":"Gastritis","c":"Cholecystitis","d":"Acute pancreatitis","ans":"C"},
{"t":"Hepatology","q":"Initial management step in acute pancreatitis","a":"Aggressive IV fluids","b":"Oral feeding","c":"Immediate surgery","d":"Steroids","ans":"D"},
{"t":"Hepatology","q":"Most common cause of chronic pancreatitis","a":"Alcohol abuse","b":"Gallstones","c":"Viral infection","d":"Trauma","ans":"A"},
{"t":"Hepatology","q":"Hypocalcemia in pancreatitis occurs due to","a":"Vitamin D deficiency","b":"Fat saponification","c":"Renal failure","d":"Hypoparathyroidism","ans":"B"},
{"t":"Hepatology","q":"Characteristic CT finding in chronic pancreatitis","a":"Portal vein thrombosis","b":"Pancreatic enlargement only","c":"Pancreatic calcification","d":"Liver nodules","ans":"C"},
{"t":"Hepatology","q":"Best time to perform contrast CT in acute pancreatitis","a":"Immediately at admission","b":"After 1 hour","c":"After 2 weeks only","d":"After 72 hours","ans":"D"},
{"t":"Hepatology","q":"Grey Turner sign indicates","a":"Retroperitoneal hemorrhage","b":"Mild pancreatitis","c":"Ascites","d":"Biliary obstruction","ans":"A"},
{"t":"Hepatology","q":"Cullen sign represents","a":"Periumbilical ecchymosis","b":"Jaundice","c":"Ascites","d":"Splenomegaly","ans":"B"},
{"t":"Hepatology","q":"Drug commonly causing pancreatitis","a":"Paracetamol","b":"Azathioprine","c":"Omeprazole","d":"Amoxicillin","ans":"C"},
{"t":"Hepatology","q":"Most important prognostic scoring system in pancreatitis","a":"Child-Pugh","b":"MELD","c":"Ranson criteria","d":"APGAR","ans":"D"},
{"t":"Hepatology","q":"Elevated triglycerides causing pancreatitis typically >","a":"200 mg/dL","b":"300 mg/dL","c":"500 mg/dL","d":"1000 mg/dL","ans":"A"},
{"t":"Hepatology","q":"Chronic pancreatitis leads to steatorrhea due to deficiency of","a":"Insulin","b":"Trypsin","c":"Lipase","d":"Amylase","ans":"B"},
{"t":"Hepatology","q":"Best test for pancreatic exocrine insufficiency","a":"Serum amylase","b":"Fecal elastase","c":"ALT","d":"Bilirubin","ans":"C"},
{"t":"Hepatology","q":"Pancreatic pseudocyst defined as collection persisting >","a":"24 hours","b":"72 hours","c":"1 week","d":"4 weeks","ans":"D"},
{"t":"Hepatology","q":"Pain of chronic pancreatitis relieved by","a":"Eating fatty meals","b":"Leaning forward","c":"Lying flat","d":"Exercise","ans":"A"},
{"t":"Hepatology","q":"First imaging in suspected pancreatitis","a":"CT scan","b":"MRI","c":"Ultrasound","d":"ERCP","ans":"B"},
{"t":"Hepatology","q":"Antibiotics in acute pancreatitis indicated when","a":"All patients","b":"Sterile necrosis","c":"Infected necrosis","d":"Mild pancreatitis","ans":"C"},
{"t":"Hepatology","q":"Most common complication early in acute pancreatitis","a":"Shock","b":"Diabetes","c":"Pseudocyst","d":"Cancer","ans":"D"},
{"t":"Hepatology","q":"Late complication of pancreatitis","a":"Hypocalcemia","b":"ARDS","c":"Pseudocyst","d":"Shock","ans":"A"},
{"t":"Hepatology","q":"Chronic pancreatitis endocrine failure leads to","a":"Diabetes mellitus","b":"Hyperthyroidism","c":"Cushing syndrome","d":"Hypoglycemia only","ans":"B"},
{"t":"Hepatology","q":"Gallstone pancreatitis definitive treatment","a":"Cholecystectomy","b":"Insulin","c":"Steroids","d":"Antacids","ans":"C"},
{"t":"Hepatology","q":"ERCP indicated urgently in pancreatitis with","a":"Hyperlipidemia","b":"Cholangitis","c":"Alcohol history","d":"Diabetes","ans":"D"},
{"t":"Hepatology","q":"Best analgesic for acute pancreatitis","a":"Morphine/opioids","b":"Aspirin","c":"NSAIDs only","d":"Paracetamol low dose","ans":"A"},
{"t":"Hepatology","q":"Most sensitive lab marker early pancreatitis","a":"Lipase","b":"Amylase","c":"CRP","d":"Bilirubin","ans":"B"},
{"t":"Hepatology","q":"Chronic pancreatitis increases risk of","a":"Pancreatic cancer","b":"Gastric ulcer","c":"Appendicitis","d":"Hepatitis A","ans":"C"},
{"t":"Hepatology","q":"Pancreatic necrosis best diagnosed by","a":"Contrast CT","b":"X-ray","c":"Ultrasound only","d":"Endoscopy","ans":"D"},
{"t":"Hepatology","q":"Ranson criteria assessed at admission and","a":"6 hrs","b":"12 hrs","c":"24 hrs","d":"48 hrs","ans":"A"},
{"t":"Hepatology","q":"Main pathophysiology acute pancreatitis","a":"Premature trypsin activation","b":"Bile acid deficiency","c":"Decreased insulin","d":"Viral infection","ans":"B"},
{"t":"Hepatology","q":"Chronic pancreatitis malabsorption treated with","a":"Pancreatic enzyme supplements","b":"Iron","c":"Vitamin C","d":"Antibiotics","ans":"C"},
{"t":"Hepatology","q":"Alcohol causes pancreatitis by","a":"Ductal obstruction + toxic metabolites","b":"Autoimmune reaction only","c":"Viral replication","d":"Gallstone formation","ans":"D"},
{"t":"Hepatology","q":"Serum amylase normal but lipase high suggests","a":"Late presentation pancreatitis","b":"No disease","c":"Hepatitis","d":"Gastritis","ans":"A"},
{"t":"Hepatology","q":"Pseudocyst complication","a":"Rupture/hemorrhage","b":"Hypertension","c":"Asthma","d":"Nephritis","ans":"B"},
{"t":"Hepatology","q":"Best nutrition in severe pancreatitis","a":"Early enteral feeding","b":"TPN always","c":"NPO for weeks","d":"High fat diet","ans":"C"},
{"t":"Hepatology","q":"Hypercalcemia causes pancreatitis via","a":"Trypsin activation","b":"Insulin deficiency","c":"Bile obstruction","d":"Viral injury","ans":"D"},
{"t":"Hepatology","q":"Pancreatic ascites due to","a":"Ductal disruption","b":"Liver failure","c":"Heart failure","d":"Kidney disease","ans":"A"},
{"t":"Hepatology","q":"Chronic pancreatitis imaging best initial","a":"CT scan","b":"MRI brain","c":"Chest X-ray","d":"Colonoscopy","ans":"B"},
{"t":"Hepatology","q":"Severe pancreatitis marker","a":"CRP >150 mg/L","b":"Low ESR","c":"Low Hb","d":"High platelets","ans":"C"},
{"t":"Hepatology","q":"Gallstone pancreatitis lab pattern","a":"Elevated ALT >150","b":"Low bilirubin","c":"Low ALP","d":"Low AST","ans":"D"},
{"t":"Hepatology","q":"Most dangerous complication acute pancreatitis","a":"ARDS","b":"Diabetes","c":"Malabsorption","d":"Cancer","ans":"A"},
{"t":"Hepatology","q":"Pancreatic insufficiency causes deficiency of","a":"Fat soluble vitamins","b":"Vitamin C","c":"Iron only","d":"Sodium","ans":"B"},
{"t":"Hepatology","q":"Chronic pancreatitis pain due to","a":"Ductal hypertension","b":"Hyperacidity","c":"Hypoglycemia","d":"Gastritis","ans":"C"},
{"t":"Hepatology","q":"Alcohol abstinence in chronic pancreatitis","a":"Slows progression","b":"No effect","c":"Worsens disease","d":"Causes diabetes immediately","ans":"D"},
{"t":"Hepatology","q":"Trypsin inhibitor deficiency seen in","a":"Hereditary pancreatitis","b":"Viral hepatitis","c":"Cirrhosis","d":"IBS","ans":"A"},
{"t":"Hepatology","q":"Best marker severity pancreatitis day 3","a":"CRP","b":"Amylase","c":"Lipase","d":"Glucose","ans":"B"},
{"t":"Hepatology","q":"Chronic pancreatitis stool finding","a":"Bulky greasy stool","b":"Watery diarrhea","c":"Bloody stool","d":"Black stool","ans":"C"},
{"t":"Hepatology","q":"Pseudocyst treatment if symptomatic","a":"Drainage","b":"Antibiotics only","c":"Steroids","d":"Observation lifelong","ans":"D"},
{"t":"Hepatology","q":"Hypertriglyceridemia pancreatitis treatment includes","a":"Insulin infusion","b":"Beta blockers","c":"Iron","d":"Vitamin K","ans":"A"},
{"t":"Hepatology","q":"Chronic pancreatitis long term complication","a":"Diabetes mellitus","b":"Asthma","c":"Nephritis","d":"Hypothyroidism","ans":"B"},
{"t":"Hepatology","q":"A cirrhotic patient has ascites with SAAG 1.4 g/dL and ascitic protein 0.8 g/dL. Most likely complication risk is","a":"Pancreatitis","b":"Spontaneous bacterial peritonitis","c":"Nephrotic syndrome","d":"Tuberculosis","ans":"B"},
{"t":"Hepatology","q":"A 45-year-old man with chronic hepatitis B has HBV DNA 25,000 IU/mL, ALT persistently elevated, HBeAg negative and anti-HBe positive. This represents","a":"Immune tolerant phase","b":"Precore mutant chronic hepatitis B","c":"Acute infection","d":"Inactive carrier state","ans":"B"},
{"t":"Hepatology","q":"In Wilson disease, neurologic symptoms correlate best with deposition of copper in","a":"Cerebellum","b":"Basal ganglia","c":"Hippocampus","d":"Thalamus","ans":"B"},
{"t":"Hepatology","q":"A patient with jaundice has elevated conjugated bilirubin but normal ALP and GGT. Likely diagnosis","a":"Hemolysis","b":"Dubin-Johnson syndrome","c":"Acute viral hepatitis","d":"Gilbert syndrome","ans":"B"},
{"t":"Hepatology","q":"A cirrhotic patient develops renal failure, urine sodium <10 mmol/L, no shock and no nephrotoxic drugs. Mechanism","a":"Acute tubular necrosis","b":"Renal vasoconstriction due to splanchnic vasodilation","c":"Glomerulonephritis","d":"Obstruction","ans":"B"},
{"t":"Hepatology","q":"A patient with chronic HCV develops palpable purpura and low complement levels. Cause","a":"Autoimmune hepatitis","b":"Mixed cryoglobulinemia","c":"Hemochromatosis","d":"Drug toxicity","ans":"B"},
{"t":"Hepatology","q":"In hepatic encephalopathy, ammonia primarily exerts toxicity via","a":"Astrocyte glutamine accumulation","b":"Direct neuronal necrosis","c":"Acetylcholine depletion","d":"Dopamine excess","ans":"A"},
{"t":"Hepatology","q":"A patient with primary biliary cholangitis most specific antibody","a":"ANA","b":"Anti-mitochondrial antibody","c":"Anti-smooth muscle antibody","d":"Anti-dsDNA","ans":"B"},
{"t":"Hepatology","q":"A cirrhotic patient with upper GI bleed should receive prophylactic","a":"Anticoagulants","b":"Antibiotics","c":"Steroids","d":"Diuretics","ans":"B"},
{"t":"Hepatology","q":"A patient with hepatic encephalopathy not responding to lactulose next drug","a":"Neomycin","b":"Rifaximin","c":"Ciprofloxacin","d":"Metronidazole IV","ans":"B"},
{"t":"Hepatology","q":"A 32-year-old woman presents with pruritus and fatigue. Labs: ALP high, AST mild, AMA positive. Pathophysiology","a":"Hepatocyte necrosis","b":"Autoimmune destruction of intrahepatic bile ducts","c":"Portal vein thrombosis","d":"Pancreatic obstruction","ans":"B"},
{"t":"Hepatology","q":"In hemochromatosis, iron deposition occurs earliest in","a":"Kupffer cells","b":"Hepatocytes periportal region","c":"Bile duct epithelium","d":"Portal vein endothelium","ans":"B"},
{"t":"Hepatology","q":"A patient with acute liver failure develops cerebral edema due to","a":"Hypernatremia","b":"Ammonia-induced astrocyte swelling","c":"Hypoglycemia","d":"Uremia","ans":"B"},
{"t":"Hepatology","q":"A 50-year-old alcoholic has AST:ALT ratio >2. Reason","a":"ALT induction","b":"Pyridoxal phosphate deficiency in hepatocytes","c":"Viral coinfection","d":"Hemolysis","ans":"B"},
{"t":"Hepatology","q":"Portal hypertension leads to ascites mainly due to","a":"Increased oncotic pressure","b":"Splanchnic vasodilation and sodium retention","c":"Renal artery stenosis","d":"Lymphoma","ans":"B"},
{"t":"Hepatology","q":"A patient with chronic liver disease has confusion after GI bleed. Key mechanism","a":"Increased nitrogen load","b":"Hypokalemia","c":"Hypoglycemia","d":"Iron deficiency","ans":"A"},
{"t":"Hepatology","q":"A transplant candidate MELD score primarily uses","a":"AST, ALT, ALP","b":"Bilirubin, INR, creatinine","c":"Albumin, sodium, potassium","d":"Platelets, Hb, WBC","ans":"B"},
{"t":"Hepatology","q":"A patient develops cholestasis after starting anabolic steroids. Mechanism","a":"Canalicular transport inhibition","b":"Hepatocyte necrosis","c":"Autoimmune destruction","d":"Viral replication","ans":"A"},
{"t":"Hepatology","q":"A cirrhotic patient has splenomegaly and thrombocytopenia. Cause","a":"Bone marrow suppression","b":"Hypersplenism from portal hypertension","c":"Iron deficiency","d":"Vitamin B12 deficiency","ans":"B"},
{"t":"Hepatology","q":"A patient with hepatocellular carcinoma shows arterial enhancement and venous washout because tumor blood supply from","a":"Portal vein","b":"Hepatic artery","c":"Inferior vena cava","d":"Splenic vein","ans":"B"},
{"t":"Hepatology","q":"A young man with Wilson disease presents with acute hemolysis. Mechanism","a":"Iron overload","b":"Free copper-induced RBC membrane damage","c":"Autoimmune antibodies","d":"Hypersplenism","ans":"B"},
{"t":"Hepatology","q":"In obstructive jaundice prolonged PT corrects after vitamin K due to deficiency of","a":"Factor V","b":"Vitamin K-dependent factors","c":"Platelets","d":"Fibrinogen","ans":"B"},
{"t":"Hepatology","q":"A cirrhotic patient with tense ascites undergoes paracentesis >6 L. Prevent renal dysfunction by","a":"Dopamine","b":"Albumin infusion","c":"Insulin","d":"Calcium gluconate","ans":"B"},
{"t":"Hepatology","q":"A patient with acute hepatitis has markedly high ALT > AST. Most likely etiology","a":"Alcoholic hepatitis","b":"Viral hepatitis","c":"Hemochromatosis","d":"Wilson disease","ans":"B"},
{"t":"Hepatology","q":"A patient develops hepatic encephalopathy after TIPS. Reason","a":"Reduced portal pressure","b":"Ammonia bypasses liver detoxification","c":"Increased albumin synthesis","d":"Reduced splanchnic flow","ans":"B"},
{"t":"Hepatology","q":"Hepatic osteodystrophy in chronic cholestasis occurs due to deficiency of","a":"Vitamin C","b":"Vitamin D","c":"Iron","d":"Folate","ans":"B"},
{"t":"Hepatology","q":"A patient with NASH cirrhosis develops HCC despite normal AFP. Best surveillance","a":"CT annually","b":"Ultrasound every 6 months","c":"Biopsy yearly","d":"PET scan","ans":"B"},
{"t":"Hepatology","q":"A patient with Budd-Chiari syndrome has hepatomegaly and ascites due to","a":"Portal vein obstruction","b":"Hepatic vein outflow obstruction","c":"Bile duct obstruction","d":"Pancreatic compression","ans":"B"},
{"t":"Hepatology","q":"A patient with fulminant hepatic failure has INR >6 and encephalopathy. Definitive treatment","a":"Steroids","b":"Liver transplantation","c":"Antivirals","d":"Plasma only","ans":"B"},
{"t":"Hepatology","q":"In chronic hepatitis, interface hepatitis refers to inflammation at","a":"Central vein","b":"Portal-parenchymal interface","c":"Bile canaliculi","d":"Sinusoids only","ans":"B"},
{"t":"Hepatology","q":"A cirrhotic patient develops hyponatremia. Mechanism","a":"SIADH","b":"Dilutional water retention due to ADH excess","c":"Renal salt wasting","d":"Hyperaldosteronism absence","ans":"B"},
{"t":"Hepatology","q":"A patient with cholangitis has Charcot triad plus hypotension and confusion. This is","a":"Reynolds pentad","b":"Murphy sign","c":"Courvoisier sign","d":"Grey Turner sign","ans":"A"},
{"t":"Hepatology","q":"Hepatorenal syndrome type 1 characterized by","a":"Rapid rise creatinine >2.5 mg/dL","b":"Chronic stable renal failure","c":"Proteinuria","d":"Hematuria","ans":"A"},
{"t":"Hepatology","q":"A cirrhotic patient has high ferritin but low transferrin saturation. Most likely","a":"Hemochromatosis","b":"Inflammation related ferritin elevation","c":"Wilson disease","d":"Iron deficiency","ans":"B"},
{"t":"Hepatology","q":"A patient with hepatic adenoma risk factor","a":"Oral contraceptive use","b":"Smoking","c":"Alcohol","d":"Viral hepatitis","ans":"A"},
{"t":"Hepatology","q":"A patient with pruritus in cholestasis treated with","a":"Cholestyramine","b":"Paracetamol","c":"Propranolol","d":"Lactulose","ans":"A"},
{"t":"Hepatology","q":"A patient with cirrhosis develops caput medusae due to","a":"Portal-systemic collateral formation","b":"Lymphatic obstruction","c":"Splenic rupture","d":"Umbilical infection","ans":"A"},
{"t":"Hepatology","q":"A patient with hepatic encephalopathy shows triphasic waves on","a":"ECG","b":"EEG","c":"EMG","d":"MRI","ans":"B"},
{"t":"Hepatology","q":"A patient with acute hepatitis has very high AST/ALT >3000. Most likely cause","a":"Ischemic hepatitis","b":"NASH","c":"Cirrhosis","d":"Hemochromatosis","ans":"A"},
{"t":"Hepatology","q":"A cirrhotic patient with severe pruritus and xanthomas most likely has","a":"Primary biliary cholangitis","b":"Hepatitis A","c":"Wilson disease","d":"Alcoholic hepatitis","ans":"A"},
{"t":"Hepatology","q":"A patient with portal hypertension treated with nonselective beta blockers works by","a":"Decreasing portal venous inflow","b":"Increasing hepatic artery flow","c":"Increasing albumin","d":"Reducing bile salts","ans":"A"},
{"t":"Hepatology","q":"A patient with acute liver failure has hypoglycemia because liver cannot","a":"Store fat","b":"Perform gluconeogenesis","c":"Metabolize insulin","d":"Produce bile","ans":"B"},
{"t":"Hepatology","q":"A patient with cholestatic jaundice develops pale stool because of lack of","a":"Stercobilin","b":"Urobilinogen","c":"Biliverdin","d":"Hemoglobin","ans":"A"},
{"t":"Hepatology","q":"A cirrhotic patient develops muscle wasting due to","a":"Increased protein synthesis","b":"Hypermetabolism and ammonia detoxification in muscle","c":"Fat accumulation","d":"Vitamin C excess","ans":"B"},
{"t":"Hepatology","q":"A patient with HCC eligible for transplant meets Milan criteria when","a":"Single tumor ≤5 cm","b":"Any size tumor","c":"Metastasis present","d":"Vascular invasion","ans":"A"},
{"t":"Hepatology","q":"Hepatic hydrothorax occurs due to","a":"Diaphragmatic defects allowing ascitic fluid movement","b":"Heart failure","c":"Pneumonia","d":"Pleural tumor","ans":"A"},
{"t":"Hepatology","q":"A patient with severe alcoholic hepatitis treated with","a":"Prednisolone","b":"Tenofovir","c":"Rifaximin","d":"Lactulose","ans":"A"},
{"t":"Hepatology","q":"In cirrhosis hyperestrogenism leads to","a":"Spider angioma","b":"Cyanosis","c":"Clubbing","d":"Leukopenia","ans":"A"},
{"t":"Hepatology","q":"A patient with hepatic failure has elevated INR uncorrected by vitamin K indicating","a":"Synthetic liver failure","b":"Vitamin deficiency","c":"Platelet dysfunction","d":"Hemolysis","ans":"A"},
{"t":"Hepatology","q":"A 58-year-old man with long-standing hepatitis C cirrhosis presents with progressive abdominal distension, confusion, recurrent variceal bleeding and weight loss over 6 months. Examination shows jaundice, asterixis, muscle wasting and ascites. Labs: bilirubin 6.5 mg/dL, INR 2.4, albumin 2.3 g/dL, creatinine 1.8 mg/dL. Despite optimal medical therapy he has repeated hospital admissions for encephalopathy and spontaneous bacterial peritonitis. What is the most appropriate definitive management to improve survival?","a":"Repeated large volume paracentesis","b":"Long term lactulose and rifaximin","c":"Transjugular intrahepatic portosystemic shunt (TIPS)","d":"Liver transplantation","ans":"D"}
];