window.MM=window.MM||{};
window.MM.med_p2_derma=[
{"t":"Dermatology","q":"The outermost protective barrier preventing transepidermal water loss is primarily formed by","a":"Stratum corneum","b":"Stratum basale","c":"Stratum spinosum","d":"Dermis","ans":"A"},
{"t":"Dermatology","q":"A child with albinism lacks melanin due to defect in melanin synthesis from tyrosine. The responsible cell type is","a":"Keratinocyte","b":"Melanocyte","c":"Langerhans cell","d":"Merkel cell","ans":"B"},
{"t":"Dermatology","q":"Which layer provides mechanical strength via desmosomes giving “spiny” appearance?","a":"Stratum lucidum","b":"Stratum corneum","c":"Stratum spinosum","d":"Stratum granulosum","ans":"C"},
{"t":"Dermatology","q":"A patient with blistering disease shows separation just above basement membrane. This junction is located between","a":"Dermis and subcutaneous tissue","b":"Stratum granulosum and corneum","c":"Stratum spinosum and granulosum","d":"Epidermis and dermis","ans":"D"},
{"t":"Dermatology","q":"Main protein providing tensile strength in dermis","a":"Collagen","b":"Elastin","c":"Keratin","d":"Actin","ans":"A"},
{"t":"Dermatology","q":"Langerhans cells originate from","a":"Neural crest","b":"Mesenchyme","c":"Bone marrow","d":"Keratinocyte lineage","ans":"C"},
{"t":"Dermatology","q":"Touch receptors associated with hair follicles are","a":"Meissner corpuscles","b":"Pacinian corpuscles","c":"Free nerve endings","d":"Hair root plexus","ans":"D"},
{"t":"Dermatology","q":"Which gland produces body odor after bacterial action during puberty?","a":"Eccrine gland","b":"Apocrine gland","c":"Sebaceous gland","d":"Ceruminous gland","ans":"B"},
{"t":"Dermatology","q":"Vitamin D synthesis in skin requires","a":"Infrared radiation","b":"Visible light","c":"Ultraviolet B radiation","d":"Ultraviolet A radiation","ans":"C"},
{"t":"Dermatology","q":"A newborn has shiny translucent skin due to underdeveloped layer rich in keratohyalin granules. This layer is","a":"Stratum corneum","b":"Stratum basale","c":"Stratum spinosum","d":"Stratum granulosum","ans":"D"},
{"t":"Dermatology","q":"Main function of melanocyte dendrites is","a":"Keratin production","b":"Transfer melanosomes to keratinocytes","c":"Immune defense","d":"Sweat secretion","ans":"B"},
{"t":"Dermatology","q":"Thick skin differs from thin skin by presence of","a":"Hair follicles","b":"Sebaceous glands","c":"Stratum lucidum","d":"Apocrine glands","ans":"C"},
{"t":"Dermatology","q":"Pacinian corpuscles detect","a":"Light touch","b":"Vibration and pressure","c":"Pain","d":"Temperature","ans":"B"},
{"t":"Dermatology","q":"Basement membrane zone primarily contains","a":"Hemidesmosomes","b":"Gap junctions","c":"Tight junctions","d":"Desmosomes only","ans":"A"},
{"t":"Dermatology","q":"Sebum secretion is stimulated mainly by","a":"Estrogen","b":"Thyroxine","c":"Androgens","d":"Cortisol","ans":"C"},
{"t":"Dermatology","q":"A patient with burns loses thermoregulation due to loss of","a":"Hair follicles","b":"Eccrine sweat glands","c":"Melanocytes","d":"Langerhans cells","ans":"B"},
{"t":"Dermatology","q":"Keratinocytes originate from","a":"Mesoderm","b":"Endoderm","c":"Neural crest","d":"Ectoderm","ans":"D"},
{"t":"Dermatology","q":"The papillary dermis mainly contains","a":"Dense collagen bundles","b":"Adipose tissue","c":"Loose connective tissue","d":"Smooth muscle","ans":"C"},
{"t":"Dermatology","q":"A patient feels sharp pain on needle prick due to activation of","a":"Free nerve endings","b":"Meissner corpuscles","c":"Pacinian corpuscles","d":"Merkel cells","ans":"A"},
{"t":"Dermatology","q":"Which cells present antigen to T lymphocytes in skin?","a":"Keratinocytes","b":"Langerhans cells","c":"Fibroblasts","d":"Melanocytes","ans":"B"},
{"t":"Dermatology","q":"Elastic recoil of skin is mainly due to","a":"Keratin","b":"Collagen","c":"Elastin","d":"Fibrin","ans":"C"},
{"t":"Dermatology","q":"A friction blister forms due to separation within","a":"Dermis","b":"Basement membrane","c":"Stratum basale","d":"Stratum spinosum","ans":"D"},
{"t":"Dermatology","q":"Skin color variation is mainly determined by","a":"Number of melanocytes","b":"Size and distribution of melanosomes","c":"Keratin thickness","d":"Collagen density","ans":"B"},
{"t":"Dermatology","q":"Arrector pili muscle contraction causes","a":"Sweating","b":"Goosebumps","c":"Sebum secretion","d":"Vasodilation","ans":"B"},
{"t":"Dermatology","q":"Subcutaneous tissue primarily stores","a":"Glycogen","b":"Calcium","c":"Fat","d":"Protein","ans":"C"},
{"t":"Dermatology","q":"A patient with vitiligo has destruction of","a":"Keratinocytes","b":"Fibroblasts","c":"Melanocytes","d":"Langerhans cells","ans":"C"},
{"t":"Dermatology","q":"Most abundant cell of epidermis","a":"Langerhans cell","b":"Merkel cell","c":"Melanocyte","d":"Keratinocyte","ans":"D"},
{"t":"Dermatology","q":"Heat dissipation in skin mainly occurs via","a":"Vasoconstriction","b":"Sweating and vasodilation","c":"Sebum secretion","d":"Keratinization","ans":"B"},
{"t":"Dermatology","q":"Collagen type predominant in dermis","a":"Type I","b":"Type II","c":"Type III only","d":"Type IV","ans":"A"},
{"t":"Dermatology","q":"A patient develops pressure ulcer due to prolonged ischemia affecting first","a":"Epidermis","b":"Dermis","c":"Subcutaneous tissue","d":"Bone","ans":"C"},
{"t":"Dermatology","q":"Meissner corpuscles detect","a":"Fine touch","b":"Pain","c":"Temperature","d":"Vibration deep","ans":"A"},
{"t":"Dermatology","q":"The skin barrier lipid matrix mainly contains","a":"Cholesterol, ceramides, fatty acids","b":"Triglycerides only","c":"Phospholipids only","d":"Glycogen","ans":"A"},
{"t":"Dermatology","q":"Nail plate is composed of","a":"Hard keratin","b":"Collagen","c":"Elastin","d":"Melanin","ans":"A"},
{"t":"Dermatology","q":"Hair growth cycle active phase","a":"Telogen","b":"Catagen","c":"Anagen","d":"Resting phase","ans":"C"},
{"t":"Dermatology","q":"The main function of stratum corneum lipids is","a":"Pigmentation","b":"Waterproof barrier","c":"Immune defense","d":"Sensation","ans":"B"},
{"t":"Dermatology","q":"A patient with peripheral neuropathy loses temperature sensation mediated by","a":"Free nerve endings","b":"Merkel cells","c":"Pacinian corpuscles","d":"Meissner corpuscles","ans":"A"},
{"t":"Dermatology","q":"Dermal papillae increase","a":"Hair growth only","b":"Surface area for attachment","c":"Sweat production","d":"Sebum secretion","ans":"B"},
{"t":"Dermatology","q":"Which layer disappears in blister formation of pemphigus vulgaris?","a":"Stratum corneum","b":"Stratum basale","c":"Stratum spinosum","d":"Dermis","ans":"C"},
{"t":"Dermatology","q":"The major role of keratohyalin granules is","a":"Pigment formation","b":"Keratin aggregation","c":"Collagen synthesis","d":"Sweat secretion","ans":"B"},
{"t":"Dermatology","q":"A person exposed to cold develops vasoconstriction to","a":"Increase heat loss","b":"Reduce heat loss","c":"Increase sweating","d":"Stimulate melanin","ans":"B"},
{"t":"Dermatology","q":"Fingerprint patterns arise from","a":"Epidermal ridges","b":"Dermal fat","c":"Hair follicles","d":"Sebaceous glands","ans":"A"},
{"t":"Dermatology","q":"Skin pH normally is","a":"Neutral 7","b":"Acidic around 5.5","c":"Alkaline 9","d":"Variable 10","ans":"B"},
{"t":"Dermatology","q":"Tanning after sun exposure occurs due to increased","a":"Melanin synthesis","b":"Collagen formation","c":"Sebum production","d":"Keratin destruction","ans":"A"},
{"t":"Dermatology","q":"The dermis is nourished by","a":"Epidermal vessels","b":"Dermal vascular plexus","c":"Sebaceous glands","d":"Sweat ducts","ans":"B"},
{"t":"Dermatology","q":"Loss of skin elasticity in aging mainly due to degeneration of","a":"Keratin","b":"Elastin fibers","c":"Melanin","d":"Glycogen","ans":"B"},
{"t":"Dermatology","q":"A patient with anhidrosis most likely has dysfunction of","a":"Apocrine glands","b":"Eccrine glands","c":"Sebaceous glands","d":"Hair follicles","ans":"B"},
{"t":"Dermatology","q":"The reticular dermis mainly contains","a":"Loose connective tissue","b":"Dense collagen bundles","c":"Adipose tissue only","d":"Smooth muscle","ans":"B"},
{"t":"Dermatology","q":"Skin acts as immune organ mainly due to presence of","a":"Fibroblasts","b":"Langerhans cells","c":"Adipocytes","d":"Myocytes","ans":"B"},
{"t":"Dermatology","q":"Cyanosis becomes visible when deoxygenated hemoglobin exceeds","a":"1 g/dL","b":"3 g/dL","c":"5 g/dL","d":"8 g/dL","ans":"C"},
{"t":"Dermatology","q":"The main function of subcutaneous fat is","a":"Pigmentation","b":"Insulation and energy storage","c":"Sensory perception","d":"Immune response","ans":"B"},
{"t":"Dermatology","q":"The skin is derived embryologically from","a":"Ectoderm and mesoderm","b":"Endoderm only","c":"Neural crest only","d":"Mesoderm only","ans":"A"},
{"t":"Dermatology","q":"The dermo-epidermal junction primarily functions to","a":"Produce pigment","b":"Anchor epidermis to dermis","c":"Secrete sweat","d":"Store fat","ans":"B"},
{"t":"Dermatology","q":"Melanin is synthesized from tyrosine by the enzyme","a":"Tyrosinase","b":"Lipase","c":"Elastase","d":"Collagenase","ans":"A"},
{"t":"Dermatology","q":"The acid mantle of the skin mainly protects against","a":"Mechanical trauma","b":"Bacterial colonization","c":"UV radiation","d":"Heat loss","ans":"B"},
{"t":"Dermatology","q":"In thick skin, the additional epidermal layer present is","a":"Stratum lucidum","b":"Stratum germinativum","c":"Stratum papillare","d":"Stratum reticulare","ans":"A"},
{"t":"Dermatology","q":"Epidermal turnover time in normal adult skin is approximately","a":"7 days","b":"14 days","c":"28 days","d":"60 days","ans":"C"},
{"t":"Dermatology","q":"The primary barrier to percutaneous drug absorption lies in","a":"Dermis","b":"Stratum corneum","c":"Subcutaneous tissue","d":"Hair follicle","ans":"B"},
{"t":"Dermatology","q":"Keratin intermediate filaments are mainly composed of","a":"Actin","b":"Tubulin","c":"Cytokeratins","d":"Myosin","ans":"C"},
{"t":"Dermatology","q":"Melanosomes are transferred to keratinocytes through","a":"Active phagocytosis of dendrite tips","b":"Diffusion","c":"Osmosis","d":"Gap junctions","ans":"A"},
{"t":"Dermatology","q":"The main chromophore responsible for UV-induced tanning is","a":"Hemoglobin","b":"Bilirubin","c":"Melanin","d":"Keratin","ans":"C"},
{"t":"Dermatology","q":"Apocrine glands become active primarily during","a":"Birth","b":"Childhood","c":"Puberty","d":"Old age","ans":"C"},
{"t":"Dermatology","q":"The nail matrix is responsible for","a":"Nail color","b":"Nail growth","c":"Nail hydration","d":"Nail sensation","ans":"B"},
{"t":"Dermatology","q":"Acanthosis refers to","a":"Epidermal thinning","b":"Dermal edema","c":"Epidermal hyperplasia of stratum spinosum","d":"Loss of keratin","ans":"C"},
{"t":"Dermatology","q":"The primary function of sebum is to","a":"Regulate temperature","b":"Lubricate skin and hair","c":"Provide sensation","d":"Produce vitamin D","ans":"B"},
{"t":"Dermatology","q":"The papillary dermis contains predominantly","a":"Thick collagen bundles","b":"Loose connective tissue","c":"Adipocytes","d":"Cartilage","ans":"B"},
{"t":"Dermatology","q":"Hair growth is cyclical; the resting phase is called","a":"Anagen","b":"Catagen","c":"Telogen","d":"Exogen","ans":"C"},
{"t":"Dermatology","q":"Vitamin D synthesis requires conversion of 7-dehydrocholesterol in","a":"Dermis","b":"Epidermis","c":"Subcutaneous tissue","d":"Sweat glands","ans":"B"},
{"t":"Dermatology","q":"The primary immune cell of epidermis presenting antigen to T-cells is","a":"Keratinocyte","b":"Melanocyte","c":"Langerhans cell","d":"Fibroblast","ans":"C"},
{"t":"Dermatology","q":"The tactile receptor associated with fine touch in fingertips is","a":"Pacinian corpuscle","b":"Meissner corpuscle","c":"Ruffini ending","d":"Free nerve ending","ans":"B"},
{"t":"Dermatology","q":"The dermis receives nutrition from","a":"Epidermal diffusion","b":"Dermal vascular plexus","c":"Sebaceous glands","d":"Sweat ducts","ans":"B"},
{"t":"Dermatology","q":"A wheal in urticaria is produced due to","a":"Epidermal necrosis","b":"Dermal edema","c":"Subcutaneous fibrosis","d":"Keratin deposition","ans":"B"},
{"t":"Dermatology","q":"The major component of the extracellular matrix giving tensile strength is","a":"Collagen type I","b":"Collagen type II","c":"Elastin","d":"Keratin","ans":"A"},
{"t":"Dermatology","q":"Transepidermal water loss mainly occurs through","a":"Sweat glands","b":"Stratum corneum diffusion","c":"Hair follicles only","d":"Sebaceous ducts","ans":"B"},
{"t":"Dermatology","q":"The basement membrane contains collagen type","a":"I","b":"II","c":"IV","d":"V","ans":"C"},
{"t":"Dermatology","q":"The skin microbiome mainly resides in","a":"Dermis","b":"Stratum corneum and appendages","c":"Subcutaneous fat","d":"Blood vessels","ans":"B"},
{"t":"Dermatology","q":"UVB radiation primarily causes","a":"Immediate tanning","b":"DNA pyrimidine dimers","c":"Dermal fibrosis","d":"Sweat suppression","ans":"B"},
{"t":"Dermatology","q":"Sebaceous glands are absent in","a":"Scalp","b":"Face","c":"Palms and soles","d":"Chest","ans":"C"},
{"t":"Dermatology","q":"The primary mediator of pruritus released from mast cells is","a":"Histamine","b":"Dopamine","c":"Serotonin","d":"Acetylcholine","ans":"A"},
{"t":"Dermatology","q":"The arrector pili muscle is innervated by","a":"Parasympathetic fibers","b":"Sympathetic fibers","c":"Somatic motor fibers","d":"Sensory fibers","ans":"B"},
{"t":"Dermatology","q":"The reticular dermis mainly consists of","a":"Dense irregular connective tissue","b":"Cartilage","c":"Muscle","d":"Loose connective tissue","ans":"A"},
{"t":"Dermatology","q":"A vesicle is defined as a fluid-filled lesion less than","a":"0.5 cm","b":"1 cm","c":"2 cm","d":"5 cm","ans":"A"},
{"t":"Dermatology","q":"The main source of skin regeneration after superficial injury is","a":"Dermal fibroblasts","b":"Hair follicle stem cells","c":"Subcutaneous adipocytes","d":"Vascular endothelium","ans":"B"},
{"t":"Dermatology","q":"Merkel cells are associated with","a":"Pressure sensation","b":"Temperature","c":"Pain","d":"Vibration","ans":"A"},
{"t":"Dermatology","q":"UVA radiation penetrates primarily into","a":"Stratum corneum","b":"Epidermis only","c":"Dermis","d":"Subcutaneous fat","ans":"C"},
{"t":"Dermatology","q":"Skin blanching on pressure occurs due to","a":"Vasodilation","b":"Blood displacement from vessels","c":"Pigment loss","d":"Keratin destruction","ans":"B"},
{"t":"Dermatology","q":"The most common cell in dermis is","a":"Fibroblast","b":"Keratinocyte","c":"Melanocyte","d":"Mast cell","ans":"A"},
{"t":"Dermatology","q":"Desmosomes connect","a":"Epidermis to dermis","b":"Keratinocyte to keratinocyte","c":"Dermis to muscle","d":"Nerves to vessels","ans":"B"},
{"t":"Dermatology","q":"Hemidesmosomes connect","a":"Keratinocytes to basement membrane","b":"Dermis to fat","c":"Nerves to epidermis","d":"Sweat gland to duct","ans":"A"},
{"t":"Dermatology","q":"The normal skin flora helps by","a":"Producing toxins","b":"Competing with pathogens","c":"Destroying collagen","d":"Increasing pH","ans":"B"},
{"t":"Dermatology","q":"The subcutaneous layer mainly acts as","a":"Sensory organ","b":"Insulation and energy storage","c":"Immune organ","d":"Pigment reservoir","ans":"B"},
{"t":"Dermatology","q":"Immediate tanning after sun exposure is due to","a":"New melanin synthesis","b":"Oxidation of existing melanin","c":"Keratin thickening","d":"Collagen deposition","ans":"B"},
{"t":"Dermatology","q":"A bulla is defined as lesion larger than","a":"0.5 cm","b":"1 cm","c":"2 cm","d":"5 cm","ans":"B"},
{"t":"Dermatology","q":"The most superficial dermal vascular network is","a":"Deep plexus","b":"Subcutaneous plexus","c":"Superficial horizontal plexus","d":"Muscular plexus","ans":"C"},
{"t":"Dermatology","q":"Sweat secretion is mediated by neurotransmitter","a":"Norepinephrine","b":"Acetylcholine","c":"Dopamine","d":"GABA","ans":"B"},
{"t":"Dermatology","q":"The primary cell forming scar tissue is","a":"Keratinocyte","b":"Fibroblast","c":"Melanocyte","d":"Mast cell","ans":"B"},
{"t":"Dermatology","q":"A macule is defined as","a":"Flat lesion without elevation","b":"Fluid filled lesion","c":"Pus filled lesion","d":"Nodular lesion","ans":"A"},
{"t":"Dermatology","q":"The skin acts as endocrine organ mainly through","a":"Insulin production","b":"Vitamin D synthesis","c":"Thyroxine release","d":"Cortisol secretion","ans":"B"},
{"t":"Dermatology","q":"Keloid formation results from excessive","a":"Elastin synthesis","b":"Collagen deposition","c":"Keratinization","d":"Melanin production","ans":"B"},
{"t":"Dermatology","q":"The primary barrier against UV radiation is","a":"Collagen","b":"Melanin","c":"Sebum","d":"Sweat","ans":"B"},
{"t":"Dermatology","q":"Skin temperature regulation occurs mainly via","a":"Hair growth","b":"Sebum secretion","c":"Sweating and vasomotor changes","d":"Keratin turnover","ans":"C"},
{"t":"Dermatology","q":"The most common site of scabies involvement in adults is","a":"Face","b":"Interdigital web spaces","c":"Scalp","d":"Back","ans":"B"},
{"t":"Dermatology","q":"The causative organism of scabies is","a":"Demodex folliculorum","b":"Sarcoptes scabiei var hominis","c":"Pediculus humanus","d":"Dermatophyte","ans":"B"},
{"t":"Dermatology","q":"Nocturnal itching is characteristic feature of","a":"Psoriasis","b":"Scabies","c":"Vitiligo","d":"Melasma","ans":"B"},
{"t":"Dermatology","q":"First line treatment of scabies","a":"Oral acyclovir","b":"Permethrin 5% cream","c":"Ketoconazole cream","d":"Clindamycin","ans":"B"},
{"t":"Dermatology","q":"Norwegian scabies is associated with","a":"Immunocompromised state","b":"Hyperthyroidism","c":"Diabetes insipidus","d":"Iron deficiency","ans":"A"},
{"t":"Dermatology","q":"Pediculosis capitis commonly affects","a":"Elderly men","b":"School children","c":"Neonates","d":"Athletes","ans":"B"},
{"t":"Dermatology","q":"Nits in pediculosis are found attached to","a":"Skin","b":"Hair shaft","c":"Sebaceous gland","d":"Nails","ans":"B"},
{"t":"Dermatology","q":"Drug of choice for pediculosis capitis","a":"Permethrin lotion","b":"Steroids","c":"Salicylic acid","d":"Acyclovir","ans":"A"},
{"t":"Dermatology","q":"Impetigo is most commonly caused by","a":"Staphylococcus aureus","b":"Mycobacterium leprae","c":"Candida albicans","d":"Herpes simplex virus","ans":"A"},
{"t":"Dermatology","q":"Honey colored crusted lesions are typical of","a":"Impetigo","b":"Psoriasis","c":"Tinea corporis","d":"Urticaria","ans":"A"},
{"t":"Dermatology","q":"Erysipelas commonly involves","a":"Upper dermis","b":"Subcutaneous tissue only","c":"Epidermis only","d":"Muscle","ans":"A"},
{"t":"Dermatology","q":"Cellulitis most commonly caused by","a":"Streptococcus pyogenes","b":"Candida","c":"HSV","d":"Mycobacterium","ans":"A"},
{"t":"Dermatology","q":"Furuncle is infection of","a":"Sweat gland","b":"Hair follicle","c":"Sebaceous cyst","d":"Nerve ending","ans":"B"},
{"t":"Dermatology","q":"Carbuncle is best described as","a":"Viral infection","b":"Multiple interconnected furuncles","c":"Fungal plaque","d":"Parasitic lesion","ans":"B"},
{"t":"Dermatology","q":"Hansen disease caused by","a":"Mycobacterium tuberculosis","b":"Mycobacterium leprae","c":"Treponema pallidum","d":"Nocardia","ans":"B"},
{"t":"Dermatology","q":"Lepromatous leprosy characterized by","a":"Strong cell mediated immunity","b":"Weak cell mediated immunity","c":"No bacteria","d":"Pure nerve disease","ans":"B"},
{"t":"Dermatology","q":"Tinea corporis caused by","a":"Dermatophytes","b":"Bacteria","c":"Virus","d":"Parasite","ans":"A"},
{"t":"Dermatology","q":"Central clearing with active border lesion suggests","a":"Tinea infection","b":"Psoriasis","c":"Eczema","d":"Urticaria","ans":"A"},
{"t":"Dermatology","q":"KOH mount used to diagnose","a":"Bacterial infection","b":"Fungal infection","c":"Viral infection","d":"Parasitic infection","ans":"B"},
{"t":"Dermatology","q":"Oral antifungal drug for extensive dermatophyte infection","a":"Fluconazole","b":"Acyclovir","c":"Penicillin","d":"Ivermectin","ans":"A"},
{"t":"Dermatology","q":"Pityriasis versicolor caused by","a":"Malassezia furfur","b":"Candida albicans","c":"Aspergillus","d":"Microsporum","ans":"A"},
{"t":"Dermatology","q":"Hypopigmented macules on chest with fine scaling seen in","a":"Tinea versicolor","b":"Vitiligo","c":"Psoriasis","d":"Leprosy","ans":"A"},
{"t":"Dermatology","q":"Herpes simplex virus typically causes","a":"Vesicular lesions","b":"Nodules","c":"Plaques","d":"Ulcers only","ans":"A"},
{"t":"Dermatology","q":"Treatment of herpes simplex infection","a":"Acyclovir","b":"Amoxicillin","c":"Ketoconazole","d":"Ivermectin","ans":"A"},
{"t":"Dermatology","q":"Varicella zoster virus reactivation causes","a":"Chickenpox","b":"Shingles","c":"Measles","d":"Rubella","ans":"B"},
{"t":"Dermatology","q":"Dermatomal painful vesicles indicate","a":"Herpes zoster","b":"Impetigo","c":"Tinea corporis","d":"Scabies","ans":"A"},
{"t":"Dermatology","q":"Molluscum contagiosum lesions are","a":"Umbilicated papules","b":"Vesicles","c":"Plaques","d":"Pustules","ans":"A"},
{"t":"Dermatology","q":"Warts are caused by","a":"HPV","b":"HSV","c":"EBV","d":"CMV","ans":"A"},
{"t":"Dermatology","q":"Condyloma acuminata caused by","a":"HPV","b":"HIV","c":"HBV","d":"HSV","ans":"A"},
{"t":"Dermatology","q":"Treatment of common wart","a":"Salicylic acid","b":"Steroid cream","c":"Antibiotics","d":"Antihistamines","ans":"A"},
{"t":"Dermatology","q":"Secondary bacterial infection of scabies commonly due to","a":"Staphylococcus aureus","b":"Mycobacterium","c":"Candida","d":"HSV","ans":"A"},
{"t":"Dermatology","q":"Ivermectin oral is useful in","a":"Crusted scabies","b":"Vitiligo","c":"Psoriasis","d":"Melasma","ans":"A"},
{"t":"Dermatology","q":"Leprosy nerve commonly involved earliest","a":"Ulnar nerve","b":"Sciatic nerve","c":"Median nerve","d":"Facial nerve","ans":"A"},
{"t":"Dermatology","q":"Acid fast bacilli seen in slit skin smear indicates","a":"Leprosy","b":"Tinea","c":"Scabies","d":"HSV","ans":"A"},
{"t":"Dermatology","q":"Satellite lesions around erythematous plaque typical of","a":"Candida infection","b":"Tinea","c":"Psoriasis","d":"Impetigo","ans":"A"},
{"t":"Dermatology","q":"Oral thrush caused by","a":"Candida albicans","b":"Dermatophyte","c":"HSV","d":"Bacteria","ans":"A"},
{"t":"Dermatology","q":"Kaposi varicelliform eruption occurs in","a":"Atopic dermatitis with HSV","b":"Psoriasis","c":"Tinea versicolor","d":"Vitiligo","ans":"A"},
{"t":"Dermatology","q":"Most contagious stage of varicella","a":"Before rash","b":"Vesicular stage","c":"Crust stage","d":"Scar stage","ans":"B"},
{"t":"Dermatology","q":"Treatment of cellulitis includes","a":"Systemic antibiotics","b":"Antifungals","c":"Antivirals","d":"Antiparasitic","ans":"A"},
{"t":"Dermatology","q":"Folliculitis most commonly caused by","a":"Staphylococcus aureus","b":"Candida","c":"Virus","d":"Mite","ans":"A"},
{"t":"Dermatology","q":"Boil formation is due to infection of","a":"Hair follicle and surrounding tissue","b":"Epidermis only","c":"Dermal vessels","d":"Sweat ducts","ans":"A"},
{"t":"Dermatology","q":"Dermatophytes invade primarily","a":"Keratinized tissue","b":"Blood vessels","c":"Muscle","d":"Nerves","ans":"A"},
{"t":"Dermatology","q":"Scabies burrow best seen in","a":"Finger web spaces","b":"Back","c":"Face","d":"Thigh","ans":"A"},
{"t":"Dermatology","q":"Tzanck smear useful in diagnosing","a":"Herpes virus infections","b":"Fungal infection","c":"Bacterial infection","d":"Parasitic infection","ans":"A"},
{"t":"Dermatology","q":"Rose gardener’s disease refers to","a":"Sporotrichosis","b":"Tinea","c":"Impetigo","d":"Scabies","ans":"A"},
{"t":"Dermatology","q":"Black dots in tinea capitis represent","a":"Broken hair shafts","b":"Pus","c":"Blood","d":"Keratin debris","ans":"A"},
{"t":"Dermatology","q":"Pseudohyphae on microscopy indicate","a":"Candida","b":"HSV","c":"Staphylococcus","d":"Mycobacterium","ans":"A"},
{"t":"Dermatology","q":"Post streptococcal glomerulonephritis complication of","a":"Impetigo","b":"Herpes","c":"Scabies","d":"Tinea","ans":"A"},
{"t":"Dermatology","q":"Erythema nodosum associated with","a":"Tuberculosis","b":"HSV","c":"Candida","d":"Scabies","ans":"A"},
{"t":"Dermatology","q":"Most important measure in treating infestations","a":"Treat close contacts","b":"Sun exposure","c":"Exercise","d":"Vitamins","ans":"A"},
{"t":"Dermatology","q":"A teenager presents with comedones, papules and pustules over face. Primary pathogenic factor in acne vulgaris is","a":"Increased sebum production","b":"Viral infection","c":"Autoimmune reaction","d":"Sweat gland blockage","ans":"A"},
{"t":"Dermatology","q":"The bacterium most associated with acne vulgaris is","a":"Staphylococcus epidermidis","b":"Cutibacterium acnes","c":"Streptococcus pyogenes","d":"Malassezia furfur","ans":"B"},
{"t":"Dermatology","q":"Open comedones are commonly called","a":"Whiteheads","b":"Nodules","c":"Blackheads","d":"Cysts","ans":"C"},
{"t":"Dermatology","q":"First line topical therapy for mild acne","a":"Oral isotretinoin","b":"Oral antibiotics","c":"Systemic steroids","d":"Topical benzoyl peroxide","ans":"D"},
{"t":"Dermatology","q":"A 16-year-old girl presents with inflammatory acne unresponsive to topical therapy. Next appropriate step","a":"Oral antibiotics","b":"Antifungal therapy","c":"Antiviral therapy","d":"Phototherapy","ans":"A"},
{"t":"Dermatology","q":"Severe nodulocystic acne drug of choice","a":"Doxycycline","b":"Isotretinoin","c":"Clindamycin topical","d":"Salicylic acid","ans":"B"},
{"t":"Dermatology","q":"A patient on isotretinoin must avoid pregnancy because of","a":"Hepatotoxicity","b":"Nephrotoxicity","c":"Teratogenicity","d":"Neurotoxicity","ans":"C"},
{"t":"Dermatology","q":"Pruritic erythematous lesions with vesicles and oozing most suggest","a":"Psoriasis","b":"Lichen planus","c":"Acne","d":"Eczema","ans":"D"},
{"t":"Dermatology","q":"The most common type of eczema in children","a":"Seborrheic dermatitis","b":"Atopic dermatitis","c":"Contact dermatitis","d":"Nummular eczema","ans":"B"},
{"t":"Dermatology","q":"Atopic dermatitis associated immunoglobulin","a":"IgA","b":"IgG","c":"IgM","d":"IgE","ans":"D"},
{"t":"Dermatology","q":"Flexural lichenification in a child with history of asthma indicates","a":"Psoriasis","b":"Atopic dermatitis","c":"Lichen planus","d":"Fungal infection","ans":"B"},
{"t":"Dermatology","q":"First line treatment of eczema flare","a":"Topical corticosteroids","b":"Oral antifungals","c":"Oral antivirals","d":"Retinoids","ans":"A"},
{"t":"Dermatology","q":"Chronic scratching in eczema leads to","a":"Koebner phenomenon","b":"Lichenification","c":"Scaling plaques","d":"Comedones","ans":"B"},
{"t":"Dermatology","q":"Well demarcated erythematous plaques with silvery scale suggest","a":"Eczema","b":"Lichen planus","c":"Psoriasis","d":"Tinea","ans":"C"},
{"t":"Dermatology","q":"Auspitz sign refers to","a":"Wickham striae","b":"Pinpoint bleeding on scale removal","c":"Central clearing","d":"Satellite lesions","ans":"B"},
{"t":"Dermatology","q":"Koebner phenomenon seen in","a":"Psoriasis","b":"Acne","c":"Urticaria","d":"Scabies","ans":"A"},
{"t":"Dermatology","q":"Most common site of psoriasis","a":"Flexures","b":"Extensor surfaces","c":"Face","d":"Palms only","ans":"B"},
{"t":"Dermatology","q":"Nail pitting indicates","a":"Psoriasis","b":"Eczema","c":"Acne","d":"Lichen simplex","ans":"A"},
{"t":"Dermatology","q":"Drug useful in severe psoriasis","a":"Methotrexate","b":"Acyclovir","c":"Ivermectin","d":"Fluconazole","ans":"A"},
{"t":"Dermatology","q":"Purple polygonal pruritic papules suggest","a":"Psoriasis","b":"Acne","c":"Lichen planus","d":"Impetigo","ans":"C"},
{"t":"Dermatology","q":"Wickham striae seen in","a":"Lichen planus","b":"Psoriasis","c":"Eczema","d":"Vitiligo","ans":"A"},
{"t":"Dermatology","q":"Lichen planus commonly involves","a":"Oral mucosa","b":"Scalp only","c":"Nails only","d":"Palms only","ans":"A"},
{"t":"Dermatology","q":"A 28-year-old presents with violaceous papules on wrist after trauma at same site. Phenomenon","a":"Auspitz sign","b":"Koebner phenomenon","c":"Nikolsky sign","d":"Darier sign","ans":"B"},
{"t":"Dermatology","q":"First line therapy for localized lichen planus","a":"Topical steroids","b":"Antibiotics","c":"Antivirals","d":"Retinoids","ans":"A"},
{"t":"Dermatology","q":"Acne scars form due to","a":"Increased keratinization only","b":"Dermal collagen destruction","c":"Sweat gland blockage","d":"Pigment loss","ans":"B"},
{"t":"Dermatology","q":"A patient with greasy scales over scalp and nasolabial folds likely has","a":"Seborrheic dermatitis","b":"Psoriasis","c":"Acne","d":"Tinea corporis","ans":"A"},
{"t":"Dermatology","q":"Main trigger in atopic dermatitis","a":"Barrier dysfunction","b":"Viral infection","c":"Bacterial toxin","d":"Drug allergy only","ans":"B"},
{"t":"Dermatology","q":"Psoriasis pathogenesis involves","a":"T cell mediated inflammation","b":"Fungal infection","c":"IgE hypersensitivity","d":"Mite infestation","ans":"A"},
{"t":"Dermatology","q":"Lichen planus associated with","a":"Hepatitis C","b":"Hepatitis A","c":"HIV only","d":"Tuberculosis","ans":"C"},
{"t":"Dermatology","q":"A patient with erythrodermic psoriasis complication risk","a":"Hypothermia and fluid loss","b":"Hypercalcemia","c":"Hypoglycemia","d":"Polycythemia","ans":"A"},
{"t":"Dermatology","q":"A teenager with moderate acne and inflammatory lesions on chest and back not responding to doxycycline. Next best step","a":"Oral isotretinoin","b":"Topical antifungal","c":"Antiviral therapy","d":"UV phototherapy","ans":"D"},
{"t":"Dermatology","q":"A child with severe itching, flexural eczema, allergic rhinitis and asthma has underlying","a":"Atopy","b":"Infection","c":"Malignancy","d":"Nutritional deficiency","ans":"A"},
{"t":"Dermatology","q":"A middle-aged patient has chronic plaques on elbows and knees with nail pitting and arthritis. Diagnosis","a":"Psoriatic arthritis","b":"Rheumatoid arthritis","c":"Osteoarthritis","d":"Gout","ans":"B"},
{"t":"Dermatology","q":"A patient develops violaceous oral lesions with burning sensation and white lacy lines. Diagnosis","a":"Lichen planus","b":"Leukoplakia","c":"Candidiasis","d":"Aphthous ulcer","ans":"A"},
{"t":"Dermatology","q":"A child with weeping erythematous lesions behind knees worsened by wool clothing likely has","a":"Atopic eczema","b":"Psoriasis","c":"Acne","d":"Scabies","ans":"C"},
{"t":"Dermatology","q":"A patient with sudden worsening psoriasis after steroid withdrawal has","a":"Rebound flare","b":"Infection","c":"Malignancy","d":"Drug allergy","ans":"A"},
{"t":"Dermatology","q":"An adult with itchy coin-shaped plaques on limbs most likely","a":"Nummular eczema","b":"Psoriasis","c":"Lichen planus","d":"Acne","ans":"D"},
{"t":"Dermatology","q":"A patient with generalized pustular psoriasis risk","a":"Sepsis","b":"Diabetes","c":"Hypertension","d":"Migraine","ans":"A"},
{"t":"Dermatology","q":"Hypertrophic lichen planus most commonly affects","a":"Shins","b":"Face","c":"Palms","d":"Scalp","ans":"B"},
{"t":"Dermatology","q":"A patient with acne worsened by cosmetics has","a":"Acne cosmetica","b":"Rosacea","c":"Folliculitis","d":"Milia","ans":"A"},
{"t":"Dermatology","q":"A patient with eczema develops honey colored crusts. Complication","a":"Secondary bacterial infection","b":"Fungal infection","c":"Viral infection","d":"Malignancy","ans":"C"},
{"t":"Dermatology","q":"A psoriatic patient develops joint stiffness in morning >1 hour indicates","a":"Psoriatic arthritis","b":"Osteoarthritis","c":"Gout","d":"Septic arthritis","ans":"A"},
{"t":"Dermatology","q":"A patient with flat topped papules on wrists intensely pruritic with pigmentation after healing has","a":"Lichen planus","b":"Psoriasis","c":"Eczema","d":"Acne","ans":"D"},
{"t":"Dermatology","q":"A child with chronic eczema needs long term maintenance therapy","a":"Emollients","b":"Antibiotics","c":"Antivirals","d":"Antifungals","ans":"A"},
{"t":"Dermatology","q":"A patient with psoriasis treated with UVB therapy mechanism","a":"Immunosuppression of T cells","b":"Bacterial killing","c":"Sebum reduction","d":"Collagen stimulation","ans":"C"},
{"t":"Dermatology","q":"A young adult with facial flushing and papules but no comedones likely has","a":"Rosacea","b":"Acne vulgaris","c":"Psoriasis","d":"Lichen planus","ans":"A"},
{"t":"Dermatology","q":"A patient with severe itching worse at night and thickened skin folds due to chronic eczema","a":"Lichen simplex chronicus","b":"Psoriasis","c":"Acne","d":"Tinea","ans":"B"},
{"t":"Dermatology","q":"A psoriasis patient with sudden hypocalcemia and widespread pustules has","a":"Generalized pustular psoriasis","b":"Acne fulminans","c":"Drug rash","d":"Viral exanthem","ans":"A"},
{"t":"Dermatology","q":"A patient with oral lichen planus risk increases for","a":"Squamous cell carcinoma","b":"Basal cell carcinoma","c":"Melanoma","d":"Sarcoma","ans":"D"},
{"t":"Dermatology","q":"A severe acne patient with fever, arthralgia and ulcerative nodules likely has","a":"Acne fulminans","b":"Rosacea","c":"Folliculitis","d":"Impetigo","ans":"A"},
{"t":"Dermatology","q":"The level of blister in pemphigus vulgaris is","a":"Subcorneal","b":"Subepidermal","c":"Suprabasal intraepidermal","d":"Dermal","ans":"A"},
{"t":"Dermatology","q":"Autoantibodies in pemphigus vulgaris target","a":"Hemidesmosomes","b":"Desmoglein 3","c":"Collagen IV","d":"Integrins","ans":"D"},
{"t":"Dermatology","q":"Nikolsky sign positive in","a":"Bullous pemphigoid","b":"Pemphigus vulgaris","c":"Dermatitis herpetiformis","d":"Porphyria cutanea tarda","ans":"C"},
{"t":"Dermatology","q":"Bullous pemphigoid blister is","a":"Flaccid","b":"Intraepidermal","c":"Pustular","d":"Tense subepidermal","ans":"B"},
{"t":"Dermatology","q":"Dermatitis herpetiformis associated with","a":"Gluten sensitivity","b":"Diabetes mellitus","c":"Tuberculosis","d":"Iron deficiency","ans":"D"},
{"t":"Dermatology","q":"Immunoglobulin deposited in dermatitis herpetiformis","a":"IgG","b":"IgA","c":"IgM","d":"IgE","ans":"A"},
{"t":"Dermatology","q":"First line treatment dermatitis herpetiformis","a":"Steroids","b":"Dapsone","c":"Acyclovir","d":"Methotrexate","ans":"C"},
{"t":"Dermatology","q":"Vitiligo characterized by loss of","a":"Keratinocytes","b":"Langerhans cells","c":"Melanocytes","d":"Fibroblasts","ans":"D"},
{"t":"Dermatology","q":"Wood lamp examination in vitiligo shows","a":"Yellow fluorescence","b":"Blue white accentuation","c":"Red fluorescence","d":"Green fluorescence","ans":"A"},
{"t":"Dermatology","q":"Melasma commonly triggered by","a":"Sun exposure and hormones","b":"Infection","c":"Trauma","d":"Fungal disease","ans":"C"},
{"t":"Dermatology","q":"Drug causing hyperpigmentation","a":"Minocycline","b":"Amoxicillin","c":"Paracetamol","d":"Metformin","ans":"B"},
{"t":"Dermatology","q":"Pitting of nails seen in","a":"Psoriasis","b":"Eczema","c":"Vitiligo","d":"Tinea versicolor","ans":"C"},
{"t":"Dermatology","q":"Clubbing indicates disease of","a":"Lung and heart","b":"Liver only","c":"Kidney only","d":"Thyroid only","ans":"D"},
{"t":"Dermatology","q":"Onychomycosis caused by","a":"Dermatophytes","b":"Virus","c":"Bacteria","d":"Parasite","ans":"B"},
{"t":"Dermatology","q":"Koilonychia seen in","a":"Iron deficiency anemia","b":"Polycythemia","c":"Hyperthyroidism","d":"Diabetes","ans":"C"},
{"t":"Dermatology","q":"Androgenetic alopecia due to effect of","a":"DHT on hair follicles","b":"Estrogen excess","c":"Cortisol deficiency","d":"Insulin excess","ans":"B"},
{"t":"Dermatology","q":"Alopecia areata mechanism","a":"Autoimmune attack on hair follicle","b":"Fungal infection","c":"Trauma","d":"Bacterial infection","ans":"C"},
{"t":"Dermatology","q":"Telogen effluvium occurs after","a":"Physiologic stress","b":"Infection only","c":"Vitamin overdose","d":"Allergy","ans":"D"},
{"t":"Dermatology","q":"Tinea capitis causes hair","a":"Broken black dots","b":"Excess growth","c":"Curling","d":"Whitening","ans":"B"},
{"t":"Dermatology","q":"Primary chancre of syphilis is","a":"Painful ulcer","b":"Painless indurated ulcer","c":"Vesicle","d":"Plaque","ans":"A"},
{"t":"Dermatology","q":"Secondary syphilis rash typically involves","a":"Palms and soles","b":"Face only","c":"Scalp only","d":"Nails only","ans":"D"},
{"t":"Dermatology","q":"Diagnostic test for syphilis screening","a":"VDRL","b":"KOH","c":"Gram stain","d":"Tzanck smear","ans":"B"},
{"t":"Dermatology","q":"Treatment of syphilis drug of choice","a":"Penicillin G","b":"Doxycycline","c":"Acyclovir","d":"Azithromycin","ans":"C"},
{"t":"Dermatology","q":"Painful grouped vesicles genital area suggests","a":"Herpes simplex virus","b":"HPV","c":"Syphilis","d":"Chlamydia","ans":"D"},
{"t":"Dermatology","q":"Genital warts caused by","a":"HPV 6,11","b":"HSV","c":"Treponema","d":"Candida","ans":"B"},
{"t":"Dermatology","q":"Donovanosis characterized by","a":"Beefy red painless ulcers","b":"Vesicles","c":"Nodules","d":"Plaques","ans":"D"},
{"t":"Dermatology","q":"Chancroid caused by","a":"Haemophilus ducreyi","b":"Treponema pallidum","c":"HSV","d":"HPV","ans":"B"},
{"t":"Dermatology","q":"Lymphogranuloma venereum caused by","a":"Chlamydia trachomatis L1-3","b":"HSV","c":"Gonorrhea","d":"Syphilis","ans":"C"},
{"t":"Dermatology","q":"First stage HIV skin manifestation","a":"Maculopapular rash","b":"Psoriasis","c":"Vitiligo","d":"Alopecia","ans":"B"},
{"t":"Dermatology","q":"Kaposi sarcoma associated virus","a":"HHV-8","b":"HSV-1","c":"HPV","d":"EBV","ans":"C"},
{"t":"Dermatology","q":"A patient presents with flaccid blisters, erosions in mouth, positive Nikolsky sign. Diagnosis","a":"Pemphigus vulgaris","b":"Bullous pemphigoid","c":"Dermatitis herpetiformis","d":"Impetigo","ans":"B"},
{"t":"Dermatology","q":"An elderly patient has tense bullae on trunk, negative Nikolsky sign. Diagnosis","a":"Bullous pemphigoid","b":"Pemphigus vulgaris","c":"SJS","d":"TEN","ans":"D"},
{"t":"Dermatology","q":"A young adult with intensely itchy grouped vesicles on elbows and gluten intolerance. Diagnosis","a":"Dermatitis herpetiformis","b":"Pemphigus","c":"Bullous pemphigoid","d":"Eczema","ans":"B"},
{"t":"Dermatology","q":"A woman with symmetrical depigmented patches on hands accentuated under Wood lamp. Management first step","a":"Topical steroids or tacrolimus","b":"Antibiotics","c":"Antifungal","d":"Antiviral","ans":"D"},
{"t":"Dermatology","q":"A man with spoon shaped nails and fatigue. Investigation most relevant","a":"Serum ferritin","b":"Blood sugar","c":"Thyroid test","d":"LFT","ans":"B"},
{"t":"Dermatology","q":"A patchy non scarring hair loss with exclamation mark hairs suggests","a":"Alopecia areata","b":"Tinea capitis","c":"Telogen effluvium","d":"Trichotillomania","ans":"D"},
{"t":"Dermatology","q":"A patient with multiple sexual partners presents painless ulcer and positive VDRL. Management","a":"Benzathine penicillin","b":"Acyclovir","c":"Fluconazole","d":"Steroids","ans":"B"},
{"t":"Dermatology","q":"Painful genital ulcer with tender lymph nodes and purulent base. Diagnosis","a":"Chancroid","b":"Syphilis","c":"HSV","d":"LGV","ans":"D"},
{"t":"Dermatology","q":"HIV patient develops violaceous plaques on skin and oral mucosa. Cause","a":"Kaposi sarcoma","b":"Psoriasis","c":"Drug rash","d":"Tinea","ans":"C"},
{"t":"Dermatology","q":"A woman with diffuse hair shedding 3 months after childbirth. Diagnosis","a":"Telogen effluvium","b":"Alopecia areata","c":"Androgenetic alopecia","d":"Tinea capitis","ans":"C"},
{"t":"Dermatology","q":"A 30-year-old presents with recurrent oral erosions and flaccid bullae over trunk, histology shows acantholysis above basal layer. Most specific test","a":"Direct immunofluorescence IgG intercellular","b":"KOH mount","c":"Gram stain","d":"PAS stain","ans":"B"},
{"t":"Dermatology","q":"A patient with chronic pruritic plaques over elbows improves on gluten free diet. Mechanism","a":"IgA deposition in dermal papillae","b":"IgG basement membrane","c":"Complement deficiency","d":"Fungal hypersensitivity","ans":"D"},
{"t":"Dermatology","q":"A 22-year-old woman presents with irregular hyperpigmented facial patches worsening in pregnancy. Best management","a":"Sunscreen and hydroquinone","b":"Oral antibiotics","c":"Oral antivirals","d":"Steroids injection","ans":"B"},
{"t":"Dermatology","q":"A nail plate separates from nail bed in hyperthyroidism. Term","a":"Onycholysis","b":"Clubbing","c":"Koilonychia","d":"Beau lines","ans":"D"},
{"t":"Dermatology","q":"A patient with patterned hair loss and miniaturized follicles. Drug therapy","a":"Finasteride","b":"Methotrexate","c":"Acyclovir","d":"Dapsone","ans":"B"},
{"t":"Dermatology","q":"A man presents with painless genital ulcer followed weeks later by generalized rash involving palms and soles. Stage","a":"Secondary syphilis","b":"Primary syphilis","c":"Latent syphilis","d":"Tertiary syphilis","ans":"C"},
{"t":"Dermatology","q":"HIV positive patient presents with multiple pearly papules with central umbilication in genital area. Cause","a":"Molluscum contagiosum","b":"HPV","c":"HSV","d":"Candida","ans":"B"},
{"t":"Dermatology","q":"A young male with painful grouped vesicles recurrent at same site genital region. Latency location of virus","a":"Sacral dorsal root ganglion","b":"Spinal cord","c":"Blood","d":"Skin","ans":"C"},
{"t":"Dermatology","q":"A patient develops sudden diffuse epidermal detachment after drug exposure, positive Nikolsky sign, mucosal erosions. Diagnosis","a":"Toxic epidermal necrolysis","b":"Pemphigus vulgaris","c":"Bullous pemphigoid","d":"Erythema multiforme minor","ans":"D"},
{"t":"Dermatology","q":"A sexually active patient presents with beefy red painless genital ulcer bleeding on touch and Donovan bodies on smear. Diagnosis","a":"Granuloma inguinale","b":"Chancroid","c":"Syphilis","d":"Herpes","ans":"B"}
];