window.MM=window.MM||{};
window.MM.med_p2_cns=[
{"t":"CNS / Neurology","q":"A 28-year-old woman presents with recurrent unilateral throbbing headache associated with photophobia, phonophobia and nausea lasting 6–12 hours and worsened by activity. Most likely diagnosis?","a":"Sinus headache","b":"Cluster headache","c":"Migraine","d":"Tension headache","ans":"C"},
{"t":"CNS / Neurology","q":"A patient develops severe unilateral periorbital pain lasting 30–60 minutes occurring daily for 2 weeks with lacrimation and nasal congestion. Diagnosis?","a":"Tension headache","b":"Trigeminal neuralgia","c":"Migraine with aura","d":"Cluster headache","ans":"D"},
{"t":"CNS / Neurology","q":"A 35-year-old office worker reports bilateral band-like tightness around head without nausea and not worsened by activity. Most likely diagnosis?","a":"Cluster headache","b":"Tension type headache","c":"Temporal arteritis","d":"Migraine","ans":"B"},
{"t":"CNS / Neurology","q":"First-line acute treatment of migraine?","a":"Amitriptyline","b":"Topiramate","c":"Sumatriptan","d":"Propranolol","ans":"C"},
{"t":"CNS / Neurology","q":"Drug used for migraine prophylaxis?","a":"Paracetamol","b":"Propranolol","c":"Metoclopramide","d":"Diclofenac","ans":"B"},
{"t":"CNS / Neurology","q":"Oxygen therapy is most effective in:","a":"Sinus headache","b":"Tension headache","c":"Migraine","d":"Cluster headache","ans":"D"},
{"t":"CNS / Neurology","q":"Ergotamine derivatives act mainly by:","a":"Prostaglandin inhibition","b":"Serotonin receptor agonism","c":"Beta-blockade","d":"Dopamine blockade","ans":"B"},
{"t":"CNS / Neurology","q":"Contraindication to ergotamine use?","a":"Asthma","b":"Diabetes","c":"Pregnancy","d":"Hypertension","ans":"C"},
{"t":"CNS / Neurology","q":"Drug of choice for chronic migraine prophylaxis in obese patient?","a":"Valproate","b":"Amitriptyline","c":"Propranolol","d":"Topiramate","ans":"D"},
{"t":"CNS / Neurology","q":"Migraine aura is caused by:","a":"Meningeal irritation","b":"Increased ICP","c":"Cortical spreading depression","d":"Vasospasm only","ans":"C"},
{"t":"CNS / Neurology","q":"A 24-year-old woman experiences flashing zigzag lines in vision followed by unilateral pulsatile headache and vomiting lasting 8 hours. Most appropriate acute treatment?","a":"Propranolol","b":"Sumatriptan","c":"Amitriptyline","d":"Morphine","ans":"B"},
{"t":"CNS / Neurology","q":"Red flag headache feature requiring imaging?","a":"Relieved by sleep","b":"Thunderclap onset","c":"Gradual onset","d":"Recurrent pattern","ans":"B"},
{"t":"CNS / Neurology","q":"First investigation in suspected subarachnoid hemorrhage presenting as worst headache of life?","a":"X-ray skull","b":"EEG","c":"CT brain","d":"MRI","ans":"C"},
{"t":"CNS / Neurology","q":"Tension headache is associated with:","a":"Vomiting","b":"Aura","c":"Bilateral tight band pain","d":"Autonomic symptoms","ans":"C"},
{"t":"CNS / Neurology","q":"A 40-year-old smoker presents with severe unilateral orbital pain waking him from sleep at same time every night for 10 days with ptosis and lacrimation. Best acute therapy?","a":"Amitriptyline","b":"High-flow oxygen","c":"Propranolol","d":"IV steroids","ans":"B"},
{"t":"CNS / Neurology","q":"Drug avoided in basilar migraine?","a":"NSAIDs","b":"Antiemetics","c":"Triptans","d":"Paracetamol","ans":"C"},
{"t":"CNS / Neurology","q":"Mechanism of triptans in migraine:","a":"CGRP receptor agonist","b":"NMDA blocker","c":"5-HT1B/1D agonist","d":"Dopamine antagonist","ans":"C"},
{"t":"CNS / Neurology","q":"Chronic daily headache most commonly due to:","a":"Meningitis","b":"Aneurysm","c":"Medication overuse","d":"Tumor","ans":"C"},
{"t":"CNS / Neurology","q":"Preferred prophylaxis in patient with migraine and hypertension?","a":"Valproate","b":"Propranolol","c":"Topiramate","d":"Flunarizine","ans":"B"},
{"t":"CNS / Neurology","q":"A 52-year-old female presents with new onset headache, scalp tenderness and jaw claudication with ESR 85 mm/hr. Immediate treatment?","a":"Carbamazepine","b":"Aspirin","c":"Sumatriptan","d":"Prednisolone","ans":"D"},
{"t":"CNS / Neurology","q":"Drug useful in menstrual migraine prophylaxis?","a":"Diazepam","b":"Naproxen","c":"Haloperidol","d":"Morphine","ans":"B"},
{"t":"CNS / Neurology","q":"Cluster headache prophylaxis drug of choice?","a":"Topiramate","b":"Amitriptyline","c":"Verapamil","d":"Propranolol","ans":"C"},
{"t":"CNS / Neurology","q":"A patient presents with progressive morning headache with vomiting and papilledema. Likely cause?","a":"Cluster headache","b":"Tension headache","c":"Raised ICP","d":"Migraine","ans":"C"},
{"t":"CNS / Neurology","q":"Most common trigger for migraine:","a":"Sleep","b":"Cold weather","c":"Exercise","d":"Stress","ans":"D"},
{"t":"CNS / Neurology","q":"Drug causing medication overuse headache:","a":"Insulin","b":"Antacids","c":"Daily analgesics","d":"Antibiotics","ans":"C"},
{"t":"CNS / Neurology","q":"A 19-year-old student has bilateral pressing headache during exams lasting whole day without nausea and relieved by massage. Best treatment?","a":"Ergotamine","b":"Oxygen","c":"NSAIDs","d":"Sumatriptan","ans":"C"},
{"t":"CNS / Neurology","q":"Role of ergotamine in migraine:","a":"Prevent aura","b":"Cure disease","c":"Prophylaxis","d":"Acute attack treatment","ans":"D"},
{"t":"CNS / Neurology","q":"Side effect of ergotamine:","a":"Sedation","b":"Peripheral ischemia","c":"Hyperglycemia","d":"Hypertension","ans":"B"},
{"t":"CNS / Neurology","q":"Preferred antiemetic in migraine:","a":"Lorazepam","b":"Atropine","c":"Metoclopramide","d":"Haloperidol","ans":"C"},
{"t":"CNS / Neurology","q":"A patient develops unilateral headache with rhinorrhea and conjunctival injection lasting 45 minutes daily in clusters for 1 month. Best prophylaxis?","a":"Amitriptyline","b":"Verapamil","c":"Propranolol","d":"Valproate","ans":"B"},
{"t":"CNS / Neurology","q":"Migraine prophylaxis indicated when attacks occur:","a":"Once yearly","b":"Once monthly","c":"≥4 per month","d":"Only severe","ans":"C"},
{"t":"CNS / Neurology","q":"Drug avoided in pregnancy for migraine prophylaxis:","a":"Paracetamol","b":"Valproate","c":"Propranolol","d":"Magnesium","ans":"B"},
{"t":"CNS / Neurology","q":"A 32-year-old female has recurrent headaches worsened by bending forward with nasal discharge and fever. Diagnosis?","a":"Cluster headache","b":"Tension headache","c":"Sinus headache","d":"Migraine","ans":"C"},
{"t":"CNS / Neurology","q":"Which headache improves with sleep?","a":"Cluster headache","b":"Tension headache","c":"Migraine","d":"Tumor","ans":"C"},
{"t":"CNS / Neurology","q":"Best prophylaxis in migraine with depression?","a":"Amitriptyline","b":"Topiramate","c":"Propranolol","d":"Verapamil","ans":"A"},
{"t":"CNS / Neurology","q":"A 45-year-old man presents with sudden worst headache of life while lifting weight followed by neck stiffness and photophobia. CT is negative. Next step?","a":"Angiography","b":"EEG","c":"Lumbar puncture","d":"MRI","ans":"C"},
{"t":"CNS / Neurology","q":"CGRP antagonists are used in:","a":"Tension headache","b":"Meningitis","c":"Acute cluster headache","d":"Migraine prophylaxis","ans":"D"},
{"t":"CNS / Neurology","q":"Drug causing weight loss helpful in migraine prophylaxis:","a":"Amitriptyline","b":"Propranolol","c":"Topiramate","d":"Valproate","ans":"C"},
{"t":"CNS / Neurology","q":"A patient with asthma requires migraine prophylaxis. Avoid:","a":"Amitriptyline","b":"Verapamil","c":"Topiramate","d":"Propranolol","ans":"D"},
{"t":"CNS / Neurology","q":"Headache associated with tearing, ptosis and miosis suggests:","a":"Tension headache","b":"Cluster headache","c":"Tumor","d":"Migraine","ans":"B"},
{"t":"CNS / Neurology","q":"Most common primary headache disorder:","a":"Cluster headache","b":"Neuralgia","c":"Tension headache","d":"Migraine","ans":"C"},
{"t":"CNS / Neurology","q":"A 30-year-old woman has 5 migraine attacks monthly despite NSAIDs. Next step?","a":"Antibiotics","b":"Surgery","c":"Stop treatment","d":"Start prophylaxis","ans":"D"},
{"t":"CNS / Neurology","q":"Drug used in status migrainosus:","a":"Digoxin","b":"Heparin","c":"IV dihydroergotamine","d":"Insulin","ans":"C"},
{"t":"CNS / Neurology","q":"Aura typically lasts:","a":"24 hours","b":"5–60 minutes","c":"2 days","d":"Seconds","ans":"B"},
{"t":"CNS / Neurology","q":"A patient with migraine develops chest tightness after medication. Likely drug?","a":"Metoclopramide","b":"Naproxen","c":"Paracetamol","d":"Triptan","ans":"D"},
{"t":"CNS / Neurology","q":"First-line acute therapy in mild migraine:","a":"Verapamil","b":"NSAIDs","c":"Propranolol","d":"Valproate","ans":"B"},
{"t":"CNS / Neurology","q":"A young male presents with strictly unilateral headache around eye occurring at same time daily for 6 weeks then disappearing for months. Disease pattern?","a":"Chronic tension headache","b":"Sinusitis","c":"Episodic cluster headache","d":"Chronic migraine","ans":"C"},
{"t":"CNS / Neurology","q":"Prophylaxis preferred in obese migraine patient with epilepsy:","a":"Propranolol","b":"Flunarizine","c":"Amitriptyline","d":"Topiramate","ans":"D"},
{"t":"CNS / Neurology","q":"Headache worsened by Valsalva maneuver suggests:","a":"Tension headache","b":"Cluster headache","c":"Raised ICP","d":"Migraine","ans":"C"},
{"t":"CNS / Neurology","q":"A patient overuses triptans daily and now has persistent daily headache. Diagnosis?","a":"Temporal arteritis","b":"Medication overuse headache","c":"Cluster headache","d":"Chronic migraine","ans":"B"},
{"t":"CNS / Neurology","q":"A 65-year-old man presents with progressive slowness of movement, resting tremor and cogwheel rigidity with reduced arm swing. Most likely diagnosis?","a":"Huntington disease","b":"Cerebellar ataxia","c":"Parkinson disease","d":"Essential tremor","ans":"C"},
{"t":"CNS / Neurology","q":"The primary neurotransmitter deficiency in Parkinson disease is:","a":"Norepinephrine","b":"Acetylcholine","c":"Serotonin","d":"Dopamine","ans":"D"},
{"t":"CNS / Neurology","q":"A 52-year-old patient newly diagnosed with Parkinson disease with mild symptoms is young and active. Preferred initial therapy?","a":"Phenytoin","b":"Dopamine agonist","c":"Levodopa","d":"Haloperidol","ans":"B"},
{"t":"CNS / Neurology","q":"Carbidopa is given with levodopa to:","a":"Cross BBB","b":"Prevent peripheral metabolism","c":"Prevent dyskinesia","d":"Increase excretion","ans":"B"},
{"t":"CNS / Neurology","q":"A patient on long-term levodopa develops alternating mobility and immobility phases during the day. This represents:","a":"Akathisia","b":"Drug toxicity","c":"On–off phenomenon","d":"Serotonin syndrome","ans":"C"},
{"t":"CNS / Neurology","q":"Histopathology of Parkinson disease shows:","a":"Astrocytosis","b":"Demyelination","c":"Lewy bodies","d":"Plaques only","ans":"C"},
{"t":"CNS / Neurology","q":"A young woman develops rigidity and tremors after taking antiemetic therapy for vomiting. Most likely drug responsible?","a":"Ranitidine","b":"Omeprazole","c":"Metoclopramide","d":"Ondansetron","ans":"C"},
{"t":"CNS / Neurology","q":"ALS involves degeneration of:","a":"Cerebellar neurons","b":"Upper and lower motor neurons","c":"Autonomic neurons","d":"Sensory neurons","ans":"B"},
{"t":"CNS / Neurology","q":"A 58-year-old male has progressive muscle wasting, fasciculations and brisk reflexes without sensory loss. Most likely diagnosis?","a":"Myopathy","b":"Peripheral neuropathy","c":"ALS","d":"Myasthenia gravis","ans":"C"},
{"t":"CNS / Neurology","q":"Most common cause of dementia worldwide:","a":"Lewy body dementia","b":"Alzheimer disease","c":"Frontotemporal dementia","d":"Vascular dementia","ans":"B"},
{"t":"CNS / Neurology","q":"Neurochemical deficit in Alzheimer disease:","a":"Histamine","b":"Glycine","c":"Acetylcholine","d":"Dopamine","ans":"C"},
{"t":"CNS / Neurology","q":"Drug used in early Alzheimer disease:","a":"Donepezil","b":"Haloperidol","c":"Levodopa","d":"Carbamazepine","ans":"A"},
{"t":"CNS / Neurology","q":"Drug added in moderate–severe Alzheimer disease:","a":"Diazepam","b":"Phenytoin","c":"Fluoxetine","d":"Memantine","ans":"D"},
{"t":"CNS / Neurology","q":"Alzheimer pathology includes:","a":"Hemorrhage","b":"Abscess","c":"Amyloid plaques","d":"Demyelination","ans":"C"},
{"t":"CNS / Neurology","q":"A 19-year-old presents with tremor, psychiatric symptoms and abnormal liver function tests. Most likely disorder?","a":"Multiple sclerosis","b":"Hemochromatosis","c":"Wilson disease","d":"Huntington disease","ans":"C"},
{"t":"CNS / Neurology","q":"Eye finding diagnostic of Wilson disease:","a":"Optic neuritis","b":"Kayser–Fleischer ring","c":"Cherry red spot","d":"Papilledema","ans":"B"},
{"t":"CNS / Neurology","q":"First-line treatment of Wilson disease:","a":"Mannitol","b":"Iron","c":"Penicillamine","d":"Steroids","ans":"C"},
{"t":"CNS / Neurology","q":"Subacute combined degeneration is caused by deficiency of:","a":"Vitamin B1","b":"Vitamin D","c":"Vitamin B12","d":"Vitamin B6","ans":"C"},
{"t":"CNS / Neurology","q":"Neurological sign of B12 deficiency:","a":"Nystagmus only","b":"Loss of vibration sense","c":"Diplopia","d":"Facial palsy","ans":"B"},
{"t":"CNS / Neurology","q":"Chronic alcoholism most commonly causes deficiency of:","a":"Vitamin E","b":"Vitamin K","c":"Thiamine","d":"Vitamin C","ans":"C"},
{"t":"CNS / Neurology","q":"A malnourished alcoholic presents with confusion, ataxia and nystagmus after hospital admission. Diagnosis?","a":"Wernicke encephalopathy","b":"Hypoglycemia","c":"Meningitis","d":"Stroke","ans":"A"},
{"t":"CNS / Neurology","q":"Immediate management of suspected Wernicke encephalopathy:","a":"Insulin","b":"IV glucose","c":"Steroids","d":"IV thiamine","ans":"D"},
{"t":"CNS / Neurology","q":"Giving glucose before thiamine leads to:","a":"Hypokalemia","b":"Recovery","c":"Worsening neurological injury","d":"Seizure prevention","ans":"C"},
{"t":"CNS / Neurology","q":"Korsakoff psychosis presents with:","a":"Chorea","b":"Confabulation","c":"Hemiplegia","d":"Aphasia","ans":"B"},
{"t":"CNS / Neurology","q":"Memory impairment in Korsakoff syndrome mainly affects:","a":"Motor memory","b":"Procedural memory","c":"Immediate memory","d":"Short-term memory","ans":"D"},
{"t":"CNS / Neurology","q":"Parkinson tremor occurs mainly:","a":"During sleep","b":"During posture holding","c":"At rest","d":"During action","ans":"C"},
{"t":"CNS / Neurology","q":"Drug useful for levodopa-induced dyskinesia:","a":"Phenytoin","b":"Amantadine","c":"Ethosuximide","d":"Diazepam","ans":"B"},
{"t":"CNS / Neurology","q":"ALS typically spares:","a":"Respiration","b":"Motor function","c":"Reflexes","d":"Sensory function","ans":"D"},
{"t":"CNS / Neurology","q":"Common cause of death in ALS:","a":"Stroke","b":"Liver failure","c":"Respiratory failure","d":"Renal failure","ans":"C"},
{"t":"CNS / Neurology","q":"Earliest symptom in Alzheimer disease:","a":"Seizures","b":"Aphasia","c":"Memory impairment","d":"Personality change","ans":"C"},
{"t":"CNS / Neurology","q":"MRI finding in Alzheimer disease:","a":"Hydrocephalus","b":"Hippocampal atrophy","c":"Brain abscess","d":"Hemorrhage","ans":"B"},
{"t":"CNS / Neurology","q":"Copper deposition in Wilson disease occurs mainly in:","a":"Spinal cord","b":"Medulla","c":"Basal ganglia","d":"Cerebellum","ans":"C"},
{"t":"CNS / Neurology","q":"Additional therapy in Wilson disease:","a":"Potassium","b":"Calcium","c":"Zinc","d":"Magnesium","ans":"C"},
{"t":"CNS / Neurology","q":"Anemia seen in B12 deficiency:","a":"Hemolytic","b":"Macrocytic","c":"Normocytic","d":"Microcytic","ans":"B"},
{"t":"CNS / Neurology","q":"Alcoholic patient develops confusion after receiving dextrose infusion in ER. Likely diagnosis?","a":"Hypokalemia","b":"Stroke","c":"Wernicke encephalopathy","d":"Delirium tremens","ans":"C"},
{"t":"CNS / Neurology","q":"Lesion location in Korsakoff syndrome:","a":"Cerebellum","b":"Mammillary bodies","c":"Pons","d":"Occipital cortex","ans":"B"},
{"t":"CNS / Neurology","q":"Typical gait in Parkinson disease:","a":"Shuffling","b":"Wide-based","c":"Spastic","d":"Ataxic","ans":"A"},
{"t":"CNS / Neurology","q":"Mask-like facies occurs in:","a":"Wilson disease","b":"ALS","c":"Myasthenia gravis","d":"Parkinson disease","ans":"D"},
{"t":"CNS / Neurology","q":"Drug that worsens Parkinson disease symptoms:","a":"Selegiline","b":"Pramipexole","c":"Haloperidol","d":"Levodopa","ans":"C"},
{"t":"CNS / Neurology","q":"Drug prolonging survival in ALS:","a":"Donepezil","b":"Riluzole","c":"Steroids","d":"Levodopa","ans":"B"},
{"t":"CNS / Neurology","q":"Alzheimer disease also shows:","a":"Glioma","b":"Neurofibrillary tangles","c":"Calcification","d":"Demyelination","ans":"B"},
{"t":"CNS / Neurology","q":"Inheritance pattern of Wilson disease:","a":"X-linked","b":"Mitochondrial","c":"Autosomal dominant","d":"Autosomal recessive","ans":"D"},
{"t":"CNS / Neurology","q":"Neuropathy in B12 deficiency is:","a":"Cranial only","b":"Autonomic only","c":"Pure motor","d":"Mixed sensory-motor","ans":"D"},
{"t":"CNS / Neurology","q":"Severe alcohol withdrawal complication:","a":"Absence seizure","b":"Delirium tremens","c":"Stroke","d":"Migraine","ans":"B"},
{"t":"CNS / Neurology","q":"Treatment of delirium tremens:","a":"Morphine","b":"Phenytoin","c":"Haloperidol alone","d":"Diazepam","ans":"D"},
{"t":"CNS / Neurology","q":"Postural instability in Parkinson disease leads to:","a":"Deafness","b":"Aphasia","c":"Falls","d":"Blindness","ans":"C"},
{"t":"CNS / Neurology","q":"Reflex pattern in ALS:","a":"Absent reflexes only","b":"Hyporeflexia with sensory loss","c":"Normal reflexes","d":"Hyperreflexia with wasting","ans":"D"},
{"t":"CNS / Neurology","q":"Dementia with visual hallucinations and fluctuating cognition:","a":"Wilson disease","b":"Vascular dementia","c":"Lewy body dementia","d":"Alzheimer disease","ans":"C"},
{"t":"CNS / Neurology","q":"Screening test for dementia:","a":"LP","b":"CT scan","c":"MMSE","d":"EEG","ans":"C"},
{"t":"CNS / Neurology","q":"Chronic alcoholic with severe memory gaps fills stories to compensate. Diagnosis?","a":"Alzheimer disease","b":"Depression","c":"Wernicke encephalopathy","d":"Korsakoff psychosis","ans":"D"},
{"t":"CNS / Neurology","q":"A 22-year-old student presents with fever, headache, neck stiffness and photophobia for 12 hours. Most likely diagnosis?","a":"Brain tumor","b":"Meningitis","c":"Migraine","d":"Encephalitis","ans":"B"},
{"t":"CNS / Neurology","q":"Classical triad of meningitis includes fever, neck stiffness and:","a":"Seizures","b":"Rash","c":"Altered mental status","d":"Vomiting","ans":"C"},
{"t":"CNS / Neurology","q":"Most common cause of acute bacterial meningitis in young adults:","a":"Streptococcus pneumoniae","b":"Listeria monocytogenes","c":"Neisseria meningitidis","d":"Haemophilus influenzae","ans":"C"},
{"t":"CNS / Neurology","q":"Most common cause of bacterial meningitis in elderly:","a":"HSV","b":"Mycoplasma","c":"Neisseria meningitidis","d":"Listeria monocytogenes","ans":"D"},
{"t":"CNS / Neurology","q":"Viral meningitis CSF shows:","a":"Low glucose","b":"High protein very high","c":"Lymphocytic predominance","d":"Neutrophils predominance","ans":"C"},
{"t":"CNS / Neurology","q":"Bacterial meningitis CSF finding:","a":"Lymphocytes","b":"Low glucose","c":"Low protein","d":"Normal glucose","ans":"B"},
{"t":"CNS / Neurology","q":"Opening pressure in bacterial meningitis is usually:","a":"Zero","b":"Normal","c":"Low","d":"High","ans":"D"},
{"t":"CNS / Neurology","q":"Contraindication to lumbar puncture before imaging:","a":"Headache","b":"Fever","c":"Papilledema","d":"Neck pain","ans":"C"},
{"t":"CNS / Neurology","q":"First investigation in suspected meningitis without focal deficits:","a":"MRI","b":"CT scan","c":"EEG","d":"Lumbar puncture","ans":"D"},
{"t":"CNS / Neurology","q":"Empirical treatment in adult bacterial meningitis includes:","a":"Amoxicillin only","b":"Acyclovir only","c":"Ceftriaxone + vancomycin","d":"Metronidazole only","ans":"C"},
{"t":"CNS / Neurology","q":"Drug added in elderly meningitis for Listeria coverage:","a":"Rifampicin","b":"Gentamicin","c":"Ampicillin","d":"Linezolid","ans":"C"},
{"t":"CNS / Neurology","q":"Role of dexamethasone in meningitis:","a":"Prevent seizures","b":"Kill bacteria","c":"Reduce intracranial bleeding","d":"Reduce inflammatory complications","ans":"D"},
{"t":"CNS / Neurology","q":"A patient presents with meningitis and petechial rash. Likely organism?","a":"TB","b":"Meningococcus","c":"Listeria","d":"Pneumococcus","ans":"B"},
{"t":"CNS / Neurology","q":"Close contacts of meningococcal meningitis should receive:","a":"Steroids","b":"Vaccine only","c":"Rifampicin prophylaxis","d":"Penicillin injection","ans":"C"},
{"t":"CNS / Neurology","q":"CSF in viral meningitis typically shows:","a":"Normal glucose","b":"Absent cells","c":"High neutrophils","d":"High glucose","ans":"A"},
{"t":"CNS / Neurology","q":"Most common cause of viral meningitis:","a":"EBV","b":"Enteroviruses","c":"CMV","d":"Rabies","ans":"B"},
{"t":"CNS / Neurology","q":"A patient has fever, headache and temporal lobe seizures. Suspected diagnosis?","a":"Abscess","b":"Tumor","c":"HSV encephalitis","d":"Migraine","ans":"C"},
{"t":"CNS / Neurology","q":"Drug of choice for HSV encephalitis:","a":"Steroids","b":"Ceftriaxone","c":"Amphotericin B","d":"Acyclovir","ans":"D"},
{"t":"CNS / Neurology","q":"Radiological finding in HSV encephalitis:","a":"Occipital lobe lesion","b":"Temporal lobe involvement","c":"Frontal lobe lesion","d":"Cerebellar lesion","ans":"B"},
{"t":"CNS / Neurology","q":"A child presents with meningitis and later develops hearing loss. This is a:","a":"Normal finding","b":"Treatment failure","c":"Complication","d":"Diagnosis criteria","ans":"C"},
{"t":"CNS / Neurology","q":"Common sequelae of bacterial meningitis:","a":"Paralysis","b":"Tremor","c":"Blindness","d":"Deafness","ans":"D"},
{"t":"CNS / Neurology","q":"Toxoplasmosis transmission mainly occurs via:","a":"Mosquito bite","b":"Blood inhalation","c":"Airborne droplets","d":"Cat feces exposure","ans":"D"},
{"t":"CNS / Neurology","q":"Toxoplasmosis in AIDS shows:","a":"Diffuse atrophy","b":"Single lesion","c":"Hemorrhage","d":"Multiple ring enhancing lesions","ans":"D"},
{"t":"CNS / Neurology","q":"Drug of choice for toxoplasmosis:","a":"Penicillin","b":"Amphotericin","c":"Pyrimethamine + sulfadiazine","d":"Acyclovir","ans":"C"},
{"t":"CNS / Neurology","q":"CSF protein in bacterial meningitis:","a":"Absent","b":"Low","c":"Very low","d":"High","ans":"D"},
{"t":"CNS / Neurology","q":"Kernig sign indicates:","a":"Neuropathy","b":"Brain tumor","c":"Meningeal irritation","d":"Stroke","ans":"C"},
{"t":"CNS / Neurology","q":"Brudzinski sign suggests:","a":"Ataxia","b":"Meningitis","c":"Myopathy","d":"Encephalopathy","ans":"B"},
{"t":"CNS / Neurology","q":"Most sensitive test for meningitis diagnosis:","a":"Blood culture","b":"X-ray","c":"CT scan","d":"CSF analysis","ans":"D"},
{"t":"CNS / Neurology","q":"TB meningitis CSF finding:","a":"Neutrophils only","b":"High glucose","c":"Lymphocytes with high protein","d":"Low protein","ans":"C"},
{"t":"CNS / Neurology","q":"Hydrocephalus after meningitis is due to:","a":"Stroke","b":"Tumor","c":"CSF obstruction","d":"Hemorrhage","ans":"C"},
{"t":"CNS / Neurology","q":"Neonatal meningitis common organism:","a":"Mycoplasma","b":"Group B streptococcus","c":"Meningococcus","d":"HSV","ans":"B"},
{"t":"CNS / Neurology","q":"Cranial nerve palsy in meningitis indicates:","a":"Allergy","b":"Recovery","c":"Mild infection","d":"Severe disease","ans":"D"},
{"t":"CNS / Neurology","q":"Initial management of suspected meningitis before LP:","a":"Give analgesics only","b":"Observe","c":"Start antibiotics","d":"Wait for MRI","ans":"C"},
{"t":"CNS / Neurology","q":"A patient with AIDS presents with headache and multiple ring lesions. Most likely diagnosis?","a":"Abscess","b":"TB","c":"Toxoplasmosis","d":"Lymphoma","ans":"C"},
{"t":"CNS / Neurology","q":"Best diagnostic test for toxoplasmosis in immunocompromised:","a":"EEG","b":"CT brain","c":"Serology","d":"MRI brain","ans":"C"},
{"t":"CNS / Neurology","q":"CSF glucose in viral meningitis:","a":"Absent","b":"Very low","c":"Normal","d":"High","ans":"C"},
{"t":"CNS / Neurology","q":"Organism causing recurrent meningitis:","a":"EBV","b":"Adenovirus","c":"HSV-2","d":"Influenza","ans":"C"},
{"t":"CNS / Neurology","q":"Gram stain positive diplococci suggests:","a":"E coli","b":"Listeria","c":"Pneumococcus","d":"Meningococcus","ans":"D"},
{"t":"CNS / Neurology","q":"Prophylaxis for meningococcal contacts alternative drug:","a":"Metronidazole","b":"Ciprofloxacin","c":"Amoxicillin","d":"Azithromycin","ans":"B"},
{"t":"CNS / Neurology","q":"CSF neutrophil predominance suggests:","a":"Fungal meningitis","b":"TB meningitis","c":"Viral meningitis","d":"Bacterial meningitis","ans":"D"},
{"t":"CNS / Neurology","q":"Most dangerous complication of meningitis:","a":"Cough","b":"Rash","c":"Raised ICP","d":"Hair loss","ans":"C"},
{"t":"CNS / Neurology","q":"Empirical therapy in neonate meningitis includes:","a":"Ceftriaxone only","b":"Ampicillin + gentamicin","c":"Acyclovir only","d":"Vancomycin only","ans":"B"},
{"t":"CNS / Neurology","q":"CSF appearance in bacterial meningitis:","a":"Colorless","b":"Bloody","c":"Clear","d":"Turbid","ans":"D"},
{"t":"CNS / Neurology","q":"MRI finding in toxoplasmosis:","a":"Diffuse edema","b":"Ring enhancing lesions","c":"Calcification","d":"Atrophy","ans":"B"},
{"t":"CNS / Neurology","q":"Fungal meningitis commonly seen in:","a":"Children only","b":"Pregnant women","c":"Immunocompromised","d":"Athletes","ans":"C"},
{"t":"CNS / Neurology","q":"Cryptococcus meningitis diagnosis test:","a":"Ziehl stain","b":"Culture only","c":"Gram stain","d":"India ink staining","ans":"D"},
{"t":"CNS / Neurology","q":"CSF chloride decreased in:","a":"Stroke","b":"Viral meningitis","c":"Migraine","d":"TB meningitis","ans":"D"},
{"t":"CNS / Neurology","q":"Most common viral cause of encephalitis:","a":"CMV","b":"HSV-1","c":"Rabies","d":"EBV","ans":"B"},
{"t":"CNS / Neurology","q":"Treatment of cryptococcal meningitis:","a":"Penicillin","b":"Ceftriaxone","c":"Amphotericin B","d":"Acyclovir","ans":"C"},
{"t":"CNS / Neurology","q":"CSF lactate high suggests:","a":"Viral meningitis","b":"Migraine","c":"Bacterial meningitis","d":"Tumor","ans":"C"},
{"t":"CNS / Neurology","q":"A 25-year-old male with chronic otitis media develops fever, headache and focal seizures. MRI shows ring enhancing lesion in temporal lobe. Most likely diagnosis?","a":"Encephalitis","b":"Glioblastoma","c":"Brain abscess","d":"Meningitis","ans":"C"},
{"t":"CNS / Neurology","q":"Most common source of brain abscess in adults:","a":"Urinary infection","b":"Otitis media","c":"Sinusitis","d":"Skin infection","ans":"B"},
{"t":"CNS / Neurology","q":"Hematogenous spread causing brain abscess commonly originates from:","a":"Arthritis","b":"Gastritis","c":"Endocarditis","d":"Dermatitis","ans":"C"},
{"t":"CNS / Neurology","q":"Imaging finding in brain abscess:","a":"Hemorrhage","b":"Calcification","c":"Ring enhancing lesion","d":"Diffuse edema only","ans":"C"},
{"t":"CNS / Neurology","q":"Initial management of suspected brain abscess:","a":"Anticoagulation","b":"Start IV antibiotics","c":"Immediate LP","d":"Oral analgesics","ans":"B"},
{"t":"CNS / Neurology","q":"Most common presenting symptom of brain abscess:","a":"Deafness","b":"Tremor","c":"Blindness","d":"Headache","ans":"D"},
{"t":"CNS / Neurology","q":"Brain abscess commonly presents with triad of headache, fever and:","a":"Rash","b":"Seizures","c":"Hearing loss","d":"Vomiting","ans":"B"},
{"t":"CNS / Neurology","q":"Organism common in otogenic brain abscess:","a":"Mycoplasma","b":"Streptococcus species","c":"Vibrio","d":"Salmonella","ans":"B"},
{"t":"CNS / Neurology","q":"A cyanotic congenital heart disease patient develops multiple brain abscesses. Cause?","a":"Stroke","b":"Tumor","c":"Trauma","d":"Hematogenous spread","ans":"D"},
{"t":"CNS / Neurology","q":"Preferred imaging modality for brain abscess:","a":"EEG","b":"X-ray skull","c":"CT with contrast","d":"Ultrasound","ans":"C"},
{"t":"CNS / Neurology","q":"Definitive treatment for large brain abscess (>2.5 cm):","a":"Antiepileptics only","b":"Observation","c":"Steroids only","d":"Surgical drainage","ans":"D"},
{"t":"CNS / Neurology","q":"Complication of untreated brain abscess:","a":"Renal failure","b":"Cataract","c":"Herniation","d":"Arthritis","ans":"C"},
{"t":"CNS / Neurology","q":"Raised intracranial pressure causes:","a":"Tachycardia","b":"Hypothermia","c":"Bradycardia","d":"Hypotension","ans":"C"},
{"t":"CNS / Neurology","q":"Cushing triad includes hypertension, bradycardia and:","a":"Tachypnea","b":"Fever","c":"Irregular respiration","d":"Hypoglycemia","ans":"C"},
{"t":"CNS / Neurology","q":"First sign of raised ICP:","a":"Polyuria","b":"Headache","c":"Rash","d":"Deafness","ans":"B"},
{"t":"CNS / Neurology","q":"Papilledema indicates:","a":"Neuropathy","b":"Raised ICP","c":"Migraine","d":"Stroke","ans":"B"},
{"t":"CNS / Neurology","q":"Immediate management of raised ICP:","a":"Heparin","b":"Aspirin","c":"Mannitol","d":"Insulin","ans":"C"},
{"t":"CNS / Neurology","q":"Position helpful in raised ICP:","a":"Supine flat","b":"Head elevation 30°","c":"Trendelenburg","d":"Prone","ans":"B"},
{"t":"CNS / Neurology","q":"Contraindication in raised ICP:","a":"Antiemetics","b":"Analgesics","c":"Lumbar puncture","d":"Oxygen","ans":"C"},
{"t":"CNS / Neurology","q":"A patient presents with early morning headache, vomiting and papilledema. Likely cause?","a":"Sinusitis","b":"Neuralgia","c":"Migraine","d":"Raised ICP","ans":"D"},
{"t":"CNS / Neurology","q":"Most common primary malignant brain tumor in adults:","a":"Schwannoma","b":"Pituitary adenoma","c":"Glioblastoma multiforme","d":"Meningioma","ans":"C"},
{"t":"CNS / Neurology","q":"Most common benign intracranial tumor:","a":"Ependymoma","b":"Meningioma","c":"Medulloblastoma","d":"Astrocytoma","ans":"B"},
{"t":"CNS / Neurology","q":"Child with cerebellar tumor presents with:","a":"Blindness","b":"Hemiplegia","c":"Aphasia","d":"Ataxia","ans":"D"},
{"t":"CNS / Neurology","q":"Adult with frontal lobe tumor commonly presents with:","a":"Diplopia","b":"Hearing loss","c":"Personality change","d":"Vertigo","ans":"C"},
{"t":"CNS / Neurology","q":"Pituitary adenoma commonly causes:","a":"Facial palsy","b":"Tunnel hearing","c":"Monocular blindness","d":"Bitemporal hemianopia","ans":"D"},
{"t":"CNS / Neurology","q":"A 45-year-old presents with seizures and progressive focal deficit. Imaging shows irregular enhancing mass crossing corpus callosum. Diagnosis?","a":"Meningitis","b":"Abscess","c":"Glioblastoma","d":"Hematoma","ans":"C"},
{"t":"CNS / Neurology","q":"Medulloblastoma occurs in:","a":"Neonates only","b":"Adults only","c":"Children","d":"Elderly","ans":"C"},
{"t":"CNS / Neurology","q":"Most common cause of secondary brain tumor:","a":"Infection","b":"Trauma","c":"Stroke","d":"Metastasis","ans":"D"},
{"t":"CNS / Neurology","q":"Common primary tumor metastasizing to brain:","a":"Colon polyp","b":"Thyroid carcinoma","c":"Lung carcinoma","d":"Skin infection","ans":"C"},
{"t":"CNS / Neurology","q":"A patient with lung cancer develops multiple brain lesions. Mechanism?","a":"CSF infection","b":"Direct trauma","c":"Congenital","d":"Hematogenous spread","ans":"D"},
{"t":"CNS / Neurology","q":"Steroids in brain tumor are used to:","a":"Kill bacteria","b":"Cure tumor","c":"Reduce edema","d":"Prevent seizures","ans":"C"},
{"t":"CNS / Neurology","q":"Seizure due to brain tumor managed initially with:","a":"Diuretics","b":"Antiepileptics","c":"Insulin","d":"Antibiotics","ans":"B"},
{"t":"CNS / Neurology","q":"Sudden dilated pupil in raised ICP indicates:","a":"Migraine","b":"Stroke recovery","c":"Uncal herniation","d":"Sinusitis","ans":"C"},
{"t":"CNS / Neurology","q":"Posterior fossa tumors commonly cause:","a":"Anemia","b":"Hypertension","c":"Hydrocephalus","d":"Diabetes","ans":"C"},
{"t":"CNS / Neurology","q":"Vomiting without nausea in brain tumor due to:","a":"Food poisoning","b":"Raised ICP","c":"Gastritis","d":"Ulcer","ans":"B"},
{"t":"CNS / Neurology","q":"A child presents with morning vomiting and ataxia. Likely tumor location?","a":"Frontal lobe","b":"Cerebellum","c":"Occipital lobe","d":"Temporal lobe","ans":"B"},
{"t":"CNS / Neurology","q":"A patient with fever, focal deficit and ring lesion — abscess vs tumor differentiation best by:","a":"EEG","b":"X-ray","c":"Blood sugar","d":"MRI diffusion","ans":"D"},
{"t":"CNS / Neurology","q":"Brain abscess capsule formation occurs in:","a":"Immediately","b":"Early stage","c":"Never","d":"Late stage","ans":"D"},
{"t":"CNS / Neurology","q":"Raised ICP causes decreased consciousness due to:","a":"Renal failure","b":"Brainstem compression","c":"Liver failure","d":"Hypoglycemia","ans":"B"},
{"t":"CNS / Neurology","q":"A patient with papilledema and focal deficits — next step before LP?","a":"Steroids","b":"CT scan","c":"EEG","d":"Antibiotics","ans":"B"},
{"t":"CNS / Neurology","q":"Ring enhancing lesion differential includes abscess and:","a":"Neuropathy","b":"Neuralgia","c":"Migraine","d":"Metastasis","ans":"D"},
{"t":"CNS / Neurology","q":"Most common organism in post-traumatic brain abscess:","a":"Candida","b":"Salmonella","c":"Staphylococcus aureus","d":"Vibrio","ans":"C"},
{"t":"CNS / Neurology","q":"Brain tumor headache typically:","a":"Only at night","b":"After meals","c":"Worse in morning","d":"Worse evening","ans":"C"},
{"t":"CNS / Neurology","q":"First investigation in suspected brain tumor:","a":"X-ray","b":"LP","c":"EEG","d":"MRI brain","ans":"D"},
{"t":"CNS / Neurology","q":"Rapid deterioration with hypertension and bradycardia indicates:","a":"Anemia","b":"Sepsis","c":"Raised ICP","d":"Shock","ans":"C"},
{"t":"CNS / Neurology","q":"Management of small brain abscess (<2 cm):","a":"Radiotherapy","b":"Surgery mandatory","c":"IV antibiotics","d":"Chemotherapy","ans":"C"},
{"t":"CNS / Neurology","q":"A patient develops seizures after neurosurgery with fever and focal signs. Likely diagnosis?","a":"Neuralgia","b":"Brain abscess","c":"Migraine","d":"Stroke","ans":"B"},
{"t":"CNS / Neurology","q":"Meningioma arises from:","a":"Astrocytes","b":"Neurons","c":"Microglia","d":"Arachnoid cap cells","ans":"D"},
{"t":"CNS / Neurology","q":"Most common symptom of pituitary tumor:","a":"Cough","b":"Rash","c":"Visual disturbance","d":"Hearing loss","ans":"C"},
{"t":"CNS / Neurology","q":"Definitive diagnosis of brain tumor:","a":"Urine test","b":"CSF exam","c":"Blood test","d":"Biopsy","ans":"D"},
{"t":"CNS / Neurology","q":"A patient with small cell lung carcinoma develops progressive cerebellar ataxia without metastasis. Most likely diagnosis?","a":"Multiple sclerosis","b":"Stroke","c":"Paraneoplastic cerebellar degeneration","d":"Brain metastasis","ans":"C"},
{"t":"CNS / Neurology","q":"Paraneoplastic neurological syndromes are caused by:","a":"Vascular occlusion","b":"Immune-mediated neuronal damage","c":"Direct tumor invasion","d":"Infection","ans":"B"},
{"t":"CNS / Neurology","q":"Anti-Hu antibodies are commonly associated with:","a":"Thyroid carcinoma","b":"Colon cancer","c":"Breast cancer","d":"Small cell lung carcinoma","ans":"D"},
{"t":"CNS / Neurology","q":"Lambert-Eaton myasthenic syndrome is associated with:","a":"Renal carcinoma","b":"Thymoma","c":"Lung carcinoma","d":"Pancreatic carcinoma","ans":"C"},
{"t":"CNS / Neurology","q":"A patient improves muscle strength after repeated contractions. Likely disorder?","a":"Neuropathy","b":"Lambert-Eaton syndrome","c":"ALS","d":"Myasthenia gravis","ans":"B"},
{"t":"CNS / Neurology","q":"Mechanism of Lambert-Eaton syndrome:","a":"Acetylcholine deficiency","b":"Muscle fiber necrosis","c":"Presynaptic calcium channel antibodies","d":"Postsynaptic receptor destruction","ans":"C"},
{"t":"CNS / Neurology","q":"Normal pressure hydrocephalus triad includes gait disturbance, urinary incontinence and:","a":"Seizures","b":"Vomiting","c":"Memory impairment","d":"Headache","ans":"C"},
{"t":"CNS / Neurology","q":"Imaging finding in hydrocephalus:","a":"Cortical atrophy only","b":"Narrow ventricles","c":"Hemorrhage","d":"Enlarged ventricles","ans":"D"},
{"t":"CNS / Neurology","q":"Treatment of normal pressure hydrocephalus:","a":"Antiepileptics","b":"Steroids","c":"VP shunt","d":"Mannitol","ans":"C"},
{"t":"CNS / Neurology","q":"A child with bulging fontanelle and sunset eyes most likely has:","a":"Epilepsy","b":"Hydrocephalus","c":"Meningitis","d":"Migraine","ans":"B"},
{"t":"CNS / Neurology","q":"Idiopathic intracranial hypertension commonly occurs in:","a":"Child","b":"Thin elderly male","c":"Elderly female","d":"Obese young female","ans":"D"},
{"t":"CNS / Neurology","q":"Most common symptom of idiopathic intracranial hypertension:","a":"Tremor","b":"Headache","c":"Weakness","d":"Hearing loss","ans":"B"},
{"t":"CNS / Neurology","q":"Fundoscopy finding in idiopathic intracranial hypertension:","a":"Cataract","b":"Retinal hemorrhage","c":"Papilledema","d":"Optic atrophy","ans":"C"},
{"t":"CNS / Neurology","q":"CSF opening pressure in idiopathic intracranial hypertension:","a":"Absent","b":"High","c":"Low","d":"Normal","ans":"B"},
{"t":"CNS / Neurology","q":"Drug used in idiopathic intracranial hypertension:","a":"Propranolol","b":"Carbamazepine","c":"Levodopa","d":"Acetazolamide","ans":"D"},
{"t":"CNS / Neurology","q":"A young obese woman presents with headache, transient visual obscurations and papilledema but normal imaging. Diagnosis?","a":"Meningitis","b":"Brain tumor","c":"IIH","d":"Migraine","ans":"C"},
{"t":"CNS / Neurology","q":"Head injury with brief loss of consciousness followed by lucid interval suggests:","a":"Concussion","b":"SAH","c":"Subdural hematoma","d":"Epidural hematoma","ans":"D"},
{"t":"CNS / Neurology","q":"Most common vessel injured in epidural hematoma:","a":"Middle meningeal artery","b":"Vertebral artery","c":"Carotid artery","d":"Basilar artery","ans":"A"},
{"t":"CNS / Neurology","q":"CT scan in epidural hematoma shows:","a":"Diffuse edema","b":"Ventricular bleed","c":"Biconvex lens shaped bleed","d":"Crescent shaped bleed","ans":"C"},
{"t":"CNS / Neurology","q":"Subdural hematoma is due to rupture of:","a":"Venules only","b":"Capillaries","c":"Bridging veins","d":"Arteries","ans":"C"},
{"t":"CNS / Neurology","q":"CT finding in subdural hematoma:","a":"Ring lesion","b":"Calcified lesion","c":"Biconvex","d":"Crescent shaped","ans":"D"},
{"t":"CNS / Neurology","q":"Diffuse axonal injury presents with:","a":"Fever","b":"Immediate coma","c":"Neck stiffness","d":"Lucid interval","ans":"B"},
{"t":"CNS / Neurology","q":"Concussion is defined as:","a":"Hemorrhage","b":"Structural brain injury","c":"Tumor","d":"Transient neurological dysfunction","ans":"D"},
{"t":"CNS / Neurology","q":"Indication for CT scan in minor head injury:","a":"Normal exam","b":"Mild headache","c":"Persistent vomiting","d":"No symptoms","ans":"C"},
{"t":"CNS / Neurology","q":"A motorcyclist presents unconscious with dilated pupil and contralateral weakness. Likely cause?","a":"Migraine","b":"Encephalitis","c":"Stroke","d":"Uncal herniation","ans":"D"},
{"t":"CNS / Neurology","q":"Management of epidural hematoma:","a":"Steroids","b":"Surgical evacuation","c":"Antibiotics","d":"Observation","ans":"B"},
{"t":"CNS / Neurology","q":"Post-traumatic seizure prophylaxis drug:","a":"Digoxin","b":"Phenytoin","c":"Insulin","d":"Warfarin","ans":"B"},
{"t":"CNS / Neurology","q":"CSF rhinorrhea after trauma suggests fracture of:","a":"Nasal septum","b":"Maxilla","c":"Skull base","d":"Mandible","ans":"C"},
{"t":"CNS / Neurology","q":"Battle sign indicates fracture of:","a":"Frontal bone","b":"Base of skull","c":"Maxilla","d":"Mandible","ans":"B"},
{"t":"CNS / Neurology","q":"Racoon eyes suggest:","a":"Tumor","b":"Stroke","c":"Basilar skull fracture","d":"Migraine","ans":"C"},
{"t":"CNS / Neurology","q":"Hydrocephalus due to aqueductal stenosis type:","a":"Communicating","b":"Ex vacuo","c":"Non-communicating","d":"Normal pressure","ans":"C"},
{"t":"CNS / Neurology","q":"Communicating hydrocephalus occurs due to:","a":"Tumor obstruction","b":"Trauma only","c":"Aqueduct block","d":"Impaired CSF absorption","ans":"D"},
{"t":"CNS / Neurology","q":"A patient with meningitis later develops gait disturbance and urinary incontinence. Cause?","a":"Myopathy","b":"Neuropathy","c":"Normal pressure hydrocephalus","d":"Stroke","ans":"C"},
{"t":"CNS / Neurology","q":"Most sensitive test for IIH diagnosis:","a":"MRI","b":"X-ray","c":"LP opening pressure","d":"EEG","ans":"C"},
{"t":"CNS / Neurology","q":"Vision loss in IIH due to:","a":"Hemorrhage","b":"Optic nerve compression","c":"Cataract","d":"Retinal detachment","ans":"B"},
{"t":"CNS / Neurology","q":"Head injury patient deteriorates after few hours — think:","a":"Seizure","b":"Expanding hematoma","c":"Infection","d":"Migraine","ans":"B"},
{"t":"CNS / Neurology","q":"Glasgow coma scale assesses:","a":"Muscle tone","b":"Reflexes","c":"Sensation","d":"Consciousness level","ans":"D"},
{"t":"CNS / Neurology","q":"Severe head injury defined as GCS:","a":"12","b":"≤8","c":"14","d":"10","ans":"B"},
{"t":"CNS / Neurology","q":"Treatment of increased ICP in head injury:","a":"Antibiotics","b":"Steroids routine","c":"Insulin","d":"Mannitol","ans":"D"},
{"t":"CNS / Neurology","q":"Second impact syndrome occurs in:","a":"Pregnant women","b":"Infants","c":"Athletes","d":"Elderly","ans":"C"},
{"t":"CNS / Neurology","q":"Post-concussion syndrome includes:","a":"Blindness","b":"Headache and dizziness","c":"Paralysis","d":"Aphasia","ans":"B"},
{"t":"CNS / Neurology","q":"Paraneoplastic neuropathy often presents as:","a":"Myopathy","b":"Radiculopathy","c":"Sensory neuropathy","d":"Motor neuropathy","ans":"C"},
{"t":"CNS / Neurology","q":"Treatment of paraneoplastic syndrome primarily:","a":"Only steroids","b":"Only IV fluids","c":"Antibiotics","d":"Treat underlying tumor","ans":"D"},
{"t":"CNS / Neurology","q":"A patient with cancer develops rapid memory loss and seizures but imaging negative. Diagnosis?","a":"Meningitis","b":"Paraneoplastic limbic encephalitis","c":"Migraine","d":"Stroke","ans":"B"},
{"t":"CNS / Neurology","q":"Antibody in paraneoplastic cerebellar degeneration (breast/ovarian):","a":"Anti-CCP","b":"Anti-Jo","c":"Anti-Yo","d":"Anti-dsDNA","ans":"C"},
{"t":"CNS / Neurology","q":"Hydrocephalus complication:","a":"Rash","b":"Tremor","c":"Papilledema","d":"Deafness","ans":"C"},
{"t":"CNS / Neurology","q":"Treatment of refractory IIH:","a":"Insulin","b":"Optic nerve sheath fenestration","c":"Warfarin","d":"Antibiotics","ans":"B"},
{"t":"CNS / Neurology","q":"Coup injury occurs at:","a":"Brainstem","b":"Opposite side","c":"Cerebellum","d":"Site of impact","ans":"D"},
{"t":"CNS / Neurology","q":"Contrecoup injury occurs at:","a":"Spinal cord","b":"Meninges","c":"Opposite impact site","d":"Same site","ans":"C"},
{"t":"CNS / Neurology","q":"Chronic subdural hematoma common in:","a":"Elderly alcoholics","b":"Pregnant women","c":"Athletes","d":"Children","ans":"A"},
{"t":"CNS / Neurology","q":"A 35-year-old computer worker presents with numbness and tingling in thumb, index and middle fingers worse at night and relieved by shaking hand. Diagnosis?","a":"Cervical radiculopathy","b":"Carpal tunnel syndrome","c":"Ulnar neuropathy","d":"Radial neuropathy","ans":"B"},
{"t":"CNS / Neurology","q":"Nerve compressed in carpal tunnel syndrome:","a":"Musculocutaneous nerve","b":"Radial nerve","c":"Median nerve","d":"Ulnar nerve","ans":"C"},
{"t":"CNS / Neurology","q":"Weakness of finger abduction suggests lesion of:","a":"Axillary nerve","b":"Radial nerve","c":"Ulnar nerve","d":"Median nerve","ans":"C"},
{"t":"CNS / Neurology","q":"Wrist drop occurs due to injury of:","a":"Femoral nerve","b":"Ulnar nerve","c":"Median nerve","d":"Radial nerve","ans":"D"},
{"t":"CNS / Neurology","q":"A patient with diabetes develops symmetric stocking glove sensory loss. Most likely diagnosis?","a":"Mononeuropathy","b":"Radiculopathy","c":"Polyneuropathy","d":"Myopathy","ans":"C"},
{"t":"CNS / Neurology","q":"Multifocal neuropathy commonly presents with:","a":"Ataxia","b":"Only cranial nerve palsy","c":"Asymmetric weakness","d":"Pure sensory loss","ans":"C"},
{"t":"CNS / Neurology","q":"Guillain-Barré syndrome is typically preceded by:","a":"Stroke","b":"Migraine","c":"Trauma","d":"Viral or diarrheal illness","ans":"D"},
{"t":"CNS / Neurology","q":"Most common organism preceding GBS:","a":"Salmonella","b":"Campylobacter jejuni","c":"Mycoplasma","d":"Staphylococcus","ans":"B"},
{"t":"CNS / Neurology","q":"Classical feature of GBS:","a":"Focal weakness","b":"Tremor","c":"Descending paralysis","d":"Ascending paralysis","ans":"D"},
{"t":"CNS / Neurology","q":"Reflexes in Guillain-Barré syndrome:","a":"Clonus","b":"Areflexia","c":"Hyperreflexia","d":"Normal","ans":"B"},
{"t":"CNS / Neurology","q":"CSF finding in GBS:","a":"Low glucose","b":"High cells and low protein","c":"Normal CSF","d":"Albuminocytologic dissociation","ans":"D"},
{"t":"CNS / Neurology","q":"Treatment of Guillain-Barré syndrome:","a":"Antibiotics","b":"Levodopa","c":"IVIG or plasmapheresis","d":"Steroids only","ans":"C"},
{"t":"CNS / Neurology","q":"Most dangerous complication of GBS:","a":"Blindness","b":"Liver failure","c":"Renal failure","d":"Respiratory failure","ans":"D"},
{"t":"CNS / Neurology","q":"A patient develops rapidly progressive ascending weakness and facial diplegia over 3 days with absent reflexes. Next best step?","a":"MRI spine","b":"CT brain","c":"Immediate intubation assessment","d":"Lumbar puncture delayed","ans":"C"},
{"t":"CNS / Neurology","q":"Nerve conduction study in GBS shows:","a":"Normal conduction","b":"Demyelination","c":"Myopathy","d":"Neuromuscular block","ans":"B"},
{"t":"CNS / Neurology","q":"Myasthenia gravis antibodies target:","a":"Sodium channel","b":"Dopamine receptor","c":"Acetylcholine receptor","d":"Presynaptic calcium channel","ans":"C"},
{"t":"CNS / Neurology","q":"Myasthenia gravis weakness typically:","a":"Spastic","b":"Constant","c":"Improves with activity","d":"Worsens with activity","ans":"D"},
{"t":"CNS / Neurology","q":"Most common presenting symptom of myasthenia gravis:","a":"Sensory loss","b":"Diplopia and ptosis","c":"Rigidity","d":"Tremor","ans":"B"},
{"t":"CNS / Neurology","q":"Diagnostic test for myasthenia gravis:","a":"CT abdomen","b":"EEG","c":"Edrophonium test","d":"EMG muscle biopsy","ans":"C"},
{"t":"CNS / Neurology","q":"Drug of choice for symptomatic treatment of MG:","a":"Baclofen","b":"Phenytoin","c":"Pyridostigmine","d":"Diazepam","ans":"C"},
{"t":"CNS / Neurology","q":"Myasthenia gravis associated tumor:","a":"Pituitary tumor","b":"Glioma","c":"Thymoma","d":"Lung carcinoma","ans":"C"},
{"t":"CNS / Neurology","q":"Myasthenic crisis causes:","a":"Ataxia","b":"Stroke","c":"Renal failure","d":"Respiratory failure","ans":"D"},
{"t":"CNS / Neurology","q":"Treatment of myasthenic crisis:","a":"Only steroids","b":"Antibiotics","c":"Only pyridostigmine","d":"IVIG or plasmapheresis","ans":"D"},
{"t":"CNS / Neurology","q":"Lambert-Eaton syndrome improves with:","a":"Fasting","b":"Sleep","c":"Repeated activity","d":"Rest","ans":"C"},
{"t":"CNS / Neurology","q":"Reflexes in Lambert-Eaton syndrome:","a":"Brisk","b":"Absent but improve after exercise","c":"Clonus","d":"Normal","ans":"B"},
{"t":"CNS / Neurology","q":"A smoker presents with proximal muscle weakness improving after effort and dry mouth. Likely diagnosis?","a":"ALS","b":"Myopathy","c":"Lambert-Eaton syndrome","d":"Myasthenia gravis","ans":"C"},
{"t":"CNS / Neurology","q":"Pathophysiology of Lambert-Eaton syndrome:","a":"Muscle necrosis","b":"Demyelination","c":"Presynaptic calcium channel blockade","d":"Postsynaptic receptor destruction","ans":"C"},
{"t":"CNS / Neurology","q":"Drug useful in Lambert-Eaton syndrome:","a":"Carbamazepine","b":"3,4-diaminopyridine","c":"Levodopa","d":"Haloperidol","ans":"B"},
{"t":"CNS / Neurology","q":"Autonomic symptoms common in Lambert-Eaton:","a":"Tearing","b":"Salivation","c":"Sweating excess","d":"Dry mouth","ans":"D"},
{"t":"CNS / Neurology","q":"A patient has ptosis worse at end of day but normal pupils. Diagnosis?","a":"Third nerve palsy","b":"Myasthenia gravis","c":"Horner syndrome","d":"Botulism","ans":"B"},
{"t":"CNS / Neurology","q":"Botulism differs from MG because pupils:","a":"Reactive","b":"Normal","c":"Constricted","d":"Dilated","ans":"D"},
{"t":"CNS / Neurology","q":"Entrapment neuropathy at elbow affects:","a":"Axillary nerve","b":"Median nerve","c":"Radial nerve","d":"Ulnar nerve","ans":"D"},
{"t":"CNS / Neurology","q":"Foot drop suggests lesion of:","a":"Obturator nerve","b":"Femoral nerve","c":"Common peroneal nerve","d":"Tibial nerve","ans":"C"},
{"t":"CNS / Neurology","q":"Multifocal motor neuropathy responds best to:","a":"Surgery","b":"Steroids","c":"IVIG","d":"Antibiotics","ans":"C"},
{"t":"CNS / Neurology","q":"A patient with asymmetric distal weakness and conduction block without sensory loss. Diagnosis?","a":"GBS","b":"Multifocal motor neuropathy","c":"Myopathy","d":"ALS","ans":"B"},
{"t":"CNS / Neurology","q":"Areflexia with ophthalmoplegia and ataxia variant of GBS:","a":"CIDP","b":"ALS","c":"Miller Fisher syndrome","d":"MG","ans":"C"},
{"t":"CNS / Neurology","q":"Antibody seen in Miller Fisher syndrome:","a":"Anti-AChR","b":"Anti-GQ1b","c":"Anti-Yo","d":"Anti-Hu","ans":"B"},
{"t":"CNS / Neurology","q":"Chronic inflammatory demyelinating polyneuropathy duration:","a":"1 week","b":"24 hours","c":"2 days","d":">8 weeks","ans":"D"},
{"t":"CNS / Neurology","q":"Best monitoring parameter in GBS:","a":"Temperature","b":"Blood sugar","c":"Forced vital capacity","d":"Blood pressure","ans":"C"},
{"t":"CNS / Neurology","q":"A patient cannot keep eyes open in upward gaze but strength improves after rest. Diagnosis?","a":"Parkinsonism","b":"Neuropathy","c":"Myopathy","d":"Myasthenia gravis","ans":"D"},
{"t":"CNS / Neurology","q":"Sensory symptoms absent in:","a":"Polyneuropathy","b":"GBS","c":"MG","d":"Radiculopathy","ans":"C"},
{"t":"CNS / Neurology","q":"Tensilon test positive indicates:","a":"Parkinson disease","b":"ALS","c":"Myasthenia gravis","d":"Stroke","ans":"C"},
{"t":"CNS / Neurology","q":"Repetitive nerve stimulation in MG shows:","a":"No conduction","b":"Normal","c":"Decremental response","d":"Incremental response","ans":"C"},
{"t":"CNS / Neurology","q":"Repetitive nerve stimulation in Lambert-Eaton shows:","a":"No change","b":"Block","c":"Decremental response","d":"Incremental response","ans":"D"},
{"t":"CNS / Neurology","q":"Most common cranial nerve involved in GBS:","a":"Optic nerve","b":"Facial nerve","c":"Hypoglossal","d":"Trigeminal nerve","ans":"B"},
{"t":"CNS / Neurology","q":"Autonomic dysfunction in GBS causes:","a":"Deafness","b":"Tremor","c":"Blindness","d":"BP fluctuations","ans":"D"},
{"t":"CNS / Neurology","q":"A patient develops progressive weakness after vaccination within 2 weeks. Suspect:","a":"Myopathy","b":"GBS","c":"MS","d":"Stroke","ans":"B"},
{"t":"CNS / Neurology","q":"Best initial therapy for mild MG:","a":"Plasmapheresis","b":"Rituximab","c":"IVIG","d":"Pyridostigmine","ans":"D"},
{"t":"CNS / Neurology","q":"Thymectomy indicated in MG:","a":"Only elderly","b":"Only children","c":"Always contraindicated","d":"With thymoma","ans":"D"},
{"t":"CNS / Neurology","q":"Ice pack test improves ptosis in:","a":"Botulism","b":"Parkinson disease","c":"Myasthenia gravis","d":"Stroke","ans":"C"},
{"t":"CNS / Neurology","q":"A 5-year-old boy presents with delayed walking, frequent falls and calf pseudohypertrophy with positive Gowers sign. Diagnosis?","a":"Spinal muscular atrophy","b":"Myasthenia gravis","c":"Duchenne muscular dystrophy","d":"Becker muscular dystrophy","ans":"C"},
{"t":"CNS / Neurology","q":"Gene mutation in Duchenne muscular dystrophy affects:","a":"Myosin","b":"Dystrophin","c":"Collagen","d":"Actin","ans":"B"},
{"t":"CNS / Neurology","q":"Inheritance pattern of Duchenne muscular dystrophy:","a":"Mitochondrial","b":"Autosomal dominant","c":"X-linked recessive","d":"Autosomal recessive","ans":"C"},
{"t":"CNS / Neurology","q":"Serum marker elevated in muscular dystrophy:","a":"Bilirubin","b":"Creatinine","c":"Troponin","d":"CK markedly elevated","ans":"D"},
{"t":"CNS / Neurology","q":"Becker muscular dystrophy differs from Duchenne by:","a":"Normal CK","b":"Female predominance","c":"Milder course","d":"Earlier onset","ans":"C"},
{"t":"CNS / Neurology","q":"A teenage boy with proximal muscle weakness and preserved ambulation till adulthood likely has:","a":"MG","b":"ALS","c":"Becker muscular dystrophy","d":"Duchenne muscular dystrophy","ans":"C"},
{"t":"CNS / Neurology","q":"Most common cause of death in Duchenne muscular dystrophy:","a":"Liver failure","b":"Stroke","c":"Renal failure","d":"Respiratory failure","ans":"D"},
{"t":"CNS / Neurology","q":"Cardiac complication in muscular dystrophy:","a":"Endocarditis","b":"Dilated cardiomyopathy","c":"Pericarditis","d":"Aortic stenosis","ans":"B"},
{"t":"CNS / Neurology","q":"Myotonic dystrophy presents with:","a":"Hyperreflexia","b":"Tremor","c":"Delayed muscle relaxation","d":"Sensory loss","ans":"C"},
{"t":"CNS / Neurology","q":"A patient unable to release handshake quickly suggests:","a":"Neuropathy","b":"Parkinsonism","c":"Myotonia","d":"ALS","ans":"C"},
{"t":"CNS / Neurology","q":"McArdle disease defect:","a":"ATP deficiency","b":"Dystrophin absence","c":"Myophosphorylase deficiency","d":"Carnitine deficiency","ans":"C"},
{"t":"CNS / Neurology","q":"McArdle disease symptom during exercise:","a":"Diplopia","b":"Exercise intolerance with cramps","c":"Ptosis","d":"Tremor","ans":"B"},
{"t":"CNS / Neurology","q":"Second wind phenomenon seen in:","a":"Myopathy steroid","b":"MG","c":"McArdle disease","d":"ALS","ans":"C"},
{"t":"CNS / Neurology","q":"Rhabdomyolysis lab finding:","a":"Leukopenia","b":"Hypoglycemia","c":"Hyperbilirubinemia","d":"Myoglobinuria","ans":"D"},
{"t":"CNS / Neurology","q":"Statin therapy may cause:","a":"Seizure","b":"Stroke","c":"Myopathy","d":"Neuropathy","ans":"C"},
{"t":"CNS / Neurology","q":"Drug induced myopathy commonly caused by:","a":"Antibiotics","b":"Insulin","c":"Antacids","d":"Steroids","ans":"D"},
{"t":"CNS / Neurology","q":"Polymyositis presents with:","a":"Fasciculations","b":"Tremor","c":"Symmetric proximal weakness","d":"Distal sensory loss","ans":"C"},
{"t":"CNS / Neurology","q":"Dermatomyositis additional feature:","a":"Rigidity","b":"Diplopia","c":"Heliotrope rash","d":"Ptosis","ans":"C"},
{"t":"CNS / Neurology","q":"Malignancy association strongest with:","a":"McArdle","b":"Dermatomyositis","c":"Becker","d":"Duchenne","ans":"B"},
{"t":"CNS / Neurology","q":"Inclusion body myositis affects:","a":"Females only","b":"Children proximal only","c":"Neonates","d":"Elderly males distal weakness","ans":"D"},
{"t":"CNS / Neurology","q":"A 45-year-old presents with progressive proximal weakness, difficulty climbing stairs and raised CK with inflammatory infiltrates on biopsy. Diagnosis?","a":"Neuropathy","b":"ALS","c":"Polymyositis","d":"MG","ans":"C"},
{"t":"CNS / Neurology","q":"Treatment of polymyositis:","a":"Dopamine agonist","b":"Steroids","c":"Antiepileptics","d":"Antibiotics","ans":"B"},
{"t":"CNS / Neurology","q":"A 30-year-old woman with purple eyelid rash and muscle weakness most likely has:","a":"Neuropathy","b":"MG","c":"ALS","d":"Dermatomyositis","ans":"D"},
{"t":"CNS / Neurology","q":"A marathon runner develops dark urine and muscle pain after exertion with high CK. Diagnosis?","a":"Nephritis","b":"Hematuria","c":"Rhabdomyolysis","d":"Hepatitis","ans":"C"},
{"t":"CNS / Neurology","q":"Treatment for rhabdomyolysis:","a":"Dialysis immediately","b":"Aggressive IV fluids","c":"Antibiotics","d":"Steroids","ans":"B"},
{"t":"CNS / Neurology","q":"A child with Gowers sign and calf hypertrophy — next step to confirm diagnosis?","a":"LP","b":"CT brain","c":"EEG","d":"Genetic testing","ans":"D"},
{"t":"CNS / Neurology","q":"Hypokalemic periodic paralysis triggered by:","a":"Trauma","b":"Fasting","c":"High carbohydrate meal","d":"Infection","ans":"C"},
{"t":"CNS / Neurology","q":"Hyperkalemic periodic paralysis attacks last:","a":"Days only","b":"Months","c":"Weeks","d":"Minutes to hours","ans":"D"},
{"t":"CNS / Neurology","q":"Mitochondrial myopathy presents with:","a":"Spasticity","b":"Hyperreflexia","c":"Exercise intolerance + lactic acidosis","d":"Sensory loss","ans":"C"},
{"t":"CNS / Neurology","q":"Ragged red fibers seen in:","a":"Neuropathy","b":"ALS","c":"Mitochondrial myopathy","d":"MG","ans":"C"},
{"t":"CNS / Neurology","q":"A 60-year-old on long-term steroids develops proximal weakness without pain. Diagnosis?","a":"Neuropathy","b":"ALS","c":"Steroid myopathy","d":"Polymyositis","ans":"C"},
{"t":"CNS / Neurology","q":"Endocrine disorder causing myopathy:","a":"Asthma","b":"Hypertension","c":"Hypothyroidism","d":"Migraine","ans":"C"},
{"t":"CNS / Neurology","q":"Myopathy with delayed reflex relaxation seen in:","a":"Diabetes","b":"Hypertension","c":"Hyperthyroidism","d":"Hypothyroidism","ans":"D"},
{"t":"CNS / Neurology","q":"Hyperthyroid myopathy presents with:","a":"Distal sensory loss","b":"Rigidity","c":"Tremor only","d":"Proximal weakness","ans":"D"},
{"t":"CNS / Neurology","q":"A patient cannot comb hair and rise from chair but reflexes preserved. Suggests:","a":"ALS","b":"Myopathy","c":"Neuropathy","d":"MG","ans":"B"},
{"t":"CNS / Neurology","q":"EMG finding in myopathy:","a":"Normal","b":"Absent","c":"Large potentials","d":"Small amplitude short duration potentials","ans":"D"},
{"t":"CNS / Neurology","q":"Muscle biopsy in polymyositis shows:","a":"Fibrosis only","b":"Endomysial inflammation","c":"Necrosis only","d":"Demyelination","ans":"B"},
{"t":"CNS / Neurology","q":"Dermatomyositis biopsy shows:","a":"Plaques","b":"Axonal degeneration","c":"Perimysial inflammation","d":"Tumor cells","ans":"C"},
{"t":"CNS / Neurology","q":"A child with exercise intolerance relieved by rest and normal strength between episodes suggests:","a":"ALS","b":"MG","c":"Metabolic myopathy","d":"Stroke","ans":"C"},
{"t":"CNS / Neurology","q":"Carnitine deficiency leads to:","a":"Stroke","b":"Tumor","c":"Neuropathy","d":"Lipid metabolism defect myopathy","ans":"D"},
{"t":"CNS / Neurology","q":"A young adult develops muscle weakness after fasting and prolonged exercise. Likely condition?","a":"ALS","b":"Fatty acid oxidation defect","c":"Duchenne","d":"MG","ans":"B"},
{"t":"CNS / Neurology","q":"Myoglobinuria color of urine:","a":"Yellow","b":"Green","c":"White","d":"Cola colored","ans":"D"},
{"t":"CNS / Neurology","q":"Most specific enzyme for muscle injury:","a":"LDH","b":"CK-MM","c":"AST","d":"CK-MB","ans":"B"},
{"t":"CNS / Neurology","q":"Complication of severe rhabdomyolysis:","a":"Liver failure","b":"Acute kidney injury","c":"Stroke","d":"Seizure","ans":"B"},
{"t":"CNS / Neurology","q":"A 7-year-old boy toe walking and lumbar lordosis suggests:","a":"MG","b":"Duchenne muscular dystrophy","c":"Neuropathy","d":"ALS","ans":"B"},
{"t":"CNS / Neurology","q":"Facial weakness and cataracts in adult muscular disease suggests:","a":"ALS","b":"Becker","c":"Myotonic dystrophy","d":"Duchenne","ans":"C"},
{"t":"CNS / Neurology","q":"Grip myotonia improves after repeated contraction called:","a":"Tetany","b":"Spasm","c":"Fatigue","d":"Warm up phenomenon","ans":"D"},
{"t":"CNS / Neurology","q":"A patient develops muscle pain and CK elevation after starting statins. Next step?","a":"Add steroid","b":"Ignore","c":"Stop statin","d":"Increase dose","ans":"C"},
{"t":"CNS / Neurology","q":"Proximal weakness with normal sensation localizes to:","a":"Spinal cord","b":"Brain","c":"Nerve disease","d":"Muscle disease","ans":"D"},
{"t":"CNS / Neurology","q":"Gold standard diagnosis of inflammatory myopathy:","a":"EEG","b":"Muscle biopsy","c":"CT brain","d":"LP","ans":"B"},
{"t":"CNS / Neurology","q":"A 55-year-old office worker presents with neck pain radiating to arm with paresthesia in thumb and reduced biceps reflex. Most likely diagnosis?","a":"Myopathy","b":"Ulnar neuropathy","c":"Cervical spondylosis","d":"Carpal tunnel syndrome","ans":"C"},
{"t":"CNS / Neurology","q":"Most common level affected in cervical spondylosis:","a":"T1–T2","b":"C5–C6","c":"C1–C2","d":"C3–C4","ans":"B"},
{"t":"CNS / Neurology","q":"Lumbar spondylosis commonly causes:","a":"Diplopia","b":"Radicular leg pain","c":"Arm pain","d":"Facial numbness","ans":"B"},
{"t":"CNS / Neurology","q":"Straight leg raising test positive suggests:","a":"Myopathy","b":"Cervical radiculopathy","c":"Neuropathy","d":"Sciatica","ans":"D"},
{"t":"CNS / Neurology","q":"Cauda equina syndrome presents with:","a":"Ptosis","b":"Saddle anesthesia","c":"Tremor","d":"Hemiplegia","ans":"B"},
{"t":"CNS / Neurology","q":"Emergency management of cauda equina syndrome:","a":"Physiotherapy","b":"Steroids only","c":"Bed rest","d":"Urgent decompression surgery","ans":"D"},
{"t":"CNS / Neurology","q":"A patient develops bilateral leg weakness, urinary retention and sensory level at umbilicus. Likely diagnosis?","a":"Peripheral neuropathy","b":"Myopathy","c":"Spinal cord compression","d":"Stroke","ans":"C"},
{"t":"CNS / Neurology","q":"Most sensitive investigation for spinal cord compression:","a":"EEG","b":"CT brain","c":"X-ray","d":"MRI spine","ans":"D"},
{"t":"CNS / Neurology","q":"Initial treatment in malignant spinal cord compression:","a":"Anticoagulation","b":"High dose steroids","c":"Antibiotics","d":"Insulin","ans":"B"},
{"t":"CNS / Neurology","q":"A patient with metastatic prostate cancer develops back pain worse at night and leg weakness. First step?","a":"LP","b":"Physiotherapy","c":"Analgesics only","d":"MRI spine urgently","ans":"D"},
{"t":"CNS / Neurology","q":"Brown-Sequard syndrome results from:","a":"Complete cord lesion","b":"Peripheral nerve injury","c":"Hemisection of spinal cord","d":"Brainstem lesion","ans":"C"},
{"t":"CNS / Neurology","q":"In Brown-Sequard syndrome ipsilateral loss of:","a":"Facial sensation","b":"Pain and temperature","c":"Smell","d":"Vibration and proprioception","ans":"D"},
{"t":"CNS / Neurology","q":"Contralateral loss in Brown-Sequard syndrome:","a":"Reflexes","b":"Proprioception","c":"Pain and temperature","d":"Motor function","ans":"C"},
{"t":"CNS / Neurology","q":"A young adult develops sudden paraplegia after trauma with flaccid paralysis and absent reflexes acutely. Stage?","a":"Recovery phase","b":"Spinal shock","c":"Chronic phase","d":"Hyperreflexia stage","ans":"B"},
{"t":"CNS / Neurology","q":"After weeks reflexes become brisk due to:","a":"Myopathy","b":"Neuropathy","c":"LMN lesion","d":"UMN lesion","ans":"D"},
{"t":"CNS / Neurology","q":"Central cord syndrome affects:","a":"Sensory only","b":"Face only","c":"Legs more than arms","d":"Arms more than legs","ans":"D"},
{"t":"CNS / Neurology","q":"Anterior spinal artery syndrome causes loss of:","a":"Proprioception only","b":"Smell","c":"Motor and pain temperature","d":"Vibration only","ans":"C"},
{"t":"CNS / Neurology","q":"Posterior column spared in anterior spinal artery syndrome:","a":"Temperature","b":"Pain","c":"Motor","d":"Vibration sense","ans":"D"},
{"t":"CNS / Neurology","q":"Subacute combined degeneration is due to deficiency of:","a":"Vitamin B1","b":"Vitamin C","c":"Vitamin B12","d":"Vitamin D","ans":"C"},
{"t":"CNS / Neurology","q":"Subacute combined degeneration affects:","a":"Basal ganglia","b":"Posterior column and corticospinal tract","c":"Cerebellum only","d":"Peripheral nerves only","ans":"B"},
{"t":"CNS / Neurology","q":"A patient has gait ataxia, positive Romberg and loss of vibration sense but preserved pain sensation. Lesion site?","a":"Spinothalamic tract","b":"Posterior columns","c":"Peripheral nerve","d":"Cerebellum","ans":"B"},
{"t":"CNS / Neurology","q":"Tabes dorsalis causes:","a":"Hyperreflexia","b":"Tremor","c":"Spasticity","d":"Loss of proprioception","ans":"D"},
{"t":"CNS / Neurology","q":"Syringomyelia causes dissociated sensory loss of:","a":"Touch","b":"Position sense","c":"Pain and temperature","d":"Vibration","ans":"C"},
{"t":"CNS / Neurology","q":"Classic sign of syringomyelia:","a":"Facial palsy","b":"Diplopia","c":"Hemiplegia","d":"Cape-like distribution sensory loss","ans":"D"},
{"t":"CNS / Neurology","q":"A young patient presents with hand muscle wasting with preserved vibration sense. Likely condition?","a":"Neuropathy","b":"Myopathy","c":"Syringomyelia","d":"Stroke","ans":"C"},
{"t":"CNS / Neurology","q":"Most common cause of spinal cord compression:","a":"Infection","b":"Congenital","c":"Metastasis","d":"Trauma","ans":"C"},
{"t":"CNS / Neurology","q":"Night pain relieved poorly by rest suggests:","a":"Mechanical back pain","b":"Neuropathy","c":"Malignancy","d":"Myopathy","ans":"C"},
{"t":"CNS / Neurology","q":"A patient with tuberculosis develops vertebral collapse and kyphosis. Diagnosis?","a":"Disc prolapse","b":"Pott disease","c":"Ankylosing spondylitis","d":"Osteoporosis","ans":"B"},
{"t":"CNS / Neurology","q":"Most common site of disc prolapse in lumbar spine:","a":"L2–L3","b":"T12–L1","c":"L1–L2","d":"L4–L5","ans":"D"},
{"t":"CNS / Neurology","q":"L5 root compression causes weakness of:","a":"Hip flexion","b":"Knee extension","c":"Foot dorsiflexion","d":"Plantar flexion","ans":"C"},
{"t":"CNS / Neurology","q":"S1 root compression causes:","a":"Triceps reflex loss","b":"Loss ankle reflex","c":"Loss knee reflex","d":"Biceps reflex loss","ans":"B"},
{"t":"CNS / Neurology","q":"Neurogenic claudication worsens with:","a":"Sitting","b":"Rest","c":"Flexion","d":"Extension walking","ans":"D"},
{"t":"CNS / Neurology","q":"Improves when bending forward:","a":"Neuropathy","b":"Myopathy","c":"Spinal stenosis","d":"Vascular claudication","ans":"C"},
{"t":"CNS / Neurology","q":"A patient develops sudden back pain, paraplegia and sensory loss after aortic surgery. Likely cause?","a":"Myopathy","b":"Neuropathy","c":"Stroke","d":"Anterior spinal artery infarct","ans":"D"},
{"t":"CNS / Neurology","q":"A man presents with progressive spastic paraparesis, sensory level and bladder dysfunction over months. Suggests:","a":"MG","b":"Myopathy","c":"Cord compression tumor","d":"Peripheral neuropathy","ans":"C"},
{"t":"CNS / Neurology","q":"First step in acute spinal cord compression suspected clinically:","a":"MRI spine","b":"Lumbar puncture","c":"Physiotherapy","d":"Analgesics","ans":"A"},
{"t":"CNS / Neurology","q":"Acute transverse myelitis presents with:","a":"Tremor","b":"Hemiplegia","c":"Facial palsy","d":"Bilateral weakness and sensory level","ans":"D"},
{"t":"CNS / Neurology","q":"Treatment of acute transverse myelitis:","a":"Anticoagulation","b":"Insulin","c":"High dose steroids","d":"Antibiotics","ans":"C"},
{"t":"CNS / Neurology","q":"A patient with MS develops spinal cord lesion causing Lhermitte sign. Meaning?","a":"Vertigo","b":"Diplopia","c":"Headache","d":"Electric shock sensation on neck flexion","ans":"D"},
{"t":"CNS / Neurology","q":"Conus medullaris lesion compared to cauda equina has:","a":"Hyporeflexia","b":"Asymmetric weakness","c":"Early bladder involvement","d":"More radicular pain","ans":"C"},
{"t":"CNS / Neurology","q":"A construction worker falls from height and presents complete paraplegia below T10 with preserved arm strength. Lesion type?","a":"Myopathy","b":"Peripheral neuropathy","c":"Stroke","d":"Complete spinal cord injury","ans":"D"},
{"t":"CNS / Neurology","q":"Hyperreflexia below lesion indicates:","a":"Neuropathy","b":"UMN lesion","c":"Myopathy","d":"LMN lesion","ans":"B"},
{"t":"CNS / Neurology","q":"Flaccid paralysis at level of lesion indicates:","a":"Cerebellar lesion","b":"LMN damage","c":"Brain lesion","d":"UMN damage","ans":"B"},
{"t":"CNS / Neurology","q":"A patient with long-standing cervical spondylosis develops hand clumsiness and spastic gait. Condition?","a":"Stroke","b":"Myopathy","c":"Cervical myelopathy","d":"Neuropathy","ans":"C"},
{"t":"CNS / Neurology","q":"Hoffmann sign indicates:","a":"Cerebellar lesion","b":"Peripheral nerve lesion","c":"LMN lesion","d":"UMN lesion","ans":"D"},
{"t":"CNS / Neurology","q":"Babinski sign indicates:","a":"Neuropathy","b":"UMN lesion","c":"Myopathy","d":"LMN lesion","ans":"B"},
{"t":"CNS / Neurology","q":"A patient has burning feet pain and loss of pain sensation but preserved vibration. Tract affected?","a":"Posterior column","b":"Cerebellar","c":"Corticospinal","d":"Spinothalamic tract","ans":"D"},
{"t":"CNS / Neurology","q":"A patient presents with progressive kyphosis and cord compression from vertebral infection. Next management?","a":"Anticoagulation","b":"Physiotherapy","c":"Ignore","d":"Antibiotics and stabilization","ans":"D"},
{"t":"CNS / Neurology","q":"Most common tumor causing spinal cord compression:","a":"Lipoma","b":"Breast or prostate metastasis","c":"Schwannoma","d":"Hemangioma","ans":"B"},
{"t":"CNS / Neurology","q":"Urgent indication in spinal cord compression:","a":"Back pain only","b":"Local tenderness","c":"Motor weakness","d":"Mild paresthesia","ans":"C"},
{"t":"CNS / Neurology","q":"A patient presents with loss of smell following head trauma. Which cranial nerve is affected?","a":"CN VII","b":"CN V","c":"CN I","d":"CN II","ans":"C"},
{"t":"CNS / Neurology","q":"Bitemporal hemianopia indicates lesion at:","a":"Lateral geniculate body","b":"Optic chiasm","c":"Optic nerve","d":"Optic tract","ans":"B"},
{"t":"CNS / Neurology","q":"Relative afferent pupillary defect is seen in lesion of:","a":"Trochlear nerve","b":"Abducens nerve","c":"Optic nerve","d":"Oculomotor nerve","ans":"C"},
{"t":"CNS / Neurology","q":"A patient presents with ptosis, dilated pupil and eye deviated down and out. Nerve involved?","a":"CN IV","b":"CN III","c":"CN VII","d":"CN VI","ans":"B"},
{"t":"CNS / Neurology","q":"Diplopia worse when looking down stairs suggests palsy of:","a":"CN II","b":"CN VI","c":"CN IV","d":"CN III","ans":"C"},
{"t":"CNS / Neurology","q":"Inability to abduct eye indicates lesion of:","a":"CN V","b":"CN III","c":"CN IV","d":"CN VI","ans":"D"},
{"t":"CNS / Neurology","q":"Corneal reflex afferent limb:","a":"CN III","b":"CN VII","c":"CN V3","d":"CN V1","ans":"D"},
{"t":"CNS / Neurology","q":"Corneal reflex efferent limb:","a":"CN IV","b":"CN VI","c":"CN VII","d":"CN V","ans":"C"},
{"t":"CNS / Neurology","q":"Jaw deviation to right on opening mouth indicates lesion of:","a":"Facial nerve","b":"Left trigeminal nerve","c":"Hypoglossal nerve","d":"Right trigeminal nerve","ans":"D"},
{"t":"CNS / Neurology","q":"Loss of taste anterior 2/3 of tongue due to lesion of:","a":"Vagus nerve","b":"Hypoglossal nerve","c":"Facial nerve","d":"Glossopharyngeal nerve","ans":"C"},
{"t":"CNS / Neurology","q":"Hyperacusis occurs due to paralysis of:","a":"Masseter","b":"Tensor tympani","c":"Palatoglossus","d":"Stapedius muscle","ans":"D"},
{"t":"CNS / Neurology","q":"A patient presents with LMN facial palsy involving forehead. Diagnosis?","a":"Trigeminal neuralgia","b":"UMN stroke","c":"Bell palsy","d":"Myasthenia gravis","ans":"C"},
{"t":"CNS / Neurology","q":"Loss of gag reflex afferent limb:","a":"CN XI","b":"CN X","c":"CN IX","d":"CN XII","ans":"C"},
{"t":"CNS / Neurology","q":"Hoarseness of voice due to lesion of:","a":"Hypoglossal nerve","b":"Vagus nerve","c":"Facial nerve","d":"Accessory nerve","ans":"B"},
{"t":"CNS / Neurology","q":"Shoulder droop and inability to shrug indicates lesion of:","a":"CN V","b":"CN XII","c":"CN X","d":"CN XI","ans":"D"},
{"t":"CNS / Neurology","q":"Tongue deviates to right side on protrusion. Lesion site?","a":"Left trigeminal nerve","b":"Left hypoglossal nerve","c":"Right vagus nerve","d":"Right hypoglossal nerve","ans":"D"},
{"t":"CNS / Neurology","q":"A diabetic patient presents with isolated ptosis and diplopia but pupil spared. Cause?","a":"Aneurysm","b":"Tumor","c":"Ischemic CN III palsy","d":"Myasthenia gravis","ans":"C"},
{"t":"CNS / Neurology","q":"Painful third nerve palsy with dilated pupil suggests:","a":"Migraine","b":"MS","c":"Diabetes","d":"Posterior communicating artery aneurysm","ans":"D"},
{"t":"CNS / Neurology","q":"Cavernous sinus syndrome involves all except:","a":"CN IV","b":"CN VI","c":"CN II","d":"CN III","ans":"C"},
{"t":"CNS / Neurology","q":"Weber syndrome involves:","a":"Ataxia","b":"Trigeminal neuralgia","c":"CN III palsy with contralateral hemiplegia","d":"Facial palsy only","ans":"C"},
{"t":"CNS / Neurology","q":"A patient presents with sudden vertigo, ipsilateral facial pain loss and contralateral body pain loss. Diagnosis?","a":"Bell palsy","b":"Stroke MCA","c":"Medial medullary syndrome","d":"Lateral medullary syndrome","ans":"D"},
{"t":"CNS / Neurology","q":"Structure spared in lateral medullary syndrome:","a":"Nucleus ambiguus","b":"Spinothalamic tract","c":"Corticospinal tract","d":"Vestibular nucleus","ans":"C"},
{"t":"CNS / Neurology","q":"Ipsilateral tongue paralysis occurs in:","a":"MS","b":"Lateral medullary syndrome","c":"Medial medullary syndrome","d":"Parkinson disease","ans":"C"},
{"t":"CNS / Neurology","q":"Trigeminal neuralgia pain distribution commonly:","a":"V1","b":"V2 and V3","c":"V3","d":"V2","ans":"B"},
{"t":"CNS / Neurology","q":"Drug of choice trigeminal neuralgia:","a":"Diazepam","b":"Levodopa","c":"Carbamazepine","d":"Phenytoin","ans":"C"},
{"t":"CNS / Neurology","q":"A patient presents with recurrent brief electric shock facial pain triggered by chewing and touching face. Diagnosis?","a":"Sinusitis","b":"Cluster headache","c":"Migraine","d":"Trigeminal neuralgia","ans":"D"},
{"t":"CNS / Neurology","q":"Loss of taste posterior 1/3 tongue due to lesion of:","a":"CN XII","b":"CN VII","c":"CN X","d":"CN IX","ans":"D"},
{"t":"CNS / Neurology","q":"Bilateral facial paralysis suggests:","a":"Tumor","b":"GBS","c":"Stroke","d":"Migraine","ans":"B"},
{"t":"CNS / Neurology","q":"Internuclear ophthalmoplegia due to lesion of:","a":"Cerebellum","b":"Oculomotor nerve","c":"MLF","d":"Optic nerve","ans":"C"},
{"t":"CNS / Neurology","q":"A young woman with diplopia on lateral gaze and nystagmus in abducting eye likely has:","a":"Parkinson disease","b":"MG","c":"Multiple sclerosis","d":"Stroke","ans":"C"},
{"t":"CNS / Neurology","q":"Horner syndrome triad:","a":"Miosis sweating lacrimation","b":"Ptosis mydriasis sweating","c":"Diplopia ptosis mydriasis","d":"Ptosis miosis anhidrosis","ans":"D"},
{"t":"CNS / Neurology","q":"Lesion causing Horner syndrome commonly:","a":"Glioma","b":"Meningioma","c":"Pituitary adenoma","d":"Pancoast tumor","ans":"D"},
{"t":"CNS / Neurology","q":"A patient with parotid tumor develops facial weakness sparing forehead. Cause?","a":"MG","b":"LMN lesion","c":"Neuropathy","d":"UMN lesion","ans":"D"},
{"t":"CNS / Neurology","q":"Most sensitive test optic neuritis:","a":"CT scan","b":"LP","c":"Visual evoked potential","d":"EEG","ans":"C"},
{"t":"CNS / Neurology","q":"Marcus Gunn pupil seen in:","a":"Myopia","b":"Glaucoma","c":"Optic neuritis","d":"Cataract","ans":"C"},
{"t":"CNS / Neurology","q":"A patient has inability to whistle, drooling and loss of nasolabial fold. Lesion?","a":"Vagus nerve","b":"Trigeminal nerve","c":"Facial nerve LMN","d":"Hypoglossal nerve","ans":"C"},
{"t":"CNS / Neurology","q":"Bilateral ptosis worse evening but pupils normal indicates:","a":"Third nerve palsy","b":"Horner syndrome","c":"Myasthenia gravis","d":"Stroke","ans":"C"},
{"t":"CNS / Neurology","q":"Facial nerve passes through which gland:","a":"Sublingual","b":"Parotid","c":"Submandibular","d":"Thyroid","ans":"B"},
{"t":"CNS / Neurology","q":"A patient cannot turn head to left against resistance. Lesion?","a":"Right hypoglossal nerve","b":"Left accessory nerve","c":"Left vagus nerve","d":"Right accessory nerve","ans":"B"},
{"t":"CNS / Neurology","q":"Loss of palatal elevation indicates lesion of:","a":"CN XII","b":"CN XI","c":"CN IX","d":"CN X","ans":"D"},
{"t":"CNS / Neurology","q":"A patient with acoustic neuroma presents first with:","a":"Diplopia","b":"Facial paralysis","c":"Headache","d":"Hearing loss","ans":"D"},
{"t":"CNS / Neurology","q":"Nerve involved in acoustic neuroma:","a":"CN VII","b":"CN V","c":"CN VIII","d":"CN X","ans":"C"},
{"t":"CNS / Neurology","q":"A patient cannot adduct eye during lateral gaze but convergence intact. Diagnosis?","a":"Sixth nerve palsy","b":"Third nerve palsy","c":"MG","d":"Internuclear ophthalmoplegia","ans":"D"},
{"t":"CNS / Neurology","q":"Most common cause of isolated sixth nerve palsy in elderly:","a":"MS","b":"Diabetes","c":"Trauma","d":"Tumor","ans":"B"},
{"t":"CNS / Neurology","q":"A patient with hoarseness and uvula deviates to opposite side. Lesion?","a":"Glossopharyngeal palsy","b":"Vagus nerve palsy","c":"Hypoglossal nerve palsy","d":"Facial nerve palsy","ans":"B"},
{"t":"CNS / Neurology","q":"Tongue fasciculations indicate:","a":"Myopathy","b":"LMN hypoglossal lesion","c":"UMN lesion","d":"MG","ans":"B"},
{"t":"CNS / Neurology","q":"A patient develops diplopia worse on looking right and head tilt to left improves it. Nerve involved?","a":"Left oculomotor nerve","b":"Left trochlear nerve","c":"Right abducens nerve","d":"Right trochlear nerve","ans":"D"},
{"t":"CNS / Neurology","q":"Loss of lacrimation occurs in lesion proximal to:","a":"Parotid gland","b":"Geniculate ganglion","c":"Mastoid","d":"Stylomastoid foramen","ans":"B"},
{"t":"CNS / Neurology","q":"Jaw jerk exaggerated indicates:","a":"LMN lesion","b":"Peripheral neuropathy","c":"UMN lesion above pons","d":"Myopathy","ans":"C"},
{"t":"CNS / Neurology","q":"Patient presents with anosmia, personality change and optic atrophy. Likely lesion site?","a":"Cerebellum","b":"Occipital lobe","c":"Brainstem","d":"Frontal lobe tumor","ans":"D"},
{"t":"CNS / Neurology","q":"Sudden onset vertigo, diplopia, dysarthria and ataxia suggests lesion in:","a":"Frontal lobe","b":"Basal ganglia","c":"Brainstem","d":"Cerebellum only","ans":"C"},
{"t":"CNS / Neurology","q":"Most common site of berry aneurysm rupture causing SAH:","a":"Basilar artery","b":"Anterior communicating artery","c":"MCA bifurcation","d":"Posterior communicating artery","ans":"B"},
{"t":"CNS / Neurology","q":"Thunderclap headache worst of life should first be investigated with:","a":"EEG","b":"LP","c":"MRI brain","d":"CT brain non-contrast","ans":"D"},
{"t":"CNS / Neurology","q":"If CT negative but suspicion of SAH remains, next step:","a":"MRI","b":"Observation","c":"LP","d":"Angiography","ans":"C"},
{"t":"CNS / Neurology","q":"Most sensitive test for multiple sclerosis:","a":"EEG","b":"CT scan","c":"X-ray","d":"MRI with contrast","ans":"D"},
{"t":"CNS / Neurology","q":"Oligoclonal bands are seen in:","a":"Migraine","b":"Stroke","c":"Multiple sclerosis","d":"Meningitis","ans":"C"},
{"t":"CNS / Neurology","q":"Treatment of acute MS relapse:","a":"Mannitol","b":"Oral antibiotics","c":"IV methylprednisolone","d":"IVIG","ans":"C"},
{"t":"CNS / Neurology","q":"Drug modifying disease progression in MS:","a":"Haloperidol","b":"Levodopa","c":"Interferon beta","d":"Diazepam","ans":"C"},
{"t":"CNS / Neurology","q":"Athetosis and chorea are lesions of:","a":"Brainstem","b":"Cortex","c":"Basal ganglia","d":"Cerebellum","ans":"C"},
{"t":"CNS / Neurology","q":"Most common cause of reversible dementia:","a":"Alzheimer disease","b":"Huntington disease","c":"Creutzfeldt Jakob disease","d":"B12 deficiency","ans":"D"},
{"t":"CNS / Neurology","q":"A patient presents with resting tremor that disappears during sleep — origin:","a":"Peripheral nerve","b":"Basal ganglia","c":"Cerebellar","d":"Cortical","ans":"B"},
{"t":"CNS / Neurology","q":"Decerebrate posturing indicates lesion below:","a":"Thalamus","b":"Cortex","c":"Cerebellum","d":"Red nucleus","ans":"D"},
{"t":"CNS / Neurology","q":"Decorticate posturing indicates lesion above:","a":"Red nucleus","b":"Spinal cord","c":"Medulla","d":"Pons","ans":"A"},
{"t":"CNS / Neurology","q":"Drug of choice absence seizure:","a":"Diazepam","b":"Phenytoin","c":"Carbamazepine","d":"Ethosuximide","ans":"D"},
{"t":"CNS / Neurology","q":"Status epilepticus first line treatment:","a":"Valproate","b":"IV lorazepam","c":"Levetiracetam","d":"Phenytoin","ans":"B"},
{"t":"CNS / Neurology","q":"Todd paralysis occurs after:","a":"Tumor","b":"Seizure","c":"Migraine","d":"Stroke","ans":"B"},
{"t":"CNS / Neurology","q":"Focal seizure with awareness previously called:","a":"Myoclonic seizure","b":"Atonic seizure","c":"Absence seizure","d":"Simple partial seizure","ans":"D"},
{"t":"CNS / Neurology","q":"Most common cause of secondary epilepsy in adults:","a":"Fever","b":"Alcohol","c":"Trauma","d":"Tumor","ans":"D"},
{"t":"CNS / Neurology","q":"Hyponatremia seizure treatment:","a":"Mannitol","b":"Insulin","c":"Hypertonic saline","d":"Dextrose","ans":"C"},
{"t":"CNS / Neurology","q":"A 68-year-old hypertensive patient suddenly develops right sided weakness and aphasia lasting 30 minutes then completely recovers. MRI normal. Most likely diagnosis?","a":"Tumor","b":"Transient ischemic attack","c":"Migraine aura","d":"Seizure","ans":"B"},
{"t":"CNS / Neurology","q":"A diabetic elderly patient develops acute hemiplegia with gaze deviation toward lesion side and global aphasia. Vessel involved?","a":"PCA","b":"MCA","c":"Basilar","d":"ACA","ans":"B"},
{"t":"CNS / Neurology","q":"A patient presents with contralateral hemiplegia sparing face and sensory loss in leg more than arm. Likely vascular territory?","a":"Vertebral","b":"PCA","c":"ACA","d":"MCA","ans":"C"},
{"t":"CNS / Neurology","q":"Sudden bilateral blindness with preserved pupillary reflex indicates lesion in:","a":"Retina","b":"Optic chiasm","c":"Optic nerve","d":"Occipital cortex","ans":"D"},
{"t":"CNS / Neurology","q":"A patient develops inability to recognize faces despite normal vision after stroke. Condition?","a":"Apraxia","b":"Ataxia","c":"Agnosia","d":"Aphasia","ans":"C"},
{"t":"CNS / Neurology","q":"A 70-year-old alcoholic suddenly becomes confused with ophthalmoplegia and ataxia after IV fluids started. Mechanism?","a":"Electrolyte imbalance","b":"Sepsis","c":"Stroke","d":"Glucose before thiamine","ans":"D"},
{"t":"CNS / Neurology","q":"A patient develops locked-in syndrome after pontine infarction. Which function preserved?","a":"Limb movement","b":"Speech","c":"Consciousness","d":"Facial expression","ans":"C"},
{"t":"CNS / Neurology","q":"A young woman presents with relapsing neurological deficits separated by time and space, optic neuritis and sensory symptoms. Investigation most diagnostic?","a":"X-ray","b":"CT scan","c":"EEG","d":"MRI plaques","ans":"D"},
{"t":"CNS / Neurology","q":"A man presents with progressive behavioral changes, disinhibition and executive dysfunction but memory preserved early. Most likely diagnosis?","a":"Lewy body dementia","b":"Frontotemporal dementia","c":"Vascular dementia","d":"Alzheimer disease","ans":"B"},
{"t":"CNS / Neurology","q":"A patient develops sudden severe headache, vomiting and neck stiffness during exertion. After 5 days develops hyponatremia due to SIADH. Diagnosis?","a":"Meningitis","b":"Migraine","c":"SAH","d":"Intracerebral hemorrhage","ans":"C"},
{"t":"CNS / Neurology","q":"A 32-year-old postpartum woman presents with severe headache, seizures and focal deficits. Imaging shows venous infarcts crossing arterial territories. Diagnosis?","a":"Abscess","b":"Tumor","c":"Cerebral venous sinus thrombosis","d":"Arterial stroke","ans":"C"},
{"t":"CNS / Neurology","q":"A patient treated with tPA suddenly deteriorates neurologically. Most feared complication?","a":"Infection","b":"Seizure","c":"Edema","d":"Hemorrhagic transformation","ans":"D"},
{"t":"CNS / Neurology","q":"A young patient with Marfan syndrome presents sudden severe headache and collapse. Likely cause?","a":"Sinusitis","b":"Tumor","c":"Aneurysmal rupture","d":"Migraine","ans":"C"},
{"t":"CNS / Neurology","q":"A patient with atrial fibrillation develops sudden painless monocular vision loss. Mechanism?","a":"Cataract","b":"Glaucoma","c":"Optic neuritis","d":"Retinal artery embolism","ans":"D"},
{"t":"CNS / Neurology","q":"A 50-year-old presents progressive gait instability, urinary incontinence and cognitive decline months after hemorrhage. Most likely cause?","a":"Tumor","b":"Normal pressure hydrocephalus","c":"Parkinson disease","d":"Alzheimer disease","ans":"B"},
{"t":"CNS / Neurology","q":"A child develops acute flaccid paralysis after viral infection affecting anterior horn cells. Diagnosis?","a":"MG","b":"Myopathy","c":"Poliomyelitis","d":"GBS","ans":"C"},
{"t":"CNS / Neurology","q":"A patient develops unilateral intention tremor, dysmetria and hypotonia. Lesion site?","a":"Cortex","b":"Spinal cord","c":"Basal ganglia","d":"Cerebellum","ans":"D"},
{"t":"CNS / Neurology","q":"A chronic alcoholic develops truncal ataxia with wide-based gait and preserved limb coordination. Lesion?","a":"Thalamus","b":"Cerebellar vermis","c":"Basal ganglia","d":"Cerebellar hemisphere","ans":"B"},
{"t":"CNS / Neurology","q":"A patient with hypertension develops sudden coma and pinpoint pupils. Likely hemorrhage site?","a":"Thalamus","b":"Cerebellum","c":"Pons","d":"Putamen","ans":"C"},
{"t":"CNS / Neurology","q":"A patient develops severe headache worsened on standing and relieved lying flat after LP. Diagnosis?","a":"SAH","b":"Post-LP low pressure headache","c":"Tumor","d":"Migraine","ans":"B"},
{"t":"CNS / Neurology","q":"A 60-year-old man presents with progressive unilateral resting tremor, rigidity and bradykinesia followed years later by dementia and visual hallucinations. Likely diagnosis?","a":"Frontotemporal dementia","b":"Alzheimer disease","c":"Vascular dementia","d":"Parkinson disease dementia / Lewy body spectrum","ans":"D"},
{"t":"CNS / Neurology","q":"A young athlete collapses with hyperthermia and muscle rigidity after anesthesia. Cause?","a":"Heat stroke","b":"Malignant hyperthermia","c":"Serotonin syndrome","d":"NMS","ans":"B"},
{"t":"CNS / Neurology","q":"A patient on antipsychotics develops fever, rigidity and autonomic instability. Diagnosis?","a":"Meningitis","b":"Malignant hyperthermia","c":"Neuroleptic malignant syndrome","d":"Serotonin syndrome","ans":"C"},
{"t":"CNS / Neurology","q":"A patient develops tremor, hyperreflexia and clonus after starting SSRI with MAOI. Diagnosis?","a":"Stroke","b":"Parkinsonism","c":"Serotonin syndrome","d":"NMS","ans":"C"},
{"t":"CNS / Neurology","q":"A diver ascends rapidly and develops joint pain and neurologic deficits due to nitrogen bubbles. Condition?","a":"Air embolism","b":"Seizure","c":"Decompression sickness","d":"Stroke","ans":"C"},
{"t":"CNS / Neurology","q":"A patient develops progressive ascending sensory level and weakness days after vaccination with spinal cord inflammation. Diagnosis?","a":"Stroke","b":"Transverse myelitis","c":"Myopathy","d":"GBS","ans":"B"},
{"t":"CNS / Neurology","q":"A patient with AIDS presents rapidly progressive dementia, myoclonus and periodic sharp waves on EEG. Diagnosis?","a":"MS","b":"Toxoplasmosis","c":"Creutzfeldt Jakob disease","d":"Alzheimer","ans":"C"},
{"t":"CNS / Neurology","q":"A traveler develops confusion and hydrophobia weeks after dog bite. Diagnosis?","a":"Meningitis","b":"Tetanus","c":"HSV encephalitis","d":"Rabies encephalitis","ans":"D"},
{"t":"CNS / Neurology","q":"A patient with migraine develops transient neurological deficit fully reversible within 1 hour without infarction. Mechanism?","a":"Hemorrhage","b":"Cortical spreading depression","c":"Edema","d":"Thrombosis","ans":"B"},
{"t":"CNS / Neurology","q":"Most important immediate step in any unconscious patient before detailed neurological evaluation:","a":"Pupillary exam","b":"Imaging","c":"Airway stabilization","d":"Reflex testing","ans":"C"},
{"t":"CNS / Neurology","q":"A 55-year-old woman presents with sudden onset of the worst headache of her life. CT head is normal. Most important next investigation:","a":"MRI brain with contrast","b":"Lumbar puncture for xanthochromia (performed after 12 hours)","c":"EEG","d":"Carotid Doppler","ans":"B"}
];