window.MM=window.MM||{};
window.MM.med_p2_endo=[
{"t":"Endocrinology","q":"Diagnostic fasting plasma glucose value diagnostic of diabetes mellitus is","a":"≥100 mg/dL","b":"≥110 mg/dL","c":"≥126 mg/dL","d":"≥140 mg/dL","ans":"C"},
{"t":"Endocrinology","q":"Random plasma glucose diagnostic of diabetes in symptomatic patient is","a":"≥160 mg/dL","b":"≥180 mg/dL","c":"≥200 mg/dL","d":"≥220 mg/dL","ans":"C"},
{"t":"Endocrinology","q":"HbA1c diagnostic threshold for diabetes mellitus","a":"5.7%","b":"6.0%","c":"6.5%","d":"7.0%","ans":"C"},
{"t":"Endocrinology","q":"Prediabetes HbA1c range","a":"5.0–5.6%","b":"5.7–6.4%","c":"6.5–7.0%","d":"≥7.0%","ans":"B"},
{"t":"Endocrinology","q":"Oral glucose tolerance test value diagnostic of diabetes at 2 hours","a":"≥140 mg/dL","b":"≥160 mg/dL","c":"≥180 mg/dL","d":"≥200 mg/dL","ans":"D"},
{"t":"Endocrinology","q":"Most common type of diabetes mellitus","a":"Type 1 DM","b":"Type 2 DM","c":"MODY","d":"Secondary diabetes","ans":"B"},
{"t":"Endocrinology","q":"Autoimmune destruction of beta cells occurs in","a":"Type 2 DM","b":"Gestational DM","c":"Type 1 DM","d":"Steroid-induced DM","ans":"C"},
{"t":"Endocrinology","q":"First line pharmacological therapy in type 2 diabetes","a":"Insulin","b":"Metformin","c":"Sulfonylurea","d":"Pioglitazone","ans":"B"},
{"t":"Endocrinology","q":"Drug that increases insulin secretion from pancreas","a":"Metformin","b":"Sitagliptin","c":"Glimepiride","d":"Acarbose","ans":"C"},
{"t":"Endocrinology","q":"Drug that decreases hepatic gluconeogenesis","a":"Metformin","b":"Repaglinide","c":"Exenatide","d":"Canagliflozin","ans":"A"},
{"t":"Endocrinology","q":"Mechanism of SGLT2 inhibitors","a":"Increase insulin secretion","b":"Increase renal glucose excretion","c":"Delay carbohydrate absorption","d":"Increase insulin sensitivity","ans":"B"},
{"t":"Endocrinology","q":"DPP-4 inhibitors act by","a":"Increasing GLP-1 levels","b":"Increasing insulin resistance","c":"Blocking renal glucose reabsorption","d":"Increasing glucagon secretion","ans":"A"},
{"t":"Endocrinology","q":"Rapid acting insulin","a":"Lispro","b":"Regular insulin","c":"NPH","d":"Glargine","ans":"A"},
{"t":"Endocrinology","q":"Intermediate acting insulin","a":"Aspart","b":"NPH","c":"Degludec","d":"Glargine","ans":"B"},
{"t":"Endocrinology","q":"Long acting insulin","a":"Regular","b":"NPH","c":"Glargine","d":"Lispro","ans":"C"},
{"t":"Endocrinology","q":"Best test for short term glycemic control (2–3 weeks)","a":"HbA1c","b":"Fasting glucose","c":"Fructosamine","d":"Random glucose","ans":"C"},
{"t":"Endocrinology","q":"Target HbA1c in most non-pregnant adults","a":"<5.5%","b":"<6.0%","c":"<7.0%","d":"<8.5%","ans":"C"},
{"t":"Endocrinology","q":"Continuous glucose monitoring measures glucose in","a":"Plasma","b":"Interstitial fluid","c":"Urine","d":"Whole blood","ans":"B"},
{"t":"Endocrinology","q":"Somogyi effect refers to","a":"Dawn hyperglycemia","b":"Post-hypoglycemic rebound hyperglycemia","c":"Insulin resistance","d":"Morning hypoglycemia","ans":"B"},
{"t":"Endocrinology","q":"Dawn phenomenon caused by","a":"Nocturnal hypoglycemia","b":"Early morning growth hormone surge","c":"Excess insulin dose","d":"Renal glucose loss","ans":"B"},
{"t":"Endocrinology","q":"Patient presents polyuria, polydipsia, weight loss, random glucose 260 mg/dL. Diagnosis","a":"Prediabetes","b":"Diabetes mellitus","c":"Impaired fasting glucose","d":"Metabolic syndrome","ans":"B"},
{"t":"Endocrinology","q":"Asymptomatic patient FBS 128 mg/dL. Next step","a":"Start insulin","b":"Repeat fasting glucose","c":"Do OGTT","d":"Start metformin","ans":"B"},
{"t":"Endocrinology","q":"Overweight adult newly diagnosed T2DM. Initial therapy","a":"Insulin","b":"Metformin","c":"Sulfonylurea","d":"GLP-1 agonist","ans":"B"},
{"t":"Endocrinology","q":"Patient on metformin develops eGFR 20 ml/min. Action","a":"Increase dose","b":"Stop metformin","c":"Add sulfonylurea","d":"Continue same","ans":"B"},
{"t":"Endocrinology","q":"Recurrent hypoglycemia on glyburide. Best change","a":"Increase dose","b":"Switch to DPP-4 inhibitor","c":"Add insulin","d":"Add acarbose","ans":"B"},
{"t":"Endocrinology","q":"Type 1 diabetic missed insulin, vomiting, abdominal pain. Likely condition","a":"HHS","b":"DKA","c":"Lactic acidosis","d":"Hypoglycemia","ans":"B"},
{"t":"Endocrinology","q":"Elderly diabetic, glucose 900 mg/dL, no ketosis. Diagnosis","a":"DKA","b":"HHS","c":"MODY","d":"Somogyi effect","ans":"B"},
{"t":"Endocrinology","q":"Newly diagnosed T1DM child initial therapy","a":"Metformin","b":"Insulin","c":"Pioglitazone","d":"Sitagliptin","ans":"B"},
{"t":"Endocrinology","q":"Pregnant woman diagnosed gestational diabetes. Drug of choice","a":"Metformin","b":"Glyburide","c":"Insulin","d":"Pioglitazone","ans":"C"},
{"t":"Endocrinology","q":"Patient fasting glucose 110 mg/dL. Category","a":"Diabetes","b":"Normal","c":"Impaired fasting glucose","d":"HHS","ans":"C"},
{"t":"Endocrinology","q":"MODY inheritance pattern","a":"Autosomal recessive","b":"Autosomal dominant","c":"X-linked","d":"Mitochondrial","ans":"B"},
{"t":"Endocrinology","q":"Drug causing weight loss in diabetes","a":"Sulfonylurea","b":"Insulin","c":"GLP-1 agonist","d":"Pioglitazone","ans":"C"},
{"t":"Endocrinology","q":"Drug causing weight gain","a":"Metformin","b":"Insulin","c":"SGLT2 inhibitor","d":"Acarbose","ans":"B"},
{"t":"Endocrinology","q":"Best monitoring for frequent glucose fluctuation","a":"HbA1c","b":"SMBG once daily","c":"CGMS","d":"Urine glucose","ans":"C"},
{"t":"Endocrinology","q":"Patient with anemia — unreliable HbA1c. Alternative test","a":"OGTT","b":"Fructosamine","c":"Random glucose","d":"Urine ketones","ans":"B"},
{"t":"Endocrinology","q":"Mechanism of acarbose","a":"Alpha-glucosidase inhibition","b":"Insulin secretion","c":"Increase GLP-1","d":"Renal glucose excretion","ans":"A"},
{"t":"Endocrinology","q":"Pioglitazone acts by","a":"Increasing insulin sensitivity","b":"Increasing insulin secretion","c":"Decreasing absorption","d":"Increasing glucagon","ans":"A"},
{"t":"Endocrinology","q":"Best screening test in asymptomatic adult","a":"Random glucose","b":"Fasting plasma glucose","c":"Urine glucose","d":"Insulin level","ans":"B"},
{"t":"Endocrinology","q":"Patient using CGMS — advantage","a":"Detects nocturnal hypoglycemia","b":"Measures HbA1c","c":"Detects urine ketones","d":"Measures plasma insulin","ans":"A"},
{"t":"Endocrinology","q":"Sulfonylurea contraindicated in","a":"Type 2 DM","b":"Pregnancy","c":"MODY","d":"Insulin resistance","ans":"B"},
{"t":"Endocrinology","q":"Best drug in heart failure diabetic","a":"Pioglitazone","b":"Metformin","c":"SGLT2 inhibitor","d":"Sulfonylurea","ans":"C"},
{"t":"Endocrinology","q":"Patient on insulin — best site absorption fastest","a":"Abdomen","b":"Arm","c":"Thigh","d":"Buttock","ans":"A"},
{"t":"Endocrinology","q":"Bedtime glucose low, morning high","a":"Dawn phenomenon","b":"Somogyi effect","c":"Insulin resistance","d":"MODY","ans":"B"},
{"t":"Endocrinology","q":"Fasting normal, post meal high glucose","a":"Impaired fasting glucose","b":"Impaired glucose tolerance","c":"Diabetes","d":"HHS","ans":"B"},
{"t":"Endocrinology","q":"Patient prefers non-injectable weight loss diabetes drug","a":"Semaglutide oral","b":"Insulin","c":"NPH","d":"Regular insulin","ans":"A"},
{"t":"Endocrinology","q":"First step after lifestyle failure in T2DM","a":"Insulin","b":"Metformin","c":"Sulfonylurea","d":"GLP-1 agonist","ans":"B"},
{"t":"Endocrinology","q":"CGMS measures glucose every","a":"Few seconds continuously","b":"Once daily","c":"Weekly","d":"Monthly","ans":"A"},
{"t":"Endocrinology","q":"Patient glucose 210 mg/dL but asymptomatic — confirm test","a":"Repeat HbA1c","b":"Repeat random glucose","c":"OGTT","d":"Insulin level","ans":"A"},
{"t":"Endocrinology","q":"Drug contraindicated in severe renal failure","a":"Metformin","b":"Insulin","c":"Linagliptin","d":"Repaglinide","ans":"A"},
{"t":"Endocrinology","q":"Patient wants real-time glucose trends and alarms","a":"SMBG","b":"Urine testing","c":"CGMS","d":"HbA1c","ans":"C"},
{"t":"Endocrinology","q":"Type 1 diabetic presents with vomiting, abdominal pain, glucose 480 mg/dL, pH 7.12, K 5.6 mEq/L. First management step","a":"IV bicarbonate","b":"Start insulin infusion","c":"IV normal saline","d":"IV potassium","ans":"C"},
{"t":"Endocrinology","q":"DKA patient potassium 2.9 mEq/L after fluids. Next step","a":"Give bicarbonate","b":"Add dextrose","c":"Start insulin","d":"Give potassium replacement","ans":"D"},
{"t":"Endocrinology","q":"DKA treatment glucose falls to 210 mg/dL but anion gap open. Management","a":"Add dextrose and continue insulin","b":"Stop fluids","c":"Give bicarbonate","d":"Stop insulin","ans":"A"},
{"t":"Endocrinology","q":"Elderly diabetic unconscious, glucose 980 mg/dL, osmolality 340, no acidosis. Diagnosis","a":"Hypoglycemia","b":"Stroke","c":"HHS","d":"DKA","ans":"C"},
{"t":"Endocrinology","q":"Most important electrolyte monitored hourly in DKA","a":"Calcium","b":"Magnesium","c":"Sodium","d":"Potassium","ans":"D"},
{"t":"Endocrinology","q":"Child treated for DKA develops headache, bradycardia, vomiting. Cause","a":"Meningitis","b":"Cerebral edema","c":"Stroke","d":"Hypoglycemia","ans":"B"},
{"t":"Endocrinology","q":"Management of cerebral edema in DKA","a":"Hypertonic saline restriction","b":"Bicarbonate","c":"Mannitol","d":"Insulin bolus","ans":"C"},
{"t":"Endocrinology","q":"Patient planned for morning surgery, NPO midnight, on basal-bolus insulin. Night basal dose","a":"Full dose","b":"Omit","c":"Double dose","d":"Half dose","ans":"A"},
{"t":"Endocrinology","q":"Morning of surgery prandial insulin","a":"Double","b":"Replace with NPH","c":"Hold","d":"Continue","ans":"C"},
{"t":"Endocrinology","q":"Postoperative persistent glucose >250 mg/dL","a":"No treatment","b":"IV insulin infusion","c":"Oral metformin","d":"Sliding scale only","ans":"B"},
{"t":"Endocrinology","q":"Long standing diabetic albumin creatinine ratio 120 mg/g. Best management","a":"Diuretics only","b":"Start dialysis","c":"Increase protein diet","d":"Start ACE inhibitor","ans":"D"},
{"t":"Endocrinology","q":"Diabetic with reduced vibration sense and foot ulcer but intact pulses. Ulcer type","a":"Arterial embolic","b":"Neuropathic","c":"Ischemic","d":"Venous","ans":"B"},
{"t":"Endocrinology","q":"Diabetic patient sudden painless loss of vision and floaters. Likely diagnosis","a":"Glaucoma","b":"Cataract","c":"Vitreous hemorrhage","d":"Retinal detachment","ans":"C"},
{"t":"Endocrinology","q":"Patient on SGLT2 inhibitor develops nausea, ketones positive, glucose 170 mg/dL. Diagnosis","a":"DKA","b":"Starvation ketosis","c":"HHS","d":"Euglycemic DKA","ans":"D"},
{"t":"Endocrinology","q":"Most sensitive screening test for diabetic neuropathy","a":"CT scan","b":"EMG only","c":"Monofilament testing","d":"MRI","ans":"C"},
{"t":"Endocrinology","q":"Pregnant woman 26 weeks OGTT abnormal. First management","a":"No treatment","b":"Diet and exercise","c":"Insulin immediately","d":"Oral hypoglycemics","ans":"B"},
{"t":"Endocrinology","q":"Gestational diabetes uncontrolled despite diet. Next step","a":"Acarbose","b":"Sulfonylurea","c":"Metformin","d":"Insulin","ans":"D"},
{"t":"Endocrinology","q":"Neonate of diabetic mother jittery 2 hours after birth. Cause","a":"Sepsis","b":"Hypocalcemia","c":"Hypoglycemia","d":"Hyperglycemia","ans":"C"},
{"t":"Endocrinology","q":"Diabetic pregnant patient first trimester insulin requirement","a":"Stop insulin","b":"Increase","c":"Decrease","d":"No change","ans":"C"},
{"t":"Endocrinology","q":"Retinopathy screening in type 2 diabetes begins","a":"Only symptoms","b":"After insulin start","c":"5 years after diagnosis","d":"At diagnosis","ans":"D"},
{"t":"Endocrinology","q":"Patient with DKA after MI. Underlying mechanism","a":"Decreased glucagon","b":"Increased counter-regulatory hormones","c":"Renal glucose loss","d":"Increased insulin secretion","ans":"B"},
{"t":"Endocrinology","q":"HHS main cause of coma","a":"Ketones","b":"Acidosis","c":"Hyperosmolarity","d":"Hypoglycemia","ans":"C"},
{"t":"Endocrinology","q":"Diabetic undergoing colonoscopy fasting 24h. Management","a":"Oral drugs only","b":"Stop basal insulin","c":"Increase insulin","d":"Continue basal insulin","ans":"D"},
{"t":"Endocrinology","q":"DKA resolved criteria includes","a":"Closed anion gap","b":"All of the above","c":"Glucose <200 mg/dL","d":"Bicarbonate ≥18","ans":"B"},
{"t":"Endocrinology","q":"Patient chronic diabetes orthostatic hypotension gastroparesis impotence. Diagnosis","a":"Radiculopathy","b":"Myopathy","c":"Autonomic neuropathy","d":"Peripheral neuropathy","ans":"C"},
{"t":"Endocrinology","q":"Diabetic foot with black toe, cold limb, absent pulses. Management","a":"Steroids","b":"Urgent vascular referral","c":"Dressings only","d":"Antibiotics only","ans":"B"},
{"t":"Endocrinology","q":"Pregnant diabetic risk of fetal anomaly highest during","a":"Third trimester","b":"Peripartum","c":"First trimester","d":"Second trimester","ans":"C"},
{"t":"Endocrinology","q":"Severe DKA pH 6.85 indication","a":"Potassium only","b":"Immediate bicarbonate","c":"Insulin only","d":"Dextrose","ans":"B"},
{"t":"Endocrinology","q":"Patient treated DKA suddenly arrhythmia with flat T waves","a":"Hypercalcemia","b":"Hyponatremia","c":"Hyperkalemia","d":"Hypokalemia","ans":"D"},
{"t":"Endocrinology","q":"Diabetic infection leading to recurrent DKA best prevention","a":"Bed rest","b":"Stop insulin","c":"Sick day rules education","d":"Antibiotic prophylaxis","ans":"C"},
{"t":"Endocrinology","q":"Pregnant diabetic macrosomia due to","a":"Placental insufficiency","b":"Maternal ketosis","c":"Fetal hyperglycemia","d":"Fetal hyperinsulinemia","ans":"D"},
{"t":"Endocrinology","q":"Surgery patient persistent ketones normal glucose on SGLT2 inhibitor","a":"Hypoglycemia","b":"HHS","c":"Euglycemic DKA","d":"Starvation ketosis","ans":"C"},
{"t":"Endocrinology","q":"Diabetic with microalbuminuria normal BP management","a":"Beta blockers","b":"ACE inhibitor","c":"Diuretics","d":"No treatment","ans":"B"},
{"t":"Endocrinology","q":"Long standing diabetes painless MI reason","a":"Retinopathy","b":"Nephropathy","c":"Autonomic neuropathy","d":"Peripheral neuropathy","ans":"C"},
{"t":"Endocrinology","q":"DKA insulin infusion goal fall glucose per hour","a":"200 mg/dL","b":"10 mg/dL","c":"50–75 mg/dL","d":"150 mg/dL","ans":"C"},
{"t":"Endocrinology","q":"HHS corrected sodium appears low due to","a":"Hypokalemia","b":"Hyperglycemia dilution","c":"Hyperlipidemia","d":"Acidosis","ans":"B"},
{"t":"Endocrinology","q":"Diabetic nephropathy referral to nephrologist when","a":"Hypertension","b":"Microalbuminuria","c":"eGFR <30 ml/min","d":"Diagnosis time","ans":"C"},
{"t":"Endocrinology","q":"DKA patient improved but vomiting persists high ketones normal glucose","a":"HHS","b":"Incomplete DKA resolution","c":"Hypoglycemia","d":"Starvation ketosis","ans":"B"},
{"t":"Endocrinology","q":"Pregnant diabetic delivery timing in well controlled","a":"42 weeks","b":"34 weeks","c":"32 weeks","d":"39 weeks","ans":"D"},
{"t":"Endocrinology","q":"Diabetic retinopathy most common early lesion","a":"Papilledema","b":"Retinal detachment","c":"Microaneurysm","d":"Neovascularization","ans":"C"},
{"t":"Endocrinology","q":"Perioperative hyperglycemia increases risk of","a":"Thrombosis","b":"Electrolyte imbalance","c":"Bleeding","d":"Infection","ans":"D"},
{"t":"Endocrinology","q":"DKA main ketone body causing acidosis","a":"Acetone","b":"Beta-hydroxybutyrate","c":"Lactate","d":"Acetoacetate","ans":"B"},
{"t":"Endocrinology","q":"Diabetic patient recurrent hypoglycemia unawareness cause","a":"Anemia","b":"Autonomic failure","c":"Retinopathy","d":"Nephropathy","ans":"B"},
{"t":"Endocrinology","q":"Pregnant diabetic polyhydramnios mechanism","a":"Placental leak","b":"Maternal hypertension","c":"Fetal hyperglycemia polyuria","d":"Infection","ans":"C"},
{"t":"Endocrinology","q":"HHS mortality higher because","a":"Ketone toxicity","b":"More insulin deficiency","c":"Severe acidosis","d":"Older patients comorbidities","ans":"D"},
{"t":"Endocrinology","q":"Diabetic with severe infection insulin requirement","a":"No change","b":"Increases","c":"Stops","d":"Decreases","ans":"B"},
{"t":"Endocrinology","q":"DKA corrected sodium calculation purpose","a":"Diagnose SIADH","b":"Replace potassium","c":"Assess dehydration severity","d":"Diagnose hyponatremia","ans":"C"},
{"t":"Endocrinology","q":"After DKA resolution switch to subcutaneous insulin timing","a":"After 12 hours","b":"Next day","c":"Stop IV immediately","d":"Overlap 1–2 hours","ans":"D"},
{"t":"Endocrinology","q":"Diabetic pregnancy postpartum insulin requirement","a":"Stop permanently","b":"Decrease sharply","c":"Increase","d":"Same","ans":"B"},
{"t":"Endocrinology","q":"Most common cause of death in HHS","a":"Cerebral edema","b":"Ketoacidosis","c":"Thromboembolism","d":"Hypoglycemia","ans":"C"},
{"t":"Endocrinology","q":"High TSH and low free T4 indicates","a":"Sick euthyroid syndrome","b":"Secondary hypothyroidism","c":"Primary hypothyroidism","d":"Subclinical hyperthyroidism","ans":"C"},
{"t":"Endocrinology","q":"Low TSH and high free T4 indicates","a":"Hyperthyroidism","b":"Primary hypothyroidism","c":"Subclinical hypothyroidism","d":"Secondary hypothyroidism","ans":"A"},
{"t":"Endocrinology","q":"Low TSH and normal free T4 suggests","a":"Central hypothyroidism","b":"Primary hypothyroidism","c":"Overt hyperthyroidism","d":"Subclinical hyperthyroidism","ans":"D"},
{"t":"Endocrinology","q":"High TSH with normal free T4 suggests","a":"Thyroiditis","b":"Subclinical hypothyroidism","c":"Euthyroid sick syndrome","d":"Overt hypothyroidism","ans":"B"},
{"t":"Endocrinology","q":"Low TSH and low T4 indicates","a":"Subclinical hyperthyroidism","b":"Graves disease","c":"Central hypothyroidism","d":"Primary hyperthyroidism","ans":"C"},
{"t":"Endocrinology","q":"Most common cause of hyperthyroidism worldwide","a":"Iodine excess","b":"Graves disease","c":"Toxic adenoma","d":"Thyroiditis","ans":"B"},
{"t":"Endocrinology","q":"Antibody seen in Graves disease","a":"Anti-mitochondrial","b":"Anti-thyroglobulin","c":"TSH receptor antibody","d":"Anti-TPO","ans":"C"},
{"t":"Endocrinology","q":"First line treatment of Graves disease","a":"Surgery","b":"Propranolol only","c":"Methimazole","d":"Levothyroxine","ans":"C"},
{"t":"Endocrinology","q":"Drug preferred in first trimester pregnancy hyperthyroidism","a":"Carbimazole","b":"Radioiodine","c":"Propylthiouracil","d":"Methimazole","ans":"C"},
{"t":"Endocrinology","q":"Thyroid storm initial management","a":"Surgery","b":"Beta blocker","c":"Levothyroxine","d":"Radioiodine","ans":"B"},
{"t":"Endocrinology","q":"Drug given after thionamide in thyroid storm","a":"Levothyroxine","b":"Lithium","c":"Steroid withdrawal","d":"Iodine solution","ans":"D"},
{"t":"Endocrinology","q":"Eye finding specific for Graves disease","a":"Conjunctivitis","b":"Cataract","c":"Lid lag","d":"Proptosis","ans":"D"},
{"t":"Endocrinology","q":"Mechanism of thyroid eye disease","a":"Vascular obstruction","b":"Autoimmune orbital inflammation","c":"Infection","d":"Direct hormone toxicity","ans":"B"},
{"t":"Endocrinology","q":"Best treatment for mild thyroid eye disease","a":"Surgery","b":"Steroids","c":"Artificial tears and smoking cessation","d":"Radioiodine","ans":"C"},
{"t":"Endocrinology","q":"Drug of choice for hypothyroidism","a":"Iodine","b":"Carbimazole","c":"Levothyroxine","d":"Liothyronine","ans":"C"},
{"t":"Endocrinology","q":"Start low dose levothyroxine in elderly because risk of","a":"Hypoglycemia","b":"Renal failure","c":"Arrhythmia","d":"Stroke","ans":"C"},
{"t":"Endocrinology","q":"Hashimoto thyroiditis antibody","a":"Anti-centromere","b":"Anti-TPO","c":"Anti-Smith","d":"Anti-TSH receptor","ans":"B"},
{"t":"Endocrinology","q":"Most common cause of hypothyroidism","a":"Iodine deficiency","b":"Drugs","c":"Hashimoto thyroiditis","d":"Graves disease","ans":"C"},
{"t":"Endocrinology","q":"Sick euthyroid syndrome lab pattern","a":"High T4","b":"High TSH","c":"Low T3 normal TSH","d":"High T3","ans":"C"},
{"t":"Endocrinology","q":"Painful thyroid gland suggests","a":"Cancer","b":"Subacute thyroiditis","c":"Graves disease","d":"Hashimoto","ans":"B"},
{"t":"Endocrinology","q":"Initial test for thyroid nodule evaluation","a":"CT scan","b":"Biopsy immediately","c":"TSH level","d":"PET scan","ans":"C"},
{"t":"Endocrinology","q":"Low TSH in thyroid nodule next step","a":"MRI","b":"Surgery","c":"FNAC","d":"Thyroid scan","ans":"D"},
{"t":"Endocrinology","q":"High TSH thyroid nodule next step","a":"Steroids","b":"Radioiodine","c":"FNAC","d":"Antibiotics","ans":"C"},
{"t":"Endocrinology","q":"Hot nodule on scan risk of malignancy","a":"Certain","b":"High","c":"Low","d":"Moderate","ans":"C"},
{"t":"Endocrinology","q":"Most common thyroid cancer","a":"Anaplastic","b":"Papillary","c":"Follicular","d":"Medullary","ans":"B"},
{"t":"Endocrinology","q":"Medullary carcinoma marker","a":"Thyroglobulin","b":"T4","c":"Calcitonin","d":"TSH","ans":"C"},
{"t":"Endocrinology","q":"Thyroglobulin used to monitor","a":"Thyroiditis","b":"Graves disease","c":"Medullary cancer","d":"Papillary cancer recurrence","ans":"D"},
{"t":"Endocrinology","q":"Hyperthyroid patient atrial fibrillation treatment","a":"Calcium","b":"ACE inhibitors","c":"Beta blockers","d":"Digoxin only","ans":"C"},
{"t":"Endocrinology","q":"Myxedema coma first treatment","a":"Methimazole","b":"IV levothyroxine","c":"Oral levothyroxine","d":"Iodine","ans":"B"},
{"t":"Endocrinology","q":"Add steroid in myxedema coma to treat possible","a":"Hypokalemia","b":"Adrenal insufficiency","c":"Hypertension","d":"Hyperglycemia","ans":"B"},
{"t":"Endocrinology","q":"Graves disease relapse after stopping drugs best definitive treatment","a":"Iodine","b":"Beta blockers","c":"Radioiodine","d":"Repeat drugs","ans":"C"},
{"t":"Endocrinology","q":"Radioiodine contraindicated in","a":"Diabetes","b":"Males","c":"Pregnancy","d":"Elderly","ans":"C"},
{"t":"Endocrinology","q":"Drug causing hypothyroidism","a":"Propranolol","b":"Amiodarone","c":"Metformin","d":"Insulin","ans":"B"},
{"t":"Endocrinology","q":"Post thyroidectomy complication","a":"Hyperkalemia","b":"Hypernatremia","c":"Hypercalcemia","d":"Hypocalcemia","ans":"D"},
{"t":"Endocrinology","q":"Hypothyroid symptoms include","a":"Tachycardia","b":"Constipation","c":"Heat intolerance","d":"Weight loss","ans":"B"},
{"t":"Endocrinology","q":"Hyperthyroid symptoms include","a":"Bradycardia","b":"Cold intolerance","c":"Weight gain","d":"Tremors","ans":"D"},
{"t":"Endocrinology","q":"Subclinical hypothyroidism treated when TSH >","a":"15","b":"10","c":"4","d":"6","ans":"B"},
{"t":"Endocrinology","q":"Thyroid eye disease diplopia cause","a":"Nerve palsy","b":"Retina detachment","c":"Lens opacity","d":"Muscle fibrosis","ans":"D"},
{"t":"Endocrinology","q":"Toxic multinodular goiter common in","a":"Children","b":"Young","c":"Pregnancy","d":"Elderly","ans":"D"},
{"t":"Endocrinology","q":"Drug before thyroid surgery","a":"Calcium","b":"Iodine","c":"Steroids","d":"Insulin","ans":"B"},
{"t":"Endocrinology","q":"FNAC Bethesda III means","a":"Normal","b":"Malignant","c":"Atypia undetermined","d":"Benign","ans":"C"},
{"t":"Endocrinology","q":"Hypothyroid pregnant treatment","a":"Decrease dose","b":"Stop therapy","c":"Increase levothyroxine dose","d":"Radioiodine","ans":"C"},
{"t":"Endocrinology","q":"Central hypothyroidism TSH level","a":"Fluctuating","b":"Low/normal","c":"Very high","d":"High","ans":"B"},
{"t":"Endocrinology","q":"Thyroid storm precipitating factor","a":"Sleep","b":"Rest","c":"Exercise","d":"Infection","ans":"D"},
{"t":"Endocrinology","q":"Graves dermopathy appearance","a":"Vesicles","b":"Pretibial myxedema","c":"Maculopapular rash","d":"Ulcers","ans":"B"},
{"t":"Endocrinology","q":"Rapidly growing hard thyroid mass suspicion","a":"Goiter","b":"Benign cyst","c":"Graves disease","d":"Anaplastic carcinoma","ans":"D"},
{"t":"Endocrinology","q":"Preferred imaging suspicious thyroid cancer","a":"MRI","b":"CT","c":"Ultrasound","d":"PET","ans":"C"},
{"t":"Endocrinology","q":"Toxic adenoma treatment definitive","a":"Levothyroxine","b":"Radioiodine","c":"Steroids","d":"Beta blockers","ans":"B"},
{"t":"Endocrinology","q":"Hypothyroidism causes hyperlipidemia due to","a":"Increased bile excretion","b":"Increased HDL metabolism","c":"Increased LDL clearance","d":"Reduced LDL receptor activity","ans":"D"},
{"t":"Endocrinology","q":"Best screening test for thyroid dysfunction","a":"Antibodies","b":"TSH","c":"T4","d":"T3","ans":"B"},
{"t":"Endocrinology","q":"A 32-year-old woman has palpitations, weight loss and anxiety. TSH suppressed, free T4 high, uptake scan shows diffuse uptake. Diagnosis","a":"Factitious thyrotoxicosis","b":"Toxic adenoma","c":"Graves disease","d":"Thyroiditis","ans":"C"},
{"t":"Endocrinology","q":"A patient with hyperthyroidism has low uptake on radioactive iodine scan and recent viral illness with neck pain. Diagnosis","a":"Thyroid carcinoma","b":"Subacute thyroiditis","c":"Graves disease","d":"Toxic multinodular goiter","ans":"B"},
{"t":"Endocrinology","q":"Patient taking excessive levothyroxine shows high T4, suppressed TSH and very low thyroglobulin. Cause","a":"Thyroiditis","b":"Toxic adenoma","c":"Graves disease","d":"Factitious thyrotoxicosis","ans":"D"},
{"t":"Endocrinology","q":"A 70-year-old with weight loss and atrial fibrillation, irregular nodular thyroid and patchy uptake. Diagnosis","a":"Hashimoto thyroiditis","b":"Thyroiditis","c":"Toxic multinodular goiter","d":"Graves disease","ans":"C"},
{"t":"Endocrinology","q":"Patient started methimazole develops fever and sore throat. Next step","a":"Add beta blocker","b":"Reduce dose","c":"CBC immediately","d":"Continue drug","ans":"C"},
{"t":"Endocrinology","q":"Hyperthyroid patient with severe asthma requires rate control. Best drug","a":"Propranolol","b":"Digoxin","c":"Diltiazem","d":"Atenolol","ans":"C"},
{"t":"Endocrinology","q":"Thyroid storm patient after giving PTU next drug should be","a":"Levothyroxine","b":"Radioiodine","c":"Lithium","d":"Iodine solution","ans":"D"},
{"t":"Endocrinology","q":"A hospitalized septic patient has low T3, low T4, normal TSH. Interpretation","a":"Subclinical hypothyroidism","b":"Central hypothyroidism","c":"Sick euthyroid syndrome","d":"Graves disease","ans":"C"},
{"t":"Endocrinology","q":"Elderly woman fatigue, hyponatremia, bradycardia, hypothermia. Most likely diagnosis","a":"Adrenal crisis","b":"SIADH","c":"Thyroid storm","d":"Myxedema coma","ans":"D"},
{"t":"Endocrinology","q":"First drug in myxedema coma along with thyroid hormone","a":"Iodine","b":"Hydrocortisone","c":"Methimazole","d":"Propranolol","ans":"B"},
{"t":"Endocrinology","q":"Patient with hypothyroidism develops chest pain after starting full dose levothyroxine. Reason","a":"Anemia","b":"Coronary vasospasm","c":"Increased myocardial oxygen demand","d":"Hyperkalemia","ans":"C"},
{"t":"Endocrinology","q":"A thyroid nodule with microcalcifications and irregular margins on ultrasound. Next step","a":"Thyroid scan","b":"FNAC","c":"T3 measurement","d":"Repeat ultrasound","ans":"B"},
{"t":"Endocrinology","q":"Thyroid nodule 1 cm with normal TSH but family history medullary carcinoma. Next step","a":"Calcitonin level","b":"Radioiodine","c":"Observe","d":"FNAC","ans":"A"},
{"t":"Endocrinology","q":"Patient with MEN2 suspected thyroid lesion best initial test","a":"TSH","b":"T4","c":"Calcitonin","d":"Thyroglobulin","ans":"C"},
{"t":"Endocrinology","q":"Pregnant woman hyperthyroid second trimester preferred drug","a":"Surgery","b":"PTU","c":"Radioiodine","d":"Methimazole","ans":"D"},
{"t":"Endocrinology","q":"Patient after radioiodine develops worsening eye disease. Prevention","a":"Iodine","b":"Levothyroxine","c":"Beta blockers","d":"Steroids","ans":"D"},
{"t":"Endocrinology","q":"Hyperthyroid patient with severe ophthalmopathy best definitive treatment","a":"Methimazole lifelong","b":"Surgery","c":"Radioiodine","d":"Iodine","ans":"B"},
{"t":"Endocrinology","q":"Thyroid nodule cystic completely on ultrasound. Next step","a":"Radioiodine","b":"Surgery","c":"FNAC","d":"Reassurance","ans":"D"},
{"t":"Endocrinology","q":"Rapid painful thyroid enlargement with fever and erythema. Diagnosis","a":"Cancer","b":"Acute suppurative thyroiditis","c":"Hashimoto","d":"Graves disease","ans":"B"},
{"t":"Endocrinology","q":"Hypothyroid patient persistent symptoms normal TSH on therapy. Next step","a":"Stop therapy","b":"Add T3","c":"Check compliance and timing","d":"Increase dose","ans":"C"},
{"t":"Endocrinology","q":"Drug interfering levothyroxine absorption","a":"Beta blockers","b":"ACE inhibitors","c":"Insulin","d":"Iron supplements","ans":"D"},
{"t":"Endocrinology","q":"Hyperthyroid patient severe agitation fever delirium. Diagnosis","a":"Encephalitis","b":"Thyroid storm","c":"Panic attack","d":"Psychosis","ans":"B"},
{"t":"Endocrinology","q":"Patient with goiter low uptake high T4 after amiodarone use. Type","a":"Graves disease","b":"Type 2 destructive thyroiditis","c":"Toxic adenoma","d":"Type 1 amiodarone thyrotoxicosis","ans":"B"},
{"t":"Endocrinology","q":"Thyroid cancer follow up rising thyroglobulin but negative scan","a":"Hypothyroidism","b":"Thyroiditis","c":"Cure","d":"Recurrence suspected","ans":"D"},
{"t":"Endocrinology","q":"Post thyroidectomy tingling lips and carpopedal spasm. Cause","a":"Hypoglycemia","b":"Hypocalcemia","c":"Hypokalemia","d":"Hypernatremia","ans":"B"},
{"t":"Endocrinology","q":"Graves disease bruit over thyroid indicates","a":"Fibrosis","b":"Malignancy","c":"Increased vascularity","d":"Infection","ans":"C"},
{"t":"Endocrinology","q":"Elderly apathetic hyperthyroidism presents mainly with","a":"Heat intolerance","b":"Goiter","c":"Depression and weight loss","d":"Tremors","ans":"C"},
{"t":"Endocrinology","q":"TSH suppressed T4 normal T3 high diagnosis","a":"Hypothyroidism","b":"Subclinical hyperthyroidism","c":"T3 toxicosis","d":"Thyroiditis","ans":"C"},
{"t":"Endocrinology","q":"Subclinical hyperthyroidism complication risk highest","a":"Renal failure","b":"Anemia","c":"Liver failure","d":"Osteoporosis","ans":"D"},
{"t":"Endocrinology","q":"Hypothyroidism causing infertility due to","a":"Decreased FSH","b":"Increased prolactin","c":"Increased LH","d":"Increased estrogen","ans":"B"},
{"t":"Endocrinology","q":"Postpartum woman hyperthyroid then hypothyroid pattern","a":"Toxic adenoma","b":"Cancer","c":"Postpartum thyroiditis","d":"Graves disease","ans":"C"},
{"t":"Endocrinology","q":"Patient hyperthyroid normal uptake scan high hCG levels. Cause","a":"Adenoma","b":"Thyroiditis","c":"Graves","d":"Trophoblastic disease","ans":"D"},
{"t":"Endocrinology","q":"Large goiter compressing trachea management","a":"Radioiodine","b":"Observation","c":"Surgery","d":"Methimazole","ans":"C"},
{"t":"Endocrinology","q":"Thyroid eye disease severe optic neuropathy treatment","a":"Iodine","b":"Beta blockers","c":"High dose steroids","d":"Lubricants","ans":"C"},
{"t":"Endocrinology","q":"Central hypothyroidism best monitoring parameter during therapy","a":"T3","b":"TSH","c":"Free T4","d":"Antibodies","ans":"C"},
{"t":"Endocrinology","q":"Hypothyroid patient pericardial effusion cause","a":"Infection","b":"MI","c":"Renal failure","d":"Increased capillary permeability","ans":"D"},
{"t":"Endocrinology","q":"Radioiodine ablation contraindicated in","a":"Relapse Graves","b":"Elderly","c":"Pregnancy","d":"Large goiter compressive","ans":"C"},
{"t":"Endocrinology","q":"Thyroid storm beta blocker benefit","a":"Stimulates thyroid","b":"Blocks T4 to T3 conversion","c":"Reduces antibodies","d":"Increases hormone release","ans":"B"},
{"t":"Endocrinology","q":"Hypothyroid patient macrocytic anemia due to","a":"Hemolysis","b":"Iron deficiency","c":"B12 deficiency association","d":"Bleeding","ans":"C"},
{"t":"Endocrinology","q":"Toxic adenoma uptake scan finding","a":"No uptake","b":"Cold gland","c":"Single hot nodule","d":"Diffuse uptake","ans":"C"},
{"t":"Endocrinology","q":"Cold thyroid nodule concern","a":"Thyroiditis","b":"Hypothyroidism","c":"Malignancy","d":"Hyperthyroidism","ans":"C"},
{"t":"Endocrinology","q":"Thyroid cancer after childhood radiation most likely","a":"Lymphoma","b":"Anaplastic","c":"Medullary carcinoma","d":"Papillary carcinoma","ans":"D"},
{"t":"Endocrinology","q":"Subclinical hypothyroidism pregnancy management","a":"Radioiodine","b":"Observe","c":"Methimazole","d":"Start levothyroxine","ans":"D"},
{"t":"Endocrinology","q":"Levothyroxine best taken","a":"With milk","b":"Empty stomach morning","c":"Night after dinner","d":"After meals","ans":"B"},
{"t":"Endocrinology","q":"Hyperthyroid tremor mechanism","a":"Calcium deficiency","b":"Hypoglycemia","c":"Beta adrenergic stimulation","d":"Dopamine excess","ans":"C"},
{"t":"Endocrinology","q":"Severe hypothyroidism hypercapnia mechanism","a":"Pulmonary embolism","b":"Metabolic acidosis","c":"Hyperventilation","d":"Hypoventilation","ans":"D"},
{"t":"Endocrinology","q":"Post thyroidectomy hoarseness cause","a":"Hypocalcemia","b":"Infection","c":"Recurrent laryngeal nerve injury","d":"Edema","ans":"C"},
{"t":"Endocrinology","q":"Hyperthyroid increased appetite but weight loss due to","a":"Malabsorption","b":"Infection","c":"Increased basal metabolic rate","d":"Vomiting","ans":"C"},
{"t":"Endocrinology","q":"Elderly with isolated low TSH no symptoms best step","a":"Radioiodine","b":"Surgery","c":"Repeat testing","d":"Treat immediately","ans":"C"},
{"t":"Endocrinology","q":"Most specific test confirming Graves disease","a":"T4 level","b":"Ultrasound","c":"Anti-TPO antibodies","d":"TSH receptor antibodies","ans":"D"},
{"t":"Endocrinology","q":"A 22-year-old woman has irregular menses, acne and hirsutism. Ultrasound shows multiple peripheral ovarian follicles. Most likely diagnosis","a":"Premature ovarian failure","b":"Polycystic ovarian syndrome","c":"Hypothyroidism","d":"Hyperprolactinemia","ans":"B"},
{"t":"Endocrinology","q":"Most important diagnostic hormonal abnormality in PCOS","a":"Low prolactin","b":"Low FSH","c":"High estrogen","d":"High LH:FSH ratio","ans":"D"},
{"t":"Endocrinology","q":"First line treatment for infertility in PCOS","a":"Spironolactone","b":"Clomiphene citrate","c":"Combined OCP","d":"Metformin","ans":"B"},
{"t":"Endocrinology","q":"Best initial management for overweight PCOS patient","a":"Surgery","b":"OCPs","c":"Weight loss","d":"GnRH agonist","ans":"C"},
{"t":"Endocrinology","q":"Drug used for hirsutism in PCOS","a":"Progesterone","b":"Bromocriptine","c":"Spironolactone","d":"Levothyroxine","ans":"C"},
{"t":"Endocrinology","q":"PCOS increases risk of","a":"Cervical cancer","b":"Type 1 diabetes","c":"Endometrial hyperplasia","d":"Ovarian failure","ans":"C"},
{"t":"Endocrinology","q":"Best investigation to confirm ovulation in PCOS treatment","a":"Prolactin","b":"Day 21 progesterone","c":"TSH","d":"Day 2 FSH","ans":"B"},
{"t":"Endocrinology","q":"Drug improving insulin resistance in PCOS","a":"Progesterone","b":"Metformin","c":"Clomiphene","d":"Letrozole","ans":"B"},
{"t":"Endocrinology","q":"PCOS ovarian morphology","a":"Single cyst","b":"Atrophic ovary","c":"Multiple peripheral follicles","d":"Solid tumor","ans":"C"},
{"t":"Endocrinology","q":"Most common menstrual abnormality in PCOS","a":"Dysmenorrhea","b":"Amenorrhea only","c":"Menorrhagia","d":"Oligomenorrhea","ans":"D"},
{"t":"Endocrinology","q":"Elevated androgen in PCOS produced mainly by","a":"Adrenal only","b":"Hypothalamus","c":"Pituitary","d":"Ovarian theca cells","ans":"D"},
{"t":"Endocrinology","q":"PCOS Rotterdam criteria require","a":"Only ultrasound","b":"All three features","c":"Only hormones","d":"Two of three features","ans":"D"},
{"t":"Endocrinology","q":"Lean PCOS infertility preferred ovulation induction","a":"OCPs","b":"Metformin alone","c":"Letrozole","d":"Steroids","ans":"C"},
{"t":"Endocrinology","q":"Complication of long-term untreated PCOS","a":"Tubal blockage","b":"Endometrial carcinoma","c":"Cervical cancer","d":"Fibroids","ans":"B"},
{"t":"Endocrinology","q":"A woman with PCOS and acanthosis nigricans indicates","a":"Estrogen deficiency","b":"Insulin resistance","c":"Hypothyroidism","d":"Hyperprolactinemia","ans":"B"},
{"t":"Endocrinology","q":"Primary hypogonadism lab pattern","a":"Normal FSH LH","b":"High prolactin","c":"High FSH high LH","d":"Low FSH low LH","ans":"C"},
{"t":"Endocrinology","q":"Secondary hypogonadism lab pattern","a":"High testosterone","b":"Low FSH LH","c":"High estrogen","d":"High FSH LH","ans":"B"},
{"t":"Endocrinology","q":"Turner syndrome karyotype","a":"47 XXY","b":"46 XX","c":"45 XO","d":"46 XY","ans":"C"},
{"t":"Endocrinology","q":"Most common feature of Turner syndrome","a":"Macroorchidism","b":"Short stature","c":"Gynecomastia","d":"Tall stature","ans":"B"},
{"t":"Endocrinology","q":"Turner syndrome associated cardiac defect","a":"PDA","b":"Coarctation of aorta","c":"VSD","d":"ASD","ans":"B"},
{"t":"Endocrinology","q":"Turner syndrome infertility cause","a":"Pituitary tumor","b":"Hyperprolactinemia","c":"Uterine agenesis","d":"Gonadal streak ovaries","ans":"D"},
{"t":"Endocrinology","q":"Klinefelter syndrome karyotype","a":"46 XY","b":"47 XXY","c":"45 XO","d":"46 XX","ans":"B"},
{"t":"Endocrinology","q":"Klinefelter syndrome characteristic feature","a":"Precocious puberty","b":"Short stature","c":"Gynecomastia","d":"Early virilization","ans":"C"},
{"t":"Endocrinology","q":"Klinefelter infertility due to","a":"Low estrogen","b":"Obstruction","c":"Azoospermia","d":"Hyperprolactin","ans":"C"},
{"t":"Endocrinology","q":"Hormonal profile in Klinefelter syndrome","a":"High estrogen low LH","b":"Low FSH LH","c":"High FSH LH low testosterone","d":"High testosterone","ans":"C"},
{"t":"Endocrinology","q":"First sign of puberty in girls","a":"Growth spurt","b":"Pubic hair","c":"Menarche","d":"Breast budding","ans":"D"},
{"t":"Endocrinology","q":"Delayed puberty female no secondary sexual characteristics at age","a":"13","b":"11","c":"15","d":"12","ans":"C"},
{"t":"Endocrinology","q":"Primary amenorrhea with normal breasts and absent uterus suggests","a":"Turner syndrome","b":"Hypothyroidism","c":"Mullerian agenesis","d":"PCOS","ans":"C"},
{"t":"Endocrinology","q":"High prolactin hypogonadism cause","a":"Fibroid","b":"Thyroid tumor","c":"Pituitary adenoma","d":"Ovarian cyst","ans":"C"},
{"t":"Endocrinology","q":"Most common cause secondary amenorrhea","a":"Turner syndrome","b":"Klinefelter","c":"Ovarian failure","d":"PCOS","ans":"D"},
{"t":"Endocrinology","q":"Hypogonadotropic hypogonadism smell absent suggests","a":"Turner syndrome","b":"Kallmann syndrome","c":"CAH","d":"PCOS","ans":"B"},
{"t":"Endocrinology","q":"Testosterone replacement indicated in","a":"Hyperprolactinemia","b":"PCOS","c":"Klinefelter syndrome","d":"Hypothyroidism","ans":"C"},
{"t":"Endocrinology","q":"Turner syndrome hormone therapy","a":"Androgen blockers","b":"Testosterone","c":"Progesterone only","d":"Estrogen replacement","ans":"D"},
{"t":"Endocrinology","q":"PCOS patient infertility resistant to clomiphene next step","a":"Steroids","b":"Surgery","c":"OCP","d":"Gonadotropin therapy","ans":"D"},
{"t":"Endocrinology","q":"Elevated AMH level seen in","a":"Turner syndrome","b":"Menopause","c":"PCOS","d":"Ovarian failure","ans":"C"},
{"t":"Endocrinology","q":"Gynecomastia with small testes and tall stature diagnosis","a":"Hypothyroidism","b":"Turner syndrome","c":"Klinefelter syndrome","d":"PCOS","ans":"C"},
{"t":"Endocrinology","q":"Primary ovarian insufficiency lab pattern","a":"Normal hormones","b":"High FSH low estrogen","c":"High prolactin","d":"Low FSH high estrogen","ans":"B"},
{"t":"Endocrinology","q":"Best initial test primary amenorrhea","a":"Prolactin","b":"MRI brain","c":"Karyotype","d":"Pregnancy test","ans":"D"},
{"t":"Endocrinology","q":"Galactorrhea amenorrhea evaluation first test","a":"Estradiol","b":"FSH","c":"Prolactin level","d":"Progesterone","ans":"C"},
{"t":"Endocrinology","q":"Treatment hyperprolactinemia","a":"Testosterone","b":"Steroids","c":"Cabergoline","d":"Estrogen","ans":"C"},
{"t":"Endocrinology","q":"PCOS acne mechanism","a":"Thyroxine excess","b":"Estrogen excess","c":"Progesterone deficiency","d":"Androgen excess","ans":"D"},
{"t":"Endocrinology","q":"Turner syndrome short stature treatment","a":"Testosterone","b":"Growth hormone","c":"Progesterone","d":"Estrogen","ans":"B"},
{"t":"Endocrinology","q":"Klinefelter increased risk","a":"Ovarian cancer","b":"Cervical cancer","c":"Breast cancer","d":"Endometrial cancer","ans":"C"},
{"t":"Endocrinology","q":"Hypogonadism decreased libido male most sensitive test","a":"FSH","b":"Prolactin","c":"Total testosterone morning","d":"LH","ans":"C"},
{"t":"Endocrinology","q":"Secondary hypogonadism fertility treatment","a":"Antiandrogens","b":"OCP","c":"Testosterone only","d":"hCG therapy","ans":"D"},
{"t":"Endocrinology","q":"PCOS associated lipid abnormality","a":"Low LDL","b":"High HDL","c":"High triglycerides","d":"Low cholesterol","ans":"C"},
{"t":"Endocrinology","q":"Amenorrhea athlete low BMI cause","a":"Turner syndrome","b":"Hypothalamic suppression","c":"Pregnancy","d":"PCOS","ans":"B"},
{"t":"Endocrinology","q":"Hyperandrogenism virilization suspect","a":"Turner syndrome","b":"Hypothyroidism","c":"PCOS","d":"Ovarian/adrenal tumor","ans":"D"},
{"t":"Endocrinology","q":"Most common chromosomal cause male infertility","a":"Edwards syndrome","b":"Down syndrome","c":"Turner syndrome","d":"Klinefelter syndrome","ans":"D"},
{"t":"Endocrinology","q":"Delayed puberty boy high FSH low testosterone diagnosis","a":"Hyperprolactinemia","b":"Constitutional delay","c":"Primary hypogonadism","d":"Secondary hypogonadism","ans":"C"},
{"t":"Endocrinology","q":"A couple has been trying to conceive for 14 months. The female partner has regular 28-day cycles and normal pelvic examination. The male partner has normal libido and erections. What should be the first investigation in evaluation of infertility","a":"Hysterosalpingography","b":"Diagnostic laparoscopy","c":"Semen analysis","d":"Serum prolactin","ans":"C"},
{"t":"Endocrinology","q":"A semen analysis shows sperm count 8 million/mL with normal motility and morphology. This finding is best described as","a":"Teratospermia","b":"Necrospermia","c":"Oligospermia","d":"Azoospermia","ans":"C"},
{"t":"Endocrinology","q":"A woman with infertility has regular cycles and mid-luteal progesterone level 12 ng/mL. This result indicates","a":"Ovarian failure","b":"Anovulation","c":"Ovulation occurred","d":"Luteal phase defect","ans":"C"},
{"t":"Endocrinology","q":"A 30-year-old woman with irregular menses and infertility has elevated prolactin levels. The most appropriate next investigation","a":"Thyroid scan","b":"Endometrial biopsy","c":"MRI pituitary","d":"Pelvic ultrasound","ans":"C"},
{"t":"Endocrinology","q":"A female patient presents with infertility and galactorrhea. Labs show high prolactin and low FSH/LH. Mechanism of infertility","a":"Tubal blockage","b":"Hypothalamic GnRH suppression","c":"Ovarian resistance","d":"Endometrial fibrosis","ans":"B"},
{"t":"Endocrinology","q":"A couple infertile for 2 years. Female HSG shows bilateral tubal blockage. Best management option","a":"Progesterone therapy","b":"IUI","c":"IVF","d":"Ovulation induction","ans":"C"},
{"t":"Endocrinology","q":"A man has azoospermia with high FSH and small testes. Diagnosis","a":"Pituitary adenoma","b":"Obstructive azoospermia","c":"Hypogonadotropic hypogonadism","d":"Primary testicular failure","ans":"D"},
{"t":"Endocrinology","q":"A man with infertility has low FSH, low LH and low testosterone. Most likely defect level","a":"Epididymal","b":"Testicular","c":"Hypothalamic-pituitary","d":"Prostate","ans":"C"},
{"t":"Endocrinology","q":"A woman with infertility has normal hormones but painful menstruation and dyspareunia. Most likely cause","a":"Thyroid disease","b":"Endometriosis","c":"Hyperprolactinemia","d":"PCOS","ans":"B"},
{"t":"Endocrinology","q":"A male infertility patient with normal sperm count but poor motility has","a":"Teratospermia","b":"Asthenospermia","c":"Oligospermia","d":"Azoospermia","ans":"B"},
{"t":"Endocrinology","q":"A woman day-3 labs show high FSH and low estradiol. Interpretation","a":"Hyperprolactinemia","b":"Good ovarian reserve","c":"Anovulation","d":"Poor ovarian reserve","ans":"D"},
{"t":"Endocrinology","q":"A couple infertility with retrograde ejaculation suspected in male. Best confirmatory test","a":"Prostate biopsy","b":"Testosterone level","c":"Post-ejaculatory urine analysis","d":"Ultrasound scrotum","ans":"C"},
{"t":"Endocrinology","q":"Female infertility evaluation: patent tubes and ovulation confirmed but no conception after 2 years. Diagnosis","a":"Tubal infertility","b":"Unexplained infertility","c":"Premature ovarian failure","d":"PCOS","ans":"B"},
{"t":"Endocrinology","q":"A woman with amenorrhea, low FSH/LH and low estrogen after excessive exercise. Cause","a":"Pituitary tumor","b":"Ovarian failure","c":"Hypothalamic suppression","d":"Hyperprolactinemia","ans":"C"},
{"t":"Endocrinology","q":"A male infertility patient has normal testosterone but high LH. Interpretation","a":"Secondary hypogonadism","b":"Androgen resistance","c":"Pituitary failure","d":"Hyperprolactinemia","ans":"B"},
{"t":"Endocrinology","q":"A woman with infertility suspected luteal phase defect. Best test","a":"Prolactin","b":"Day 21 progesterone","c":"TSH","d":"Day 3 FSH","ans":"B"},
{"t":"Endocrinology","q":"A female patient with recurrent miscarriages and infertility. Most appropriate uterine evaluation","a":"CT scan","b":"Hormonal assay","c":"Hysteroscopy","d":"Semen analysis","ans":"C"},
{"t":"Endocrinology","q":"A man infertility with normal hormones but varicocele on exam. Management","a":"Testosterone therapy","b":"Varicocele repair","c":"Steroids","d":"Observation only","ans":"B"},
{"t":"Endocrinology","q":"A female infertility patient with anovulation due to PCOS. First-line ovulation induction","a":"hCG only","b":"Progesterone","c":"Letrozole","d":"Estrogen","ans":"C"},
{"t":"Endocrinology","q":"A male infertility case with fructose absent in semen. Suggests obstruction at","a":"Prostate","b":"Testis","c":"Epididymis","d":"Seminal vesicle/ejaculatory duct","ans":"D"},
{"t":"Endocrinology","q":"Woman infertility with high prolactin normal MRI. Treatment","a":"Surgery","b":"Progesterone","c":"Cabergoline","d":"Estrogen","ans":"C"},
{"t":"Endocrinology","q":"A patient with primary amenorrhea and infertility has 46 XY karyotype and female phenotype. Diagnosis","a":"PCOS","b":"Turner syndrome","c":"Mullerian agenesis","d":"Androgen insensitivity syndrome","ans":"D"},
{"t":"Endocrinology","q":"A man infertility low semen volume acidic pH. Cause","a":"Epididymal failure","b":"Seminal vesicle obstruction","c":"Varicocele","d":"Hormonal deficiency","ans":"B"},
{"t":"Endocrinology","q":"Female infertility with high TSH elevated prolactin. Primary problem","a":"Pituitary tumor","b":"Hypothyroidism","c":"PCOS","d":"Ovarian failure","ans":"B"},
{"t":"Endocrinology","q":"A woman infertility normal ovulation but hydrosalpinx present. Management","a":"Metformin","b":"Clomiphene","c":"Progesterone","d":"IVF after salpingectomy","ans":"D"},
{"t":"Endocrinology","q":"Male infertility high FSH normal LH testosterone low. Interpretation","a":"Androgen resistance","b":"Hypothalamic failure","c":"Sertoli cell failure","d":"Pituitary tumor","ans":"C"},
{"t":"Endocrinology","q":"Female infertility suspected diminished ovarian reserve. Best marker","a":"Progesterone","b":"AMH level","c":"Prolactin","d":"TSH","ans":"B"},
{"t":"Endocrinology","q":"A woman infertility post pelvic inflammatory disease. Likely cause","a":"PCOS","b":"Endometriosis","c":"Ovarian failure","d":"Tubal damage","ans":"D"},
{"t":"Endocrinology","q":"Male infertility with Kallmann syndrome treatment for fertility","a":"Estrogen","b":"Surgery","c":"Testosterone only","d":"hCG and FSH therapy","ans":"D"},
{"t":"Endocrinology","q":"A female patient with regular cycles infertility suspected cervical factor. Best test","a":"MRI","b":"Postcoital test","c":"HSG","d":"Hormones","ans":"B"},
{"t":"Endocrinology","q":"A woman infertility and dyspareunia laparoscopic chocolate cyst seen. Diagnosis","a":"PID","b":"PCOS","c":"Endometriosis","d":"Fibroid","ans":"C"},
{"t":"Endocrinology","q":"Male infertility high prolactin low testosterone. Mechanism","a":"Obstruction","b":"Varicocele","c":"Testicular damage","d":"GnRH suppression","ans":"D"},
{"t":"Endocrinology","q":"A woman infertility with intrauterine adhesions after curettage. Diagnosis","a":"Endometriosis","b":"Fibroid","c":"Asherman syndrome","d":"PCOS","ans":"C"},
{"t":"Endocrinology","q":"Female infertility with premature ovarian insufficiency treatment for pregnancy","a":"Clomiphene","b":"Letrozole","c":"Donor oocyte IVF","d":"Metformin","ans":"C"},
{"t":"Endocrinology","q":"Male infertility evaluation most sensitive sperm function test","a":"Semen volume","b":"Sperm count","c":"Sperm motility","d":"Sperm morphology strict criteria","ans":"D"},
{"t":"Endocrinology","q":"A patient infertility elevated LH low FSH estrogen normal. Suggests","a":"Hypogonadism","b":"Hyperprolactinemia","c":"PCOS","d":"Ovarian failure","ans":"C"},
{"t":"Endocrinology","q":"Female infertility repeated implantation failure next management","a":"Antibiotics","b":"Clomiphene","c":"Hysteroscopy","d":"Metformin","ans":"C"},
{"t":"Endocrinology","q":"Male infertility after vasectomy reversal absent sperm. Cause","a":"Hypogonadism","b":"Anti-sperm antibodies","c":"Varicocele","d":"Pituitary failure","ans":"B"},
{"t":"Endocrinology","q":"Woman infertility with hyperandrogenism rapid onset virilization. Suspicion","a":"Hypothyroidism","b":"PCOS","c":"Hyperprolactinemia","d":"Androgen secreting tumor","ans":"D"},
{"t":"Endocrinology","q":"Female infertility low BMI low GnRH pulsatility. Treatment","a":"Surgery","b":"OCP","c":"Pulsatile GnRH therapy","d":"Estrogen","ans":"C"},
{"t":"Endocrinology","q":"Male infertility normal sperm count but DNA fragmentation high. Best option","a":"Testosterone","b":"ICSI","c":"Clomiphene","d":"Observation","ans":"B"},
{"t":"Endocrinology","q":"Woman infertility elevated FSH age 42 best management","a":"Metformin","b":"IVF with donor egg","c":"OCP","d":"Ovulation induction","ans":"B"},
{"t":"Endocrinology","q":"Female infertility irregular cycles and galactorrhea treatment","a":"Progesterone","b":"Surgery","c":"Dopamine agonist","d":"Estrogen","ans":"C"},
{"t":"Endocrinology","q":"Male infertility varicocele mechanism","a":"Obstruction","b":"Infection","c":"Hormonal suppression","d":"Increased scrotal temperature","ans":"D"},
{"t":"Endocrinology","q":"A woman infertility day-3 FSH normal but AMH low. Interpretation","a":"PCOS","b":"Reduced ovarian reserve","c":"Hypothyroidism","d":"Hyperprolactinemia","ans":"B"},
{"t":"Endocrinology","q":"Female infertility thick cervical mucus anti-sperm antibodies suspected treatment","a":"Metformin","b":"IUI","c":"Surgery","d":"Progesterone","ans":"B"},
{"t":"Endocrinology","q":"Male infertility cryptorchidism childhood history risk","a":"Epididymal cyst","b":"Prostate obstruction","c":"Pituitary failure","d":"Testicular failure","ans":"D"},
{"t":"Endocrinology","q":"Woman infertility normal workup age <35 trying 1 year management","a":"IVF","b":"Surgery","c":"Expectant management","d":"Steroids","ans":"C"},
{"t":"Endocrinology","q":"Female infertility due to anovulation hyperandrogenism obesity first drug","a":"Progesterone","b":"GnRH agonist","c":"Letrozole","d":"Estrogen","ans":"C"},
{"t":"Endocrinology","q":"Male infertility low testosterone high prolactin treatment","a":"Surgery","b":"Testosterone injection","c":"Dopamine agonist","d":"Steroids","ans":"C"},
{"t":"Endocrinology","q":"A 32-year-old woman presents with amenorrhea and galactorrhea. Serum prolactin markedly elevated. Next best investigation to confirm cause","a":"Thyroid scan","b":"MRI pituitary","c":"CT abdomen","d":"Pelvic ultrasound","ans":"B"},
{"t":"Endocrinology","q":"Most common functioning pituitary adenoma","a":"GH secreting","b":"ACTH secreting","c":"Prolactinoma","d":"TSH secreting","ans":"C"},
{"t":"Endocrinology","q":"First line treatment of prolactinoma","a":"Radiotherapy","b":"Surgery","c":"Steroids","d":"Cabergoline","ans":"D"},
{"t":"Endocrinology","q":"A patient with pituitary macroadenoma develops bitemporal hemianopia. Structure compressed","a":"Lateral geniculate body","b":"Optic chiasm","c":"Optic tract","d":"Optic nerve","ans":"B"},
{"t":"Endocrinology","q":"Drug of choice in acromegaly","a":"Methimazole","b":"Hydrocortisone","c":"Octreotide","d":"Bromocriptine","ans":"C"},
{"t":"Endocrinology","q":"Best screening test for acromegaly","a":"Random GH","b":"Prolactin","c":"IGF-1 level","d":"Insulin tolerance test","ans":"C"},
{"t":"Endocrinology","q":"Confirmatory test for acromegaly","a":"ACTH stimulation test","b":"Water deprivation test","c":"Dexamethasone suppression","d":"Oral glucose tolerance test for GH suppression","ans":"D"},
{"t":"Endocrinology","q":"A patient fails GH suppression after oral glucose. Diagnosis","a":"Diabetes insipidus","b":"Hypopituitarism","c":"SIADH","d":"Gigantism/acromegaly","ans":"D"},
{"t":"Endocrinology","q":"Insulin tolerance test assesses","a":"ADH function","b":"GH and ACTH reserve","c":"TSH only","d":"Prolactin only","ans":"B"},
{"t":"Endocrinology","q":"Contraindication to insulin tolerance test","a":"Anemia","b":"Epilepsy or ischemic heart disease","c":"Obesity","d":"Hypertension","ans":"B"},
{"t":"Endocrinology","q":"Water deprivation test differentiates","a":"Primary vs secondary hypogonadism","b":"Hyperthyroidism vs hypothyroidism","c":"Central vs nephrogenic diabetes insipidus","d":"SIADH vs Cushing","ans":"C"},
{"t":"Endocrinology","q":"After desmopressin urine osmolality rises markedly. Diagnosis","a":"Psychogenic polydipsia","b":"Central DI","c":"SIADH","d":"Nephrogenic DI","ans":"B"},
{"t":"Endocrinology","q":"SIADH laboratory finding","a":"High serum osmolality","b":"Hypernatremia","c":"Low serum osmolality","d":"Dilute urine","ans":"C"},
{"t":"Endocrinology","q":"First line management SIADH mild symptoms","a":"Hypertonic saline","b":"Desmopressin","c":"Fluid restriction","d":"Mannitol","ans":"C"},
{"t":"Endocrinology","q":"Severe symptomatic hyponatremia in SIADH treatment","a":"Diuretics only","b":"Potassium","c":"Hypertonic saline","d":"Dextrose","ans":"C"},
{"t":"Endocrinology","q":"Hypopituitarism most sensitive hormone lost first","a":"TSH","b":"Prolactin","c":"ACTH","d":"GH","ans":"D"},
{"t":"Endocrinology","q":"Hypopituitarism life threatening deficiency","a":"GH","b":"Gonadotropin","c":"ACTH deficiency","d":"Prolactin","ans":"C"},
{"t":"Endocrinology","q":"Replacement order in hypopituitarism treatment","a":"GH first","b":"Thyroxine before steroids","c":"Estrogen first","d":"Steroids before thyroxine","ans":"D"},
{"t":"Endocrinology","q":"A postpartum woman develops failure to lactate and hypotension after hemorrhage. Diagnosis","a":"SIADH","b":"Acromegaly","c":"Sheehan syndrome","d":"Prolactinoma","ans":"C"},
{"t":"Endocrinology","q":"Craniopharyngioma common presentation in children","a":"Hypertension","b":"Growth failure","c":"Diabetes mellitus","d":"Hyperthyroidism","ans":"B"},
{"t":"Endocrinology","q":"Pituitary apoplexy presents with","a":"Chronic fatigue","b":"Sudden severe headache and vision loss","c":"Fever only","d":"Gradual headache","ans":"B"},
{"t":"Endocrinology","q":"Immediate treatment pituitary apoplexy","a":"Methimazole","b":"Insulin","c":"High dose steroids","d":"Dopamine agonist","ans":"C"},
{"t":"Endocrinology","q":"Child height <3rd percentile evaluation first step","a":"CT brain","b":"MRI abdomen","c":"Bone age X-ray","d":"Thyroid scan","ans":"C"},
{"t":"Endocrinology","q":"Delayed bone age suggests","a":"Familial short stature","b":"Acromegaly","c":"Constitutional growth delay","d":"Gigantism","ans":"C"},
{"t":"Endocrinology","q":"Growth hormone deficiency lab","a":"High cortisol","b":"High prolactin","c":"High IGF-1","d":"Low IGF-1","ans":"D"},
{"t":"Endocrinology","q":"Treatment childhood GH deficiency","a":"Testosterone","b":"Recombinant GH","c":"Estrogen","d":"Hydrocortisone","ans":"B"},
{"t":"Endocrinology","q":"Tall child advanced bone age cause","a":"Turner syndrome","b":"Hypothyroidism","c":"Precocious puberty","d":"GH deficiency","ans":"C"},
{"t":"Endocrinology","q":"Tanner stage II in girls indicates","a":"Adult breast","b":"Pubic hair adult","c":"Breast budding","d":"Menarche","ans":"C"},
{"t":"Endocrinology","q":"First sign puberty boys","a":"Facial hair","b":"Growth spurt","c":"Voice change","d":"Testicular enlargement","ans":"D"},
{"t":"Endocrinology","q":"Precocious puberty defined in girls age less than","a":"9 years","b":"7 years","c":"10 years","d":"8 years","ans":"D"},
{"t":"Endocrinology","q":"Central precocious puberty treatment","a":"Progesterone","b":"GnRH agonist","c":"Steroids","d":"Estrogen","ans":"B"},
{"t":"Endocrinology","q":"Excess GH before epiphyseal closure causes","a":"Dwarfism","b":"Acromegaly","c":"Gigantism","d":"Osteoporosis","ans":"C"},
{"t":"Endocrinology","q":"Excess GH after epiphyseal closure causes","a":"Dwarfism","b":"Gigantism","c":"Acromegaly","d":"Hypopituitarism","ans":"C"},
{"t":"Endocrinology","q":"SIADH urine sodium level","a":"Variable","b":"Zero","c":"Low","d":"High","ans":"D"},
{"t":"Endocrinology","q":"Diabetes insipidus serum sodium","a":"Low","b":"Variable","c":"High","d":"Normal","ans":"C"},
{"t":"Endocrinology","q":"Drug causing SIADH commonly","a":"Metformin","b":"Lithium","c":"Carbamazepine","d":"Insulin","ans":"C"},
{"t":"Endocrinology","q":"Treatment nephrogenic DI","a":"Desmopressin","b":"Hypertonic saline","c":"Thiazide diuretic","d":"Dopamine agonist","ans":"C"},
{"t":"Endocrinology","q":"Pituitary stalk compression hormone affected first","a":"ACTH increased","b":"GH increased","c":"Prolactin increased","d":"TSH increased","ans":"C"},
{"t":"Endocrinology","q":"Adult GH deficiency symptom","a":"Hyperactivity","b":"Increased fat mass","c":"Weight loss","d":"Increased muscle mass","ans":"B"},
{"t":"Endocrinology","q":"Hypopituitarism skin finding","a":"Hyperpigmentation","b":"Cyanosis","c":"Pale skin","d":"Jaundice","ans":"C"},
{"t":"Endocrinology","q":"ACTH stimulation test used to diagnose","a":"SIADH","b":"Adrenal insufficiency","c":"Hyperthyroidism","d":"Acromegaly","ans":"B"},
{"t":"Endocrinology","q":"Secondary adrenal insufficiency ACTH level","a":"Normal high","b":"High","c":"Low","d":"Variable","ans":"C"},
{"t":"Endocrinology","q":"Pituitary dwarfism proportionate body","a":"Only limbs short","b":"Only trunk short","c":"Yes","d":"No","ans":"C"},
{"t":"Endocrinology","q":"Craniopharyngioma calcification best imaging","a":"MRI only","b":"CT scan","c":"Ultrasound","d":"X-ray chest","ans":"B"},
{"t":"Endocrinology","q":"ADH deficiency hallmark symptom","a":"Oliguria","b":"Hypertension","c":"Edema","d":"Polyuria","ans":"D"},
{"t":"Endocrinology","q":"SIADH volume status","a":"Hypervolemic","b":"Hypovolemic","c":"Shock","d":"Euvolemic","ans":"D"},
{"t":"Endocrinology","q":"Pituitary tumor causing Cushing disease hormone elevated","a":"Prolactin","b":"ACTH","c":"TSH","d":"GH","ans":"B"},
{"t":"Endocrinology","q":"Empty sella syndrome usually presents with","a":"Hyperthyroidism","b":"Acromegaly","c":"Hyperpituitarism","d":"Hypopituitarism","ans":"D"},
{"t":"Endocrinology","q":"Growth velocity assessment important for","a":"Asthma","b":"Obesity diagnosis","c":"Detecting endocrine growth disorder","d":"Diabetes","ans":"C"},
{"t":"Endocrinology","q":"Pubertal staging chart used","a":"Glasgow scale","b":"APGAR","c":"Bishop score","d":"Tanner staging","ans":"D"},
{"t":"Endocrinology","q":"A patient presents with fatigue, weight loss, hyperpigmentation and hypotension. Laboratory tests show low morning cortisol and elevated ACTH. What is the most likely diagnosis?","a":"Cushing syndrome","b":"Secondary adrenal insufficiency","c":"SIADH","d":"Addison disease","ans":"D"},
{"t":"Endocrinology","q":"A short Synacthen (ACTH stimulation) test shows no significant rise in serum cortisol after administration. What does this finding indicate?","a":"Hyperaldosteronism","b":"Normal adrenal function","c":"Primary adrenal insufficiency","d":"Pituitary adenoma","ans":"C"},
{"t":"Endocrinology","q":"In secondary adrenal insufficiency, what pattern is typically observed during the Synacthen test?","a":"Hyperkalemia only","b":"Suppressed ACTH only","c":"Markedly elevated cortisol","d":"Normal or delayed cortisol response","ans":"D"},
{"t":"Endocrinology","q":"What is the most common cause of primary adrenal insufficiency worldwide?","a":"Adrenal hemorrhage","b":"Autoimmune adrenalitis","c":"Tuberculosis","d":"Pituitary failure","ans":"C"},
{"t":"Endocrinology","q":"A patient with central obesity, purple striae and proximal muscle weakness has elevated 24-hour urinary cortisol. What is the next step to confirm Cushing syndrome?","a":"Synacthen test","b":"Overnight dexamethasone suppression test","c":"Serum aldosterone","d":"Plasma renin level","ans":"B"},
{"t":"Endocrinology","q":"Low-dose dexamethasone fails to suppress cortisol, and ACTH is elevated. What is the most likely cause?","a":"Exogenous steroid use","b":"Adrenal carcinoma","c":"Cushing disease (pituitary)","d":"Adrenal adenoma","ans":"C"},
{"t":"Endocrinology","q":"In ACTH-independent Cushing syndrome, laboratory findings typically show","a":"High renin","b":"High ACTH","c":"Low cortisol","d":"Low ACTH","ans":"D"},
{"t":"Endocrinology","q":"First-line treatment of Cushing disease due to pituitary adenoma","a":"Bilateral adrenalectomy","b":"Transsphenoidal surgery","c":"Ketoconazole","d":"Radiotherapy","ans":"B"},
{"t":"Endocrinology","q":"A patient presents with severe hypotension, vomiting, abdominal pain and hyponatremia. Immediate management of suspected adrenal crisis is","a":"Diuretics","b":"Oral steroids","c":"IV hydrocortisone and IV fluids","d":"Insulin infusion","ans":"C"},
{"t":"Endocrinology","q":"Which electrolyte abnormality is characteristic of primary adrenal insufficiency?","a":"Hypokalemia only","b":"Hypercalcemia only","c":"Hyponatremia and hyperkalemia","d":"Hypernatremia and hypokalemia","ans":"C"},
{"t":"Endocrinology","q":"A patient with episodic headache, sweating and palpitations has paroxysmal hypertension. Best initial diagnostic test","a":"Aldosterone level","b":"Urine sodium","c":"Plasma metanephrines","d":"Serum cortisol","ans":"C"},
{"t":"Endocrinology","q":"Imaging for localization of confirmed pheochromocytoma","a":"Thyroid ultrasound","b":"CT/MRI abdomen","c":"Echocardiography","d":"Chest X-ray","ans":"B"},
{"t":"Endocrinology","q":"Preoperative preparation for pheochromocytoma requires","a":"Only diuretics","b":"Calcium channel blocker only","c":"Alpha-blockade before beta-blockade","d":"Beta-blocker first","ans":"C"},
{"t":"Endocrinology","q":"Giving beta-blocker before alpha-blocker in pheochromocytoma causes","a":"No effect","b":"Bradycardia only","c":"Hypertensive crisis","d":"Hypotension","ans":"C"},
{"t":"Endocrinology","q":"Congenital adrenal hyperplasia most commonly caused by deficiency of","a":"17-hydroxylase","b":"3-beta HSD","c":"11-beta hydroxylase","d":"21-hydroxylase","ans":"D"},
{"t":"Endocrinology","q":"Female newborn with ambiguous genitalia, hyponatremia and hyperkalemia suggests","a":"Hypothyroidism","b":"Turner syndrome","c":"CAH salt-wasting form","d":"Klinefelter syndrome","ans":"C"},
{"t":"Endocrinology","q":"Treatment of classic congenital adrenal hyperplasia","a":"Dopamine agonist","b":"Hydrocortisone replacement","c":"Insulin","d":"Thyroxine","ans":"B"},
{"t":"Endocrinology","q":"A patient with hypercalcemia, kidney stones and bone pain most likely has","a":"Vitamin D deficiency","b":"Renal failure","c":"Primary hyperparathyroidism","d":"Hypoparathyroidism","ans":"C"},
{"t":"Endocrinology","q":"Laboratory pattern in primary hyperparathyroidism","a":"Low calcium high phosphate","b":"High calcium low PTH","c":"High calcium high PTH","d":"Low calcium low PTH","ans":"C"},
{"t":"Endocrinology","q":"Most common cause of primary hyperparathyroidism","a":"Renal failure","b":"Parathyroid adenoma","c":"Vitamin D excess","d":"Parathyroid carcinoma","ans":"B"},
{"t":"Endocrinology","q":"Acute symptomatic hypercalcemia initial treatment","a":"Oral calcium","b":"Steroids only","c":"Insulin","d":"IV normal saline","ans":"D"},
{"t":"Endocrinology","q":"Drug used after hydration in severe hypercalcemia","a":"Propranolol","b":"Metformin","c":"Calcitonin or bisphosphonate","d":"Thyroxine","ans":"C"},
{"t":"Endocrinology","q":"Hypocalcemia presenting with tetany immediate treatment","a":"Phosphate binders","b":"IV calcium gluconate","c":"Diuretics","d":"Oral vitamin D","ans":"B"},
{"t":"Endocrinology","q":"Chronic hypocalcemia cause with low PTH","a":"Vitamin D deficiency","b":"Malignancy","c":"Hypoparathyroidism","d":"Renal failure","ans":"C"},
{"t":"Endocrinology","q":"ECG finding in hypocalcemia","a":"Peaked T waves","b":"Short QT interval","c":"ST depression","d":"Prolonged QT interval","ans":"D"},
{"t":"Endocrinology","q":"A hospitalized patient develops sudden severe hypotension, confusion, vomiting, abdominal pain and hypoglycemia after stopping long-term steroid therapy. What is the most appropriate immediate management?","a":"Beta blockers","b":"IV hydrocortisone and isotonic saline","c":"IV insulin","d":"Oral prednisone later","ans":"B"},
{"t":"Endocrinology","q":"A patient suspected of pheochromocytoma has elevated plasma metanephrines. Blood pressure remains uncontrolled. What is the correct pharmacologic preparation before surgery?","a":"Start diuretics","b":"Start ACE inhibitor","c":"Start phenoxybenzamine followed by beta-blocker","d":"Start propranolol alone","ans":"C"},
{"t":"Endocrinology","q":"A young adult with resistant hypertension has hypokalemia and metabolic alkalosis. Plasma renin suppressed and aldosterone elevated. What is the most likely diagnosis?","a":"SIADH","b":"Addison disease","c":"Primary hyperaldosteronism","d":"Cushing disease","ans":"C"},
{"t":"Endocrinology","q":"A patient presents with features of Cushing syndrome but ACTH is low and CT shows adrenal mass. What is the diagnosis?","a":"Ectopic ACTH","b":"Adrenal adenoma producing cortisol","c":"Pituitary Cushing disease","d":"Steroid withdrawal","ans":"B"},
{"t":"Endocrinology","q":"A neonate presents with vomiting, dehydration, hyponatremia and hyperkalemia within first week of life. 17-hydroxyprogesterone elevated. What is the diagnosis?","a":"Hypothyroidism","b":"Sepsis","c":"Pyloric stenosis","d":"Congenital adrenal hyperplasia","ans":"D"},
{"t":"Endocrinology","q":"A patient with chronic kidney disease has low calcium, high phosphate and high PTH. What is the condition called?","a":"Vitamin D intoxication","b":"Secondary hyperparathyroidism","c":"Hypoparathyroidism","d":"Primary hyperparathyroidism","ans":"B"},
{"t":"Endocrinology","q":"A patient presents with confusion, constipation, polyuria and ECG shows short QT interval. Serum calcium is 14.5 mg/dL. What is the immediate next step?","a":"Oral calcium","b":"Desmopressin","c":"IV fluids hydration","d":"Fluid restriction","ans":"C"},
{"t":"Endocrinology","q":"A patient after thyroid surgery develops perioral numbness and carpopedal spasm. What is the most appropriate treatment?","a":"Oral potassium","b":"Steroids","c":"IV magnesium","d":"IV calcium gluconate","ans":"D"},
{"t":"Endocrinology","q":"A patient with chronic steroid therapy suddenly stops medication and presents with shock and hypoglycemia. Which hormone deficiency is primarily responsible for death if untreated?","a":"Growth hormone","b":"Cortisol","c":"Aldosterone only","d":"Thyroxine","ans":"B"},
{"t":"Endocrinology","q":"A patient with suspected ectopic ACTH secretion has severe hypokalemia, metabolic alkalosis and hyperpigmentation. Which investigation best differentiates pituitary vs ectopic ACTH source?","a":"Random cortisol","b":"Low dose dexamethasone","c":"High dose dexamethasone suppression test","d":"Synacthen test","ans":"C"},
{"t":"Endocrinology","q":"A patient with hypercalcemia due to malignancy has suppressed PTH levels. What is the mechanism of hypercalcemia?","a":"Renal calcium loss","b":"Increased calcitonin","c":"PTHrP mediated bone resorption","d":"Vitamin D deficiency","ans":"C"},
{"t":"Endocrinology","q":"A patient presents with episodic hypertension, palpitations and diaphoresis. During surgery tumor manipulation causes severe hypertensive crisis. Which drug should be immediately administered?","a":"Atropine","b":"Dopamine","c":"Nitroprusside","d":"Phenylephrine","ans":"C"},
{"t":"Endocrinology","q":"A patient with chronic hypocalcemia develops cataracts and basal ganglia calcifications. Most likely underlying disorder?","a":"Hyperthyroidism","b":"Hypoparathyroidism","c":"Vitamin D excess","d":"Hyperparathyroidism","ans":"B"},
{"t":"Endocrinology","q":"A patient with long-standing Cushing syndrome develops proximal muscle weakness, osteoporosis and diabetes. What is the primary pathophysiology responsible for these features?","a":"Thyroid hormone excess","b":"Excess aldosterone","c":"Growth hormone deficiency","d":"Chronic glucocorticoid excess causing protein catabolism","ans":"D"},
{"t":"Endocrinology","q":"A patient with severe hypercalcemia remains symptomatic despite hydration and calcitonin. Which is the most definitive pharmacologic therapy to reduce calcium levels long term?","a":"Loop diuretics alone","b":"Bisphosphonate therapy","c":"Vitamin D supplementation","d":"Thiazide diuretics","ans":"B"},
{"t":"Endocrinology","q":"A patient with known Addison disease presents with fever, vomiting and hypotension after a severe infection and cannot retain oral medication. What is the most appropriate immediate treatment?","a":"IV hydrocortisone with isotonic saline","b":"Insulin infusion","c":"Fluid restriction","d":"Oral hydrocortisone tablets","ans":"A"},
{"t":"Endocrinology","q":"A patient undergoing evaluation for Cushing syndrome has elevated 24-hour urinary cortisol and non-suppressed cortisol after low-dose dexamethasone. Plasma ACTH is undetectable. What is the most likely source?","a":"Pituitary adenoma","b":"Exogenous steroid intake","c":"Adrenal cortisol-secreting tumor","d":"Ectopic ACTH tumor","ans":"C"},
{"t":"Endocrinology","q":"During workup of resistant hypertension, plasma metanephrines are elevated. Imaging shows adrenal mass. Before surgery the patient must receive which preparation to prevent intraoperative complications?","a":"ACE inhibitor therapy only","b":"Diuretics only","c":"Immediate beta-blocker alone","d":"Alpha-blocker followed by beta-blocker","ans":"D"},
{"t":"Endocrinology","q":"A neonate with congenital adrenal hyperplasia develops severe dehydration, hyponatremia and hyperkalemia. Which hormone deficiency primarily causes the salt-wasting crisis?","a":"Cortisol deficiency only","b":"Thyroxine deficiency","c":"Growth hormone deficiency","d":"Aldosterone deficiency","ans":"D"},
{"t":"Endocrinology","q":"A patient presents with hypercalcemia, suppressed PTH and elevated vitamin D level due to granulomatous disease. What is the preferred pharmacologic treatment?","a":"Desmopressin","b":"Calcium supplements","c":"Steroids","d":"Thiazide diuretics","ans":"C"},
{"t":"Endocrinology","q":"A patient with hypocalcemia has positive Chvostek and Trousseau signs after total thyroidectomy. Which long-term therapy is required after acute stabilization?","a":"Loop diuretics","b":"Calcitonin","c":"Bisphosphonate therapy","d":"Oral calcium and vitamin D supplementation","ans":"D"},
{"t":"Endocrinology","q":"A patient suspected of ectopic ACTH syndrome has markedly elevated ACTH and cortisol that do not suppress with high-dose dexamethasone. What is the next best step to localize the source?","a":"Inferior petrosal sinus sampling","b":"Bone scan","c":"Thyroid ultrasound","d":"Pituitary MRI only","ans":"A"},
{"t":"Endocrinology","q":"A patient with chronic kidney disease develops secondary hyperparathyroidism. Which biochemical pattern is expected?","a":"High calcium high PTH","b":"High calcium low phosphate","c":"Low calcium high phosphate high PTH","d":"Low calcium low PTH","ans":"C"},
{"t":"Endocrinology","q":"A patient with severe hypercalcemia develops altered mental status and renal impairment. After aggressive hydration, which additional therapy rapidly lowers serum calcium?","a":"Spironolactone","b":"Thyroxine","c":"Vitamin D","d":"Calcitonin","ans":"D"},
{"t":"Endocrinology","q":"A patient with primary hyperparathyroidism is asymptomatic but has calcium persistently >1 mg/dL above normal and reduced bone density. What is the definitive management?","a":"Parathyroidectomy","b":"Oral phosphate therapy","c":"Observation only","d":"Steroid therapy","ans":"A"}
];