window.MM=window.MM||{};
window.MM.micro=[
{"t":"Bacteriology","q":"The MOST accurate definition of pathogenicity is:","a":"Ability to survive in environment","b":"Ability to cause disease in host","c":"Ability to produce spores","d":"Ability to resist antibiotics","ans":"B"},
{"t":"Bacteriology","q":"Virulence refers to:","a":"Presence of capsule","b":"Degree of pathogenicity","c":"Ability to colonize only","d":"Resistance to phagocytosis","ans":"B"},
{"t":"Bacteriology","q":"Which factor is MOST important for bacterial adherence to host cells?","a":"Endotoxin","b":"Flagella","c":"Pili/fimbriae","d":"Exotoxin","ans":"C"},
{"t":"Bacteriology","q":"Colonization differs from infection because colonization:","a":"Always causes disease","b":"Invades bloodstream","c":"Does not cause tissue damage","d":"Triggers immune response","ans":"C"},
{"t":"Bacteriology","q":"Normal flora contributes to host defense by:","a":"Producing exotoxins","b":"Competing for nutrients","c":"Increasing pH","d":"Destroying antibodies","ans":"B"},
{"t":"Bacteriology","q":"Which organism is part of normal skin flora?","a":"Neisseria meningitidis","b":"Streptococcus pyogenes","c":"Staphylococcus epidermidis","d":"Salmonella typhi","ans":"C"},
{"t":"Bacteriology","q":"Capsule is an important virulence factor because it:","a":"Enhances motility","b":"Inhibits phagocytosis","c":"Produces toxins","d":"Aids sporulation","ans":"B"},
{"t":"Bacteriology","q":"Which bacterium is classically encapsulated?","a":"Escherichia coli","b":"Mycobacterium tuberculosis","c":"Streptococcus pneumoniae","d":"Corynebacterium diphtheriae","ans":"C"},
{"t":"Bacteriology","q":"Antigenic variation allows bacteria to:","a":"Increase toxin production","b":"Evade host immune response","c":"Resist antibiotics","d":"Enhance sporulation","ans":"B"},
{"t":"Bacteriology","q":"Antigenic variation is BEST exemplified by:","a":"Staphylococcus aureus","b":"Neisseria gonorrhoeae","c":"Clostridium tetani","d":"Bacillus anthracis","ans":"B"},
{"t":"Bacteriology","q":"Phase variation refers to:","a":"Change in bacterial size","b":"Reversible on-off expression of surface antigens","c":"Permanent genetic mutation","d":"Change in metabolic phase","ans":"B"},
{"t":"Bacteriology","q":"Endotoxin is a component of:","a":"Gram-positive cell wall","b":"Gram-negative outer membrane","c":"Capsule","d":"Ribosome","ans":"B"},
{"t":"Bacteriology","q":"Endotoxin is chemically composed of:","a":"Protein","b":"Polysaccharide","c":"Lipopolysaccharide","d":"Peptidoglycan","ans":"C"},
{"t":"Bacteriology","q":"The toxic component of endotoxin is:","a":"O antigen","b":"Core polysaccharide","c":"Lipid A","d":"Capsule","ans":"C"},
{"t":"Bacteriology","q":"Endotoxins characteristically cause:","a":"Specific neutralizing antibodies","b":"Fever and shock","c":"Enzymatic tissue destruction","d":"Local necrosis only","ans":"B"},
{"t":"Bacteriology","q":"Exotoxins are typically:","a":"Heat stable","b":"Weakly antigenic","c":"Protein in nature","d":"Released only on cell lysis","ans":"C"},
{"t":"Bacteriology","q":"Which toxin inhibits protein synthesis by inactivating EF-2?","a":"Tetanus toxin","b":"Botulinum toxin","c":"Diphtheria toxin","d":"Cholera toxin","ans":"C"},
{"t":"Bacteriology","q":"Superantigens act by:","a":"Activating complement","b":"Cross-linking MHC II and T-cell receptor","c":"Inhibiting phagocytosis","d":"Blocking antibodies","ans":"B"},
{"t":"Bacteriology","q":"Toxic shock syndrome toxin is produced by:","a":"Streptococcus pneumoniae","b":"Staphylococcus aureus","c":"Clostridium perfringens","d":"Escherichia coli","ans":"B"},
{"t":"Bacteriology","q":"Which toxin increases cAMP in intestinal epithelial cells causing watery diarrhea?","a":"Shiga toxin","b":"Cholera toxin","c":"Tetanus toxin","d":"Diphtheria toxin","ans":"B"},
{"t":"Bacteriology","q":"Shiga toxin inhibits:","a":"DNA synthesis","b":"RNA synthesis","c":"Protein synthesis","d":"Cell wall synthesis","ans":"C"},
{"t":"Bacteriology","q":"Which organism produces both exotoxin and endotoxin?","a":"Staphylococcus aureus","b":"Corynebacterium diphtheriae","c":"Escherichia coli","d":"Clostridium tetani","ans":"C"},
{"t":"Bacteriology","q":"Gram stain differentiates bacteria based on:","a":"Capsule thickness","b":"Cell wall lipid content","c":"Peptidoglycan thickness","d":"Ribosomal structure","ans":"C"},
{"t":"Bacteriology","q":"Gram-positive bacteria appear purple because they:","a":"Lose crystal violet","b":"Retain crystal violet–iodine complex","c":"Take up safranin only","d":"Lack peptidoglycan","ans":"B"},
{"t":"Bacteriology","q":"Acid-fast staining is used to detect:","a":"Spirochetes","b":"Mycoplasma","c":"Mycobacterium","d":"Chlamydia","ans":"C"},
{"t":"Bacteriology","q":"Ziehl–Neelsen stain identifies bacteria with:","a":"Capsule","b":"Spores","c":"Mycolic acid","d":"Flagella","ans":"C"},
{"t":"Bacteriology","q":"Albert stain is used for identification of:","a":"Mycobacterium tuberculosis","b":"Corynebacterium diphtheriae","c":"Bacillus anthracis","d":"Neisseria meningitidis","ans":"B"},
{"t":"Bacteriology","q":"Metachromatic granules are composed of:","a":"Calcium phosphate","b":"Polyphosphate","c":"Lipid","d":"Glycogen","ans":"B"},
{"t":"Bacteriology","q":"Blood agar is an example of:","a":"Selective medium","b":"Enriched medium","c":"Transport medium","d":"Indicator medium","ans":"B"},
{"t":"Bacteriology","q":"Chocolate agar is enriched with:","a":"Serum","b":"Blood heated to lyse RBCs","c":"Egg yolk","d":"Tellurite","ans":"B"},
{"t":"Bacteriology","q":"MacConkey agar is used to differentiate bacteria based on:","a":"Hemolysis","b":"Lactose fermentation","c":"Motility","d":"Capsule","ans":"B"},
{"t":"Bacteriology","q":"Lactose fermenters appear ___ on MacConkey agar:","a":"Colorless","b":"Blue","c":"Pink","d":"Green","ans":"C"},
{"t":"Bacteriology","q":"Which organism is a non-lactose fermenter?","a":"E. coli","b":"Klebsiella","c":"Salmonella","d":"Enterobacter","ans":"C"},
{"t":"Bacteriology","q":"Lowenstein–Jensen medium is used for:","a":"Corynebacterium","b":"Mycobacterium tuberculosis","c":"Neisseria","d":"Vibrio","ans":"B"},
{"t":"Bacteriology","q":"Tellurite agar is selective for:","a":"Staphylococcus","b":"Corynebacterium diphtheriae","c":"Neisseria","d":"Mycobacterium","ans":"B"},
{"t":"Bacteriology","q":"Anaerobic bacteria are BEST cultured using:","a":"Blood agar","b":"Candle jar","c":"Robertson cooked meat medium","d":"Lowenstein–Jensen medium","ans":"C"},
{"t":"Bacteriology","q":"Bacterial spores are resistant to:","a":"Dry heat","b":"Radiation","c":"Desiccation","d":"All of the above","ans":"D"},
{"t":"Bacteriology","q":"Which bacterium forms spores?","a":"Escherichia coli","b":"Staphylococcus aureus","c":"Clostridium tetani","d":"Neisseria meningitidis","ans":"C"},
{"t":"Bacteriology","q":"Spores are primarily a mechanism for:","a":"Reproduction","b":"Genetic variation","c":"Survival","d":"Virulence","ans":"C"},
{"t":"Bacteriology","q":"Bacterial genetic material is located in:","a":"Nucleus","b":"Mitochondria","c":"Nucleoid","d":"Ribosome","ans":"C"},
{"t":"Bacteriology","q":"Plasmids commonly carry genes for:","a":"Ribosomal proteins","b":"Housekeeping enzymes","c":"Antibiotic resistance","d":"Cell wall synthesis only","ans":"C"},
{"t":"Bacteriology","q":"Conjugation requires:","a":"Bacteriophage","b":"Pilus","c":"Transformation","d":"Transposon","ans":"B"},
{"t":"Bacteriology","q":"Transformation involves:","a":"Uptake of naked DNA","b":"Virus-mediated DNA transfer","c":"Cell-to-cell contact","d":"RNA transfer","ans":"A"},
{"t":"Bacteriology","q":"Transduction is mediated by:","a":"Plasmid","b":"Transposon","c":"Bacteriophage","d":"Pilus","ans":"C"},
{"t":"Bacteriology","q":"R plasmids encode:","a":"Capsule","b":"Flagella","c":"Antibiotic resistance","d":"Toxins only","ans":"C"},
{"t":"Bacteriology","q":"Beta-lactam antibiotics act by inhibiting:","a":"Protein synthesis","b":"DNA replication","c":"Cell wall synthesis","d":"RNA transcription","ans":"C"},
{"t":"Bacteriology","q":"Beta-lactamase mediates resistance by:","a":"Altering ribosomes","b":"Destroying antibiotic","c":"Reducing permeability","d":"Increasing efflux","ans":"B"},
{"t":"Bacteriology","q":"MRSA resistance is due to:","a":"Efflux pumps","b":"Altered penicillin-binding protein","c":"Reduced porins","d":"Enzymatic degradation","ans":"B"},
{"t":"Bacteriology","q":"Vancomycin resistance occurs due to:","a":"Beta-lactamase production","b":"Altered D-Ala-D-Ala target","c":"Efflux pump","d":"Ribosomal mutation","ans":"B"},
{"t":"Bacteriology","q":"Efflux pump–mediated resistance results in:","a":"Antibiotic degradation","b":"Decreased intracellular drug concentration","c":"Altered target enzyme","d":"Increased drug uptake","ans":"B"},
{"t":"Bacteriology","q":"Biofilm formation contributes to antibiotic resistance by:","a":"Increasing mutation rate","b":"Enhancing drug penetration","c":"Reducing antibiotic access","d":"Destroying immune cells","ans":"C"},
{"t":"Bacteriology","q":"Which organism is classically associated with biofilm on prosthetic devices?","a":"Streptococcus pyogenes","b":"Staphylococcus epidermidis","c":"Clostridium difficile","d":"Neisseria gonorrhoeae","ans":"B"},
{"t":"Bacteriology","q":"Sterilization is defined as:","a":"Removal of spores only","b":"Killing of pathogenic organisms","c":"Elimination of all forms of life","d":"Reduction of microbial load","ans":"C"},
{"t":"Bacteriology","q":"Disinfection differs from sterilization because disinfection:","a":"Kills spores","b":"Eliminates all microbes","c":"Kills vegetative forms only","d":"Is ineffective against bacteria","ans":"C"},
{"t":"Bacteriology","q":"Autoclaving uses:","a":"Dry heat","b":"Moist heat under pressure","c":"Radiation","d":"Filtration","ans":"B"},
{"t":"Bacteriology","q":"Standard autoclaving conditions are:","a":"100°C for 10 minutes","b":"121°C for 15 minutes","c":"160°C for 2 hours","d":"180°C for 30 minutes","ans":"B"},
{"t":"Bacteriology","q":"Dry heat sterilization is achieved by:","a":"Autoclave","b":"Hot air oven","c":"Pasteurization","d":"UV light","ans":"B"},
{"t":"Bacteriology","q":"Pasteurization is primarily used to:","a":"Sterilize surgical instruments","b":"Kill spores","c":"Reduce pathogenic bacteria in milk","d":"Destroy viruses only","ans":"C"},
{"t":"Bacteriology","q":"Filtration is BEST used for sterilization of:","a":"Culture media","b":"Heat-sensitive fluids","c":"Surgical instruments","d":"Glassware","ans":"B"},
{"t":"Bacteriology","q":"HEPA filters are effective against:","a":"Toxins only","b":"Viruses only","c":"Bacteria and spores","d":"Prions","ans":"C"},
{"t":"Bacteriology","q":"UV radiation kills bacteria by:","a":"Protein denaturation","b":"Cell wall lysis","c":"DNA damage","d":"RNA inhibition","ans":"C"},
{"t":"Bacteriology","q":"Prions are resistant to:","a":"Autoclaving","b":"UV radiation","c":"Formaldehyde","d":"Standard sterilization methods","ans":"D"},
{"t":"Bacteriology","q":"Which chemical disinfectant is used for skin antisepsis?","a":"Phenol","b":"Glutaraldehyde","c":"Alcohol","d":"Ethylene oxide","ans":"C"},
{"t":"Bacteriology","q":"Ethylene oxide is used for sterilization of:","a":"Glassware","b":"Heat-sensitive instruments","c":"Culture media","d":"Linen","ans":"B"},
{"t":"Bacteriology","q":"Phenol acts by:","a":"DNA damage","b":"Protein denaturation","c":"Cell wall synthesis inhibition","d":"Ribosomal inhibition","ans":"B"},
{"t":"Bacteriology","q":"Which disinfectant is effective against Mycobacterium tuberculosis?","a":"Alcohol","b":"Phenol","c":"Both A and B","d":"Neither","ans":"C"},
{"t":"Bacteriology","q":"Quaternary ammonium compounds are ineffective against:","a":"Gram-positive bacteria","b":"Gram-negative bacteria","c":"Mycobacteria","d":"Enveloped viruses","ans":"C"},
{"t":"Bacteriology","q":"The MOST resistant bacterial form is:","a":"Vegetative cell","b":"Capsule","c":"Spore","d":"Biofilm cell","ans":"C"},
{"t":"Bacteriology","q":"The D-value refers to:","a":"Temperature of sterilization","b":"Time to kill 90% of organisms","c":"Time to sterilize completely","d":"Drug concentration","ans":"B"},
{"t":"Bacteriology","q":"Z-value refers to:","a":"Time required for sterilization","b":"Temperature change needed to change D-value by tenfold","c":"Pressure used in autoclave","d":"Degree of contamination","ans":"B"},
{"t":"Bacteriology","q":"Chemical indicators in autoclave test:","a":"Sterility","b":"Temperature exposure","c":"Spore killing","d":"pH","ans":"B"},
{"t":"Bacteriology","q":"Biological indicators for autoclave contain spores of:","a":"Clostridium tetani","b":"Bacillus anthracis","c":"Geobacillus stearothermophilus","d":"Bacillus subtilis","ans":"C"},
{"t":"Bacteriology","q":"Biological indicator for dry heat sterilization uses spores of:","a":"Clostridium difficile","b":"Bacillus subtilis","c":"Geobacillus stearothermophilus","d":"E. coli","ans":"B"},
{"t":"Bacteriology","q":"Which factor does NOT affect disinfectant activity?","a":"Organic matter","b":"Temperature","c":"pH","d":"Color of disinfectant","ans":"D"},
{"t":"Bacteriology","q":"The MOST effective method to prevent hospital-acquired infections is:","a":"Antibiotic prophylaxis","b":"Sterilization","c":"Hand hygiene","d":"Vaccination","ans":"C"},
{"t":"Bacteriology","q":"Alcohol is ineffective against:","a":"Gram-positive bacteria","b":"Gram-negative bacteria","c":"Mycobacteria","d":"Bacterial spores","ans":"D"},
{"t":"Bacteriology","q":"Halogens like iodine act by:","a":"DNA damage","b":"Protein denaturation","c":"Cell wall synthesis inhibition","d":"Ribosomal inhibition","ans":"B"},
{"t":"Bacteriology","q":"Iodophors are preferred over iodine because they:","a":"Are less effective","b":"Are more toxic","c":"Have sustained release and less irritation","d":"Kill spores","ans":"C"},
{"t":"Bacteriology","q":"Chlorine is MOST effective against:","a":"Spores only","b":"Viruses and bacteria","c":"Mycobacteria only","d":"Prions","ans":"B"},
{"t":"Bacteriology","q":"Bleaching powder acts by releasing:","a":"Oxygen","b":"Chlorine","c":"Ozone","d":"Hydrogen peroxide","ans":"B"},
{"t":"Bacteriology","q":"Hydrogen peroxide kills bacteria by:","a":"Free radical formation","b":"Protein synthesis inhibition","c":"Cell wall damage","d":"DNA replication inhibition","ans":"A"},
{"t":"Bacteriology","q":"Which organism lacks a cell wall and is resistant to beta-lactams?","a":"Chlamydia","b":"Mycoplasma","c":"Rickettsia","d":"Spirochete","ans":"B"},
{"t":"Bacteriology","q":"L-forms are bacteria that:","a":"Are spores","b":"Lack cell wall","c":"Are acid-fast","d":"Are encapsulated","ans":"B"},
{"t":"Bacteriology","q":"Which bacteria is obligate intracellular?","a":"Mycoplasma","b":"Chlamydia","c":"E. coli","d":"Klebsiella","ans":"B"},
{"t":"Bacteriology","q":"Chlamydia lacks:","a":"DNA","b":"RNA","c":"Ribosomes","d":"Peptidoglycan","ans":"D"},
{"t":"Bacteriology","q":"Rickettsia is transmitted by:","a":"Food","b":"Water","c":"Arthropod vectors","d":"Aerosols","ans":"C"},
{"t":"Bacteriology","q":"Which stain is used for spirochetes?","a":"Gram stain","b":"Ziehl–Neelsen","c":"Dark field microscopy","d":"Albert stain","ans":"C"},
{"t":"Bacteriology","q":"Treponema pallidum is detected by:","a":"Gram stain","b":"Culture","c":"Dark field microscopy","d":"MacConkey agar","ans":"C"},
{"t":"Bacteriology","q":"Which test is non-treponemal?","a":"FTA-ABS","b":"TPHA","c":"VDRL","d":"ELISA","ans":"C"},
{"t":"Bacteriology","q":"The window period in syphilis serology refers to:","a":"Late stage disease","b":"Period before antibody formation","c":"Time of treatment","d":"Relapse phase","ans":"B"},
{"t":"Bacteriology","q":"Sterilization by radiation is MOST useful for:","a":"Culture media","b":"Disposable medical supplies","c":"Surgical instruments","d":"Linen","ans":"B"},
{"t":"Bacteriology","q":"Ionizing radiation kills microorganisms by:","a":"Protein denaturation","b":"Free radical–mediated DNA damage","c":"Cell wall disruption","d":"Ribosome inhibition","ans":"B"},
{"t":"Bacteriology","q":"Non-ionizing radiation includes:","a":"Gamma rays","b":"X-rays","c":"UV rays","d":"Electron beams","ans":"C"},
{"t":"Bacteriology","q":"Which bacteria shows swarming motility?","a":"Salmonella","b":"Proteus","c":"Shigella","d":"Klebsiella","ans":"B"},
{"t":"Bacteriology","q":"Motility of bacteria is due to:","a":"Capsule","b":"Pili","c":"Flagella","d":"Spores","ans":"C"},
{"t":"Bacteriology","q":"Hanging drop method is used to demonstrate:","a":"Capsule","b":"Motility","c":"Spores","d":"Acid-fastness","ans":"B"},
{"t":"Bacteriology","q":"Capsule staining is a type of:","a":"Simple stain","b":"Differential stain","c":"Negative stain","d":"Special stain","ans":"C"},
{"t":"Bacteriology","q":"India ink preparation is used to demonstrate:","a":"Spores","b":"Flagella","c":"Capsule","d":"Acid-fast bacilli","ans":"C"},
{"t":"Bacteriology","q":"Which organism has a prominent capsule?","a":"Neisseria gonorrhoeae","b":"Streptococcus pneumoniae","c":"Corynebacterium diphtheriae","d":"Clostridium tetani","ans":"B"},
{"t":"Bacteriology","q":"The Quellung reaction is used to detect:","a":"Spores","b":"Capsule swelling","c":"Acid-fastness","d":"Motility","ans":"B"},
{"t":"Bacteriology","q":"Pathogenicity islands are:","a":"Plasmids","b":"Chromosomal regions with virulence genes","c":"Ribosomal DNA","d":"Transposons only","ans":"B"},
{"t":"Bacteriology","q":"Which factor allows bacteria to survive inside macrophages?","a":"Capsule","b":"Catalase","c":"IgA protease","d":"Endotoxin","ans":"B"},
{"t":"Bacteriology","q":"IgA protease helps bacteria by:","a":"Destroying IgG","b":"Destroying IgM","c":"Destroying secretory IgA","d":"Activating complement","ans":"C"},
{"t":"Bacteriology","q":"Which organism produces IgA protease?","a":"Staphylococcus aureus","b":"Neisseria gonorrhoeae","c":"Clostridium tetani","d":"Bacillus anthracis","ans":"B"},
{"t":"Bacteriology","q":"Bacterial quorum sensing is related to:","a":"Antibiotic resistance only","b":"Population density–dependent gene expression","c":"Spore formation","d":"Antigenic variation","ans":"B"},
{"t":"Bacteriology","q":"Quorum sensing is IMPORTANT for:","a":"Sporulation","b":"Biofilm formation","c":"Capsule synthesis only","d":"Motility","ans":"B"},
{"t":"Bacteriology","q":"Which organism uses quorum sensing extensively?","a":"Mycobacterium tuberculosis","b":"Pseudomonas aeruginosa","c":"Clostridium tetani","d":"Treponema pallidum","ans":"B"},
{"t":"Bacteriology","q":"Heat-resistant spores are destroyed by:","a":"Boiling","b":"Pasteurization","c":"Autoclaving","d":"Alcohol","ans":"C"},
{"t":"Bacteriology","q":"Sterilization of inoculating loop is done by:","a":"Autoclaving","b":"Hot air oven","c":"Flaming","d":"UV light","ans":"C"},
{"t":"Bacteriology","q":"Which organism is killed by low temperature pasteurization?","a":"Bacillus spores","b":"Coxiella burnetii","c":"Mycobacterium tuberculosis","d":"Clostridium tetani","ans":"B"},
{"t":"Bacteriology","q":"Thermal death time is defined as:","a":"Temperature needed to kill organisms","b":"Time needed to kill all organisms at a given temperature","c":"Time to kill spores only","d":"Time to kill 90% organisms","ans":"B"},
{"t":"Bacteriology","q":"Antiseptics are applied to:","a":"Instruments","b":"Inanimate objects","c":"Living tissues","d":"Culture media","ans":"C"},
{"t":"Bacteriology","q":"Disinfectants are applied to:","a":"Skin","b":"Living tissue","c":"Inanimate objects","d":"Blood","ans":"C"},
{"t":"Bacteriology","q":"Which method does NOT kill spores?","a":"Autoclaving","b":"Dry heat","c":"Alcohol","d":"Radiation","ans":"C"},
{"t":"Bacteriology","q":"Which bacterium shows pleomorphism?","a":"E. coli","b":"Corynebacterium diphtheriae","c":"Salmonella typhi","d":"Vibrio cholerae","ans":"B"},
{"t":"Bacteriology","q":"Pleomorphism refers to:","a":"Variable staining","b":"Variable shape and size","c":"Capsule formation","d":"Spore formation","ans":"B"},
{"t":"Bacteriology","q":"Which organism is comma-shaped?","a":"E. coli","b":"Vibrio cholerae","c":"Campylobacter","d":"Helicobacter","ans":"B"},
{"t":"Bacteriology","q":"Which bacteria is spiral-shaped?","a":"Shigella","b":"Campylobacter jejuni","c":"Klebsiella","d":"Proteus","ans":"B"},
{"t":"Bacteriology","q":"Endospore staining is BEST done by:","a":"Ziehl–Neelsen","b":"Albert stain","c":"Schaeffer–Fulton method","d":"Gram stain","ans":"C"},
{"t":"Bacteriology","q":"Which structure is responsible for bacterial motility?","a":"Pili","b":"Capsule","c":"Flagella","d":"Ribosome","ans":"C"},
{"t":"Bacteriology","q":"Monotrichous flagella means:","a":"Flagella all over surface","b":"One flagellum at one end","c":"One flagellum at both ends","d":"Tuft of flagella at one end","ans":"B"},
{"t":"Bacteriology","q":"Peritrichous flagella are seen in:","a":"Vibrio","b":"Pseudomonas","c":"Proteus","d":"Campylobacter","ans":"C"},
{"t":"Bacteriology","q":"Which structure mediates twitching motility?","a":"Flagella","b":"Pili","c":"Capsule","d":"Spores","ans":"B"},
{"t":"Bacteriology","q":"LPS is present in:","a":"Gram-positive bacteria","b":"Gram-negative bacteria","c":"Acid-fast bacteria","d":"Mycoplasma","ans":"B"},
{"t":"Bacteriology","q":"Teichoic acids are present in:","a":"Gram-negative bacteria","b":"Gram-positive bacteria","c":"Mycobacteria","d":"Spirochetes","ans":"B"},
{"t":"Bacteriology","q":"Teichoic acid function includes:","a":"Antibiotic resistance","b":"Antigenic specificity","c":"Motility","d":"Sporulation","ans":"B"},
{"t":"Bacteriology","q":"Which bacteria lacks both cell wall and LPS?","a":"Chlamydia","b":"Mycoplasma","c":"Rickettsia","d":"Mycobacterium","ans":"B"},
{"t":"Bacteriology","q":"Sterilization of syringes is BEST achieved by:","a":"Boiling","b":"Autoclaving","c":"Alcohol","d":"UV light","ans":"B"},
{"t":"Bacteriology","q":"A disinfectant that is inactivated by organic matter is:","a":"Phenol","b":"Chlorine","c":"Alcohol","d":"Iodine","ans":"B"},
{"t":"Bacteriology","q":"Which organism is killed by pasteurization but not spores?","a":"Bacillus anthracis spores","b":"Clostridium tetani spores","c":"Mycobacterium tuberculosis","d":"Clostridium botulinum spores","ans":"C"},
{"t":"Bacteriology","q":"Antibiotic resistance due to ribosomal alteration is seen with resistance to:","a":"Penicillin","b":"Tetracycline","c":"Macrolides","d":"Vancomycin","ans":"C"},
{"t":"Bacteriology","q":"Tetracycline resistance commonly occurs due to:","a":"Enzymatic degradation","b":"Efflux pumps","c":"Target destruction","d":"Beta-lactamase","ans":"B"},
{"t":"Bacteriology","q":"Horizontal gene transfer does NOT include:","a":"Conjugation","b":"Transduction","c":"Transformation","d":"Mutation","ans":"D"},
{"t":"Bacteriology","q":"Which factor contributes MOST to hospital antibiotic resistance?","a":"Community spread","b":"Overuse of antibiotics","c":"Poor sanitation","d":"Lack of vaccines","ans":"B"},
{"t":"Bacteriology","q":"Sterilization by gas is useful for:","a":"Glassware","b":"Culture media","c":"Plastic equipment","d":"Linen","ans":"C"},
{"t":"Bacteriology","q":"Which bacterium survives inside macrophages by inhibiting phagolysosome fusion?","a":"Streptococcus pyogenes","b":"Mycobacterium tuberculosis","c":"E. coli","d":"Neisseria meningitidis","ans":"B"},
{"t":"Bacteriology","q":"Which virulence factor allows attachment to uroepithelium?","a":"Capsule","b":"Type 1 fimbriae","c":"Endotoxin","d":"Exotoxin","ans":"B"},
{"t":"Bacteriology","q":"Which organism produces heat-labile toxin?","a":"ETEC","b":"Shigella","c":"Salmonella","d":"Vibrio parahaemolyticus","ans":"A"},
{"t":"Bacteriology","q":"Heat-stable toxin acts by increasing:","a":"cAMP","b":"cGMP","c":"Calcium","d":"Sodium channels","ans":"B"},
{"t":"Bacteriology","q":"Which sterilization method is MOST suitable for serum?","a":"Autoclaving","b":"Dry heat","c":"Filtration","d":"Radiation","ans":"C"},
{"t":"Bacteriology","q":"Which bacteria produces spores with terminal bulging appearance?","a":"Bacillus anthracis","b":"Clostridium tetani","c":"Clostridium perfringens","d":"Bacillus cereus","ans":"B"},
{"t":"Bacteriology","q":"Which bacterium is non-motile?","a":"Proteus","b":"Vibrio","c":"Klebsiella","d":"Salmonella","ans":"C"},
{"t":"Bacteriology","q":"Which organism produces a pseudomembrane?","a":"Streptococcus pyogenes","b":"Corynebacterium diphtheriae","c":"Neisseria meningitidis","d":"Staphylococcus aureus","ans":"B"},
{"t":"Bacteriology","q":"Which mechanism allows bacteria to avoid complement-mediated killing?","a":"Capsule","b":"Flagella","c":"Pili","d":"Spores","ans":"A"},
{"t":"Bacteriology","q":"Which disinfectant is effective against spores at high concentration?","a":"Alcohol","b":"Phenol","c":"Glutaraldehyde","d":"Quaternary ammonium","ans":"C"},
{"t":"Bacteriology","q":"Which organism is catalase positive?","a":"Streptococcus pyogenes","b":"Enterococcus","c":"Staphylococcus aureus","d":"Clostridium","ans":"C"},
{"t":"Bacteriology","q":"Catalase helps bacteria by:","a":"Producing hydrogen peroxide","b":"Neutralizing reactive oxygen species","c":"Enhancing motility","d":"Producing ATP","ans":"B"},
{"t":"Bacteriology","q":"Which test differentiates Staphylococcus aureus from other staphylococci?","a":"Catalase test","b":"Coagulase test","c":"Oxidase test","d":"Indole test","ans":"B"},
{"t":"Bacteriology","q":"Coagulase contributes to virulence by:","a":"Destroying antibodies","b":"Clotting plasma and preventing phagocytosis","c":"Increasing motility","d":"Producing exotoxin","ans":"B"},
{"t":"Bacteriology","q":"The SINGLE most important factor in prevention of bacterial infections in hospitals is:","a":"Broad-spectrum antibiotics","b":"Sterilization","c":"Hand hygiene","d":"Vaccination","ans":"C"},
{"t":"Bacteriology","q":"Mycobacterium tuberculosis is classified as:","a":"Gram-positive cocci","b":"Acid-fast bacillus","c":"Gram-negative bacillus","d":"Spore-forming bacillus","ans":"B"},
{"t":"Bacteriology","q":"Acid-fastness of Mycobacterium tuberculosis is due to presence of:","a":"Capsule","b":"Peptidoglycan","c":"Mycolic acid","d":"Teichoic acid","ans":"C"},
{"t":"Bacteriology","q":"The PRIMARY route of transmission of tuberculosis is:","a":"Feco-oral","b":"Blood transfusion","c":"Airborne droplets","d":"Sexual contact","ans":"C"},
{"t":"Bacteriology","q":"Ghon complex consists of:","a":"Cavitation and fibrosis","b":"Primary focus and hilar lymph nodes","c":"Miliary nodules","d":"Caseous pneumonia","ans":"B"},
{"t":"Bacteriology","q":"Cord factor of Mycobacterium tuberculosis is responsible for:","a":"Acid fastness","b":"Granuloma formation","c":"Drug resistance","d":"Spore formation","ans":"B"},
{"t":"Bacteriology","q":"Which stain is used to demonstrate Mycobacterium tuberculosis?","a":"Gram stain","b":"Albert stain","c":"Ziehl–Neelsen stain","d":"Giemsa stain","ans":"C"},
{"t":"Bacteriology","q":"Lowenstein–Jensen medium contains which component?","a":"Blood","b":"Egg","c":"Serum","d":"Charcoal","ans":"B"},
{"t":"Bacteriology","q":"Drug resistance in Mycobacterium tuberculosis MOST commonly occurs due to:","a":"Plasmid transfer","b":"Transduction","c":"Spontaneous chromosomal mutation","d":"Conjugation","ans":"C"},
{"t":"Bacteriology","q":"Rifampicin acts by inhibiting:","a":"DNA synthesis","b":"RNA polymerase","c":"Protein synthesis","d":"Cell wall synthesis","ans":"B"},
{"t":"Bacteriology","q":"Salmonella typhi is transmitted mainly by:","a":"Respiratory droplets","b":"Contaminated food and water","c":"Sexual contact","d":"Arthropod bite","ans":"B"},
{"t":"Bacteriology","q":"Enteric fever is caused by:","a":"Salmonella paratyphi only","b":"Salmonella typhi","c":"Shigella dysenteriae","d":"Escherichia coli","ans":"B"},
{"t":"Bacteriology","q":"The MOST important virulence factor of Salmonella typhi is:","a":"Capsule","b":"Flagella","c":"Vi antigen","d":"Endotoxin only","ans":"C"},
{"t":"Bacteriology","q":"Carrier state of Salmonella typhi is associated with colonization of:","a":"Intestine","b":"Gall bladder","c":"Liver","d":"Spleen","ans":"B"},
{"t":"Bacteriology","q":"Which culture medium is used for isolation of Salmonella from stool?","a":"Blood agar","b":"MacConkey agar","c":"TCBS agar","d":"Lowenstein–Jensen","ans":"B"},
{"t":"Bacteriology","q":"Salmonella is classified as:","a":"Lactose fermenter","b":"Non-lactose fermenter","c":"Acid-fast bacillus","d":"Spirochete","ans":"B"},
{"t":"Bacteriology","q":"Widal test detects antibodies against:","a":"Capsular antigen only","b":"O and H antigens","c":"Vi antigen only","d":"Endotoxin","ans":"B"},
{"t":"Bacteriology","q":"Staphylococcus aureus is identified by:","a":"Catalase positive, coagulase positive","b":"Catalase negative, coagulase positive","c":"Catalase positive, coagulase negative","d":"Catalase negative, coagulase negative","ans":"A"},
{"t":"Bacteriology","q":"Coagulase helps Staphylococcus aureus by:","a":"Destroying antibodies","b":"Clotting plasma and avoiding phagocytosis","c":"Increasing motility","d":"Forming spores","ans":"B"},
{"t":"Bacteriology","q":"The MOST common cause of hospital-acquired infections is:","a":"Streptococcus pyogenes","b":"Staphylococcus aureus","c":"Neisseria meningitidis","d":"Salmonella typhi","ans":"B"},
{"t":"Bacteriology","q":"Toxic shock syndrome is caused by:","a":"Alpha toxin","b":"Enterotoxin","c":"TSST-1","d":"Exfoliative toxin","ans":"C"},
{"t":"Bacteriology","q":"Staphylococcal food poisoning is due to:","a":"Endotoxin","b":"Heat-stable enterotoxin","c":"Beta-lactamase","d":"Coagulase","ans":"B"},
{"t":"Bacteriology","q":"Streptococcus pyogenes is:","a":"Gram-negative diplococci","b":"Gram-positive cocci in clusters","c":"Gram-positive cocci in chains","d":"Gram-negative bacilli","ans":"C"},
{"t":"Bacteriology","q":"Lancefield grouping of streptococci is based on:","a":"Hemolysis","b":"Capsule","c":"Cell wall carbohydrate","d":"Exotoxin","ans":"C"},
{"t":"Bacteriology","q":"Beta-hemolytic streptococci produce hemolysis that is:","a":"Partial and greenish","b":"Complete and clear","c":"No hemolysis","d":"Delayed hemolysis","ans":"B"},
{"t":"Bacteriology","q":"Rheumatic fever occurs due to:","a":"Direct bacterial invasion","b":"Immune complex deposition","c":"Molecular mimicry","d":"Endotoxin release","ans":"C"},
{"t":"Bacteriology","q":"Streptolysin O antibody is detected by:","a":"Widal test","b":"ASO titer","c":"VDRL","d":"Weil–Felix test","ans":"B"},
{"t":"Bacteriology","q":"Streptococcus pneumoniae is identified by:","a":"Bacitracin sensitivity","b":"Optochin sensitivity","c":"Novobiocin sensitivity","d":"Vancomycin resistance","ans":"B"},
{"t":"Bacteriology","q":"The MOST important virulence factor of Streptococcus pneumoniae is:","a":"Capsule","b":"Endotoxin","c":"Flagella","d":"Protein A","ans":"A"},
{"t":"Bacteriology","q":"Neisseria meningitidis is transmitted by:","a":"Feco-oral route","b":"Sexual contact","c":"Respiratory droplets","d":"Blood transfusion","ans":"C"},
{"t":"Bacteriology","q":"Neisseria species are:","a":"Gram-positive cocci","b":"Gram-negative diplococci","c":"Acid-fast bacilli","d":"Spirochetes","ans":"B"},
{"t":"Bacteriology","q":"Neisseria gonorrhoeae differs from Neisseria meningitidis by:","a":"Capsule","b":"Oxidase test","c":"Glucose fermentation only","d":"Maltose fermentation","ans":"D"},
{"t":"Bacteriology","q":"Which Neisseria ferments both glucose and maltose?","a":"N. gonorrhoeae","b":"N. meningitidis","c":"N. lactamica","d":"Moraxella","ans":"B"},
{"t":"Bacteriology","q":"The MOST common cause of septic arthritis in sexually active adults is:","a":"Staphylococcus aureus","b":"Streptococcus pyogenes","c":"Neisseria gonorrhoeae","d":"Salmonella","ans":"C"},
{"t":"Bacteriology","q":"Treponema pallidum is BEST visualized by:","a":"Gram stain","b":"Culture","c":"Dark-field microscopy","d":"Ziehl–Neelsen stain","ans":"C"},
{"t":"Bacteriology","q":"Primary syphilis presents as:","a":"Painful ulcer","b":"Painless indurated chancre","c":"Vesicular rash","d":"Gummas","ans":"B"},
{"t":"Bacteriology","q":"Secondary syphilis is characterized by:","a":"Painless ulcer only","b":"Generalized rash including palms and soles","c":"Gummatous lesions","d":"Neurosyphilis only","ans":"B"},
{"t":"Bacteriology","q":"VDRL is classified as:","a":"Treponemal test","b":"Non-treponemal test","c":"Culture method","d":"Antigen detection test","ans":"B"},
{"t":"Bacteriology","q":"Which test remains positive for life in syphilis?","a":"VDRL","b":"RPR","c":"TPHA","d":"ESR","ans":"C"},
{"t":"Bacteriology","q":"Clostridium species are:","a":"Aerobic cocci","b":"Facultative anaerobic bacilli","c":"Obligate anaerobic spore-forming bacilli","d":"Acid-fast bacilli","ans":"C"},
{"t":"Bacteriology","q":"Clostridium tetani causes disease by:","a":"Local tissue invasion","b":"Endotoxin","c":"Neurotoxin","d":"Immune complex formation","ans":"C"},
{"t":"Bacteriology","q":"Tetanospasmin causes:","a":"Flaccid paralysis","b":"Spastic paralysis","c":"Sensory loss","d":"Autonomic failure only","ans":"B"},
{"t":"Bacteriology","q":"Botulinum toxin causes:","a":"Spastic paralysis","b":"Flaccid paralysis","c":"Demyelination","d":"Muscle necrosis","ans":"B"},
{"t":"Bacteriology","q":"Clostridium perfringens alpha toxin causes:","a":"Neurotoxicity","b":"Hemolysis and myonecrosis","c":"Diarrhea only","d":"Septic shock only","ans":"B"},
{"t":"Bacteriology","q":"Gas gangrene is MOST commonly caused by:","a":"Clostridium tetani","b":"Clostridium botulinum","c":"Clostridium perfringens","d":"Clostridium difficile","ans":"C"},
{"t":"Bacteriology","q":"Clostridium difficile causes disease by:","a":"Endotoxin","b":"Enterotoxin and cytotoxin","c":"Neurotoxin","d":"Capsule","ans":"B"},
{"t":"Bacteriology","q":"Pseudomembranous colitis is associated with use of:","a":"Antivirals","b":"Broad-spectrum antibiotics","c":"Antifungals","d":"Antitubercular drugs","ans":"B"},
{"t":"Bacteriology","q":"Escherichia coli is classified as:","a":"Gram-positive cocci","b":"Gram-negative bacilli","c":"Acid-fast bacilli","d":"Spirochete","ans":"B"},
{"t":"Bacteriology","q":"E. coli is MOST commonly associated with:","a":"Pneumonia","b":"Urinary tract infection","c":"Meningitis in adults only","d":"Typhoid fever","ans":"B"},
{"t":"Bacteriology","q":"Enterotoxigenic E. coli causes diarrhea by:","a":"Invasion of mucosa","b":"Increasing cAMP/cGMP","c":"Destroying intestinal villi","d":"Producing endotoxin only","ans":"B"},
{"t":"Bacteriology","q":"E. coli O157:H7 produces:","a":"Cholera-like toxin","b":"Shiga-like toxin","c":"Neurotoxin","d":"Endotoxin only","ans":"B"},
{"t":"Bacteriology","q":"Hemolytic uremic syndrome is MOST commonly associated with:","a":"ETEC","b":"EPEC","c":"EHEC","d":"EIEC","ans":"C"},
{"t":"Bacteriology","q":"Pseudomonas aeruginosa is:","a":"Lactose fermenter","b":"Non-motile","c":"Oxidase positive","d":"Anaerobe","ans":"C"},
{"t":"Bacteriology","q":"Pseudomonas produces a characteristic pigment called:","a":"Pyocyanin","b":"Melanin","c":"Carotene","d":"Hemozoin","ans":"A"},
{"t":"Bacteriology","q":"Pseudomonas infections are COMMON in:","a":"Healthy adults","b":"Burn patients","c":"Neonates only","d":"Elderly females only","ans":"B"},
{"t":"Bacteriology","q":"The grape-like odor of Pseudomonas is due to:","a":"Capsule","b":"Endotoxin","c":"Aminoacetophenone","d":"Pyoverdin","ans":"C"},
{"t":"Bacteriology","q":"Helicobacter pylori is associated with:","a":"Duodenal ulcer","b":"Gastric carcinoma","c":"MALT lymphoma","d":"All of the above","ans":"D"},
{"t":"Bacteriology","q":"Helicobacter pylori is identified by:","a":"Coagulase test","b":"Urease test","c":"Oxidase test","d":"Indole test","ans":"B"},
{"t":"Bacteriology","q":"Urease helps H. pylori by:","a":"Causing motility","b":"Neutralizing gastric acid","c":"Producing toxin","d":"Destroying antibodies","ans":"B"},
{"t":"Bacteriology","q":"Acinetobacter is clinically important because it is:","a":"Highly motile","b":"Spore forming","c":"Multidrug resistant","d":"Acid fast","ans":"C"},
{"t":"Bacteriology","q":"Acinetobacter is MOST commonly associated with:","a":"Community-acquired pneumonia","b":"Hospital-acquired infections","c":"Food poisoning","d":"Sexually transmitted disease","ans":"B"},
{"t":"Bacteriology","q":"Which organism is non-fermenter and oxidase negative?","a":"Pseudomonas","b":"Acinetobacter","c":"Vibrio","d":"E. coli","ans":"B"},
{"t":"Bacteriology","q":"Mycoplasma pneumoniae lacks:","a":"DNA","b":"RNA","c":"Ribosomes","d":"Cell wall","ans":"D"},
{"t":"Bacteriology","q":"Mycoplasma pneumoniae causes:","a":"Lobar pneumonia","b":"Atypical pneumonia","c":"Tuberculosis","d":"Bronchial asthma","ans":"B"},
{"t":"Bacteriology","q":"Cold agglutinins are seen in infection with:","a":"Legionella","b":"Mycoplasma pneumoniae","c":"Chlamydia","d":"Streptococcus","ans":"B"},
{"t":"Bacteriology","q":"Legionella pneumophila is transmitted by:","a":"Person-to-person","b":"Contaminated water aerosols","c":"Food","d":"Sexual contact","ans":"B"},
{"t":"Bacteriology","q":"Legionella grows BEST on:","a":"Blood agar","b":"MacConkey agar","c":"Charcoal yeast extract agar","d":"Lowenstein–Jensen","ans":"C"},
{"t":"Bacteriology","q":"Chlamydia trachomatis is:","a":"Gram-positive cocci","b":"Obligate intracellular bacterium","c":"Spore-forming bacillus","d":"Acid-fast bacillus","ans":"B"},
{"t":"Bacteriology","q":"Chlamydia lacks:","a":"DNA","b":"RNA","c":"ATP synthesis","d":"Ribosomes","ans":"C"},
{"t":"Bacteriology","q":"Inclusion bodies in Chlamydia are stained by:","a":"Ziehl–Neelsen","b":"Giemsa","c":"Albert stain","d":"India ink","ans":"B"},
{"t":"Bacteriology","q":"Which organism causes reactive arthritis?","a":"E. coli","b":"Chlamydia trachomatis","c":"Staphylococcus aureus","d":"Salmonella typhi","ans":"B"},
{"t":"Bacteriology","q":"The MOST common cause of bacterial meningitis in young adults is:","a":"Haemophilus influenzae","b":"Neisseria meningitidis","c":"Streptococcus pneumoniae","d":"Listeria monocytogenes","ans":"C"},
{"t":"Bacteriology","q":"Penicillin resistance in Streptococcus pneumoniae is due to:","a":"Beta-lactamase","b":"Altered penicillin-binding proteins","c":"Efflux pumps","d":"Capsule","ans":"B"},
{"t":"Bacteriology","q":"Which organism is associated with water-borne outbreaks of pneumonia?","a":"Mycoplasma","b":"Legionella","c":"Chlamydia","d":"Klebsiella","ans":"B"},
{"t":"Bacteriology","q":"Klebsiella pneumoniae is characterized by:","a":"No capsule","b":"Large mucoid colonies","c":"Non-lactose fermentation","d":"Oxidase positivity","ans":"B"},
{"t":"Bacteriology","q":"Klebsiella pneumoniae causes pneumonia with:","a":"Rusty sputum","b":"Green sputum","c":"Currant jelly sputum","d":"Frothy sputum","ans":"C"},
{"t":"Bacteriology","q":"Which organism is urease positive?","a":"E. coli","b":"Salmonella","c":"Helicobacter pylori","d":"Shigella","ans":"C"},
{"t":"Bacteriology","q":"Shigella differs from Salmonella because Shigella is:","a":"Motile","b":"Non-motile","c":"Encapsulated","d":"Spore forming","ans":"B"},
{"t":"Bacteriology","q":"Shigella causes disease by:","a":"Endotoxin only","b":"Shiga toxin and invasion","c":"Capsule","d":"Biofilm","ans":"B"},
{"t":"Bacteriology","q":"Which organism commonly causes traveler’s diarrhea?","a":"EHEC","b":"ETEC","c":"EPEC","d":"EIEC","ans":"B"},
{"t":"Bacteriology","q":"Which organism is oxidase negative?","a":"Pseudomonas","b":"Neisseria","c":"Vibrio","d":"E. coli","ans":"D"},
{"t":"Bacteriology","q":"Vibrio cholerae grows BEST on:","a":"MacConkey agar","b":"Blood agar","c":"TCBS agar","d":"Chocolate agar","ans":"C"},
{"t":"Bacteriology","q":"TCBS agar is selective for:","a":"Salmonella","b":"Vibrio","c":"Shigella","d":"Campylobacter","ans":"B"},
{"t":"Bacteriology","q":"The rice-water stool of cholera is due to:","a":"Invasion of mucosa","b":"Increased cAMP","c":"Inflammatory damage","d":"Hemorrhage","ans":"B"},
{"t":"Bacteriology","q":"Which organism is curved, motile, and oxidase positive?","a":"E. coli","b":"Vibrio cholerae","c":"Shigella","d":"Klebsiella","ans":"B"},
{"t":"Bacteriology","q":"Campylobacter jejuni causes:","a":"Typhoid fever","b":"Bloody diarrhea","c":"Pseudomembranous colitis","d":"Cholera","ans":"B"},
{"t":"Bacteriology","q":"Campylobacter jejuni is associated with:","a":"Rheumatic fever","b":"Guillain–Barré syndrome","c":"Reactive arthritis only","d":"Diphtheria","ans":"B"},
{"t":"Bacteriology","q":"The MOST common cause of uncomplicated UTI is:","a":"Klebsiella","b":"Proteus","c":"E. coli","d":"Pseudomonas","ans":"C"},
{"t":"Bacteriology","q":"Proteus species are characterized by:","a":"Lactose fermentation","b":"Swarming motility","c":"Oxidase positivity","d":"Capsule formation","ans":"B"},
{"t":"Bacteriology","q":"Proteus predisposes to renal stones because it produces:","a":"Urease","b":"Catalase","c":"Coagulase","d":"Beta-lactamase","ans":"A"},
{"t":"Bacteriology","q":"Which organism commonly causes ventilator-associated pneumonia?","a":"Streptococcus pneumoniae","b":"Pseudomonas aeruginosa","c":"Mycoplasma pneumoniae","d":"Neisseria meningitidis","ans":"B"},
{"t":"Bacteriology","q":"Which organism produces green discoloration of pus?","a":"Staphylococcus aureus","b":"Streptococcus pyogenes","c":"Pseudomonas aeruginosa","d":"Klebsiella","ans":"C"},
{"t":"Bacteriology","q":"The MOST important virulence factor of Neisseria gonorrhoeae is:","a":"Capsule","b":"Pili","c":"Endotoxin","d":"Flagella","ans":"B"},
{"t":"Bacteriology","q":"Pili of Neisseria show:","a":"Antigenic stability","b":"Antigenic variation","c":"No immune role","d":"Heat resistance","ans":"B"},
{"t":"Bacteriology","q":"Gonococcal arthritis occurs due to:","a":"Local invasion only","b":"Hematogenous spread","c":"Toxin mediated injury","d":"Capsule formation","ans":"B"},
{"t":"Bacteriology","q":"Which organism causes chancroid?","a":"Treponema pallidum","b":"Haemophilus ducreyi","c":"Neisseria gonorrhoeae","d":"Chlamydia trachomatis","ans":"B"},
{"t":"Bacteriology","q":"Haemophilus influenzae requires which factors for growth?","a":"Factor X only","b":"Factor V only","c":"Factor X and V","d":"Iron and serum","ans":"C"},
{"t":"Bacteriology","q":"Satellite phenomenon is seen with:","a":"E. coli","b":"Haemophilus influenzae","c":"Neisseria","d":"Streptococcus","ans":"B"},
{"t":"Bacteriology","q":"Which organism causes epiglottitis in children?","a":"Streptococcus pneumoniae","b":"Haemophilus influenzae type b","c":"Neisseria meningitidis","d":"Staphylococcus aureus","ans":"B"},
{"t":"Bacteriology","q":"The vaccine against Haemophilus influenzae type b is:","a":"Live attenuated","b":"Killed whole cell","c":"Conjugate vaccine","d":"Toxoid","ans":"C"},
{"t":"Bacteriology","q":"The MOST important preventive measure against bacterial meningitis in children is:","a":"Antibiotic prophylaxis","b":"Hand hygiene","c":"Vaccination","d":"Early diagnosis","ans":"C"},
{"t":"Virology","q":"Viruses are BEST described as:","a":"Unicellular organisms","b":"Obligate intracellular parasites","c":"Free-living microorganisms","d":"Prokaryotic cells","ans":"B"},
{"t":"Virology","q":"The basic structure common to all viruses includes:","a":"Cell wall and membrane","b":"Nucleus and cytoplasm","c":"Nucleic acid and capsid","d":"Ribosomes and enzymes","ans":"C"},
{"t":"Virology","q":"Viral capsid is composed of repeating units called:","a":"Virions","b":"Capsomeres","c":"Nucleosomes","d":"Peplomers","ans":"B"},
{"t":"Virology","q":"Enveloped viruses acquire their envelope from:","a":"Host ribosomes","b":"Host cell membrane","c":"Viral capsid","d":"Bacterial cell wall","ans":"B"},
{"t":"Virology","q":"Which virus is NON-enveloped?","a":"HIV","b":"Influenza virus","c":"Hepatitis B virus","d":"Adenovirus","ans":"D"},
{"t":"Virology","q":"The nucleic acid of viruses can be:","a":"DNA only","b":"RNA only","c":"Both DNA or RNA (never both together)","d":"Always double stranded","ans":"C"},
{"t":"Virology","q":"Interferons (IFN) act by:","a":"Killing viruses directly","b":"Inhibiting viral protein synthesis","c":"Destroying infected cells","d":"Activating complement only","ans":"B"},
{"t":"Virology","q":"Interferons are produced mainly by:","a":"B lymphocytes","b":"Plasma cells","c":"Virus-infected cells","d":"Neutrophils","ans":"C"},
{"t":"Virology","q":"Which interferon is MOST important for antiviral activity?","a":"IFN-α","b":"IFN-β","c":"IFN-γ","d":"TNF-α","ans":"A"},
{"t":"Virology","q":"Natural killer (NK) cells destroy virus-infected cells by recognizing:","a":"Viral antigens only","b":"Absence of MHC-I molecules","c":"Presence of antibodies","d":"Complement proteins","ans":"B"},
{"t":"Virology","q":"Complement helps in viral defense mainly by:","a":"Opsonization and lysis of enveloped viruses","b":"DNA degradation","c":"Inhibiting viral entry","d":"Blocking replication","ans":"A"},
{"t":"Virology","q":"Which virus is a DNA virus?","a":"Influenza","b":"HIV","c":"Hepatitis B","d":"Dengue","ans":"C"},
{"t":"Virology","q":"Hepatitis B virus belongs to family:","a":"Flaviviridae","b":"Retroviridae","c":"Hepadnaviridae","d":"Togaviridae","ans":"C"},
{"t":"Virology","q":"Hepatitis B virus contains:","a":"Double-stranded RNA","b":"Partially double-stranded DNA","c":"Single-stranded DNA","d":"Circular RNA","ans":"B"},
{"t":"Virology","q":"Dane particle refers to:","a":"Hepatitis A virus","b":"Complete hepatitis B virion","c":"Hepatitis C virus","d":"Hepatitis E virus","ans":"B"},
{"t":"Virology","q":"HBsAg indicates:","a":"Immunity only","b":"Past infection only","c":"Current infection or carrier state","d":"Window period","ans":"C"},
{"t":"Virology","q":"Anti-HBs antibody indicates:","a":"Active infection","b":"Window period","c":"Immunity to hepatitis B","d":"High infectivity","ans":"C"},
{"t":"Virology","q":"HBeAg positivity suggests:","a":"Recovery phase","b":"Low infectivity","c":"High viral replication and infectivity","d":"Vaccinated state","ans":"C"},
{"t":"Virology","q":"The MOST infectious phase of hepatitis B is indicated by:","a":"Anti-HBs","b":"HBsAg only","c":"HBeAg","d":"Anti-HBc IgG","ans":"C"},
{"t":"Virology","q":"Window period of hepatitis B is characterized by presence of:","a":"HBsAg","b":"Anti-HBs","c":"Anti-HBc IgM","d":"HBeAg","ans":"C"},
{"t":"Virology","q":"Hepatitis B is transmitted by all EXCEPT:","a":"Blood transfusion","b":"Sexual contact","c":"Perinatal transmission","d":"Feco-oral route","ans":"D"},
{"t":"Virology","q":"The hepatitis virus with HIGHEST risk of chronicity is:","a":"HAV","b":"HBV","c":"HCV","d":"HEV","ans":"C"},
{"t":"Virology","q":"Hepatitis C virus is classified as:","a":"DNA virus","b":"Retrovirus","c":"RNA virus","d":"Partially double-stranded DNA virus","ans":"C"},
{"t":"Virology","q":"Hepatitis A virus is transmitted mainly by:","a":"Blood","b":"Sexual contact","c":"Feco-oral route","d":"Vertical transmission","ans":"C"},
{"t":"Virology","q":"Which hepatitis virus causes acute hepatitis with HIGH mortality in pregnancy?","a":"HAV","b":"HBV","c":"HCV","d":"HEV","ans":"D"},
{"t":"Virology","q":"Hepatitis A infection confers:","a":"Chronic infection","b":"Carrier state","c":"Lifelong immunity","d":"Cirrhosis","ans":"C"},
{"t":"Virology","q":"HIV belongs to the family:","a":"Flaviviridae","b":"Retroviridae","c":"Orthomyxoviridae","d":"Coronaviridae","ans":"B"},
{"t":"Virology","q":"HIV primarily infects cells expressing:","a":"CD8","b":"CD4","c":"CD19","d":"CD16","ans":"B"},
{"t":"Virology","q":"HIV gp120 binds to:","a":"CD8 receptor","b":"CD4 receptor","c":"CCR5 only","d":"CXCR4 only","ans":"B"},
{"t":"Virology","q":"Reverse transcriptase converts:","a":"DNA → RNA","b":"RNA → DNA","c":"DNA → protein","d":"Protein → RNA","ans":"B"},
{"t":"Virology","q":"Integration of viral DNA into host genome is mediated by:","a":"Protease","b":"Reverse transcriptase","c":"Integrase","d":"RNA polymerase","ans":"C"},
{"t":"Virology","q":"The MOST important laboratory marker for monitoring HIV progression is:","a":"Viral RNA load only","b":"CD4 cell count","c":"Antibody titer","d":"ESR","ans":"B"},
{"t":"Virology","q":"AIDS is diagnosed when CD4 count falls below:","a":"1000/µL","b":"750/µL","c":"500/µL","d":"200/µL","ans":"D"},
{"t":"Virology","q":"The window period of HIV refers to:","a":"End-stage disease","b":"Period before antibody detection","c":"Time of ART therapy","d":"Latent infection only","ans":"B"},
{"t":"Virology","q":"The MOST sensitive test for early HIV infection is:","a":"Western blot","b":"ELISA antibody test","c":"p24 antigen","d":"CD4 count","ans":"C"},
{"t":"Virology","q":"Opportunistic infections in HIV are mainly due to:","a":"B-cell dysfunction","b":"Neutropenia","c":"T-cell deficiency","d":"Complement deficiency","ans":"C"},
{"t":"Virology","q":"Kaposi sarcoma in HIV is associated with:","a":"EBV","b":"CMV","c":"HHV-8","d":"HSV-2","ans":"C"},
{"t":"Virology","q":"Influenza virus belongs to family:","a":"Paramyxoviridae","b":"Orthomyxoviridae","c":"Togaviridae","d":"Flaviviridae","ans":"B"},
{"t":"Virology","q":"Influenza virus genome is:","a":"Single-stranded DNA","b":"Double-stranded RNA","c":"Segmented negative-sense RNA","d":"Non-segmented RNA","ans":"C"},
{"t":"Virology","q":"Antigenic drift in influenza is due to:","a":"Reassortment","b":"Minor mutations","c":"Recombination","d":"Integration","ans":"B"},
{"t":"Virology","q":"Antigenic shift results in:","a":"Seasonal flu","b":"Pandemic influenza","c":"Mild disease","d":"Loss of infectivity","ans":"B"},
{"t":"Virology","q":"Antigenic shift occurs due to:","a":"Point mutation","b":"RNA polymerase error","c":"Gene segment reassortment","d":"Immune pressure","ans":"C"},
{"t":"Virology","q":"The major surface antigens of influenza virus are:","a":"Capsid proteins","b":"Hemagglutinin and neuraminidase","c":"Matrix proteins","d":"Nucleoproteins","ans":"B"},
{"t":"Virology","q":"Neuraminidase inhibitors include:","a":"Acyclovir","b":"Oseltamivir","c":"Zidovudine","d":"Ribavirin","ans":"B"},
{"t":"Virology","q":"SARS-CoV-2 belongs to family:","a":"Orthomyxoviridae","b":"Flaviviridae","c":"Coronaviridae","d":"Retroviridae","ans":"C"},
{"t":"Virology","q":"SARS-CoV-2 genome is:","a":"DNA","b":"Double-stranded RNA","c":"Single-stranded positive-sense RNA","d":"Negative-sense RNA","ans":"C"},
{"t":"Virology","q":"SARS-CoV-2 enters cells via binding to:","a":"CD4","b":"ACE-2 receptor","c":"CCR5","d":"ICAM-1","ans":"B"},
{"t":"Virology","q":"The MOST common diagnostic test for COVID-19 is:","a":"Viral culture","b":"RT-PCR","c":"Antibody test only","d":"ESR","ans":"B"},
{"t":"Virology","q":"Severe COVID-19 is associated with:","a":"Low IL-6","b":"Cytokine storm","c":"Reduced CRP","d":"Hypoglycemia","ans":"B"},
{"t":"Virology","q":"Dengue virus is transmitted by:","a":"Culex mosquito","b":"Anopheles mosquito","c":"Aedes mosquito","d":"Sandfly","ans":"C"},
{"t":"Virology","q":"Dengue virus belongs to family:","a":"Togaviridae","b":"Flaviviridae","c":"Orthomyxoviridae","d":"Paramyxoviridae","ans":"B"},
{"t":"Virology","q":"Dengue virus genome is:","a":"DNA","b":"Double-stranded RNA","c":"Single-stranded RNA","d":"Segmented RNA","ans":"C"},
{"t":"Virology","q":"Dengue hemorrhagic fever is due to:","a":"Primary infection","b":"Antibody-dependent enhancement","c":"Bacterial superinfection","d":"Direct endothelial invasion only","ans":"B"},
{"t":"Virology","q":"A low platelet count in dengue is due to:","a":"Bone marrow failure only","b":"Immune-mediated destruction","c":"Hypersplenism","d":"Hemodilution","ans":"B"},
{"t":"Virology","q":"NS1 antigen is useful for diagnosis of dengue in:","a":"Late convalescent phase","b":"First few days of illness","c":"Chronic infection","d":"Post-vaccination","ans":"B"},
{"t":"Virology","q":"Which virus causes chronic hepatitis MOST commonly?","a":"HAV","b":"HBV","c":"HCV","d":"HEV","ans":"C"},
{"t":"Virology","q":"Fulminant hepatitis is MOST commonly associated with:","a":"HAV","b":"HBV + HDV co-infection","c":"HCV","d":"HEV alone","ans":"B"},
{"t":"Virology","q":"Hepatitis D virus requires presence of:","a":"HAV","b":"HBV","c":"HCV","d":"HEV","ans":"B"},
{"t":"Virology","q":"Hepatitis D virus uses which antigen for its envelope?","a":"HBeAg","b":"HBcAg","c":"HBsAg","d":"Anti-HBs","ans":"C"},
{"t":"Virology","q":"HIV transmission does NOT occur through:","a":"Blood transfusion","b":"Sexual contact","c":"Breastfeeding","d":"Casual contact","ans":"D"},
{"t":"Virology","q":"The MOST common cause of death in AIDS patients is:","a":"HIV itself","b":"Opportunistic infections","c":"Drug toxicity","d":"Autoimmune disease","ans":"B"},
{"t":"Virology","q":"CMV infection in AIDS commonly causes:","a":"Pneumonia only","b":"Retinitis","c":"Meningitis","d":"Encephalitis only","ans":"B"},
{"t":"Virology","q":"Which virus causes infectious mononucleosis?","a":"CMV","b":"EBV","c":"HSV-1","d":"Adenovirus","ans":"B"},
{"t":"Virology","q":"Atypical lymphocytes are seen in infection with:","a":"HIV","b":"EBV","c":"Dengue","d":"Influenza","ans":"B"},
{"t":"Virology","q":"Herpes simplex virus establishes latency in:","a":"Liver","b":"Dorsal root ganglia","c":"Blood","d":"Lymph nodes","ans":"B"},
{"t":"Virology","q":"Varicella-zoster virus causes:","a":"Measles","b":"Chickenpox and shingles","c":"Rubella","d":"Smallpox","ans":"B"},
{"t":"Virology","q":"Reactivation of varicella-zoster virus results in:","a":"Chickenpox","b":"Measles","c":"Herpes zoster","d":"Rubella","ans":"C"},
{"t":"Virology","q":"Rabies virus is transmitted through:","a":"Airborne droplets","b":"Feco-oral route","c":"Animal bite","d":"Blood transfusion","ans":"C"},
{"t":"Virology","q":"Negri bodies are seen in:","a":"Influenza","b":"Rabies","c":"Dengue","d":"Polio","ans":"B"},
{"t":"Virology","q":"Rabies virus primarily affects:","a":"Liver","b":"Lungs","c":"Central nervous system","d":"Kidney","ans":"C"},
{"t":"Virology","q":"Polio virus belongs to family:","a":"Picornaviridae","b":"Flaviviridae","c":"Retroviridae","d":"Orthomyxoviridae","ans":"A"},
{"t":"Virology","q":"Polio virus causes paralysis by damaging:","a":"Sensory neurons","b":"Motor neurons","c":"Autonomic neurons","d":"Muscle fibers","ans":"B"},
{"t":"Virology","q":"Measles virus belongs to family:","a":"Paramyxoviridae","b":"Togaviridae","c":"Flaviviridae","d":"Orthomyxoviridae","ans":"A"},
{"t":"Virology","q":"Koplik spots are seen in:","a":"Rubella","b":"Measles","c":"Chickenpox","d":"Mumps","ans":"B"},
{"t":"Virology","q":"Mumps virus causes:","a":"Orchitis","b":"Hepatitis","c":"Encephalitis only","d":"Rash","ans":"A"},
{"t":"Virology","q":"Which virus causes congenital cataracts?","a":"CMV","b":"Rubella","c":"HSV","d":"EBV","ans":"B"},
{"t":"Virology","q":"TORCH infections include all EXCEPT:","a":"Toxoplasma","b":"Rubella","c":"Cytomegalovirus","d":"HIV","ans":"D"},
{"t":"Virology","q":"Which virus commonly causes hand-foot-mouth disease?","a":"Coxsackie virus","b":"Influenza virus","c":"Dengue virus","d":"EBV","ans":"A"},
{"t":"Virology","q":"The MOST common cause of viral encephalitis is:","a":"Rabies","b":"HSV-1","c":"CMV","d":"Polio","ans":"B"},
{"t":"Virology","q":"Inclusion bodies seen in CMV are called:","a":"Negri bodies","b":"Owl’s eye inclusions","c":"Guarnieri bodies","d":"Cowdry bodies","ans":"B"},
{"t":"Virology","q":"Cowdry type A inclusions are seen in:","a":"CMV","b":"HSV","c":"EBV","d":"Dengue","ans":"B"},
{"t":"Virology","q":"Which virus causes fifth disease?","a":"Parvovirus B19","b":"Measles virus","c":"Rubella virus","d":"Adenovirus","ans":"A"},
{"t":"Virology","q":"Parvovirus B19 infects:","a":"Neutrophils","b":"Platelets","c":"Erythroid precursors","d":"Lymphocytes","ans":"C"},
{"t":"Virology","q":"Which virus lacks an envelope?","a":"HIV","b":"Influenza","c":"Adenovirus","d":"SARS-CoV-2","ans":"C"},
{"t":"Virology","q":"Viral replication takes place in host:","a":"Nucleus only","b":"Cytoplasm only","c":"Either nucleus or cytoplasm","d":"Cell membrane","ans":"C"},
{"t":"Virology","q":"Poxviruses replicate in:","a":"Nucleus","b":"Cytoplasm","c":"Mitochondria","d":"Ribosomes","ans":"B"},
{"t":"Virology","q":"The MOST effective immune response against viruses is:","a":"Antibodies only","b":"Cell-mediated immunity","c":"Complement alone","d":"Neutrophils","ans":"B"},
{"t":"Virology","q":"Neutralizing antibodies act by:","a":"Killing infected cells","b":"Preventing viral attachment","c":"Activating macrophages","d":"Destroying viral genome","ans":"B"},
{"t":"Virology","q":"Which virus shows segmented genome allowing reassortment?","a":"Dengue","b":"HIV","c":"Influenza","d":"Polio","ans":"C"},
{"t":"Virology","q":"A virus with reverse transcription in its life cycle is:","a":"Influenza","b":"Hepatitis B","c":"Dengue","d":"Adenovirus","ans":"B"},
{"t":"Virology","q":"The MOST common mode of transmission of HAV is:","a":"Blood","b":"Sexual contact","c":"Feco-oral route","d":"Vertical","ans":"C"},
{"t":"Virology","q":"Which hepatitis virus has NO chronic carrier state?","a":"HBV","b":"HCV","c":"HAV","d":"HDV","ans":"C"},
{"t":"Virology","q":"Co-infection of HBV and HDV results in:","a":"Mild disease","b":"No effect","c":"Severe acute hepatitis","d":"Chronic carrier state only","ans":"C"},
{"t":"Virology","q":"Superinfection of HDV in HBV carrier causes:","a":"Asymptomatic infection","b":"Fulminant hepatitis","c":"Mild disease","d":"Immunity","ans":"B"},
{"t":"Virology","q":"HIV protease inhibitors act by:","a":"Blocking viral entry","b":"Preventing viral maturation","c":"Inhibiting reverse transcription","d":"Blocking integration","ans":"B"},
{"t":"Virology","q":"Reverse transcriptase inhibitors include:","a":"Acyclovir","b":"Zidovudine","c":"Oseltamivir","d":"Ribavirin","ans":"B"},
{"t":"Virology","q":"The MOST common presenting feature of acute HIV infection is:","a":"Kaposi sarcoma","b":"Flu-like illness","c":"Chronic diarrhea","d":"TB","ans":"B"},
{"t":"Virology","q":"Dengue shock syndrome occurs due to:","a":"Dehydration only","b":"Plasma leakage","c":"Bradycardia","d":"Renal failure","ans":"B"},
{"t":"Virology","q":"Which dengue serotype infection increases risk of hemorrhagic fever on reinfection?","a":"Same serotype","b":"Different serotype","c":"Any serotype","d":"Only primary infection","ans":"B"},
{"t":"Virology","q":"Viral inclusion bodies represent:","a":"Bacterial contamination","b":"Accumulated viral particles","c":"Host cell debris only","d":"Immune complexes","ans":"B"},
{"t":"Virology","q":"The BEST sample for diagnosis of influenza is:","a":"Blood","b":"Urine","c":"Nasopharyngeal swab","d":"Stool","ans":"C"},
{"t":"Virology","q":"Which virus causes bronchiolitis in infants?","a":"Adenovirus","b":"RSV","c":"Influenza","d":"Rhinovirus","ans":"B"},
{"t":"Virology","q":"RSV belongs to family:","a":"Paramyxoviridae","b":"Orthomyxoviridae","c":"Picornaviridae","d":"Flaviviridae","ans":"A"},
{"t":"Virology","q":"Palivizumab is used for prevention of:","a":"Influenza","b":"RSV infection","c":"HIV","d":"Dengue","ans":"B"},
{"t":"Virology","q":"Rhinovirus causes:","a":"Pneumonia","b":"Common cold","c":"Bronchiolitis","d":"Influenza","ans":"B"},
{"t":"Virology","q":"Rhinovirus replicates BEST at:","a":"37°C","b":"39°C","c":"33°C","d":"25°C","ans":"C"},
{"t":"Virology","q":"Which virus causes croup?","a":"RSV","b":"Parainfluenza virus","c":"Influenza virus","d":"Adenovirus","ans":"B"},
{"t":"Virology","q":"The MOST common viral cause of diarrhea in children is:","a":"Adenovirus","b":"Norovirus","c":"Rotavirus","d":"Astrovirus","ans":"C"},
{"t":"Virology","q":"Rotavirus causes diarrhea by:","a":"Invasion","b":"Toxin production","c":"Villous atrophy","d":"Hemorrhage","ans":"C"},
{"t":"Virology","q":"Which virus is detected by HBsAg ELISA?","a":"HAV","b":"HBV","c":"HCV","d":"HEV","ans":"B"},
{"t":"Virology","q":"The MOST common cause of post-transfusion hepatitis is:","a":"HAV","b":"HBV","c":"HCV","d":"HEV","ans":"C"},
{"t":"Virology","q":"Which virus causes cervical cancer?","a":"HSV-2","b":"HPV","c":"EBV","d":"CMV","ans":"B"},
{"t":"Virology","q":"High-risk HPV types include:","a":"6 and 11","b":"16 and 18","c":"31 and 33","d":"40 and 42","ans":"B"},
{"t":"Virology","q":"HPV infects:","a":"Hepatocytes","b":"Keratinocytes","c":"Neurons","d":"Lymphocytes","ans":"B"},
{"t":"Virology","q":"Viral oncogenesis is mediated by:","a":"Inflammation only","b":"Integration of viral genome","c":"Antibody production","d":"Complement activation","ans":"B"},
{"t":"Virology","q":"Which virus causes Burkitt lymphoma?","a":"HIV","b":"CMV","c":"EBV","d":"HPV","ans":"C"},
{"t":"Virology","q":"Which virus is responsible for progressive multifocal leukoencephalopathy?","a":"JC virus","b":"BK virus","c":"EBV","d":"CMV","ans":"A"},
{"t":"Virology","q":"BK virus primarily affects:","a":"Brain","b":"Kidney","c":"Liver","d":"Lung","ans":"B"},
{"t":"Virology","q":"The MOST important preventive measure for viral hepatitis B is:","a":"Antibiotics","b":"Antivirals","c":"Vaccination","d":"Isolation","ans":"C"},
{"t":"Virology","q":"The hepatitis B vaccine is:","a":"Live attenuated","b":"Killed whole virus","c":"Recombinant subunit vaccine","d":"Toxoid","ans":"C"},
{"t":"Virology","q":"Which virus shows highest mutation rate?","a":"Adenovirus","b":"Influenza virus","c":"HIV","d":"Hepatitis B","ans":"C"},
{"t":"Virology","q":"HIV genetic variability is due to:","a":"Segmented genome","b":"Reverse transcriptase errors","c":"Host enzymes","d":"Antigenic shift","ans":"B"},
{"t":"Virology","q":"The MOST common cause of viral myocarditis is:","a":"Influenza virus","b":"Coxsackie B virus","c":"Adenovirus","d":"EBV","ans":"B"},
{"t":"Virology","q":"Viral latency refers to:","a":"Viral clearance","b":"Dormant virus without replication","c":"Rapid replication","d":"Severe disease","ans":"B"},
{"t":"Virology","q":"Reactivation of latent virus occurs MOST commonly with:","a":"Strong immunity","b":"Stress and immunosuppression","c":"Vaccination","d":"Antibiotic therapy","ans":"B"},
{"t":"Parasitology","q":"A 28-year-old healthcare worker sustains a needle-stick injury from a patient whose serology shows HBsAg positive, HBeAg positive, and high HBV DNA levels. The SINGLE most accurate interpretation of the source patient’s infectivity is:","a":"Low infectivity due to immune clearance","b":"High infectivity due to active viral replication","c":"Window period of infection","d":"Past resolved infection","ans":"B"},
{"t":"Parasitology","q":"A patient presents with acute hepatitis. Serology shows HBsAg negative, anti-HBs negative, anti-HBc IgM positive. This serological pattern MOST strongly indicates:","a":"Vaccinated state","b":"Chronic hepatitis B","c":"Window period of acute HBV infection","d":"Resolved infection","ans":"C"},
{"t":"Parasitology","q":"A 35-year-old IV drug user develops rapidly progressive hepatic failure. Serology reveals HBsAg positive with sudden worsening and detection of anti-HDV. The MOST likely explanation is:","a":"HBV co-infection causing mild disease","b":"HDV superinfection on chronic HBV","c":"HAV superinfection","d":"Vaccine failure","ans":"B"},
{"t":"Parasitology","q":"A pregnant woman in her third trimester develops acute hepatitis with very high mortality risk. The MOST likely causative virus is:","a":"HAV","b":"HBV","c":"HCV","d":"HEV","ans":"D"},
{"t":"Parasitology","q":"A patient has chronic hepatitis with fluctuating ALT levels and very high risk of cirrhosis. The virus MOST strongly associated with this course is:","a":"HAV","b":"HBV","c":"HCV","d":"HEV","ans":"C"},
{"t":"Parasitology","q":"A laboratory worker is exposed to HIV. Which test becomes positive EARLIEST after infection?","a":"Anti-HIV ELISA","b":"Western blot","c":"p24 antigen","d":"CD4 count decline","ans":"C"},
{"t":"Parasitology","q":"A patient with HIV has a CD4 count of 90/µL and presents with visual blurring. Fundoscopy shows fluffy yellow-white retinal lesions. The MOST likely diagnosis is:","a":"Toxoplasma encephalitis","b":"CMV retinitis","c":"HSV retinitis","d":"Syphilitic uveitis","ans":"B"},
{"t":"Parasitology","q":"A patient on antiretroviral therapy shows falling viral load but persistent low CD4 count. This MOST accurately reflects:","a":"Treatment failure","b":"Immune reconstitution delay","c":"Drug resistance","d":"Laboratory error","ans":"B"},
{"t":"Parasitology","q":"A man presents with fever, myalgia, headache, and retro-orbital pain. Platelets are 45,000/µL. NS1 antigen is positive. The MOST accurate diagnosis is:","a":"Chikungunya","b":"Dengue (early phase)","c":"Malaria","d":"Typhoid fever","ans":"B"},
{"t":"Parasitology","q":"A patient previously infected with Dengue serotype 1 now develops hemorrhagic fever after infection with serotype 2. The underlying mechanism is:","a":"Viral mutation","b":"Cytokine storm only","c":"Antibody-dependent enhancement","d":"Direct endothelial invasion","ans":"C"},
{"t":"Parasitology","q":"A 65-year-old man develops severe viral pneumonia during winter. PCR shows a segmented negative-sense RNA virus. The MOST likely virus is:","a":"RSV","b":"Influenza A","c":"Adenovirus","d":"SARS-CoV-2","ans":"B"},
{"t":"Parasitology","q":"A sudden global outbreak with a novel influenza strain occurs. The PRIMARY virological mechanism responsible is:","a":"Antigenic drift","b":"Antigenic shift","c":"Point mutation","d":"Recombination","ans":"B"},
{"t":"Parasitology","q":"A patient with influenza is treated with a drug that blocks release of progeny virions from host cells. The drug MOST likely targets:","a":"Hemagglutinin","b":"Neuraminidase","c":"RNA polymerase","d":"Matrix protein","ans":"B"},
{"t":"Parasitology","q":"A patient presents with severe hypoxia, elevated IL-6 levels, and diffuse alveolar damage after SARS-CoV-2 infection. The PRIMARY pathological mechanism is:","a":"Direct viral cytolysis only","b":"Immune complex deposition","c":"Cytokine storm","d":"Secondary bacterial sepsis","ans":"C"},
{"t":"Parasitology","q":"SARS-CoV-2 gains entry into host cells primarily via binding to:","a":"CD4","b":"CCR5","c":"ACE-2 receptor","d":"ICAM-1","ans":"C"},
{"t":"Parasitology","q":"A child presents with fever, cough, conjunctivitis, and Koplik spots. The virus MOST likely responsible belongs to:","a":"Togaviridae","b":"Paramyxoviridae","c":"Orthomyxoviridae","d":"Flaviviridae","ans":"B"},
{"t":"Parasitology","q":"A patient develops shingles years after chickenpox. This phenomenon represents:","a":"Reinfection","b":"Antigenic variation","c":"Reactivation of latent virus","d":"Persistent productive infection","ans":"C"},
{"t":"Parasitology","q":"A virus that completes its entire replication cycle in the cytoplasm is:","a":"Adenovirus","b":"Herpesvirus","c":"Poxvirus","d":"Influenza virus","ans":"C"},
{"t":"Parasitology","q":"A patient presents with acute encephalitis involving temporal lobes. The MOST likely causative virus is:","a":"CMV","b":"EBV","c":"HSV-1","d":"Rabies virus","ans":"C"},
{"t":"Parasitology","q":"A farmer bitten by a dog develops hydrophobia weeks later. The virus reaches CNS via:","a":"Hematogenous spread","b":"Lymphatic spread","c":"Retrograde axonal transport","d":"CSF circulation","ans":"C"},
{"t":"Parasitology","q":"Negri bodies are MOST characteristically found in:","a":"Hippocampus neurons","b":"Cerebellar Purkinje cells","c":"Basal ganglia neurons","d":"Spinal motor neurons","ans":"B"},
{"t":"Parasitology","q":"A neonate develops cataracts, deafness, and PDA. The MOST likely congenital viral infection is:","a":"CMV","b":"HSV","c":"Rubella","d":"Toxoplasma","ans":"C"},
{"t":"Parasitology","q":"A child with aplastic crisis has a history of chronic hemolytic anemia. The virus MOST likely responsible is:","a":"EBV","b":"Parvovirus B19","c":"CMV","d":"Adenovirus","ans":"B"},
{"t":"Parasitology","q":"A renal transplant recipient develops progressive multifocal leukoencephalopathy. The causative virus is:","a":"BK virus","b":"JC virus","c":"EBV","d":"CMV","ans":"B"},
{"t":"Parasitology","q":"A patient with infectious mononucleosis shows atypical lymphocytes. These cells are:","a":"Infected B cells","b":"Activated CD8⁺ T cells","c":"Plasma cells","d":"NK cells","ans":"B"},
{"t":"Parasitology","q":"A virus shows reverse transcription during replication but is NOT a retrovirus. This virus is:","a":"HIV","b":"HBV","c":"HCV","d":"HDV","ans":"B"},
{"t":"Parasitology","q":"The antigen used in hepatitis B vaccine is:","a":"HBcAg","b":"HBeAg","c":"HBsAg","d":"Whole virus","ans":"C"},
{"t":"Parasitology","q":"A patient with acute HIV infection is MOST likely to present initially with:","a":"Kaposi sarcoma","b":"Pneumocystis pneumonia","c":"Flu-like illness","d":"CMV retinitis","ans":"C"},
{"t":"Parasitology","q":"A virus that lacks an envelope is MOST resistant to:","a":"Dry heat","b":"Detergents","c":"Acidic environment","d":"UV radiation","ans":"B"},
{"t":"Parasitology","q":"Which immune mechanism is MOST critical for clearance of viral infections?","a":"Neutrophils","b":"Humoral immunity alone","c":"Cell-mediated immunity","d":"Complement alone","ans":"C"},
{"t":"Parasitology","q":"A patient has high anti-HBc IgG, negative HBsAg, and positive anti-HBs. This indicates:","a":"Window period","b":"Chronic infection","c":"Immunity due to vaccination","d":"Immunity due to natural infection","ans":"D"},
{"t":"Parasitology","q":"A severe COVID-19 patient shows microthrombi in pulmonary vessels. The underlying process MOST closely involves:","a":"Type I hypersensitivity","b":"Immune complex disease","c":"Endothelial injury with coagulation activation","d":"Direct bacterial superinfection","ans":"C"},
{"t":"Parasitology","q":"Dengue NS1 antigen detection is MOST useful during:","a":"Late convalescence","b":"Secondary infection only","c":"Early febrile phase","d":"Chronic infection","ans":"C"},
{"t":"Parasitology","q":"A virus with the HIGHEST mutation rate causing rapid drug resistance is:","a":"Influenza virus","b":"HIV","c":"HBV","d":"SARS-CoV-2","ans":"B"},
{"t":"Parasitology","q":"A patient with chronic hepatitis develops hepatocellular carcinoma. The virus MOST strongly associated oncogenically is:","a":"HAV","b":"HBV","c":"HEV","d":"Dengue virus","ans":"B"},
{"t":"Parasitology","q":"Which viral protein of HIV mediates attachment to CD4 cells?","a":"gp41","b":"gp120","c":"p24","d":"p17","ans":"B"},
{"t":"Parasitology","q":"A drug that prevents HIV virion maturation acts by inhibiting:","a":"Reverse transcriptase","b":"Integrase","c":"Protease","d":"Fusion protein","ans":"C"},
{"t":"Parasitology","q":"A patient with viral pneumonia shows multinucleated giant cells on histology. The MOST likely virus family is:","a":"Flaviviridae","b":"Paramyxoviridae","c":"Picornaviridae","d":"Adenoviridae","ans":"B"},
{"t":"Parasitology","q":"A virus transmitted by Aedes mosquito with positive-sense RNA genome is:","a":"Chikungunya","b":"Dengue","c":"Yellow fever","d":"All of the above","ans":"D"},
{"t":"Parasitology","q":"A patient recovers from hepatitis A. Which serological marker confirms lifelong immunity?","a":"Anti-HAV IgM","b":"Anti-HAV IgG","c":"HBsAg","d":"Anti-HBc","ans":"B"}
];